/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.18_02 from the
 * contents of APItest.xs. Do not edit this file, edit APItest.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "APItest.xs"
#define PERL_IN_XS_APITEST
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"


/* for my_cxt tests */

#define MY_CXT_KEY "XS::APItest::_guts" XS_VERSION

typedef struct {
    int i;
    SV *sv;
} my_cxt_t;

START_MY_CXT

/* indirect functions to test the [pa]MY_CXT macros */

int
my_cxt_getint_p(pMY_CXT)
{
    return MY_CXT.i;
}

void
my_cxt_setint_p(pMY_CXT_ int i)
{
    MY_CXT.i = i;
}

SV*
my_cxt_getsv_interp(void)
{
#ifdef PERL_IMPLICIT_CONTEXT
    dTHX;
    dMY_CXT_INTERP(my_perl);
#else
    dMY_CXT;
#endif
    return MY_CXT.sv;
}

void
my_cxt_setsv_p(SV* sv _pMY_CXT)
{
    MY_CXT.sv = sv;
}


/* from exception.c */
int apitest_exception(int);

/* from core_or_not.inc */
bool sv_setsv_cow_hashkey_core(void);
bool sv_setsv_cow_hashkey_notcore(void);

/* A routine to test hv_delayfree_ent
   (which itself is tested by testing on hv_free_ent  */

typedef void (freeent_function)(pTHX_ HV *, register HE *);

void
test_freeent(freeent_function *f) {
    dTHX;
    dSP;
    HV *test_hash = newHV();
    HE *victim;
    SV *test_scalar;
    U32 results[4];
    int i;

#ifdef PURIFY
    victim = (HE*)safemalloc(sizeof(HE));
#else
    /* Storing then deleting something should ensure that a hash entry is
       available.  */
    hv_store(test_hash, "", 0, &PL_sv_yes, 0);
    hv_delete(test_hash, "", 0, 0);

    /* We need to "inline" new_he here as it's static, and the functions we
       test expect to be able to call del_HE on the HE  */
    if (!PL_body_roots[HE_SVSLOT])
	croak("PL_he_root is 0");
    victim = (HE*) PL_body_roots[HE_SVSLOT];
    PL_body_roots[HE_SVSLOT] = HeNEXT(victim);
#endif

    victim->hent_hek = Perl_share_hek(aTHX_ "", 0, 0);

    test_scalar = newSV(0);
    SvREFCNT_inc(test_scalar);
    HeVAL(victim) = test_scalar;

    /* Need this little game else we free the temps on the return stack.  */
    results[0] = SvREFCNT(test_scalar);
    SAVETMPS;
    results[1] = SvREFCNT(test_scalar);
    f(aTHX_ test_hash, victim);
    results[2] = SvREFCNT(test_scalar);
    FREETMPS;
    results[3] = SvREFCNT(test_scalar);

    i = 0;
    do {
	mPUSHu(results[i]);
    } while (++i < sizeof(results)/sizeof(results[0]));

    /* Goodbye to our extra reference.  */
    SvREFCNT_dec(test_scalar);
}


static I32
bitflip_key(pTHX_ IV action, SV *field) {
    MAGIC *mg = mg_find(field, PERL_MAGIC_uvar);
    SV *keysv;
    if (mg && (keysv = mg->mg_obj)) {
	STRLEN len;
	const char *p = SvPV(keysv, len);

	if (len) {
	    SV *newkey = newSV(len);
	    char *new_p = SvPVX(newkey);

	    if (SvUTF8(keysv)) {
		const char *const end = p + len;
		while (p < end) {
		    STRLEN len;
		    UV chr = utf8_to_uvuni((U8 *)p, &len);
		    new_p = (char *)uvuni_to_utf8((U8 *)new_p, chr ^ 32);
		    p += len;
		}
		SvUTF8_on(newkey);
	    } else {
		while (len--)
		    *new_p++ = *p++ ^ 32;
	    }
	    *new_p = '\0';
	    SvCUR_set(newkey, SvCUR(keysv));
	    SvPOK_on(newkey);

	    mg->mg_obj = newkey;
	}
    }
    return 0;
}

static I32
rot13_key(pTHX_ IV action, SV *field) {
    MAGIC *mg = mg_find(field, PERL_MAGIC_uvar);
    SV *keysv;
    if (mg && (keysv = mg->mg_obj)) {
	STRLEN len;
	const char *p = SvPV(keysv, len);

	if (len) {
	    SV *newkey = newSV(len);
	    char *new_p = SvPVX(newkey);

	    /* There's a deliberate fencepost error here to loop len + 1 times
	       to copy the trailing \0  */
	    do {
		char new_c = *p++;
		/* Try doing this cleanly and clearly in EBCDIC another way: */
		switch (new_c) {
		case 'A': new_c = 'N'; break;
		case 'B': new_c = 'O'; break;
		case 'C': new_c = 'P'; break;
		case 'D': new_c = 'Q'; break;
		case 'E': new_c = 'R'; break;
		case 'F': new_c = 'S'; break;
		case 'G': new_c = 'T'; break;
		case 'H': new_c = 'U'; break;
		case 'I': new_c = 'V'; break;
		case 'J': new_c = 'W'; break;
		case 'K': new_c = 'X'; break;
		case 'L': new_c = 'Y'; break;
		case 'M': new_c = 'Z'; break;
		case 'N': new_c = 'A'; break;
		case 'O': new_c = 'B'; break;
		case 'P': new_c = 'C'; break;
		case 'Q': new_c = 'D'; break;
		case 'R': new_c = 'E'; break;
		case 'S': new_c = 'F'; break;
		case 'T': new_c = 'G'; break;
		case 'U': new_c = 'H'; break;
		case 'V': new_c = 'I'; break;
		case 'W': new_c = 'J'; break;
		case 'X': new_c = 'K'; break;
		case 'Y': new_c = 'L'; break;
		case 'Z': new_c = 'M'; break;
		case 'a': new_c = 'n'; break;
		case 'b': new_c = 'o'; break;
		case 'c': new_c = 'p'; break;
		case 'd': new_c = 'q'; break;
		case 'e': new_c = 'r'; break;
		case 'f': new_c = 's'; break;
		case 'g': new_c = 't'; break;
		case 'h': new_c = 'u'; break;
		case 'i': new_c = 'v'; break;
		case 'j': new_c = 'w'; break;
		case 'k': new_c = 'x'; break;
		case 'l': new_c = 'y'; break;
		case 'm': new_c = 'z'; break;
		case 'n': new_c = 'a'; break;
		case 'o': new_c = 'b'; break;
		case 'p': new_c = 'c'; break;
		case 'q': new_c = 'd'; break;
		case 'r': new_c = 'e'; break;
		case 's': new_c = 'f'; break;
		case 't': new_c = 'g'; break;
		case 'u': new_c = 'h'; break;
		case 'v': new_c = 'i'; break;
		case 'w': new_c = 'j'; break;
		case 'x': new_c = 'k'; break;
		case 'y': new_c = 'l'; break;
		case 'z': new_c = 'm'; break;
		}
		*new_p++ = new_c;
	    } while (len--);
	    SvCUR_set(newkey, SvCUR(keysv));
	    SvPOK_on(newkey);
	    if (SvUTF8(keysv))
		SvUTF8_on(newkey);

	    mg->mg_obj = newkey;
	}
    }
    return 0;
}

#include "const-c.inc"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 249 "APItest.c"

/* INCLUDE:  Including 'const-xs.inc' from 'APItest.xs' */


XS(XS_XS__APItest__Hash_constant); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest__Hash_constant)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::Hash::constant", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 123 "const-xs.inc"
	STRLEN		len;
#line 270 "APItest.c"
	SV *	sv = ST(0);
	const char *	s = SvPV(sv, len);
#line 128 "const-xs.inc"
#ifdef SYMBIAN
	sv = newSVpvf("%"SVf" is not a valid XS::APItest macro", sv);
#else
	HV *constant_missing = get_missing_hash(aTHX);
	if (hv_exists(constant_missing, s, SvUTF8(sv) ? -(I32)len : (I32)len)) {
	    sv = newSVpvf("Your vendor has not defined XS::APItest macro %" SVf
			  ", used", sv);
	} else {
	    sv = newSVpvf("%"SVf" is not a valid XS::APItest macro",
			  sv);
	}
#endif
	PUSHs(sv_2mortal(sv));
#line 287 "APItest.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'APItest.xs' from 'const-xs.inc' */


XS(XS_XS__APItest__Hash_rot13_hash); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest__Hash_rot13_hash)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::Hash::rot13_hash", "hash");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	HV *	hash;

	if (SvROK(ST(0)) && SvTYPE(SvRV(ST(0)))==SVt_PVHV)
	    hash = (HV*)SvRV(ST(0));
	else
	    Perl_croak(aTHX_ "%s: %s is not a hash reference",
			"XS::APItest::Hash::rot13_hash",
			"hash");
#line 243 "APItest.xs"
	{
	    struct ufuncs uf;
	    uf.uf_val = rot13_key;
	    uf.uf_set = 0;
	    uf.uf_index = 0;

	    sv_magic((SV*)hash, NULL, PERL_MAGIC_uvar, (char*)&uf, sizeof(uf));
	}
#line 326 "APItest.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_XS__APItest__Hash_bitflip_hash); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest__Hash_bitflip_hash)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::Hash::bitflip_hash", "hash");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	HV *	hash;

	if (SvROK(ST(0)) && SvTYPE(SvRV(ST(0)))==SVt_PVHV)
	    hash = (HV*)SvRV(ST(0));
	else
	    Perl_croak(aTHX_ "%s: %s is not a hash reference",
			"XS::APItest::Hash::bitflip_hash",
			"hash");
#line 256 "APItest.xs"
	{
	    struct ufuncs uf;
	    uf.uf_val = bitflip_key;
	    uf.uf_set = 0;
	    uf.uf_index = 0;

	    sv_magic((SV*)hash, NULL, PERL_MAGIC_uvar, (char*)&uf, sizeof(uf));
	}
#line 361 "APItest.c"
    }
    XSRETURN_EMPTY;
}

#define UTF8KLEN(sv, len)   (SvUTF8(sv) ? -(I32)len : (I32)len)

XS(XS_XS__APItest__Hash_exists); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest__Hash_exists)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::Hash::exists", "hash, key_sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 270 "APItest.xs"
	STRLEN len;
	const char *key;
#line 383 "APItest.c"
	HV *	hash;
	SV *	key_sv = ST(1);
	bool	RETVAL;

	if (SvROK(ST(0)) && SvTYPE(SvRV(ST(0)))==SVt_PVHV)
	    hash = (HV*)SvRV(ST(0));
	else
	    Perl_croak(aTHX_ "%s: %s is not a hash reference",
			"XS::APItest::Hash::exists",
			"hash");
#line 276 "APItest.xs"
	key = SvPV(key_sv, len);
	RETVAL = hv_exists(hash, key, UTF8KLEN(key_sv, len));
#line 397 "APItest.c"
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_XS__APItest__Hash_exists_ent); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest__Hash_exists_ent)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::Hash::exists_ent", "hash, key_sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 284 "APItest.xs"
#line 418 "APItest.c"
	HV *	hash;
	SV *	key_sv = ST(1);
	bool	RETVAL;

	if (SvROK(ST(0)) && SvTYPE(SvRV(ST(0)))==SVt_PVHV)
	    hash = (HV*)SvRV(ST(0));
	else
	    Perl_croak(aTHX_ "%s: %s is not a hash reference",
			"XS::APItest::Hash::exists_ent",
			"hash");
#line 288 "APItest.xs"
	RETVAL = hv_exists_ent(hash, key_sv, 0);
#line 431 "APItest.c"
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_XS__APItest__Hash_delete); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest__Hash_delete)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::Hash::delete", "hash, key_sv, flags = 0");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 295 "APItest.xs"
	STRLEN len;
	const char *key;
#line 454 "APItest.c"
	HV *	hash;
	SV *	key_sv = ST(1);
	I32	flags;
	SV *	RETVAL;

	if (SvROK(ST(0)) && SvTYPE(SvRV(ST(0)))==SVt_PVHV)
	    hash = (HV*)SvRV(ST(0));
	else
	    Perl_croak(aTHX_ "%s: %s is not a hash reference",
			"XS::APItest::Hash::delete",
			"hash");

	if (items < 3)
	    flags = 0;
	else {
	    flags = (I32)SvIV(ST(2));
	}
#line 302 "APItest.xs"
	key = SvPV(key_sv, len);
	/* It's already mortal, so need to increase reference count.  */
	RETVAL
	    = SvREFCNT_inc(hv_delete(hash, key, UTF8KLEN(key_sv, len), flags));
#line 477 "APItest.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_XS__APItest__Hash_delete_ent); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest__Hash_delete_ent)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::Hash::delete_ent", "hash, key_sv, flags = 0");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	HV *	hash;
	SV *	key_sv = ST(1);
	I32	flags;
	SV *	RETVAL;

	if (SvROK(ST(0)) && SvTYPE(SvRV(ST(0)))==SVt_PVHV)
	    hash = (HV*)SvRV(ST(0));
	else
	    Perl_croak(aTHX_ "%s: %s is not a hash reference",
			"XS::APItest::Hash::delete_ent",
			"hash");

	if (items < 3)
	    flags = 0;
	else {
	    flags = (I32)SvIV(ST(2));
	}
#line 316 "APItest.xs"
	/* It's already mortal, so need to increase reference count.  */
	RETVAL = SvREFCNT_inc(hv_delete_ent(hash, key_sv, flags, 0));
#line 517 "APItest.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_XS__APItest__Hash_store_ent); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest__Hash_store_ent)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::Hash::store_ent", "hash, key, value");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 324 "APItest.xs"
	SV *copy;
	HE *result;
#line 540 "APItest.c"
	HV *	hash;
	SV *	key = ST(1);
	SV *	value = ST(2);
	SV *	RETVAL;

	if (SvROK(ST(0)) && SvTYPE(SvRV(ST(0)))==SVt_PVHV)
	    hash = (HV*)SvRV(ST(0));
	else
	    Perl_croak(aTHX_ "%s: %s is not a hash reference",
			"XS::APItest::Hash::store_ent",
			"hash");
#line 331 "APItest.xs"
	copy = newSV(0);
	result = hv_store_ent(hash, key, copy, 0);
	SvSetMagicSV(copy, value);
	if (!result) {
	    SvREFCNT_dec(copy);
	    XSRETURN_EMPTY;
	}
	/* It's about to become mortal, so need to increase reference count.
	 */
	RETVAL = SvREFCNT_inc(HeVAL(result));
#line 563 "APItest.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_XS__APItest__Hash_store); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest__Hash_store)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::Hash::store", "hash, key_sv, value");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 347 "APItest.xs"
	STRLEN len;
	const char *key;
	SV *copy;
	SV **result;
#line 588 "APItest.c"
	HV *	hash;
	SV *	key_sv = ST(1);
	SV *	value = ST(2);
	SV *	RETVAL;

	if (SvROK(ST(0)) && SvTYPE(SvRV(ST(0)))==SVt_PVHV)
	    hash = (HV*)SvRV(ST(0));
	else
	    Perl_croak(aTHX_ "%s: %s is not a hash reference",
			"XS::APItest::Hash::store",
			"hash");
#line 356 "APItest.xs"
	key = SvPV(key_sv, len);
	copy = newSV(0);
	result = hv_store(hash, key, UTF8KLEN(key_sv, len), copy, 0);
	SvSetMagicSV(copy, value);
	if (!result) {
	    SvREFCNT_dec(copy);
	    XSRETURN_EMPTY;
	}
	/* It's about to become mortal, so need to increase reference count.
	 */
	RETVAL = SvREFCNT_inc(*result);
#line 612 "APItest.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_XS__APItest__Hash_fetch_ent); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest__Hash_fetch_ent)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::Hash::fetch_ent", "hash, key_sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 373 "APItest.xs"
	HE *result;
#line 634 "APItest.c"
	HV *	hash;
	SV *	key_sv = ST(1);
	SV *	RETVAL;

	if (SvROK(ST(0)) && SvTYPE(SvRV(ST(0)))==SVt_PVHV)
	    hash = (HV*)SvRV(ST(0));
	else
	    Perl_croak(aTHX_ "%s: %s is not a hash reference",
			"XS::APItest::Hash::fetch_ent",
			"hash");
#line 378 "APItest.xs"
	result = hv_fetch_ent(hash, key_sv, 0, 0);
	if (!result) {
	    XSRETURN_EMPTY;
	}
	/* Force mg_get  */
	RETVAL = newSVsv(HeVAL(result));
#line 652 "APItest.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_XS__APItest__Hash_fetch); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest__Hash_fetch)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::Hash::fetch", "hash, key_sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 390 "APItest.xs"
	STRLEN len;
	const char *key;
	SV **result;
#line 676 "APItest.c"
	HV *	hash;
	SV *	key_sv = ST(1);
	SV *	RETVAL;

	if (SvROK(ST(0)) && SvTYPE(SvRV(ST(0)))==SVt_PVHV)
	    hash = (HV*)SvRV(ST(0));
	else
	    Perl_croak(aTHX_ "%s: %s is not a hash reference",
			"XS::APItest::Hash::fetch",
			"hash");
#line 397 "APItest.xs"
	key = SvPV(key_sv, len);
	result = hv_fetch(hash, key, UTF8KLEN(key_sv, len), 0);
	if (!result) {
	    XSRETURN_EMPTY;
	}
	/* Force mg_get  */
	RETVAL = newSVsv(*result);
#line 695 "APItest.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_XS__APItest__Hash_common); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest__Hash_common)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::Hash::common", "params");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	HV *	params;
#line 412 "APItest.xs"
	HE *result;
	HV *hv = NULL;
	SV *keysv = NULL;
	const char *key = NULL;
	STRLEN klen = 0;
	int flags = 0;
	int action = 0;
	SV *val = NULL;
	U32 hash = 0;
	SV **svp;
#line 727 "APItest.c"
	SV *	RETVAL;

	if (SvROK(ST(0)) && SvTYPE(SvRV(ST(0)))==SVt_PVHV)
	    params = (HV*)SvRV(ST(0));
	else
	    Perl_croak(aTHX_ "%s: %s is not a hash reference",
			"XS::APItest::Hash::common",
			"params");
#line 423 "APItest.xs"
	if ((svp = hv_fetchs(params, "hv", 0))) {
	    SV *const rv = *svp;
	    if (!SvROK(rv))
		croak("common passed a non-reference for parameter hv");
	    hv = (HV *)SvRV(rv);
	}
	if ((svp = hv_fetchs(params, "keysv", 0)))
	    keysv = *svp;
	if ((svp = hv_fetchs(params, "keypv", 0))) {
	    key = SvPV_const(*svp, klen);
	    if (SvUTF8(*svp))
		flags = HVhek_UTF8;
	}
	if ((svp = hv_fetchs(params, "action", 0)))
	    action = SvIV(*svp);
	if ((svp = hv_fetchs(params, "val", 0)))
	    val = *svp;
	if ((svp = hv_fetchs(params, "hash", 0)))
	    action = SvUV(*svp);

	result = (HE *)hv_common(hv, keysv, key, klen, flags, action, val, hash);
	if (!result) {
	    XSRETURN_EMPTY;
	}
	/* Force mg_get  */
	RETVAL = newSVsv(HeVAL(result));
#line 763 "APItest.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_XS__APItest__Hash_test_hv_free_ent); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest__Hash_test_hv_free_ent)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::Hash::test_hv_free_ent", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 455 "APItest.xs"
	test_freeent(&Perl_hv_free_ent);
	XSRETURN(4);
#line 788 "APItest.c"
	PUTBACK;
	return;
    }
}


XS(XS_XS__APItest__Hash_test_hv_delayfree_ent); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest__Hash_test_hv_delayfree_ent)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::Hash::test_hv_delayfree_ent", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 461 "APItest.xs"
	test_freeent(&Perl_hv_delayfree_ent);
	XSRETURN(4);
#line 812 "APItest.c"
	PUTBACK;
	return;
    }
}


XS(XS_XS__APItest__Hash_test_share_unshare_pvn); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest__Hash_test_share_unshare_pvn)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::Hash::test_share_unshare_pvn", "input");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 467 "APItest.xs"
	STRLEN len;
	U32 hash;
	char *pvx;
	char *p;
#line 836 "APItest.c"
	SV *	input = ST(0);
	SV *	RETVAL;
#line 474 "APItest.xs"
	pvx = SvPV(input, len);
	PERL_HASH(hash, pvx, len);
	p = sharepvn(pvx, len, hash);
	RETVAL = newSVpvn(p, len);
	unsharepvn(p, len, hash);
#line 845 "APItest.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_XS__APItest__Hash_refcounted_he_exists); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest__Hash_refcounted_he_exists)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::Hash::refcounted_he_exists", "key, level=0");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	key = ST(0);
	IV	level;
	bool	RETVAL;

	if (items < 2)
	    level = 0;
	else {
	    level = (IV)SvIV(ST(1));
	}
#line 487 "APItest.xs"
	if (level) {
	    croak("level must be zero, not %"IVdf, level);
	}
	RETVAL = (Perl_refcounted_he_fetch(aTHX_ PL_curcop->cop_hints_hash,
					   key, NULL, 0, 0, 0)
		  != &PL_sv_placeholder);
#line 881 "APItest.c"
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_XS__APItest__Hash_refcounted_he_fetch); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest__Hash_refcounted_he_fetch)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::Hash::refcounted_he_fetch", "key, level=0");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	key = ST(0);
	IV	level;
	SV *	RETVAL;

	if (items < 2)
	    level = 0;
	else {
	    level = (IV)SvIV(ST(1));
	}
#line 502 "APItest.xs"
	if (level) {
	    croak("level must be zero, not %"IVdf, level);
	}
	RETVAL = Perl_refcounted_he_fetch(aTHX_ PL_curcop->cop_hints_hash, key,
					  NULL, 0, 0, 0);
	SvREFCNT_inc(RETVAL);
#line 917 "APItest.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_XS__APItest_CLONE); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_CLONE)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 539 "APItest.xs"
    MY_CXT_CLONE;
    MY_CXT.sv = newSVpv("initial_clone",0);
#line 938 "APItest.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_XS__APItest_print_double); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_print_double)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::print_double", "val");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	double	val = (double)SvNV(ST(0));
#line 546 "APItest.xs"
        printf("%5.3f\n",val);
#line 959 "APItest.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_XS__APItest_have_long_double); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_have_long_double)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::have_long_double", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 551 "APItest.xs"
#ifdef HAS_LONG_DOUBLE
        RETVAL = 1;
#else
        RETVAL = 0;
#endif
#line 985 "APItest.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_XS__APItest_print_long_double); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_print_long_double)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::print_long_double", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 562 "APItest.xs"
#ifdef HAS_LONG_DOUBLE
#   if defined(PERL_PRIfldbl) && (LONG_DOUBLESIZE > DOUBLESIZE)
        long double val = 7.0;
        printf("%5.3" PERL_PRIfldbl "\n",val);
#   else
        double val = 7.0;
        printf("%5.3f\n",val);
#   endif
#endif
#line 1014 "APItest.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_XS__APItest_print_int); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_print_int)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::print_int", "val");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	val = (int)SvIV(ST(0));
#line 576 "APItest.xs"
        printf("%d\n",val);
#line 1035 "APItest.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_XS__APItest_print_long); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_print_long)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::print_long", "val");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	long	val = (long)SvIV(ST(0));
#line 582 "APItest.xs"
        printf("%ld\n",val);
#line 1056 "APItest.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_XS__APItest_print_float); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_print_float)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::print_float", "val");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	float	val = (float)SvNV(ST(0));
#line 588 "APItest.xs"
        printf("%5.3f\n",val);
#line 1077 "APItest.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_XS__APItest_print_flush); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_print_flush)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::print_flush", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 593 "APItest.xs"
	fflush(stdout);
#line 1097 "APItest.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_XS__APItest_mpushp); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_mpushp)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::mpushp", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 598 "APItest.xs"
	EXTEND(SP, 3);
	mPUSHp("one", 3);
	mPUSHp("two", 3);
	mPUSHp("three", 5);
	XSRETURN(3);
#line 1123 "APItest.c"
	PUTBACK;
	return;
    }
}


XS(XS_XS__APItest_mpushn); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_mpushn)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::mpushn", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 607 "APItest.xs"
	EXTEND(SP, 3);
	mPUSHn(0.5);
	mPUSHn(-0.25);
	mPUSHn(0.125);
	XSRETURN(3);
#line 1150 "APItest.c"
	PUTBACK;
	return;
    }
}


XS(XS_XS__APItest_mpushi); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_mpushi)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::mpushi", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 616 "APItest.xs"
	EXTEND(SP, 3);
	mPUSHi(-1);
	mPUSHi(2);
	mPUSHi(-3);
	XSRETURN(3);
#line 1177 "APItest.c"
	PUTBACK;
	return;
    }
}


XS(XS_XS__APItest_mpushu); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_mpushu)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::mpushu", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 625 "APItest.xs"
	EXTEND(SP, 3);
	mPUSHu(1);
	mPUSHu(2);
	mPUSHu(3);
	XSRETURN(3);
#line 1204 "APItest.c"
	PUTBACK;
	return;
    }
}


XS(XS_XS__APItest_mxpushp); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_mxpushp)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::mxpushp", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 634 "APItest.xs"
	mXPUSHp("one", 3);
	mXPUSHp("two", 3);
	mXPUSHp("three", 5);
	XSRETURN(3);
#line 1230 "APItest.c"
	PUTBACK;
	return;
    }
}


XS(XS_XS__APItest_mxpushn); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_mxpushn)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::mxpushn", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 642 "APItest.xs"
	mXPUSHn(0.5);
	mXPUSHn(-0.25);
	mXPUSHn(0.125);
	XSRETURN(3);
#line 1256 "APItest.c"
	PUTBACK;
	return;
    }
}


XS(XS_XS__APItest_mxpushi); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_mxpushi)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::mxpushi", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 650 "APItest.xs"
	mXPUSHi(-1);
	mXPUSHi(2);
	mXPUSHi(-3);
	XSRETURN(3);
#line 1282 "APItest.c"
	PUTBACK;
	return;
    }
}


XS(XS_XS__APItest_mxpushu); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_mxpushu)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::mxpushu", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 658 "APItest.xs"
	mXPUSHu(1);
	mXPUSHu(2);
	mXPUSHu(3);
	XSRETURN(3);
#line 1308 "APItest.c"
	PUTBACK;
	return;
    }
}


XS(XS_XS__APItest_call_sv); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_call_sv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::call_sv", "sv, flags, ...");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV*	sv = ST(0);
	I32	flags = (I32)SvIV(ST(1));
#line 669 "APItest.xs"
	I32 i;
#line 1333 "APItest.c"
#line 671 "APItest.xs"
	for (i=0; i<items-2; i++)
	    ST(i) = ST(i+2); /* pop first two args */
	PUSHMARK(SP);
	SP += items - 2;
	PUTBACK;
	i = call_sv(sv, flags);
	SPAGAIN;
	EXTEND(SP, 1);
	PUSHs(sv_2mortal(newSViv(i)));
#line 1344 "APItest.c"
	PUTBACK;
	return;
    }
}


XS(XS_XS__APItest_call_pv); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_call_pv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::call_pv", "subname, flags, ...");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	char*	subname = (char *)SvPV_nolen(ST(0));
	I32	flags = (I32)SvIV(ST(1));
#line 686 "APItest.xs"
	I32 i;
#line 1369 "APItest.c"
#line 688 "APItest.xs"
	for (i=0; i<items-2; i++)
	    ST(i) = ST(i+2); /* pop first two args */
	PUSHMARK(SP);
	SP += items - 2;
	PUTBACK;
	i = call_pv(subname, flags);
	SPAGAIN;
	EXTEND(SP, 1);
	PUSHs(sv_2mortal(newSViv(i)));
#line 1380 "APItest.c"
	PUTBACK;
	return;
    }
}


XS(XS_XS__APItest_call_method); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_call_method)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::call_method", "methname, flags, ...");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	char*	methname = (char *)SvPV_nolen(ST(0));
	I32	flags = (I32)SvIV(ST(1));
#line 703 "APItest.xs"
	I32 i;
#line 1405 "APItest.c"
#line 705 "APItest.xs"
	for (i=0; i<items-2; i++)
	    ST(i) = ST(i+2); /* pop first two args */
	PUSHMARK(SP);
	SP += items - 2;
	PUTBACK;
	i = call_method(methname, flags);
	SPAGAIN;
	EXTEND(SP, 1);
	PUSHs(sv_2mortal(newSViv(i)));
#line 1416 "APItest.c"
	PUTBACK;
	return;
    }
}


XS(XS_XS__APItest_eval_sv); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_eval_sv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::eval_sv", "sv, flags");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV*	sv = ST(0);
	I32	flags = (I32)SvIV(ST(1));
#line 720 "APItest.xs"
    	I32 i;
#line 1441 "APItest.c"
#line 722 "APItest.xs"
	PUTBACK;
	i = eval_sv(sv, flags);
	SPAGAIN;
	EXTEND(SP, 1);
	PUSHs(sv_2mortal(newSViv(i)));
#line 1448 "APItest.c"
	PUTBACK;
	return;
    }
}


XS(XS_XS__APItest_eval_pv); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_eval_pv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::eval_pv", "p, croak_on_error");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	const char*	p = (const char *)SvPV_nolen(ST(0));
	I32	croak_on_error = (I32)SvIV(ST(1));
#line 733 "APItest.xs"
	PUTBACK;
	EXTEND(SP, 1);
	PUSHs(eval_pv(p, croak_on_error));
#line 1475 "APItest.c"
	PUTBACK;
	return;
    }
}


XS(XS_XS__APItest_require_pv); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_require_pv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::require_pv", "pv");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	const char*	pv = (const char *)SvPV_nolen(ST(0));
#line 741 "APItest.xs"
	PUTBACK;
	require_pv(pv);
#line 1500 "APItest.c"
	PUTBACK;
	return;
    }
}


XS(XS_XS__APItest_apitest_exception); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_apitest_exception)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::apitest_exception", "throw_e");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	throw_e = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;

	RETVAL = apitest_exception(throw_e);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_XS__APItest_mycroak); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_mycroak)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::mycroak", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV*	sv = ST(0);
#line 754 "APItest.xs"
    if (SvOK(sv)) {
        Perl_croak(aTHX_ "%s", SvPV_nolen(sv));
    }
    else {
	Perl_croak(aTHX_ NULL);
    }
#line 1550 "APItest.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_XS__APItest_strtab); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_strtab)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::strtab", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	RETVAL;
#line 764 "APItest.xs"
   RETVAL = newRV_inc((SV*)PL_strtab);
#line 1571 "APItest.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_XS__APItest_my_cxt_getint); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_my_cxt_getint)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::my_cxt_getint", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 771 "APItest.xs"
	dMY_CXT;
	RETVAL = my_cxt_getint_p(aMY_CXT);
#line 1596 "APItest.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_XS__APItest_my_cxt_setint); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_my_cxt_setint)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::my_cxt_setint", "i");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	i = (int)SvIV(ST(0));
#line 780 "APItest.xs"
	dMY_CXT;
	my_cxt_setint_p(aMY_CXT_ i);
#line 1619 "APItest.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_XS__APItest_my_cxt_getsv); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_my_cxt_getsv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::my_cxt_getsv", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 786 "APItest.xs"
	EXTEND(SP, 1);
	ST(0) = my_cxt_getsv_interp();
	XSRETURN(1);
#line 1643 "APItest.c"
	PUTBACK;
	return;
    }
}


XS(XS_XS__APItest_my_cxt_setsv); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_my_cxt_setsv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::my_cxt_setsv", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 794 "APItest.xs"
	dMY_CXT;
	SvREFCNT_dec(MY_CXT.sv);
	my_cxt_setsv_p(sv _aMY_CXT);
	SvREFCNT_inc(sv);
#line 1668 "APItest.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_XS__APItest_sv_setsv_cow_hashkey_core); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_sv_setsv_cow_hashkey_core)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::sv_setsv_cow_hashkey_core", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	bool	RETVAL;

	RETVAL = sv_setsv_cow_hashkey_core();
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_XS__APItest_sv_setsv_cow_hashkey_notcore); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_sv_setsv_cow_hashkey_notcore)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::sv_setsv_cow_hashkey_notcore", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	bool	RETVAL;

	RETVAL = sv_setsv_cow_hashkey_notcore();
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_XS__APItest_BEGIN); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_BEGIN)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::BEGIN", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 808 "APItest.xs"
	sv_inc(get_sv("XS::APItest::BEGIN_called", GV_ADD|GV_ADDMULTI));
#line 1732 "APItest.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_XS__APItest_CHECK); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_CHECK)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::CHECK", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 813 "APItest.xs"
	sv_inc(get_sv("XS::APItest::CHECK_called", GV_ADD|GV_ADDMULTI));
#line 1752 "APItest.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_XS__APItest_UNITCHECK); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_UNITCHECK)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::UNITCHECK", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 818 "APItest.xs"
	sv_inc(get_sv("XS::APItest::UNITCHECK_called", GV_ADD|GV_ADDMULTI));
#line 1772 "APItest.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_XS__APItest_INIT); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_INIT)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::INIT", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 823 "APItest.xs"
	sv_inc(get_sv("XS::APItest::INIT_called", GV_ADD|GV_ADDMULTI));
#line 1792 "APItest.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_XS__APItest_END); /* prototype to pass -Wmissing-prototypes */
XS(XS_XS__APItest_END)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "XS::APItest::END", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 828 "APItest.xs"
	sv_inc(get_sv("XS::APItest::END_called", GV_ADD|GV_ADDMULTI));
#line 1812 "APItest.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_XS__APItest); /* prototype to pass -Wmissing-prototypes */
XS(boot_XS__APItest)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("XS::APItest::Hash::constant", XS_XS__APItest__Hash_constant, file);
        newXS("XS::APItest::Hash::rot13_hash", XS_XS__APItest__Hash_rot13_hash, file);
        newXS("XS::APItest::Hash::bitflip_hash", XS_XS__APItest__Hash_bitflip_hash, file);
        newXS("XS::APItest::Hash::exists", XS_XS__APItest__Hash_exists, file);
        newXS("XS::APItest::Hash::exists_ent", XS_XS__APItest__Hash_exists_ent, file);
        newXS("XS::APItest::Hash::delete", XS_XS__APItest__Hash_delete, file);
        newXS("XS::APItest::Hash::delete_ent", XS_XS__APItest__Hash_delete_ent, file);
        newXS("XS::APItest::Hash::store_ent", XS_XS__APItest__Hash_store_ent, file);
        newXS("XS::APItest::Hash::store", XS_XS__APItest__Hash_store, file);
        newXS("XS::APItest::Hash::fetch_ent", XS_XS__APItest__Hash_fetch_ent, file);
        newXS("XS::APItest::Hash::fetch", XS_XS__APItest__Hash_fetch, file);
        newXS("XS::APItest::Hash::common", XS_XS__APItest__Hash_common, file);
        newXS("XS::APItest::Hash::test_hv_free_ent", XS_XS__APItest__Hash_test_hv_free_ent, file);
        newXS("XS::APItest::Hash::test_hv_delayfree_ent", XS_XS__APItest__Hash_test_hv_delayfree_ent, file);
        newXS("XS::APItest::Hash::test_share_unshare_pvn", XS_XS__APItest__Hash_test_share_unshare_pvn, file);
        newXS("XS::APItest::Hash::refcounted_he_exists", XS_XS__APItest__Hash_refcounted_he_exists, file);
        newXS("XS::APItest::Hash::refcounted_he_fetch", XS_XS__APItest__Hash_refcounted_he_fetch, file);
        newXS("XS::APItest::CLONE", XS_XS__APItest_CLONE, file);
        newXS("XS::APItest::print_double", XS_XS__APItest_print_double, file);
        newXS("XS::APItest::have_long_double", XS_XS__APItest_have_long_double, file);
        newXS("XS::APItest::print_long_double", XS_XS__APItest_print_long_double, file);
        newXS("XS::APItest::print_int", XS_XS__APItest_print_int, file);
        newXS("XS::APItest::print_long", XS_XS__APItest_print_long, file);
        newXS("XS::APItest::print_float", XS_XS__APItest_print_float, file);
        newXS("XS::APItest::print_flush", XS_XS__APItest_print_flush, file);
        newXS("XS::APItest::mpushp", XS_XS__APItest_mpushp, file);
        newXS("XS::APItest::mpushn", XS_XS__APItest_mpushn, file);
        newXS("XS::APItest::mpushi", XS_XS__APItest_mpushi, file);
        newXS("XS::APItest::mpushu", XS_XS__APItest_mpushu, file);
        newXS("XS::APItest::mxpushp", XS_XS__APItest_mxpushp, file);
        newXS("XS::APItest::mxpushn", XS_XS__APItest_mxpushn, file);
        newXS("XS::APItest::mxpushi", XS_XS__APItest_mxpushi, file);
        newXS("XS::APItest::mxpushu", XS_XS__APItest_mxpushu, file);
        newXS("XS::APItest::call_sv", XS_XS__APItest_call_sv, file);
        newXS("XS::APItest::call_pv", XS_XS__APItest_call_pv, file);
        newXS("XS::APItest::call_method", XS_XS__APItest_call_method, file);
        newXS("XS::APItest::eval_sv", XS_XS__APItest_eval_sv, file);
        newXS("XS::APItest::eval_pv", XS_XS__APItest_eval_pv, file);
        newXS("XS::APItest::require_pv", XS_XS__APItest_require_pv, file);
        newXS("XS::APItest::apitest_exception", XS_XS__APItest_apitest_exception, file);
        newXS("XS::APItest::mycroak", XS_XS__APItest_mycroak, file);
        newXS("XS::APItest::strtab", XS_XS__APItest_strtab, file);
        newXS("XS::APItest::my_cxt_getint", XS_XS__APItest_my_cxt_getint, file);
        newXS("XS::APItest::my_cxt_setint", XS_XS__APItest_my_cxt_setint, file);
        newXS("XS::APItest::my_cxt_getsv", XS_XS__APItest_my_cxt_getsv, file);
        newXS("XS::APItest::my_cxt_setsv", XS_XS__APItest_my_cxt_setsv, file);
        newXS("XS::APItest::sv_setsv_cow_hashkey_core", XS_XS__APItest_sv_setsv_cow_hashkey_core, file);
        newXS("XS::APItest::sv_setsv_cow_hashkey_notcore", XS_XS__APItest_sv_setsv_cow_hashkey_notcore, file);
        newXS("XS::APItest::BEGIN", XS_XS__APItest_BEGIN, file);
        newXS("XS::APItest::CHECK", XS_XS__APItest_CHECK, file);
        newXS("XS::APItest::UNITCHECK", XS_XS__APItest_UNITCHECK, file);
        newXS("XS::APItest::INIT", XS_XS__APItest_INIT, file);
        newXS("XS::APItest::END", XS_XS__APItest_END, file);

    /* Initialisation Section */

#line 2 "const-xs.inc"
  {
#ifdef dTHX
    dTHX;
#endif
    HV *symbol_table = get_hv("XS::APItest::", TRUE);
#ifndef SYMBIAN
    HV *constant_missing;
#endif

    static const struct notfound_s values_for_notfound[] =
      {
#ifdef HV_DELETE
#else
        { "HV_DELETE", 9 },
#endif
#ifdef HV_DISABLE_UVAR_XKEY
#else
        { "HV_DISABLE_UVAR_XKEY", 20 },
#endif
#ifdef G_DISCARD
#else
        { "G_DISCARD", 9 },
#endif
#ifdef HV_FETCH_ISSTORE
#else
        { "HV_FETCH_ISSTORE", 16 },
#endif
#ifdef HV_FETCH_ISEXISTS
#else
        { "HV_FETCH_ISEXISTS", 17 },
#endif
#ifdef HV_FETCH_LVALUE
#else
        { "HV_FETCH_LVALUE", 15 },
#endif
#ifdef HV_FETCH_JUST_SV
#else
        { "HV_FETCH_JUST_SV", 16 },
#endif
        { NULL, 0 } };
	const struct notfound_s *value_for_notfound = values_for_notfound;

    static const struct iv_s values_for_iv[] =
      {
#ifdef HV_DELETE
        { "HV_DELETE", 9, HV_DELETE },
#endif
#ifdef HV_DISABLE_UVAR_XKEY
        { "HV_DISABLE_UVAR_XKEY", 20, HV_DISABLE_UVAR_XKEY },
#endif
#ifdef G_DISCARD
        { "G_DISCARD", 9, G_DISCARD },
#endif
#ifdef HV_FETCH_ISSTORE
        { "HV_FETCH_ISSTORE", 16, HV_FETCH_ISSTORE },
#endif
#ifdef HV_FETCH_ISEXISTS
        { "HV_FETCH_ISEXISTS", 17, HV_FETCH_ISEXISTS },
#endif
#ifdef HV_FETCH_LVALUE
        { "HV_FETCH_LVALUE", 15, HV_FETCH_LVALUE },
#endif
#ifdef HV_FETCH_JUST_SV
        { "HV_FETCH_JUST_SV", 16, HV_FETCH_JUST_SV },
#endif
        { NULL, 0, 0 } };
	const struct iv_s *value_for_iv = values_for_iv;
#ifndef SYMBIAN
	constant_missing = get_missing_hash(aTHX);
#endif
        while (value_for_iv->name) {
	    constant_add_symbol(aTHX_  symbol_table, value_for_iv->name,
				value_for_iv->namelen, newSViv(value_for_iv->value));
	    ++value_for_iv;
	}
	while (value_for_notfound->name) {

	    /* Need to add prototypes, else parsing will vary by platform.  */
	    SV **sv = hv_fetch(symbol_table, value_for_notfound->name,
			       value_for_notfound->namelen, TRUE);
	    if (!sv) {
		Perl_croak(aTHX_ 
			   "Couldn't add key '%s' to %%XS::APItest::",
			   value_for_notfound->name);
	    }
	    if (!SvOK(*sv) && SvTYPE(*sv) != SVt_PVGV) {
		/* Nothing was here before, so mark a prototype of ""  */
		sv_setpvn(*sv, "", 0);
	    } else if (SvPOK(*sv) && SvCUR(*sv) == 0) {
		/* There is already a prototype of "" - do nothing  */
	    } else {
		/* Someone has been here before us - have to make a real
		   typeglob.  */
		/* It turns out to be incredibly hard to deal with all the
		   corner cases of sub foo (); and reporting errors correctly,
		   so lets cheat a bit.  Start with a constant subroutine  */
		CV *cv = newCONSTSUB(symbol_table, value_for_notfound->name,
				     &PL_sv_yes);
		/* and then turn it into a non constant declaration only.  */
		SvREFCNT_dec(CvXSUBANY(cv).any_ptr);
		CvCONST_off(cv);
		CvXSUB(cv) = NULL;
		CvXSUBANY(cv).any_ptr = NULL;
	    }
#ifndef SYMBIAN
	    if (!hv_store(constant_missing, value_for_notfound->name,
			  value_for_notfound->namelen, &PL_sv_yes, 0))
		Perl_croak(aTHX_  "Couldn't add key '%s' to missing_hash",
			   value_for_notfound->name);
#endif

	    ++value_for_notfound;
	}
    /* As we've been creating subroutines, we better invalidate any cached
       methods  */
    ++PL_sub_generation;
  }

#line 530 "APItest.xs"
{
    MY_CXT_INIT;
    MY_CXT.i  = 99;
    MY_CXT.sv = newSVpv("initial",0);
}                              

#line 2016 "APItest.c"

    /* End of Initialisation Section */

    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

