#!/usr/bin/perl

my $f = $ARGV[0];
$f =~ s/^(.*?):$/$1/igm;
if ($f =~ /^(.*?):(.*?)$/) {
	my $file = $1;
        my $basename = `basename $file`;
	chomp $basename;
	my $line = $2-1;
	open my $handle, "<", $file;
	my @lines = <$handle>;
	open my $e, ">", "/tmp/editcode.$$.".$basename;
	for my $l (($line-5>=0?$line-5:0)..$line+5) {
		print $e $lines[$l];
	}
	close $e;
	system("sudo rm -f /home/tobias/.nano_history");
	system("nano /tmp/editcode.$$.".$basename);
	open my $e, "<", "/tmp/editcode.$$.".$basename;
	my @elines = <$e>;
	open my $handle, ">", $file;
	for my $l (0..($line-5-1>=0?$line-5-1:-1)) {
		print $handle $lines[$l];
	}
	for my $line (@elines) {
		print $handle $line;
	}
	for my $l (($line+5+1<@lines?$line+5+1:@lines)..@lines) {
		print $handle $lines[$l];
	}
}
