/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/tobias/perl-5.10.0/miniperl ../bin/enc2xs -Q -o eu_01_t.c -f eu_01_t.fnm
 enc2xs VERSION 2.05
*/
extern encode_t euc_kr_encoding;
