/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/tobias/perl-5.10.0/miniperl ../bin/enc2xs -Q -o jo_02_t.c -f jo_02_t.fnm
 enc2xs VERSION 2.05
*/
extern encode_t johab_encoding;
