#!/usr/bin/perl

while (<>) {
	my $line = $_;

	print $line;
	if ( $line =~ /^\s/ ) {

		$line =~ s/[\\]/\\\\/igm;
		$line =~ s/["]/\\"/igm;
		chomp $line;
		my $line2 = $line;
		$line2 =~ s/\s//igm;
		if ( $line && $line !~ /else|if|while|for/ && length($line2) > 3 && $line =~ /[;]/ && $line =~ /[)(=}{]/ ) {
			$line = "\t\t\t{ FILE* f = fopen(\"crash-code.txt\", \"a\"); fprintf(f, \"%s\", \"" . $line . "\\n\"); fclose(f); } ;\n";

			print $line;
		}
	}
}
