#!/usr/bin/perl

while (<>) {
	my $line = $_;

	print $line;
	if ( $line =~ /^\s/ ) {

		$line =~ s/["]/\\"/igm;
		chomp $line;
		my $line2 = $line;
		$line2 =~ s/\s//igm;
		if ( $line && $line !~ /else|if|while/ && length($line2) > 3 ) {
			$line = "\t\t\tprintf(\"%s\", \"" . $line . "\\n\");\n";

			print $line;
		}
	}
}
