/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.18_02 from the
 * contents of Util.xs. Do not edit this file, edit Util.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Util.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"


#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 20 "Util.c"

XS(XS_Hash__Util_all_keys); /* prototype to pass -Wmissing-prototypes */
XS(XS_Hash__Util_all_keys)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Hash::Util::all_keys", "hash, keys, placeholder");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV*	hash = ST(0);
	SV*	keys = ST(1);
	SV*	placeholder = ST(2);
#line 16 "Util.xs"
	AV* av_k;
        AV* av_p;
        HV* hv;
        SV *key;
        HE *he;
#line 43 "Util.c"
	SV *	RETVAL;
#line 22 "Util.xs"
	if (!SvROK(hash) || SvTYPE(SvRV(hash)) != SVt_PVHV)
	   croak("First argument to all_keys() must be an HASH reference");
	if (!SvROK(keys) || SvTYPE(SvRV(keys)) != SVt_PVAV)
	   croak("Second argument to all_keys() must be an ARRAY reference");
        if (!SvROK(placeholder) || SvTYPE(SvRV(placeholder)) != SVt_PVAV)
	   croak("Third argument to all_keys() must be an ARRAY reference");

	hv = (HV*)SvRV(hash);
	av_k = (AV*)SvRV(keys);
	av_p = (AV*)SvRV(placeholder);

        av_clear(av_k);
        av_clear(av_p);

        (void)hv_iterinit(hv);
	while((he = hv_iternext_flags(hv, HV_ITERNEXT_WANTPLACEHOLDERS))!= NULL) {
	    key=hv_iterkeysv(he);
            if (HeVAL(he) == &PL_sv_placeholder) {
                SvREFCNT_inc(key);
	        av_push(av_p, key);
            } else {
                SvREFCNT_inc(key);
	        av_push(av_k, key);
            }
        }
        RETVAL=hash;
#line 72 "Util.c"
    }
    XSRETURN(1);
}


XS(XS_Hash__Util_hidden_ref_keys); /* prototype to pass -Wmissing-prototypes */
XS(XS_Hash__Util_hidden_ref_keys)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Hash::Util::hidden_ref_keys", "hash");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV*	hash = ST(0);
#line 54 "Util.xs"
        HV* hv;
        SV *key;
        HE *he;
#line 97 "Util.c"
#line 58 "Util.xs"
	if (!SvROK(hash) || SvTYPE(SvRV(hash)) != SVt_PVHV)
	   croak("First argument to hidden_keys() must be an HASH reference");

	hv = (HV*)SvRV(hash);

        (void)hv_iterinit(hv);
	while((he = hv_iternext_flags(hv, HV_ITERNEXT_WANTPLACEHOLDERS))!= NULL) {
	    key=hv_iterkeysv(he);
            if (HeVAL(he) == &PL_sv_placeholder) {
                XPUSHs( key );
            }
        }
#line 111 "Util.c"
	PUTBACK;
	return;
    }
}


XS(XS_Hash__Util_legal_ref_keys); /* prototype to pass -Wmissing-prototypes */
XS(XS_Hash__Util_legal_ref_keys)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Hash::Util::legal_ref_keys", "hash");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV*	hash = ST(0);
#line 75 "Util.xs"
        HV* hv;
        SV *key;
        HE *he;
#line 137 "Util.c"
#line 79 "Util.xs"
	if (!SvROK(hash) || SvTYPE(SvRV(hash)) != SVt_PVHV)
	   croak("First argument to legal_keys() must be an HASH reference");

	hv = (HV*)SvRV(hash);

        (void)hv_iterinit(hv);
	while((he = hv_iternext_flags(hv, HV_ITERNEXT_WANTPLACEHOLDERS))!= NULL) {
	    key=hv_iterkeysv(he);
            XPUSHs( key );
        }
#line 149 "Util.c"
	PUTBACK;
	return;
    }
}


XS(XS_Hash__Util_hv_store); /* prototype to pass -Wmissing-prototypes */
XS(XS_Hash__Util_hv_store)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Hash::Util::hv_store", "hvref, key, val");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV*	hvref = ST(0);
	SV*	key = ST(1);
	SV*	val = ST(2);
#line 97 "Util.xs"
	HV* hv;
#line 173 "Util.c"
	SV *	RETVAL;
#line 99 "Util.xs"
    {
	if (!SvROK(hvref) || SvTYPE(SvRV(hvref)) != SVt_PVHV)
	   croak("First argument to alias_hv() must be a hash reference");
	hv = (HV*)SvRV(hvref);
        SvREFCNT_inc(val);
	if (!hv_store_ent(hv, key, val, 0)) {
	    SvREFCNT_dec(val);
	    XSRETURN_NO;
	} else {
	    XSRETURN_YES;
	}

    }
#line 189 "Util.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Hash__Util); /* prototype to pass -Wmissing-prototypes */
XS(boot_Hash__Util)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Hash::Util::all_keys", XS_Hash__Util_all_keys, file, "\\%\\@\\@");
        newXS("Hash::Util::hidden_ref_keys", XS_Hash__Util_hidden_ref_keys, file);
        newXS("Hash::Util::legal_ref_keys", XS_Hash__Util_legal_ref_keys, file);
        newXSproto("Hash::Util::hv_store", XS_Hash__Util_hv_store, file, "\\%$$");
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

