#!/bin/bash
export LC_ALL=C

grep "Spende " /home/tobias/Dokumente/Bank/Gnu\ Cash/Gnu\ Cash* | grep Spenden | perl -n -e 's/^.*?Spende //gm; print' | sort | uniq | perl -n -e 's/[0-9].*$//igm; s/\t.*$//igm; $_ .= " "; my $l = $_; while ($l =~ /([A-Z])([A-Z]+)/) { my $s1 = $1; my $s2 = lc($2); $l =~ s/$s1$s2/ $s1$s2 /igm; }; $l =~ s/[\/(].*//igm; $l =~ s/\s+/ /igm; $l =~ s/^\s+//igm; $l =~ s/\s+$//igm; $l =~ s/[\r\n]//igm; print $l.qq{\n};' | sort | uniq > doc/Contributors.txt

