/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.18_02 from the
 * contents of RealPPPort.xs. Do not edit this file, edit RealPPPort.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "RealPPPort.xs"
/*******************************************************************************
*
*  !!!!! Do NOT edit this file directly! -- Edit PPPort_xs.PL instead. !!!!!
*
*  This file was automatically generated from the definition files in the
*  parts/inc/ subdirectory by PPPort_xs.PL. To learn more about how all this
*  works, please read the F<HACKERS> file that came with this distribution.
*
********************************************************************************
*
*  Perl/Pollution/Portability
*
********************************************************************************
*
*  $Revision: 13 $
*  $Author: mhx $
*  $Date: 2007/01/02 12:32:26 +0100 $
*
********************************************************************************
*
*  Version 3.x, Copyright (C) 2004-2007, Marcus Holland-Moritz.
*  Version 2.x, Copyright (C) 2001, Paul Marquess.
*  Version 1.x, Copyright (C) 1999, Kenneth Albanowski.
*
*  This program is free software; you can redistribute it and/or
*  modify it under the same terms as Perl itself.
*
*******************************************************************************/

/* ========== BEGIN XSHEAD ================================================== */



/* =========== END XSHEAD =================================================== */

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

/* ========== BEGIN XSINIT ================================================== */

/* ---- code from parts/inc/call ---- */
#define NEED_eval_pv
#define NEED_load_module
#define NEED_vload_module

/* ---- code from parts/inc/strlfuncs ---- */
#define NEED_my_strlcat
#define NEED_my_strlcpy

/* ---- code from parts/inc/shared_pv ---- */
#define NEED_newSVpvn_share

/* ---- code from parts/inc/newCONSTSUB ---- */
#define NEED_newCONSTSUB

/* ---- code from parts/inc/SvPV ---- */
#define NEED_sv_2pv_flags
#define NEED_sv_pvn_force_flags
#define NEED_sv_2pvbyte

/* ---- code from parts/inc/sv_xpvf ---- */
#define NEED_vnewSVpvf
#define NEED_sv_catpvf_mg
#define NEED_sv_catpvf_mg_nocontext
#define NEED_sv_setpvf_mg
#define NEED_sv_setpvf_mg_nocontext

/* ---- code from parts/inc/snprintf ---- */
#define NEED_my_snprintf

/* ---- code from parts/inc/variables ---- */
#define NEED_PL_signals

/* ---- code from parts/inc/newRV ---- */
#define NEED_newRV_noinc

/* ---- code from parts/inc/warn ---- */
#define NEED_warner

/* ---- code from parts/inc/grok ---- */
#define NEED_grok_number
#define NEED_grok_numeric_radix
#define NEED_grok_bin
#define NEED_grok_hex
#define NEED_grok_oct

/* =========== END XSINIT =================================================== */

#include "ppport.h"

/* ========== BEGIN XSMISC ================================================== */

/* ---- code from parts/inc/misc ---- */
XS(XS_Devel__PPPort_dXSTARG);  /* prototype */
XS(XS_Devel__PPPort_dXSTARG)
{
  dXSARGS;
  dXSTARG;
  IV iv;
  SP -= items;
  iv = SvIV(ST(0)) + 1;
  PUSHi(iv);
  XSRETURN(1);
}

XS(XS_Devel__PPPort_dAXMARK);  /* prototype */
XS(XS_Devel__PPPort_dAXMARK)
{
  dSP;
  dAXMARK;
  dITEMS;
  IV iv;
  SP -= items;
  iv = SvIV(ST(0)) - 1;
  PUSHs(sv_2mortal(newSViv(iv)));
  XSRETURN(1);
}

/* ---- code from parts/inc/exception ---- */
/* defined in module3.c */
int exception(int throw_e);

/* ---- code from parts/inc/newCONSTSUB ---- */
void call_newCONSTSUB_1(void)
{
#ifdef PERL_NO_GET_CONTEXT
	dTHX;
#endif
	newCONSTSUB(gv_stashpv("Devel::PPPort", FALSE), "test_value_1", newSViv(1));
}

extern void call_newCONSTSUB_2(void);
extern void call_newCONSTSUB_3(void);

/* ---- code from parts/inc/MY_CXT ---- */
#define MY_CXT_KEY "Devel::PPPort::_guts" XS_VERSION

typedef struct {
  /* Put Global Data in here */
  int dummy;
} my_cxt_t;

START_MY_CXT

/* ---- code from parts/inc/sv_xpvf ---- */
static SV * test_vnewSVpvf(pTHX_ const char *pat, ...)
{
  SV *sv;
  va_list args;
  va_start(args, pat);
#if (PERL_BCDVERSION >= 0x5004000)
  sv = vnewSVpvf(pat, &args);
#else
  sv = newSVpv((char *) pat, 0);
#endif
  va_end(args);
  return sv;
}

static void test_sv_vcatpvf(pTHX_ SV *sv, const char *pat, ...)
{
  va_list args;
  va_start(args, pat);
#if (PERL_BCDVERSION >= 0x5004000)
  sv_vcatpvf(sv, pat, &args);
#else
  sv_catpv(sv, (char *) pat);
#endif
  va_end(args);
}

static void test_sv_vsetpvf(pTHX_ SV *sv, const char *pat, ...)
{
  va_list args;
  va_start(args, pat);
#if (PERL_BCDVERSION >= 0x5004000)
  sv_vsetpvf(sv, pat, &args);
#else
  sv_setpv(sv, (char *) pat);
#endif
  va_end(args);
}

/* ---- code from parts/inc/variables ---- */
U32 get_PL_signals_1(void)
{
  return PL_signals;
}

extern U32 get_PL_signals_2(void);
extern U32 get_PL_signals_3(void);

#define ppp_TESTVAR(var)   STMT_START { XPUSHs(newSViv(&var != NULL)); count++; } STMT_END

/* =========== END XSMISC =================================================== */

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 212 "RealPPPort.c"

XS(XS_Devel__PPPort_no_THX_arg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_no_THX_arg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::no_THX_arg", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	IV	RETVAL;
	dXSTARG;
#line 223 "RealPPPort.xs"
		RETVAL = 1 + sv_2iv(sv);
#line 231 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_with_THX_arg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_with_THX_arg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::with_THX_arg", "error");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	char *	error = (char *)SvPV_nolen(ST(0));
#line 231 "RealPPPort.xs"
		Perl_croak(aTHX_ "%s", error);
#line 255 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_G_SCALAR); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_G_SCALAR)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::G_SCALAR", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	I32	RETVAL;
	dXSTARG;
#line 240 "RealPPPort.xs"
		RETVAL = G_SCALAR;
#line 278 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_G_ARRAY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_G_ARRAY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::G_ARRAY", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	I32	RETVAL;
	dXSTARG;
#line 247 "RealPPPort.xs"
		RETVAL = G_ARRAY;
#line 301 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_G_DISCARD); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_G_DISCARD)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::G_DISCARD", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	I32	RETVAL;
	dXSTARG;
#line 254 "RealPPPort.xs"
		RETVAL = G_DISCARD;
#line 324 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_eval_sv); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_eval_sv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::eval_sv", "sv, flags");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV*	sv = ST(0);
	I32	flags = (I32)SvIV(ST(1));
#line 263 "RealPPPort.xs"
		I32 i;
#line 349 "RealPPPort.c"
#line 265 "RealPPPort.xs"
		PUTBACK;
		i = eval_sv(sv, flags);
		SPAGAIN;
		EXTEND(SP, 1);
		PUSHs(sv_2mortal(newSViv(i)));
#line 356 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_eval_pv); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_eval_pv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::eval_pv", "p, croak_on_error");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	char*	p = (char *)SvPV_nolen(ST(0));
	I32	croak_on_error = (I32)SvIV(ST(1));
#line 276 "RealPPPort.xs"
		PUTBACK;
		EXTEND(SP, 1);
		PUSHs(eval_pv(p, croak_on_error));
#line 383 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_call_sv); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_call_sv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::call_sv", "sv, flags, ...");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV*	sv = ST(0);
	I32	flags = (I32)SvIV(ST(1));
#line 285 "RealPPPort.xs"
		I32 i;
#line 408 "RealPPPort.c"
#line 287 "RealPPPort.xs"
		for (i=0; i<items-2; i++)
		  ST(i) = ST(i+2); /* pop first two args */
		PUSHMARK(SP);
		SP += items - 2;
		PUTBACK;
		i = call_sv(sv, flags);
		SPAGAIN;
		EXTEND(SP, 1);
		PUSHs(sv_2mortal(newSViv(i)));
#line 419 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_call_pv); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_call_pv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::call_pv", "subname, flags, ...");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	char*	subname = (char *)SvPV_nolen(ST(0));
	I32	flags = (I32)SvIV(ST(1));
#line 302 "RealPPPort.xs"
		I32 i;
#line 444 "RealPPPort.c"
#line 304 "RealPPPort.xs"
		for (i=0; i<items-2; i++)
		  ST(i) = ST(i+2); /* pop first two args */
		PUSHMARK(SP);
		SP += items - 2;
		PUTBACK;
		i = call_pv(subname, flags);
		SPAGAIN;
		EXTEND(SP, 1);
		PUSHs(sv_2mortal(newSViv(i)));
#line 455 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_call_argv); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_call_argv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::call_argv", "subname, flags, ...");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	char*	subname = (char *)SvPV_nolen(ST(0));
	I32	flags = (I32)SvIV(ST(1));
#line 319 "RealPPPort.xs"
		I32 i;
		char *args[8];
#line 481 "RealPPPort.c"
#line 322 "RealPPPort.xs"
		if (items > 8)  /* play safe */
		  XSRETURN_UNDEF;
		for (i=2; i<items; i++)
		  args[i-2] = SvPV_nolen(ST(i));
		args[items-2] = NULL;
		PUTBACK;
		i = call_argv(subname, flags, args);
		SPAGAIN;
		EXTEND(SP, 1);
		PUSHs(sv_2mortal(newSViv(i)));
#line 493 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_call_method); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_call_method)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::call_method", "methname, flags, ...");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	char*	methname = (char *)SvPV_nolen(ST(0));
	I32	flags = (I32)SvIV(ST(1));
#line 338 "RealPPPort.xs"
		I32 i;
#line 518 "RealPPPort.c"
#line 340 "RealPPPort.xs"
		for (i=0; i<items-2; i++)
		  ST(i) = ST(i+2); /* pop first two args */
		PUSHMARK(SP);
		SP += items - 2;
		PUTBACK;
		i = call_method(methname, flags);
		SPAGAIN;
		EXTEND(SP, 1);
		PUSHs(sv_2mortal(newSViv(i)));
#line 529 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_load_module); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_load_module)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::load_module", "flags, name, version, ...");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	U32	flags = (unsigned long)SvUV(ST(0));
	SV *	name = ST(1);
	SV *	version = ST(2);
#line 356 "RealPPPort.xs"
		/* Both SV parameters are donated to the ops built inside
		   load_module, so we need to bump the refcounts.  */
		Perl_load_module(aTHX_ flags, SvREFCNT_inc_simple(name),
		                 SvREFCNT_inc_simple(version), NULL);
#line 556 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_newSVpvs); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_newSVpvs)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::newSVpvs", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 368 "RealPPPort.xs"
		XPUSHs(newSVpvs("newSVpvs"));
		XSRETURN(1);
#line 579 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_sv_catpvs); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_catpvs)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_catpvs", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	sv = ST(0);
#line 375 "RealPPPort.xs"
		sv_catpvs(sv, "sv_catpvs");
#line 603 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_sv_setpvs); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_setpvs)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_setpvs", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	sv = ST(0);
#line 381 "RealPPPort.xs"
		sv_setpvs(sv, "sv_setpvs");
#line 627 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_hv_fetchs); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_hv_fetchs)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::hv_fetchs", "hv");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	hv = ST(0);
#line 387 "RealPPPort.xs"
		SV **s;
#line 651 "RealPPPort.c"
#line 389 "RealPPPort.xs"
		s = hv_fetchs((HV *) SvRV(hv), "hv_fetchs", 0);
		XPUSHs(sv_mortalcopy(*s));
		XSRETURN(1);
#line 656 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_hv_stores); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_hv_stores)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::hv_stores", "hv, sv");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	hv = ST(0);
	SV *	sv = ST(1);
#line 398 "RealPPPort.xs"
		(void) hv_stores((HV *) SvRV(hv), "hv_stores", SvREFCNT_inc_simple(sv));
#line 681 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_my_strlfunc); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_my_strlfunc)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::my_strlfunc", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 407 "RealPPPort.xs"
		char buf[8];
		int len;
#line 705 "RealPPPort.c"
#line 410 "RealPPPort.xs"
                len = my_strlcpy(buf, "foo", sizeof(buf));
		XPUSHs(newSViv(len));
		XPUSHs(newSVpv(buf, 0));
		len = my_strlcat(buf, "bar", sizeof(buf));
		XPUSHs(newSViv(len));
		XPUSHs(newSVpv(buf, 0));
		len = my_strlcat(buf, "baz", sizeof(buf));
		XPUSHs(newSViv(len));
		XPUSHs(newSVpv(buf, 0));
		len = my_strlcpy(buf, "1234567890", sizeof(buf));
		XPUSHs(newSViv(len));
		XPUSHs(newSVpv(buf, 0));
		len = my_strlcpy(buf, "1234", sizeof(buf));
		XPUSHs(newSViv(len));
		XPUSHs(newSVpv(buf, 0));
		len = my_strlcat(buf, "567890123456", sizeof(buf));
		XPUSHs(newSViv(len));
		XPUSHs(newSVpv(buf, 0));
		XSRETURN(12);
#line 726 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_sv_catpv_mg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_catpv_mg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_catpv_mg", "sv, string");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	char *	string = (char *)SvPV_nolen(ST(1));
#line 439 "RealPPPort.xs"
		sv_catpv_mg(sv, string);
#line 749 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_sv_catpvn_mg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_catpvn_mg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_catpvn_mg", "sv, sv2");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	SV *	sv2 = ST(1);
#line 446 "RealPPPort.xs"
		char *str;
		STRLEN len;
#line 772 "RealPPPort.c"
#line 449 "RealPPPort.xs"
		str = SvPV(sv2, len);
		sv_catpvn_mg(sv, str, len);
#line 776 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_sv_catsv_mg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_catsv_mg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_catsv_mg", "sv, sv2");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	SV *	sv2 = ST(1);
#line 457 "RealPPPort.xs"
		sv_catsv_mg(sv, sv2);
#line 798 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_sv_setiv_mg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_setiv_mg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_setiv_mg", "sv, iv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	IV	iv = (IV)SvIV(ST(1));
#line 464 "RealPPPort.xs"
		sv_setiv_mg(sv, iv);
#line 820 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_sv_setnv_mg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_setnv_mg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_setnv_mg", "sv, nv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	NV	nv = (NV)SvNV(ST(1));
#line 471 "RealPPPort.xs"
		sv_setnv_mg(sv, nv);
#line 842 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_sv_setpv_mg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_setpv_mg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_setpv_mg", "sv, pv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	char *	pv = (char *)SvPV_nolen(ST(1));
#line 478 "RealPPPort.xs"
		sv_setpv_mg(sv, pv);
#line 864 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_sv_setpvn_mg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_setpvn_mg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_setpvn_mg", "sv, sv2");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	SV *	sv2 = ST(1);
#line 485 "RealPPPort.xs"
		char *str;
		STRLEN len;
#line 887 "RealPPPort.c"
#line 488 "RealPPPort.xs"
		str = SvPV(sv2, len);
		sv_setpvn_mg(sv, str, len);
#line 891 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_sv_setsv_mg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_setsv_mg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_setsv_mg", "sv, sv2");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	SV *	sv2 = ST(1);
#line 496 "RealPPPort.xs"
		sv_setsv_mg(sv, sv2);
#line 913 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_sv_setuv_mg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_setuv_mg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_setuv_mg", "sv, uv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	UV	uv = (UV)SvUV(ST(1));
#line 503 "RealPPPort.xs"
		sv_setuv_mg(sv, uv);
#line 935 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_sv_usepvn_mg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_usepvn_mg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_usepvn_mg", "sv, sv2");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	SV *	sv2 = ST(1);
#line 510 "RealPPPort.xs"
		char *str, *copy;
		STRLEN len;
#line 958 "RealPPPort.c"
#line 513 "RealPPPort.xs"
		str = SvPV(sv2, len);
		New(42, copy, len+1, char);
		Copy(str, copy, len+1, char);
		sv_usepvn_mg(sv, copy, len);
#line 964 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_SvVSTRING_mg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvVSTRING_mg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvVSTRING_mg", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	int	RETVAL;
	dXSTARG;
#line 522 "RealPPPort.xs"
		RETVAL = SvVSTRING_mg(sv) != NULL;
#line 987 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_sv_magic_portable); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_magic_portable)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_magic_portable", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 530 "RealPPPort.xs"
		MAGIC *mg;
		const char *foo = "foo";
#line 1010 "RealPPPort.c"
	int	RETVAL;
	dXSTARG;
#line 533 "RealPPPort.xs"
#if (PERL_BCDVERSION >= 0x5004000)
		sv_magic_portable(sv, 0, '~', foo, 0);
		mg = mg_find(sv, '~');
		RETVAL = mg->mg_ptr == foo;
#else
		sv_magic(sv, 0, '~', (char *) foo, strlen(foo));
		mg = mg_find(sv, '~');
		RETVAL = strEQ(mg->mg_ptr, foo);
#endif
		sv_unmagic(sv, '~');
#line 1024 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_gv_stashpvn); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_gv_stashpvn)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::gv_stashpvn", "name, create");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char *	name = (char *)SvPV_nolen(ST(0));
	I32	create = (I32)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 555 "RealPPPort.xs"
		RETVAL = gv_stashpvn(name, strlen(name), create) != NULL;
#line 1049 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_get_sv); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_get_sv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::get_sv", "name, create");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char *	name = (char *)SvPV_nolen(ST(0));
	I32	create = (I32)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 564 "RealPPPort.xs"
		RETVAL = get_sv(name, create) != NULL;
#line 1074 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_get_av); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_get_av)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::get_av", "name, create");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char *	name = (char *)SvPV_nolen(ST(0));
	I32	create = (I32)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 573 "RealPPPort.xs"
		RETVAL = get_av(name, create) != NULL;
#line 1099 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_get_hv); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_get_hv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::get_hv", "name, create");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char *	name = (char *)SvPV_nolen(ST(0));
	I32	create = (I32)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 582 "RealPPPort.xs"
		RETVAL = get_hv(name, create) != NULL;
#line 1124 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_get_cv); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_get_cv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::get_cv", "name, create");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char *	name = (char *)SvPV_nolen(ST(0));
	I32	create = (I32)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 591 "RealPPPort.xs"
		RETVAL = get_cv(name, create) != NULL;
#line 1149 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_newSVpvn); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_newSVpvn)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::newSVpvn", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 598 "RealPPPort.xs"
		XPUSHs(newSVpvn("test", 4));
		XPUSHs(newSVpvn("test", 2));
		XPUSHs(newSVpvn("test", 0));
		XPUSHs(newSVpvn(NULL, 2));
		XPUSHs(newSVpvn(NULL, 0));
		XSRETURN(5);
#line 1177 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_xsreturn); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_xsreturn)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::xsreturn", "two");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	two = (int)SvIV(ST(0));
#line 609 "RealPPPort.xs"
		XPUSHs(newSVpvn("test1", 5));
		if (two)
		  XPUSHs(newSVpvn("test2", 5));
		if (two)
		  XSRETURN(2);
		else
		  XSRETURN(1);
#line 1207 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_boolSV); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_boolSV)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::boolSV", "value");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	value = (int)SvIV(ST(0));
	SV *	RETVAL;
#line 621 "RealPPPort.xs"
		RETVAL = newSVsv(boolSV(value));
#line 1230 "RealPPPort.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_DEFSV); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_DEFSV)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::DEFSV", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	RETVAL;
#line 628 "RealPPPort.xs"
		RETVAL = newSVsv(DEFSV);
#line 1253 "RealPPPort.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_ERRSV); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_ERRSV)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::ERRSV", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 635 "RealPPPort.xs"
		RETVAL = SvTRUE(ERRSV);
#line 1277 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_UNDERBAR); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_UNDERBAR)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::UNDERBAR", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	RETVAL;
#line 642 "RealPPPort.xs"
		{
		  dUNDERBAR;
		  RETVAL = newSVsv(UNDERBAR);
		}
#line 1302 "RealPPPort.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_prepush); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_prepush)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::prepush", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 652 "RealPPPort.xs"
		{
		  dXSTARG;
		  XSprePUSH;
		  PUSHi(42);
		  XSRETURN(1);
		}
#line 1329 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_PERL_ABS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_PERL_ABS)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::PERL_ABS", "a");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	a = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;

	RETVAL = PERL_ABS(a);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SVf); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SVf)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SVf", "x");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	x = ST(0);
#line 667 "RealPPPort.xs"
#if (PERL_BCDVERSION >= 0x5004000)
		x = newSVpvf("[%"SVf"]", x);
#endif
		XPUSHs(x);
		XSRETURN(1);
#line 1379 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_exception); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_exception)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::exception", "throw_e");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	throw_e = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;

	RETVAL = exception(throw_e);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_TestSvUV_set); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_TestSvUV_set)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::TestSvUV_set", "sv, val");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	UV	val = (UV)SvUV(ST(1));
	IV	RETVAL;
	dXSTARG;
#line 692 "RealPPPort.xs"
		SvUV_set(sv, val);
		RETVAL = SvUVX(sv) == val ? 42 : -1;
#line 1428 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_TestSvPVX_const); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_TestSvPVX_const)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::TestSvPVX_const", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	IV	RETVAL;
	dXSTARG;
#line 701 "RealPPPort.xs"
                RETVAL = strEQ(SvPVX_const(sv), "mhx") ? 43 : -1;
#line 1452 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_TestSvPVX_mutable); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_TestSvPVX_mutable)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::TestSvPVX_mutable", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	IV	RETVAL;
	dXSTARG;
#line 709 "RealPPPort.xs"
                RETVAL = strEQ(SvPVX_mutable(sv), "mhx") ? 44 : -1;
#line 1476 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_TestSvSTASH_set); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_TestSvSTASH_set)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::TestSvSTASH_set", "sv, name");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	char *	name = (char *)SvPV_nolen(ST(1));
#line 718 "RealPPPort.xs"
		sv = SvRV(sv);
		SvREFCNT_dec(SvSTASH(sv));
                SvSTASH_set(sv, (HV*) SvREFCNT_inc(gv_stashpv(name, 0)));
#line 1501 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_newSVpvn_share); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_newSVpvn_share)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::newSVpvn_share", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 729 "RealPPPort.xs"
		const char *s;
		SV *sv;
		STRLEN len;
		U32 hash;
#line 1524 "RealPPPort.c"
	int	RETVAL;
	dXSTARG;
#line 734 "RealPPPort.xs"
		RETVAL = 0;
		s = "mhx";
		len = 3;
		PERL_HASH(hash, (char *) s, len);
		sv = newSVpvn_share(s, len, 0);
		s = 0;
		RETVAL += strEQ(SvPV_nolen_const(sv), "mhx");
		RETVAL += SvCUR(sv) == len;
		RETVAL += SvSHARED_HASH(sv) == hash;
		SvREFCNT_dec(sv);
		s = "foobar";
		len = 6;
		PERL_HASH(hash, (char *) s, len);
		sv = newSVpvn_share(s, -(I32) len, hash);
		s = 0;
		RETVAL += strEQ(SvPV_nolen_const(sv), "foobar");
		RETVAL += SvCUR(sv) == len;
		RETVAL += SvSHARED_HASH(sv) == hash;
		SvREFCNT_dec(sv);
#line 1547 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_call_newCONSTSUB_1); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_call_newCONSTSUB_1)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::call_newCONSTSUB_1", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {

	call_newCONSTSUB_1();
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_call_newCONSTSUB_2); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_call_newCONSTSUB_2)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::call_newCONSTSUB_2", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {

	call_newCONSTSUB_2();
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_call_newCONSTSUB_3); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_call_newCONSTSUB_3)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::call_newCONSTSUB_3", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {

	call_newCONSTSUB_3();
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_CopSTASHPV); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_CopSTASHPV)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::CopSTASHPV", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char *	RETVAL;
	dXSTARG;
#line 776 "RealPPPort.xs"
		RETVAL = CopSTASHPV(PL_curcop);
#line 1627 "RealPPPort.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_CopFILE); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_CopFILE)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::CopFILE", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char *	RETVAL;
	dXSTARG;
#line 783 "RealPPPort.xs"
		RETVAL = CopFILE(PL_curcop);
#line 1650 "RealPPPort.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPVbyte); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPVbyte)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPVbyte", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 795 "RealPPPort.xs"
		char *str;
		STRLEN len;
#line 1673 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 798 "RealPPPort.xs"
		str = SvPVbyte(sv, len);
		RETVAL = strEQ(str, "mhx") ? (IV) len : (IV) -1;
#line 1679 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPV_nolen); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPV_nolen)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPV_nolen", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 807 "RealPPPort.xs"
		char *str;
#line 1701 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 809 "RealPPPort.xs"
		str = SvPV_nolen(sv);
		RETVAL = strEQ(str, "mhx") ? 42 : 0;
#line 1707 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPV_const); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPV_const)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPV_const", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 818 "RealPPPort.xs"
		const char *str;
		STRLEN len;
#line 1730 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 821 "RealPPPort.xs"
		str = SvPV_const(sv, len);
		RETVAL = len + (strEQ(str, "mhx") ? 40 : 0);
#line 1736 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPV_mutable); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPV_mutable)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPV_mutable", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 830 "RealPPPort.xs"
		char *str;
		STRLEN len;
#line 1759 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 833 "RealPPPort.xs"
		str = SvPV_mutable(sv, len);
		RETVAL = len + (strEQ(str, "mhx") ? 41 : 0);
#line 1765 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPV_flags); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPV_flags)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPV_flags", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 842 "RealPPPort.xs"
		char *str;
		STRLEN len;
#line 1788 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 845 "RealPPPort.xs"
		str = SvPV_flags(sv, len, SV_GMAGIC);
		RETVAL = len + (strEQ(str, "mhx") ? 42 : 0);
#line 1794 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPV_flags_const); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPV_flags_const)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPV_flags_const", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 854 "RealPPPort.xs"
		const char *str;
		STRLEN len;
#line 1817 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 857 "RealPPPort.xs"
		str = SvPV_flags_const(sv, len, SV_GMAGIC);
		RETVAL = len + (strEQ(str, "mhx") ? 43 : 0);
#line 1823 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPV_flags_const_nolen); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPV_flags_const_nolen)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPV_flags_const_nolen", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 866 "RealPPPort.xs"
		const char *str;
#line 1845 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 868 "RealPPPort.xs"
		str = SvPV_flags_const_nolen(sv, SV_GMAGIC);
		RETVAL = strEQ(str, "mhx") ? 47 : 0;
#line 1851 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPV_flags_mutable); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPV_flags_mutable)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPV_flags_mutable", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 877 "RealPPPort.xs"
		char *str;
		STRLEN len;
#line 1874 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 880 "RealPPPort.xs"
		str = SvPV_flags_mutable(sv, len, SV_GMAGIC);
		RETVAL = len + (strEQ(str, "mhx") ? 45 : 0);
#line 1880 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPV_force); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPV_force)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPV_force", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 889 "RealPPPort.xs"
		char *str;
		STRLEN len;
#line 1903 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 892 "RealPPPort.xs"
		str = SvPV_force(sv, len);
		RETVAL = len + (strEQ(str, "mhx") ? 46 : 0);
#line 1909 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPV_force_nolen); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPV_force_nolen)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPV_force_nolen", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 901 "RealPPPort.xs"
		char *str;
#line 1931 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 903 "RealPPPort.xs"
		str = SvPV_force_nolen(sv);
		RETVAL = strEQ(str, "mhx") ? 50 : 0;
#line 1937 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPV_force_mutable); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPV_force_mutable)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPV_force_mutable", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 912 "RealPPPort.xs"
		char *str;
		STRLEN len;
#line 1960 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 915 "RealPPPort.xs"
		str = SvPV_force_mutable(sv, len);
		RETVAL = len + (strEQ(str, "mhx") ? 48 : 0);
#line 1966 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPV_force_nomg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPV_force_nomg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPV_force_nomg", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 924 "RealPPPort.xs"
		char *str;
		STRLEN len;
#line 1989 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 927 "RealPPPort.xs"
		str = SvPV_force_nomg(sv, len);
		RETVAL = len + (strEQ(str, "mhx") ? 49 : 0);
#line 1995 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPV_force_nomg_nolen); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPV_force_nomg_nolen)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPV_force_nomg_nolen", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 936 "RealPPPort.xs"
		char *str;
#line 2017 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 938 "RealPPPort.xs"
		str = SvPV_force_nomg_nolen(sv);
		RETVAL = strEQ(str, "mhx") ? 53 : 0;
#line 2023 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPV_force_flags); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPV_force_flags)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPV_force_flags", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 947 "RealPPPort.xs"
		char *str;
		STRLEN len;
#line 2046 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 950 "RealPPPort.xs"
		str = SvPV_force_flags(sv, len, SV_GMAGIC);
		RETVAL = len + (strEQ(str, "mhx") ? 51 : 0);
#line 2052 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPV_force_flags_nolen); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPV_force_flags_nolen)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPV_force_flags_nolen", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 959 "RealPPPort.xs"
		char *str;
#line 2074 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 961 "RealPPPort.xs"
		str = SvPV_force_flags_nolen(sv, SV_GMAGIC);
		RETVAL = strEQ(str, "mhx") ? 55 : 0;
#line 2080 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPV_force_flags_mutable); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPV_force_flags_mutable)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPV_force_flags_mutable", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 970 "RealPPPort.xs"
		char *str;
		STRLEN len;
#line 2103 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 973 "RealPPPort.xs"
		str = SvPV_force_flags_mutable(sv, len, SV_GMAGIC);
		RETVAL = len + (strEQ(str, "mhx") ? 53 : 0);
#line 2109 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPV_nolen_const); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPV_nolen_const)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPV_nolen_const", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 982 "RealPPPort.xs"
		const char *str;
#line 2131 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 984 "RealPPPort.xs"
		str = SvPV_nolen_const(sv);
		RETVAL = strEQ(str, "mhx") ? 57 : 0;
#line 2137 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPV_nomg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPV_nomg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPV_nomg", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 993 "RealPPPort.xs"
		char *str;
		STRLEN len;
#line 2160 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 996 "RealPPPort.xs"
		str = SvPV_nomg(sv, len);
		RETVAL = len + (strEQ(str, "mhx") ? 55 : 0);
#line 2166 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPV_nomg_const); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPV_nomg_const)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPV_nomg_const", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 1005 "RealPPPort.xs"
		const char *str;
		STRLEN len;
#line 2189 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 1008 "RealPPPort.xs"
		str = SvPV_nomg_const(sv, len);
		RETVAL = len + (strEQ(str, "mhx") ? 56 : 0);
#line 2195 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvPV_nomg_const_nolen); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvPV_nomg_const_nolen)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvPV_nomg_const_nolen", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 1017 "RealPPPort.xs"
		const char *str;
#line 2217 "RealPPPort.c"
	IV	RETVAL;
	dXSTARG;
#line 1019 "RealPPPort.xs"
		str = SvPV_nomg_const_nolen(sv);
		RETVAL = strEQ(str, "mhx") ? 60 : 0;
#line 2223 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_MY_CXT_1); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_MY_CXT_1)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::MY_CXT_1", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 1031 "RealPPPort.xs"
		dMY_CXT;
		RETVAL = MY_CXT.dummy == 42;
		++MY_CXT.dummy;
#line 2248 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_MY_CXT_2); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_MY_CXT_2)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::MY_CXT_2", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 1040 "RealPPPort.xs"
		dMY_CXT;
		RETVAL = MY_CXT.dummy == 43;
#line 2272 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_MY_CXT_CLONE); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_MY_CXT_CLONE)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::MY_CXT_CLONE", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 1048 "RealPPPort.xs"
		MY_CXT_CLONE;
		RETVAL = 42;
#line 2296 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_iv_size); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_iv_size)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::iv_size", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	IV	RETVAL;
	dXSTARG;
#line 1060 "RealPPPort.xs"
		RETVAL = IVSIZE == sizeof(IV);
#line 2319 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_uv_size); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_uv_size)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::uv_size", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	IV	RETVAL;
	dXSTARG;
#line 1067 "RealPPPort.xs"
		RETVAL = UVSIZE == sizeof(UV);
#line 2342 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_iv_type); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_iv_type)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::iv_type", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	IV	RETVAL;
	dXSTARG;
#line 1074 "RealPPPort.xs"
		RETVAL = sizeof(IVTYPE) == sizeof(IV);
#line 2365 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_uv_type); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_uv_type)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::uv_type", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	IV	RETVAL;
	dXSTARG;
#line 1081 "RealPPPort.xs"
		RETVAL = sizeof(UVTYPE) == sizeof(UV);
#line 2388 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_mPUSHp); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_mPUSHp)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::mPUSHp", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1092 "RealPPPort.xs"
	EXTEND(SP, 3);
	mPUSHp("one", 3);
	mPUSHp("two", 3);
	mPUSHp("three", 5);
	XSRETURN(3);
#line 2415 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_mPUSHn); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_mPUSHn)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::mPUSHn", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1101 "RealPPPort.xs"
	EXTEND(SP, 3);
	mPUSHn(0.5);
	mPUSHn(-0.25);
	mPUSHn(0.125);
	XSRETURN(3);
#line 2442 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_mPUSHi); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_mPUSHi)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::mPUSHi", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1110 "RealPPPort.xs"
	EXTEND(SP, 3);
	mPUSHi(-1);
	mPUSHi(2);
	mPUSHi(-3);
	XSRETURN(3);
#line 2469 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_mPUSHu); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_mPUSHu)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::mPUSHu", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1119 "RealPPPort.xs"
	EXTEND(SP, 3);
	mPUSHu(1);
	mPUSHu(2);
	mPUSHu(3);
	XSRETURN(3);
#line 2496 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_mXPUSHp); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_mXPUSHp)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::mXPUSHp", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1128 "RealPPPort.xs"
	mXPUSHp("one", 3);
	mXPUSHp("two", 3);
	mXPUSHp("three", 5);
	XSRETURN(3);
#line 2522 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_mXPUSHn); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_mXPUSHn)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::mXPUSHn", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1136 "RealPPPort.xs"
	mXPUSHn(0.5);
	mXPUSHn(-0.25);
	mXPUSHn(0.125);
	XSRETURN(3);
#line 2548 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_mXPUSHi); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_mXPUSHi)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::mXPUSHi", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1144 "RealPPPort.xs"
	mXPUSHi(-1);
	mXPUSHi(2);
	mXPUSHi(-3);
	XSRETURN(3);
#line 2574 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_mXPUSHu); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_mXPUSHu)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::mXPUSHu", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1152 "RealPPPort.xs"
	mXPUSHu(1);
	mXPUSHu(2);
	mXPUSHu(3);
	XSRETURN(3);
#line 2600 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_checkmem); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_checkmem)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::checkmem", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 1164 "RealPPPort.xs"
    char *p;

#line 2622 "RealPPPort.c"
	int	RETVAL;
	dXSTARG;
#line 1167 "RealPPPort.xs"
    RETVAL = 0;
    Newx(p, 6, char);
    CopyD("Hello", p, 6, char);
    if (memEQ(p, "Hello", 6))
      RETVAL++;
    ZeroD(p, 6, char);
    if (memEQ(p, "\0\0\0\0\0\0", 6))
      RETVAL++;
    Poison(p, 6, char);
    if (memNE(p, "\0\0\0\0\0\0", 6))
      RETVAL++;
    Safefree(p);

    Newxz(p, 6, char);
    if (memEQ(p, "\0\0\0\0\0\0", 6))
      RETVAL++;
    Safefree(p);

    Newxc(p, 3, short, char);
    Safefree(p);

#line 2647 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvREFCNT); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvREFCNT)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvREFCNT", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1198 "RealPPPort.xs"
		SV *sv, *svr;
#line 2670 "RealPPPort.c"
#line 1200 "RealPPPort.xs"
		sv = newSV(0);
		XPUSHs(newSViv(SvREFCNT(sv) == 1));
		svr = SvREFCNT_inc(sv);
		XPUSHs(newSViv(sv == svr));
		XPUSHs(newSViv(SvREFCNT(sv) == 2));
		svr = SvREFCNT_inc_simple(sv);
		XPUSHs(newSViv(sv == svr));
		XPUSHs(newSViv(SvREFCNT(sv) == 3));
		svr = SvREFCNT_inc_NN(sv);
		XPUSHs(newSViv(sv == svr));
		XPUSHs(newSViv(SvREFCNT(sv) == 4));
		svr = SvREFCNT_inc_simple_NN(sv);
		XPUSHs(newSViv(sv == svr));
		XPUSHs(newSViv(SvREFCNT(sv) == 5));
		SvREFCNT_inc_void(sv);
		XPUSHs(newSViv(SvREFCNT(sv) == 6));
		SvREFCNT_inc_simple_void(sv);
		XPUSHs(newSViv(SvREFCNT(sv) == 7));
		SvREFCNT_inc_void_NN(sv);
		XPUSHs(newSViv(SvREFCNT(sv) == 8));
		SvREFCNT_inc_simple_void_NN(sv);
		XPUSHs(newSViv(SvREFCNT(sv) == 9));
		while (SvREFCNT(sv) > 1)
		  SvREFCNT_dec(sv);
		XPUSHs(newSViv(SvREFCNT(sv) == 1));
		SvREFCNT_dec(sv);
		XSRETURN(14);
#line 2699 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_vnewSVpvf); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_vnewSVpvf)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::vnewSVpvf", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	RETVAL;
#line 1235 "RealPPPort.xs"
		RETVAL = test_vnewSVpvf(aTHX_ "%s-%d", "Perl", 42);
#line 2721 "RealPPPort.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_sv_vcatpvf); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_vcatpvf)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_vcatpvf", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	SV *	RETVAL;
#line 1243 "RealPPPort.xs"
		RETVAL = newSVsv(sv);
		test_sv_vcatpvf(aTHX_ RETVAL, "%s-%d", "Perl", 42);
#line 2746 "RealPPPort.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_sv_vsetpvf); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_vsetpvf)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_vsetpvf", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	SV *	RETVAL;
#line 1252 "RealPPPort.xs"
		RETVAL = newSVsv(sv);
		test_sv_vsetpvf(aTHX_ RETVAL, "%s-%d", "Perl", 42);
#line 2771 "RealPPPort.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_sv_catpvf_mg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_catpvf_mg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_catpvf_mg", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 1261 "RealPPPort.xs"
#if (PERL_BCDVERSION >= 0x5004000)
		sv_catpvf_mg(sv, "%s-%d", "Perl", 42);
#endif
#line 2796 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_Perl_sv_catpvf_mg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_Perl_sv_catpvf_mg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::Perl_sv_catpvf_mg", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 1269 "RealPPPort.xs"
#if (PERL_BCDVERSION >= 0x5004000)
		Perl_sv_catpvf_mg(aTHX_ sv, "%s-%d", "-Perl", 43);
#endif
#line 2819 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_sv_catpvf_mg_nocontext); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_catpvf_mg_nocontext)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_catpvf_mg_nocontext", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 1277 "RealPPPort.xs"
#if (PERL_BCDVERSION >= 0x5004000)
#ifdef PERL_IMPLICIT_CONTEXT
		sv_catpvf_mg_nocontext(sv, "%s-%d", "-Perl", 44);
#else
		sv_catpvf_mg(sv, "%s-%d", "-Perl", 44);
#endif
#endif
#line 2846 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_sv_setpvf_mg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_setpvf_mg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_setpvf_mg", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 1289 "RealPPPort.xs"
#if (PERL_BCDVERSION >= 0x5004000)
		sv_setpvf_mg(sv, "%s-%d", "mhx", 42);
#endif
#line 2869 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_Perl_sv_setpvf_mg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_Perl_sv_setpvf_mg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::Perl_sv_setpvf_mg", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 1297 "RealPPPort.xs"
#if (PERL_BCDVERSION >= 0x5004000)
		Perl_sv_setpvf_mg(aTHX_ sv, "%s-%d", "foo", 43);
#endif
#line 2892 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_sv_setpvf_mg_nocontext); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_setpvf_mg_nocontext)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_setpvf_mg_nocontext", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
#line 1305 "RealPPPort.xs"
#if (PERL_BCDVERSION >= 0x5004000)
#ifdef PERL_IMPLICIT_CONTEXT
		sv_setpvf_mg_nocontext(sv, "%s-%d", "bar", 44);
#else
		sv_setpvf_mg(sv, "%s-%d", "bar", 44);
#endif
#endif
#line 2919 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_sv_setuv); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_setuv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_setuv", "uv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	UV	uv = (UV)SvUV(ST(0));
	SV *	RETVAL;
#line 1321 "RealPPPort.xs"
		RETVAL = newSViv(1);
		sv_setuv(RETVAL, uv);
#line 2942 "RealPPPort.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_newSVuv); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_newSVuv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::newSVuv", "uv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	UV	uv = (UV)SvUV(ST(0));
	SV *	RETVAL;
#line 1330 "RealPPPort.xs"
		RETVAL = newSVuv(uv);
#line 2966 "RealPPPort.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_sv_2uv); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_sv_2uv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::sv_2uv", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	UV	RETVAL;
	dXSTARG;
#line 1338 "RealPPPort.xs"
		RETVAL = sv_2uv(sv);
#line 2991 "RealPPPort.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_SvUVx); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_SvUVx)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::SvUVx", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	sv = ST(0);
	UV	RETVAL;
	dXSTARG;
#line 1346 "RealPPPort.xs"
		sv--;
		RETVAL = SvUVx(++sv);
#line 3016 "RealPPPort.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_XSRETURN_UV); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_XSRETURN_UV)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::XSRETURN_UV", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1354 "RealPPPort.xs"
		XSRETURN_UV(42);
#line 3039 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_PUSHu); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_PUSHu)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::PUSHu", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1359 "RealPPPort.xs"
		dTARG;
#line 3062 "RealPPPort.c"
#line 1361 "RealPPPort.xs"
		TARG = sv_newmortal();
		EXTEND(SP, 1);
		PUSHu(42);
		XSRETURN(1);
#line 3068 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_XPUSHu); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_XPUSHu)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::XPUSHu", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1369 "RealPPPort.xs"
		dTARG;
#line 3091 "RealPPPort.c"
#line 1371 "RealPPPort.xs"
		TARG = sv_newmortal();
		XPUSHu(43);
		XSRETURN(1);
#line 3096 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_my_snprintf); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_my_snprintf)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::my_snprintf", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1382 "RealPPPort.xs"
		char buf[128];
		int len;
#line 3120 "RealPPPort.c"
#line 1385 "RealPPPort.xs"
		len = my_snprintf(buf, sizeof buf, "foo%s%d", "bar", 42);
		XPUSHs(newSViv(len));
		XPUSHs(newSVpv(buf, 0));
		XSRETURN(2);
#line 3126 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_compare_PL_signals); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_compare_PL_signals)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::compare_PL_signals", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 1397 "RealPPPort.xs"
		{
		  U32 ref = get_PL_signals_1();
		  RETVAL = ref == get_PL_signals_2() && ref == get_PL_signals_3();
		}
#line 3152 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_PL_sv_undef); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_PL_sv_undef)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::PL_sv_undef", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	RETVAL;
#line 1407 "RealPPPort.xs"
		RETVAL = newSVsv(&PL_sv_undef);
#line 3174 "RealPPPort.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_PL_sv_yes); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_PL_sv_yes)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::PL_sv_yes", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	RETVAL;
#line 1414 "RealPPPort.xs"
		RETVAL = newSVsv(&PL_sv_yes);
#line 3197 "RealPPPort.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_PL_sv_no); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_PL_sv_no)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::PL_sv_no", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	RETVAL;
#line 1421 "RealPPPort.xs"
		RETVAL = newSVsv(&PL_sv_no);
#line 3220 "RealPPPort.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_PL_na); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_PL_na)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::PL_na", "string");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char *	string = (char *)SvPV_nolen(ST(0));
	int	RETVAL;
	dXSTARG;
#line 1429 "RealPPPort.xs"
		PL_na = strlen(string);
		RETVAL = PL_na;
#line 3246 "RealPPPort.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_PL_Sv); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_PL_Sv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::PL_Sv", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	RETVAL;
#line 1437 "RealPPPort.xs"
		PL_Sv = newSVpv("mhx", 0);
		RETVAL = PL_Sv;
#line 3269 "RealPPPort.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_PL_copline); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_PL_copline)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::PL_copline", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	RETVAL;
#line 1445 "RealPPPort.xs"
		RETVAL = newSViv((IV) PL_copline);
#line 3292 "RealPPPort.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_PL_expect); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_PL_expect)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::PL_expect", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	RETVAL;
#line 1452 "RealPPPort.xs"
		RETVAL = newSViv((IV) PL_expect);
#line 3315 "RealPPPort.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_PL_rsfp); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_PL_rsfp)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::PL_rsfp", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	RETVAL;
#line 1459 "RealPPPort.xs"
		RETVAL = newSViv(PL_rsfp != 0);
#line 3338 "RealPPPort.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_PL_rsfp_filters); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_PL_rsfp_filters)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::PL_rsfp_filters", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	RETVAL;
#line 1466 "RealPPPort.xs"
		RETVAL = newSViv(PL_rsfp_filters != 0);
#line 3361 "RealPPPort.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_PL_hexdigit); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_PL_hexdigit)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::PL_hexdigit", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	RETVAL;
#line 1473 "RealPPPort.xs"
		RETVAL = newSVpv((char *) PL_hexdigit, 0);
#line 3384 "RealPPPort.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_PL_hints); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_PL_hints)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::PL_hints", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	RETVAL;
#line 1480 "RealPPPort.xs"
		RETVAL = newSViv((IV) PL_hints);
#line 3407 "RealPPPort.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_PL_ppaddr); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_PL_ppaddr)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::PL_ppaddr", "string");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	char *	string = (char *)SvPV_nolen(ST(0));
#line 1488 "RealPPPort.xs"
		PUSHMARK(SP);
		XPUSHs(sv_2mortal(newSVpv(string, 0)));
		PUTBACK;
		ENTER;
		(void)*(PL_ppaddr[OP_UC])(aTHXR);
		SPAGAIN;
		LEAVE;
		XSRETURN(1);
#line 3439 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_other_variables); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_other_variables)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::other_variables", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1500 "RealPPPort.xs"
		int count = 0;
#line 3462 "RealPPPort.c"
#line 1502 "RealPPPort.xs"
		ppp_TESTVAR(PL_DBsignal);
		ppp_TESTVAR(PL_DBsingle);
		ppp_TESTVAR(PL_DBsub);
		ppp_TESTVAR(PL_DBtrace);
		ppp_TESTVAR(PL_compiling);
		ppp_TESTVAR(PL_curcop);
		ppp_TESTVAR(PL_curstash);
		ppp_TESTVAR(PL_debstash);
		ppp_TESTVAR(PL_defgv);
		ppp_TESTVAR(PL_diehook);
		ppp_TESTVAR(PL_dirty);
		ppp_TESTVAR(PL_dowarn);
		ppp_TESTVAR(PL_errgv);
		ppp_TESTVAR(PL_laststatval);
		ppp_TESTVAR(PL_no_modify);
		ppp_TESTVAR(PL_perl_destruct_level);
		ppp_TESTVAR(PL_perldb);
		ppp_TESTVAR(PL_stack_base);
		ppp_TESTVAR(PL_stack_sp);
		ppp_TESTVAR(PL_statcache);
		ppp_TESTVAR(PL_stdingv);
		ppp_TESTVAR(PL_sv_arenaroot);
		ppp_TESTVAR(PL_tainted);
		ppp_TESTVAR(PL_tainting);
		XSRETURN(count);
#line 3489 "RealPPPort.c"
	PUTBACK;
	return;
    }
}


XS(XS_Devel__PPPort_newRV_inc_REFCNT); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_newRV_inc_REFCNT)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::newRV_inc_REFCNT", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 1535 "RealPPPort.xs"
		SV *sv, *rv;
#line 3510 "RealPPPort.c"
	U32	RETVAL;
	dXSTARG;
#line 1537 "RealPPPort.xs"
		sv = newSViv(42);
		rv = newRV_inc(sv);
		SvREFCNT_dec(sv);
		RETVAL = SvREFCNT(sv);
		sv_2mortal(rv);
#line 3519 "RealPPPort.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_newRV_noinc_REFCNT); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_newRV_noinc_REFCNT)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::newRV_noinc_REFCNT", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 1548 "RealPPPort.xs"
		SV *sv, *rv;
#line 3540 "RealPPPort.c"
	U32	RETVAL;
	dXSTARG;
#line 1550 "RealPPPort.xs"
		sv = newSViv(42);
		rv = newRV_noinc(sv);
		RETVAL = SvREFCNT(sv);
		sv_2mortal(rv);
#line 3548 "RealPPPort.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_warner); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_warner)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::warner", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 1564 "RealPPPort.xs"
#if (PERL_BCDVERSION >= 0x5004000)
		warner(packWARN(WARN_MISC), "warner %s:%d", "bar", 42);
#endif
#line 3571 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_Perl_warner); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_Perl_warner)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::Perl_warner", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 1571 "RealPPPort.xs"
#if (PERL_BCDVERSION >= 0x5004000)
		Perl_warner(aTHX_ packWARN(WARN_MISC), "Perl_warner %s:%d", "bar", 42);
#endif
#line 3593 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_Perl_warner_nocontext); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_Perl_warner_nocontext)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::Perl_warner_nocontext", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 1578 "RealPPPort.xs"
#if (PERL_BCDVERSION >= 0x5004000)
		Perl_warner_nocontext(packWARN(WARN_MISC), "Perl_warner_nocontext %s:%d", "bar", 42);
#endif
#line 3615 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_ckWARN); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_ckWARN)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::ckWARN", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 1585 "RealPPPort.xs"
#if (PERL_BCDVERSION >= 0x5004000)
		if (ckWARN(WARN_MISC))
		  Perl_warner_nocontext(packWARN(WARN_MISC), "ckWARN %s:%d", "bar", 42);
#endif
#line 3638 "RealPPPort.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Devel__PPPort_grok_number); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_grok_number)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::grok_number", "string");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	string = ST(0);
#line 1598 "RealPPPort.xs"
		const char *pv;
		STRLEN len;
#line 3660 "RealPPPort.c"
	UV	RETVAL;
	dXSTARG;
#line 1601 "RealPPPort.xs"
		pv = SvPV(string, len);
		if (!grok_number(pv, len, &RETVAL))
		  XSRETURN_UNDEF;
#line 3667 "RealPPPort.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_grok_bin); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_grok_bin)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::grok_bin", "string");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	string = ST(0);
#line 1611 "RealPPPort.xs"
		char *pv;
		I32 flags;
		STRLEN len;
#line 3691 "RealPPPort.c"
	UV	RETVAL;
	dXSTARG;
#line 1615 "RealPPPort.xs"
		pv = SvPV(string, len);
		RETVAL = grok_bin(pv, &len, &flags, NULL);
#line 3697 "RealPPPort.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_grok_hex); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_grok_hex)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::grok_hex", "string");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	string = ST(0);
#line 1624 "RealPPPort.xs"
		char *pv;
		I32 flags;
		STRLEN len;
#line 3721 "RealPPPort.c"
	UV	RETVAL;
	dXSTARG;
#line 1628 "RealPPPort.xs"
		pv = SvPV(string, len);
		RETVAL = grok_hex(pv, &len, &flags, NULL);
#line 3727 "RealPPPort.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_grok_oct); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_grok_oct)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::grok_oct", "string");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	string = ST(0);
#line 1637 "RealPPPort.xs"
		char *pv;
		I32 flags;
		STRLEN len;
#line 3751 "RealPPPort.c"
	UV	RETVAL;
	dXSTARG;
#line 1641 "RealPPPort.xs"
		pv = SvPV(string, len);
		RETVAL = grok_oct(pv, &len, &flags, NULL);
#line 3757 "RealPPPort.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_Perl_grok_number); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_Perl_grok_number)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::Perl_grok_number", "string");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	string = ST(0);
#line 1650 "RealPPPort.xs"
		const char *pv;
		STRLEN len;
#line 3780 "RealPPPort.c"
	UV	RETVAL;
	dXSTARG;
#line 1653 "RealPPPort.xs"
		pv = SvPV(string, len);
		if (!Perl_grok_number(aTHX_ pv, len, &RETVAL))
		  XSRETURN_UNDEF;
#line 3787 "RealPPPort.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_Perl_grok_bin); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_Perl_grok_bin)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::Perl_grok_bin", "string");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	string = ST(0);
#line 1663 "RealPPPort.xs"
		char *pv;
		I32 flags;
		STRLEN len;
#line 3811 "RealPPPort.c"
	UV	RETVAL;
	dXSTARG;
#line 1667 "RealPPPort.xs"
		pv = SvPV(string, len);
		RETVAL = Perl_grok_bin(aTHX_ pv, &len, &flags, NULL);
#line 3817 "RealPPPort.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_Perl_grok_hex); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_Perl_grok_hex)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::Perl_grok_hex", "string");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	string = ST(0);
#line 1676 "RealPPPort.xs"
		char *pv;
		I32 flags;
		STRLEN len;
#line 3841 "RealPPPort.c"
	UV	RETVAL;
	dXSTARG;
#line 1680 "RealPPPort.xs"
		pv = SvPV(string, len);
		RETVAL = Perl_grok_hex(aTHX_ pv, &len, &flags, NULL);
#line 3847 "RealPPPort.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Devel__PPPort_Perl_grok_oct); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__PPPort_Perl_grok_oct)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Devel::PPPort::Perl_grok_oct", "string");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	string = ST(0);
#line 1689 "RealPPPort.xs"
		char *pv;
		I32 flags;
		STRLEN len;
#line 3871 "RealPPPort.c"
	UV	RETVAL;
	dXSTARG;
#line 1693 "RealPPPort.xs"
		pv = SvPV(string, len);
		RETVAL = Perl_grok_oct(aTHX_ pv, &len, &flags, NULL);
#line 3877 "RealPPPort.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Devel__PPPort); /* prototype to pass -Wmissing-prototypes */
XS(boot_Devel__PPPort)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("Devel::PPPort::no_THX_arg", XS_Devel__PPPort_no_THX_arg, file);
        newXS("Devel::PPPort::with_THX_arg", XS_Devel__PPPort_with_THX_arg, file);
        newXS("Devel::PPPort::G_SCALAR", XS_Devel__PPPort_G_SCALAR, file);
        newXS("Devel::PPPort::G_ARRAY", XS_Devel__PPPort_G_ARRAY, file);
        newXS("Devel::PPPort::G_DISCARD", XS_Devel__PPPort_G_DISCARD, file);
        newXS("Devel::PPPort::eval_sv", XS_Devel__PPPort_eval_sv, file);
        newXS("Devel::PPPort::eval_pv", XS_Devel__PPPort_eval_pv, file);
        newXS("Devel::PPPort::call_sv", XS_Devel__PPPort_call_sv, file);
        newXS("Devel::PPPort::call_pv", XS_Devel__PPPort_call_pv, file);
        newXS("Devel::PPPort::call_argv", XS_Devel__PPPort_call_argv, file);
        newXS("Devel::PPPort::call_method", XS_Devel__PPPort_call_method, file);
        newXS("Devel::PPPort::load_module", XS_Devel__PPPort_load_module, file);
        newXS("Devel::PPPort::newSVpvs", XS_Devel__PPPort_newSVpvs, file);
        newXS("Devel::PPPort::sv_catpvs", XS_Devel__PPPort_sv_catpvs, file);
        newXS("Devel::PPPort::sv_setpvs", XS_Devel__PPPort_sv_setpvs, file);
        newXS("Devel::PPPort::hv_fetchs", XS_Devel__PPPort_hv_fetchs, file);
        newXS("Devel::PPPort::hv_stores", XS_Devel__PPPort_hv_stores, file);
        newXS("Devel::PPPort::my_strlfunc", XS_Devel__PPPort_my_strlfunc, file);
        newXS("Devel::PPPort::sv_catpv_mg", XS_Devel__PPPort_sv_catpv_mg, file);
        newXS("Devel::PPPort::sv_catpvn_mg", XS_Devel__PPPort_sv_catpvn_mg, file);
        newXS("Devel::PPPort::sv_catsv_mg", XS_Devel__PPPort_sv_catsv_mg, file);
        newXS("Devel::PPPort::sv_setiv_mg", XS_Devel__PPPort_sv_setiv_mg, file);
        newXS("Devel::PPPort::sv_setnv_mg", XS_Devel__PPPort_sv_setnv_mg, file);
        newXS("Devel::PPPort::sv_setpv_mg", XS_Devel__PPPort_sv_setpv_mg, file);
        newXS("Devel::PPPort::sv_setpvn_mg", XS_Devel__PPPort_sv_setpvn_mg, file);
        newXS("Devel::PPPort::sv_setsv_mg", XS_Devel__PPPort_sv_setsv_mg, file);
        newXS("Devel::PPPort::sv_setuv_mg", XS_Devel__PPPort_sv_setuv_mg, file);
        newXS("Devel::PPPort::sv_usepvn_mg", XS_Devel__PPPort_sv_usepvn_mg, file);
        newXS("Devel::PPPort::SvVSTRING_mg", XS_Devel__PPPort_SvVSTRING_mg, file);
        newXS("Devel::PPPort::sv_magic_portable", XS_Devel__PPPort_sv_magic_portable, file);
        newXS("Devel::PPPort::gv_stashpvn", XS_Devel__PPPort_gv_stashpvn, file);
        newXS("Devel::PPPort::get_sv", XS_Devel__PPPort_get_sv, file);
        newXS("Devel::PPPort::get_av", XS_Devel__PPPort_get_av, file);
        newXS("Devel::PPPort::get_hv", XS_Devel__PPPort_get_hv, file);
        newXS("Devel::PPPort::get_cv", XS_Devel__PPPort_get_cv, file);
        newXS("Devel::PPPort::newSVpvn", XS_Devel__PPPort_newSVpvn, file);
        newXS("Devel::PPPort::xsreturn", XS_Devel__PPPort_xsreturn, file);
        newXS("Devel::PPPort::boolSV", XS_Devel__PPPort_boolSV, file);
        newXS("Devel::PPPort::DEFSV", XS_Devel__PPPort_DEFSV, file);
        newXS("Devel::PPPort::ERRSV", XS_Devel__PPPort_ERRSV, file);
        newXS("Devel::PPPort::UNDERBAR", XS_Devel__PPPort_UNDERBAR, file);
        newXS("Devel::PPPort::prepush", XS_Devel__PPPort_prepush, file);
        newXS("Devel::PPPort::PERL_ABS", XS_Devel__PPPort_PERL_ABS, file);
        newXS("Devel::PPPort::SVf", XS_Devel__PPPort_SVf, file);
        newXS("Devel::PPPort::exception", XS_Devel__PPPort_exception, file);
        newXS("Devel::PPPort::TestSvUV_set", XS_Devel__PPPort_TestSvUV_set, file);
        newXS("Devel::PPPort::TestSvPVX_const", XS_Devel__PPPort_TestSvPVX_const, file);
        newXS("Devel::PPPort::TestSvPVX_mutable", XS_Devel__PPPort_TestSvPVX_mutable, file);
        newXS("Devel::PPPort::TestSvSTASH_set", XS_Devel__PPPort_TestSvSTASH_set, file);
        newXS("Devel::PPPort::newSVpvn_share", XS_Devel__PPPort_newSVpvn_share, file);
        newXS("Devel::PPPort::call_newCONSTSUB_1", XS_Devel__PPPort_call_newCONSTSUB_1, file);
        newXS("Devel::PPPort::call_newCONSTSUB_2", XS_Devel__PPPort_call_newCONSTSUB_2, file);
        newXS("Devel::PPPort::call_newCONSTSUB_3", XS_Devel__PPPort_call_newCONSTSUB_3, file);
        newXS("Devel::PPPort::CopSTASHPV", XS_Devel__PPPort_CopSTASHPV, file);
        newXS("Devel::PPPort::CopFILE", XS_Devel__PPPort_CopFILE, file);
        newXS("Devel::PPPort::SvPVbyte", XS_Devel__PPPort_SvPVbyte, file);
        newXS("Devel::PPPort::SvPV_nolen", XS_Devel__PPPort_SvPV_nolen, file);
        newXS("Devel::PPPort::SvPV_const", XS_Devel__PPPort_SvPV_const, file);
        newXS("Devel::PPPort::SvPV_mutable", XS_Devel__PPPort_SvPV_mutable, file);
        newXS("Devel::PPPort::SvPV_flags", XS_Devel__PPPort_SvPV_flags, file);
        newXS("Devel::PPPort::SvPV_flags_const", XS_Devel__PPPort_SvPV_flags_const, file);
        newXS("Devel::PPPort::SvPV_flags_const_nolen", XS_Devel__PPPort_SvPV_flags_const_nolen, file);
        newXS("Devel::PPPort::SvPV_flags_mutable", XS_Devel__PPPort_SvPV_flags_mutable, file);
        newXS("Devel::PPPort::SvPV_force", XS_Devel__PPPort_SvPV_force, file);
        newXS("Devel::PPPort::SvPV_force_nolen", XS_Devel__PPPort_SvPV_force_nolen, file);
        newXS("Devel::PPPort::SvPV_force_mutable", XS_Devel__PPPort_SvPV_force_mutable, file);
        newXS("Devel::PPPort::SvPV_force_nomg", XS_Devel__PPPort_SvPV_force_nomg, file);
        newXS("Devel::PPPort::SvPV_force_nomg_nolen", XS_Devel__PPPort_SvPV_force_nomg_nolen, file);
        newXS("Devel::PPPort::SvPV_force_flags", XS_Devel__PPPort_SvPV_force_flags, file);
        newXS("Devel::PPPort::SvPV_force_flags_nolen", XS_Devel__PPPort_SvPV_force_flags_nolen, file);
        newXS("Devel::PPPort::SvPV_force_flags_mutable", XS_Devel__PPPort_SvPV_force_flags_mutable, file);
        newXS("Devel::PPPort::SvPV_nolen_const", XS_Devel__PPPort_SvPV_nolen_const, file);
        newXS("Devel::PPPort::SvPV_nomg", XS_Devel__PPPort_SvPV_nomg, file);
        newXS("Devel::PPPort::SvPV_nomg_const", XS_Devel__PPPort_SvPV_nomg_const, file);
        newXS("Devel::PPPort::SvPV_nomg_const_nolen", XS_Devel__PPPort_SvPV_nomg_const_nolen, file);
        newXS("Devel::PPPort::MY_CXT_1", XS_Devel__PPPort_MY_CXT_1, file);
        newXS("Devel::PPPort::MY_CXT_2", XS_Devel__PPPort_MY_CXT_2, file);
        newXS("Devel::PPPort::MY_CXT_CLONE", XS_Devel__PPPort_MY_CXT_CLONE, file);
        newXS("Devel::PPPort::iv_size", XS_Devel__PPPort_iv_size, file);
        newXS("Devel::PPPort::uv_size", XS_Devel__PPPort_uv_size, file);
        newXS("Devel::PPPort::iv_type", XS_Devel__PPPort_iv_type, file);
        newXS("Devel::PPPort::uv_type", XS_Devel__PPPort_uv_type, file);
        newXS("Devel::PPPort::mPUSHp", XS_Devel__PPPort_mPUSHp, file);
        newXS("Devel::PPPort::mPUSHn", XS_Devel__PPPort_mPUSHn, file);
        newXS("Devel::PPPort::mPUSHi", XS_Devel__PPPort_mPUSHi, file);
        newXS("Devel::PPPort::mPUSHu", XS_Devel__PPPort_mPUSHu, file);
        newXS("Devel::PPPort::mXPUSHp", XS_Devel__PPPort_mXPUSHp, file);
        newXS("Devel::PPPort::mXPUSHn", XS_Devel__PPPort_mXPUSHn, file);
        newXS("Devel::PPPort::mXPUSHi", XS_Devel__PPPort_mXPUSHi, file);
        newXS("Devel::PPPort::mXPUSHu", XS_Devel__PPPort_mXPUSHu, file);
        newXS("Devel::PPPort::checkmem", XS_Devel__PPPort_checkmem, file);
        newXS("Devel::PPPort::SvREFCNT", XS_Devel__PPPort_SvREFCNT, file);
        newXS("Devel::PPPort::vnewSVpvf", XS_Devel__PPPort_vnewSVpvf, file);
        newXS("Devel::PPPort::sv_vcatpvf", XS_Devel__PPPort_sv_vcatpvf, file);
        newXS("Devel::PPPort::sv_vsetpvf", XS_Devel__PPPort_sv_vsetpvf, file);
        newXS("Devel::PPPort::sv_catpvf_mg", XS_Devel__PPPort_sv_catpvf_mg, file);
        newXS("Devel::PPPort::Perl_sv_catpvf_mg", XS_Devel__PPPort_Perl_sv_catpvf_mg, file);
        newXS("Devel::PPPort::sv_catpvf_mg_nocontext", XS_Devel__PPPort_sv_catpvf_mg_nocontext, file);
        newXS("Devel::PPPort::sv_setpvf_mg", XS_Devel__PPPort_sv_setpvf_mg, file);
        newXS("Devel::PPPort::Perl_sv_setpvf_mg", XS_Devel__PPPort_Perl_sv_setpvf_mg, file);
        newXS("Devel::PPPort::sv_setpvf_mg_nocontext", XS_Devel__PPPort_sv_setpvf_mg_nocontext, file);
        newXS("Devel::PPPort::sv_setuv", XS_Devel__PPPort_sv_setuv, file);
        newXS("Devel::PPPort::newSVuv", XS_Devel__PPPort_newSVuv, file);
        newXS("Devel::PPPort::sv_2uv", XS_Devel__PPPort_sv_2uv, file);
        newXS("Devel::PPPort::SvUVx", XS_Devel__PPPort_SvUVx, file);
        newXS("Devel::PPPort::XSRETURN_UV", XS_Devel__PPPort_XSRETURN_UV, file);
        newXS("Devel::PPPort::PUSHu", XS_Devel__PPPort_PUSHu, file);
        newXS("Devel::PPPort::XPUSHu", XS_Devel__PPPort_XPUSHu, file);
        newXS("Devel::PPPort::my_snprintf", XS_Devel__PPPort_my_snprintf, file);
        newXS("Devel::PPPort::compare_PL_signals", XS_Devel__PPPort_compare_PL_signals, file);
        newXS("Devel::PPPort::PL_sv_undef", XS_Devel__PPPort_PL_sv_undef, file);
        newXS("Devel::PPPort::PL_sv_yes", XS_Devel__PPPort_PL_sv_yes, file);
        newXS("Devel::PPPort::PL_sv_no", XS_Devel__PPPort_PL_sv_no, file);
        newXS("Devel::PPPort::PL_na", XS_Devel__PPPort_PL_na, file);
        newXS("Devel::PPPort::PL_Sv", XS_Devel__PPPort_PL_Sv, file);
        newXS("Devel::PPPort::PL_copline", XS_Devel__PPPort_PL_copline, file);
        newXS("Devel::PPPort::PL_expect", XS_Devel__PPPort_PL_expect, file);
        newXS("Devel::PPPort::PL_rsfp", XS_Devel__PPPort_PL_rsfp, file);
        newXS("Devel::PPPort::PL_rsfp_filters", XS_Devel__PPPort_PL_rsfp_filters, file);
        newXS("Devel::PPPort::PL_hexdigit", XS_Devel__PPPort_PL_hexdigit, file);
        newXS("Devel::PPPort::PL_hints", XS_Devel__PPPort_PL_hints, file);
        newXS("Devel::PPPort::PL_ppaddr", XS_Devel__PPPort_PL_ppaddr, file);
        newXS("Devel::PPPort::other_variables", XS_Devel__PPPort_other_variables, file);
        newXS("Devel::PPPort::newRV_inc_REFCNT", XS_Devel__PPPort_newRV_inc_REFCNT, file);
        newXS("Devel::PPPort::newRV_noinc_REFCNT", XS_Devel__PPPort_newRV_noinc_REFCNT, file);
        newXS("Devel::PPPort::warner", XS_Devel__PPPort_warner, file);
        newXS("Devel::PPPort::Perl_warner", XS_Devel__PPPort_Perl_warner, file);
        newXS("Devel::PPPort::Perl_warner_nocontext", XS_Devel__PPPort_Perl_warner_nocontext, file);
        newXS("Devel::PPPort::ckWARN", XS_Devel__PPPort_ckWARN, file);
        newXS("Devel::PPPort::grok_number", XS_Devel__PPPort_grok_number, file);
        newXS("Devel::PPPort::grok_bin", XS_Devel__PPPort_grok_bin, file);
        newXS("Devel::PPPort::grok_hex", XS_Devel__PPPort_grok_hex, file);
        newXS("Devel::PPPort::grok_oct", XS_Devel__PPPort_grok_oct, file);
        newXS("Devel::PPPort::Perl_grok_number", XS_Devel__PPPort_Perl_grok_number, file);
        newXS("Devel::PPPort::Perl_grok_bin", XS_Devel__PPPort_Perl_grok_bin, file);
        newXS("Devel::PPPort::Perl_grok_hex", XS_Devel__PPPort_Perl_grok_hex, file);
        newXS("Devel::PPPort::Perl_grok_oct", XS_Devel__PPPort_Perl_grok_oct, file);

    /* Initialisation Section */

#line 201 "RealPPPort.xs"
	/* ---- code from parts/inc/misc ---- */
	newXS("Devel::PPPort::dXSTARG", XS_Devel__PPPort_dXSTARG, file);
	newXS("Devel::PPPort::dAXMARK", XS_Devel__PPPort_dAXMARK, file);

	/* ---- code from parts/inc/MY_CXT ---- */
	{
	  MY_CXT_INIT;
	  /* If any of the fields in the my_cxt_t struct need
	   * to be initialised, do it here.
	   */
	  MY_CXT.dummy = 42;
	}

#line 4054 "RealPPPort.c"

    /* End of Initialisation Section */

    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

