wird angegeben <> die elektrische stromstaerke <>  <> in ampere <> 50
angibt <> der ph-wert <> den saeuregrad <> von einer loesung <> 50
angibt <> die kernladungszahl <> die anzahl <> der protonen <> 50
bedeutet <> _cern_ <> _europaeische_organisation_fuer_kernforschung_ <>  <> (true)
bedeutet <> tft <> thin film transistor <>  <> (true)
befassen <>die mendelschen gesetze <> sich <> mit vererbungsgesetzen <> (true)
beschreiben <> die mendelschen regeln <> die vererbungsregeln <>  <> (true)
beschrieb <> _albert_einstein_ <> die relativitaetstheorie <>  <> (true)
bestehen <> die blaeschen <>  <> in dem mineralwasser aus kohlendioxid <> (true)
besteht <> die atomhuelle <>  <> aus elektronen <> (true)
besteht <> die mine <>  <> aus graphit;von einem bleistift <> (true)
besteht <> die seife <>  <> aus salzen von fettsaeuren <> (true)
besteht <> ein diamant <>  <> aus reinem kohlenstoff <> (true)
besteht <> ein getreidekorn <>  <> aus schale mehlkoerper und keimling <> (true)
besteht <> ein molekuel <>  <> aus mindestens atomen <> (true)
besteht <> erdgas <> hauptsaechlich <> aus methan <> (true)
besteht <> erdoel <> hauptsaechlich <> aus kohlenstoff <> (true)
besteht <> gelantine <> hauptsaechlich <> aus glutin <> (true)
besteht <> marmor <> hauptsaechlich <> aus calciumcarbonat <> (true)
besteht <>  <>  <> ein korund aus eisenoxid <> (true)
besteht <> quarz <>  <> aus siliziumdioxid <> (true)
besteht <> salz <>  <> aus kristallen <> (true)
besteht <> schnee <>  <> aus kristallen <> (true)
besteht <> wasser <> aus sauerstoff und wasserstoff <>  <> (true)
besteht <> zucker <>  <> aus kristallen <> (true)
bildet <> eine fluessigkeit <> eine oberflaeche <>  <> (true)
dienen <> die weissen blutkoerperchen <>  <>  der vernichtung von viren bzw bakterien <> (true)
dienen <>  <>  <> die weissen blutkoerperchen der immunabwehr <> (true)
dient <> benzolsaeure <> als konservierungsmittel <>  <> (true)
dient <> die c-14-methode <>  <> zur altersbestimmung <> (true)
dient <> die schweissabsonderung <>  <> der waermeregulation <> (true)
dient <> eine zentrifuge <>  <> zur mechanischen trennung von gemischen <> (true)
dient <> karbolsaeure <> als desinfektionsmittel <>  <> (true)
dient <> kohlenstoff-14 <>  <> der radiometrischen altersbestimmung <> (true)
dient <> natriumglutamat <> als geschmacksverstaerker <> in lebensmitteln <> (true)
enhaelt <> margarine <> einen butter <> nicht <> (true)
enhaelt <> marzipan <> mandeln <>  <> (true)
entdeckte <> _irene_curie_ <> die kuenstliche radioaktivitaet <>  <> (true)
entdeckte <> _marie_curie_ <> 1898 das polonium <>  <> (true)
entdeckte <> paracelsus <> das zink <>  <> (true)
entdeckte <> robert brown <> die molekuelbewegung <>  <> (true)
entdeckt wurde <> das chloroform <>  <> 1831 <> (true)
entdeckt wurde <> europium <>  <> 1896 <> (true)
entdeckt wurde <> jod <>  <> 1811 <> (true)
enthaelt <> chromargan <> ein kupfer <> nicht <> (true)
enthaelt <> der schweiss <> butansaeure <>  <> (true)
enthaelt <> kaffee <>  <> ueber 200 verschiedene chemische verbindungen <> (true)
enthaelt <> margarine <> kartoffelstaerke <>  <> (true)
enthalten ist <> ethanol <>  <> in bier <> (true)
enthalten ist <> ethanol <>  <> in schnaps <> (true)
enthalten ist <> ethanol <>  <> in wein <> (true)
entspricht <> ein hektar <> 100 quadratmetern <>  <> (true)
entsteht <> bei einer metallbindung <> ein gitter <>  <> (true)
entsteht <> ein salz <>  <> durch ionenbindung <> (true)
entsteht <> gummi <>  <> durch vulkanisation aus rohkautschuk <> (true)
entsteht <> kohlendioxid <>  <> durch durch die verbrennung von fossilen brennstoffen <> (true)
entsteht <> polyvinylchlorid <>  <> durch polymerisation <> (true)
entwickelt hat <> _alessandro_graf_volta_ <> die theorie des elektrischen stroms <>  <> (true)
erhoeht <> glukagon <> den blutzuckerspiegel <>  <> (true)
erkennt <> das alter der baeume<> man <> an den jahresringen <> (true)
erzeugen kann/can <> eine solarzelle <> energie <>  <> (true)
erzeugen kann/can <> man <> elektrische energie <> mit einer solarzelle <> (true)
erzeugter ist <> ein homunkulus <> ein kuenstlich mensch <>  <> (true)
gefriert <> wasser <> bei 32 grad fahrenheit <>  <> (true)
gefuellt wurden <> gasballons <>  <> mit wasserstoff <> (true)
gefuellt wurden <> luftschiffe <>  <> mit wasserstoff <> (true)
gehoeren <> actinoide <>  <> zu den metallen <> (true)
gehoert <> uran <>  <> zu den actinoiden <> (true)
gewinnt <> die verschiedenen bestandteile des erdoels <> man <> durch fraktionierende destillation <> (true)
gewinnt <> penicillin <> man <> aus schimmelpilzen <> (true)
gibt <> es <> 10 chemische elemente <>  <> (true)
gibt <> es <> 20 reinelemente <>  <> (true)
gibt <> es <> 93 natuerliche elemente <>  <> (true)
haben <> alzheimer-patienten <> ein durstgefuehl <> nicht <> (true)
haben <> elektronen <> eine negative ladung <>  <> (true)
hat <> 46 chromosomen <> eine menschliche zelle <>  <> (true)
hat <> actinium <> _das_chemische_zeichen_ac_ <>  <> (true)
hat <> actinium <> die ordnungszahl <> 89 <> (true)
hat <> actinium <> einen schmelzpunkt  <> _von_1047_grad_celsius_ <> (true)
hat <> actinium <> einen siedepunkt  <> _von_3197_grad_celsius_ <> (true)
hat <> aluminium <> _das_chemische_zeichen_al_ <>  <> (true)
hat <> aluminium <> die ordnungszahl <> 13 <> (true)
hat <> aluminium <> einen schmelzpunkt  <> _von_660_grad_celsius_ <> (true)
hat <> aluminium <> einen siedepunkt  <> _von_2467_grad_celsius_ <> (true)
hat <> americium <> _das_chemische_zeichen_am_ <>  <> (true)
hat <> americium <> die ordnungszahl <> 95 <> (true)
hat <> americium <> einen schmelzpunkt  <> _von_994_grad_celsius_ <> (true)
hat <> americium <> einen siedepunkt  <> _von_2607_grad_celsius_ <> (true)
hat <> antimon <> _das_chemische_zeichen_sb_ <>  <> (true)
hat <> antimon <> die ordnungszahl <> 51 <> (true)
hat <> antimon <> einen schmelzpunkt  <> _von_630_grad_celsius_ <> (true)
hat <> antimon <> einen siedepunkt  <> _von_1750_grad_celsius_ <> (true)
hat <> argon <> _das_chemische_zeichen_ar_ <>  <> (true)
hat <> argon <> die ordnungszahl <> 18 <> (true)
hat <> argon <> einen schmelzpunkt  <> _von_minus_190_grad_celsius_ <> (true)
hat <> argon <> einen siedepunkt  <> _von_minus_186_grad_celsius_ <> (true)
hat <> arsen <> _das_chemische_zeichen_as_ <>  <> (true)
hat <> arsen <> _das_chemische_zeichen_at_ <>  <> (true)
hat <> arsen <> die ordnungszahl <> 33 <> (true)
hat <> arsen <> die ordnungszahl <> 85 <> (true)
hat <> arsen <> einen schmelzpunkt  <> _von_302_grad_celsius_ <> (true)
hat <> arsen <> einen schmelzpunkt  <> _von_613_grad_celsius_ <> (true)
hat <> arsen <> einen siedepunkt  <> _von_337_grad_celsius_ <> (true)
hat <> barium <> _das_chemische_zeichen_ba_ <>  <> (true)
hat <> barium <> die ordnungszahl <> 56 <> (true)
hat <> barium <> einen schmelzpunkt  <> _von_725_grad_celsius_ <> (true)
hat <> barium <> einen siedepunkt  <> _von_1640_grad_celsius_ <> (true)
hat <> berkelium <> _das_chemische_zeichen_bk_ <>  <> (true)
hat <> berkelium <> die ordnungszahl <> 97 <> (true)
hat <> berkelium <> einen schmelzpunkt  <> _von_986_grad_celsius_ <> (true)
hat <> beryllium <> _das_chemische_zeichen_be_ <>  <> (true)
hat <> beryllium <> die ordungszahl <> 4 <> (true)
hat <> beryllium <> einen schmelzpunkt  <> _von_1278_grad_celsius_ <> (true)
hat <> beryllium <> einen siedepunkt  <> _von_2970_grad_celsius_ <> (true)
hat <> bismut <> _das_chemische_zeichen_bi_ <>  <> (true)
hat <> bismut <> die ordnungszahl <> 83 <> (true)
hat <> bismut <> einen schmelzpunkt  <> _von_271_grad_celsius_ <> (true)
hat <> bismut <> einen siedepunkt  <> _von_1560_grad_celsius_ <> (true)
hat <> blausaeure <> _das_chemische_zeichen_hcn_ <>  <> (true)
hat <> blei <> _das_chemische_zeichen_pb_ <>  <> (true)
hat <> blei <> die ordungszahl <> 82 <> (true)
hat <> blei <> _einen_schmelzpunkt_327_grad_celsius_ <>  <> (true)
hat <> blei <> einen siedepunkt  <> _von_1740_grad_celsius_ <> (true)
hat <> bohrium <> _das_chemische_zeichen_bh_ <>  <> (true)
hat <> bohrium <> die ordnungszahl <> 107 <> (true)
hat <> bohrium <> die ordnungszahl <> 5 <> (true)
hat <> bohrium <> einen schmelzpunkt  <> _von_230_grad_celsius_ <> (true)
hat <> bohrium <> einen siedepunkt  <> _von_2550_grad_celsius_ <> (true)
hat <> bor <> _das_chemische_zeichen_b_ <>  <> (true)
hat <> bor <> die ordnungszahl <> 5 <> (true)
hat <> brom <> _das_chemische_zeichen_br_ <>  <> (true)
hat <> brom <> die ordnungszahl <> 35 <> (true)
hat <> brom <> einen schmelzpunkt  <> von minus 7 grad_celsius <> (true)
hat <> brom <> einen siedepunkt  <> _von_59_grad_celsius_ <> (true)
hat <> cadmium <> _das_chemische_zeichen_cd_ <>  <> (true)
hat <> cadmium <> die ordnungszahl <>  <> (true)
hat <> cadmium <> einen schmelzpunkt <> _von_321_grad_celsius_ <> (true)
hat <> cadmium <> einen siedpunkt  <> _von_765_grad_celsius_ <> (true)
hat <> caesium <> _das_chemische_zeichen_cs_ <>  <> (true)
hat <> caesium <> die ordnungszahl <> 55 <> (true)
hat <> caesium <> einen schmelzpunkt  <> _von_28_grad_celsius_ <> (true)
hat <> caesium <> einen siedepunkt  <> _von_690_grad_celsius_ <> (true)
hat <> caesium <>  <> das groesste natuerliche metall <> (true)
hat <> calcium <> _das_chemische_zeichen_ca_ <>  <> (true)
hat <> calcium <> die ordungszahl <> 20 <> (true)
hat <> calcium <> einen schmelzpunkt <> _von_1487_grad_celsius_ <> (true)
hat <> calcium <> eine schmelzpunkt <> _von_839_grad_celsius_ <> (true)
hat <> californium <> _das_chemische_zeichen_cf_ <>  <> (true)
hat <> californium <> die ordungszahl <> 98 <> (true)
hat <> californium <> einen schmelzpunkt <> _von_90_grad_celsius_ <> (true)
hat <> cer <> _das_chemische_zeichen_ce_ <>  <> (true)
hat <> cer <> die ordungszahl <> 58 <> (true)
hat <> cer <> einen schmelzpunkt <> _von_798_grad_celsius_ <> (true)
hat <> cer <> einen siedepunkt <> _von_3257_grad_celsius_ <> (true)
hat <> chlor <> _das_chemische_zeichen_ci_ <>  <> (true)
hat <> chlor <> die ordungszahl <> 17 <> (true)
hat <> chlor <> einen schmelzpunkt <> _von_minus_101_grad_celsius_ <> (true)
hat <> chlor <> einen siedepunkt <> _von_minus_34_grad_celsius_ <> (true)
hat <> chrom <> _das_chemische_zeichen_cr_ <>  <> (true)
hat <> chrom <> die ordnungszahl <> 24 <> (true)
hat <> chrom <> einen schmelzpunkt <> _von_1857_grad_celsius_ <> (true)
hat <> chrom <> einen siedepunkt <> _von_2482_grad_celsius_ <> (true)
hat <> cobalt <> _das_chemische_zeichen_co_ <>  <> (true)
hat <> cobalt <> die ordnungszahl <> 27 <> (true)
hat <> cobalt <> einen schmelzpunkt <> _von_1495_grad_celsius_ <> (true)
hat <> cobalt <> einen siedepunkt <> _von_2870_grad_celsius_ <> (true)
hat <> curium <> _das_chemische_zeichen_cm_ <>  <> (true)
hat <> curium <> die ordnungszahl <> 96 <> (true)
hat <> curium <> einen schmelzpunkt <> _von_1340_grad_celsius_ <> (true)
hat <> darmstadtium <> _das_chemische_zeichen_ds_ <>  <> (true)
hat <> darmstadtium <> die ordnungszahl <> 110 <> (true)
hat <> das atomium <> 9 kugeln <> <> (true)
hat <> das periodensystem <> 7 perioden <>  <> (true)
hat <> die menschliche retina <> drei zapfentypen <>  <> (true)
hat <> dubnium <> _das_chemische_zeichen_db_ <>  <> (true)
hat <> dubnium <> die ordnungszahl <> 105 <> (true)
hat <> dysprosium <> _das_chemische_zeichen_dy_ <>  <> (true)
hat <> dysprosium <> die ordungszahl <> 66 <> (true)
hat <> eine fluessigkeit <> ein bestimmtes volumen <>  <> (true)
hat <> ein erwachsener mensch <> 32 zaehne <>  <> (true)
hat <> ein festkoerper <> eine bestimmte gestalt <>  <> (true)
hat <> ein kilowatt <>  <> 1,36 ps <> (true)
hat <> einsteinium <> _das_chemische_zeichen_es_ <>  <> (true)
hat <> einsteinium <> die ordnungszahl <> 99 <> (true)
hat <> einsteinium <> einen schmelzpunkt <> _von_860_grad_celsius_ <> (true)
hat <> eisen <> _das_chemische_zeichen_fe_ <>  <> (true)
hat <> eisen <> die ordnungszahl <> 26 <> (true)
hat <> eisen <> einen schmelzpunkt <> _von_1535_grad_celsius_ <> (true)
hat <> eisen <> einen siedepunkt <> _von_2750_grad_celsius_ <> (true)
hat <> erbium <> _das_chemische_zeichen_er_ <>  <> (true)
hat <> erbium <> die ordnungszahl <> 68 <> (true)
hat <> erbium <> einen schmelzpunkt <> _von_1522_grad_celsius_ <> (true)
hat <> europium <> _das_chemische_zeichen_eu_ <>  <> (true)
hat <> europium <> die ordungszahl <> 63 <> (true)
hat <> europium <> einen schmelzpunkt <> _von_822_grad_celsius_ <> (true)
hat <> europium <> einen siedepunkt <> _von_1597_grad_celsius_ <> (true)
hat <> gadolinium <> _das_chemische_zeichen_gd_ <>  <> (true)
hat <> gadolinium <> die ordnungszahl <> 64 <> (true)
hat <> gadolinium <> einen siedepunkt  <> _von_3233_grad_celsius_ <> (true)
hat <> gallium <> _das_chemische_zeichen_ga_ <>  <> (true)
hat <> gallium <> einen schmelzpunkt <> _von_30_grad_celsius_ <> (true)
hat <> gallium <> einen siedepunkt <> _von_2403_grad_celsius_ <> (true)
hat <> germanium <> _das_chemische_zeichen_ge_ <>  <> (true)
hat <> germanium <> die ordnungszahl <> 32 <> (true)
hat <> germanium <> einen schmelzpunkt <> _von_1064_grad_celsius_ <> (true)
hat <> germanium <> einen siedepunkt <> _von_2839_grad_celsius_ <> (true)
hat <> germanium <> einen siedepunkt <> _von_2940_grad_celsius_ <> (true)
hat <> gold <> _das_chemische_zeichen_au_ <>  <> (true)
hat <> gold <> die ordnungszahl <> 79 <> (true)
hat <> hafnium <> _das_chemische_symbol_hf_ <>  <> (true)
hat <> hafnium <> die ordungszahl <> 72 <> (true)
hat <> hafnium <> einen schmelzpunkt <> _von_2150_grad_celsius_ <> (true)
hat <> hafnium <> einen siedepunkt <> _von_540_grad_celsius_ <> (true)
hat <> hassium <> _das_chemische_zeichen_hs_ <>  <> (true)
hat <> hassium <> die ordnungszahl <> 108 <> (true)
hat hat <> erbium <> einen siedepunkt <> _von_2510_grad_celsius_ <> (true)
hat hat <> gallium <> die ordungszahl <> 31 <> (true)
hat hat <> germanium <> einen schmelzpunkt <> _von_937_grad_celsius_ <> (true)
hat hat <> helium <> einen schmelzpunkt <> _von_minus_272_grad_celsius_ <> (true)
hat hat <> iod <> einen schmelzpunkt <> _von_113_grad_celsius_ <> (true)
hat hat <> platin <> einen schmelzpunkt <> _von_1772_grad_celsius_ <> (true)
hat <> helium <> _das_chemische_zeichen_he_ <>  <> (true)
hat <> helium <> den niedrigsten siedepunkt <>  <> (true)
hat <> helium <> die ordungszahl <> 2 <> (true)
hat <> helium <> einen siedepunkt <> _von_minus_268_grad_celsius_ <> (true)
hat <> holium <> _das_chemische_zeichen_ho_ <>  <> (true)
hat <> indium <> _das_chemische_zeichen_in_ <>  <> (true)
hat <> indium <> die ordungszahl <> 49 <> (true)
hat <> indium <> einen schmelzpunkt <> _von_156_grad_celsius_ <> (true)
hat <> indium <> einen siedepunkt <> _von_2080_grad_celsius_ <> (true)
hat <> iod <> _das_chemische_zeichen_i_ <>  <> (true)
hat <> iod <> die ordnungszahl <> 53 <> (true)
hat <> iod <> einen siedepunkt <> _von_184_grad_celsius_ <> (true)
hat <> iridium <> _das_chemische_zeichen_ir_ <>  <> (true)
hat <> iridium <> die groesste dichte <>  <> (true)
hat <> iridium <> die ordnungszahl <> 77 <> (true)
hat <> iridium <> einen schmelzpunkt <> _von_2410_grad_celsius_ <> (true)
hat <> iridium <> einen siedepunkt <> _von_4130_grad_celsius_ <> (true)
hat <> _isaac_newton_ <> das gravitationsgesetz <> formuliert <> (true)
hat <> _joseph_priestley_ <> das tafelwasser <> erfunden <> (true)
hat <> kaliumcyanid <> _kcn_ <> das chemische formel <> (true)
hat <> kalium <> _das_chemische_zeichen_k_ <>  <> (true)
hat <> kalium <> die ordnungszahl <> 19 <> (true)
hat <> kalium <> einen schmelzpunkt <> _von_64_grad_celsius_ <> (true)
hat <> kalium <> einen siedepunkt <> _von_774_grad_celsius_ <> (true)
hat <> kohlendioxid <> die chemische formel co2 <>  <> (true)
hat <> kohlenstoff <> _das_chemische_zeichen_c_ <>  <> (true)
hat <> kohlenstoff <> die ordungszahl <> 6 <> (true)
hat <> kohlenstoff <> einen schmelzpunkt <> _von_3550_grad_celsius_ <> (true)
hat <> kohlenstoff <> einen siedepunkt <> _von_4827_grad_celsius_ <> (true)
hat <> krypton <> _das_chemische_zeichen_kr_ <>  <> (true)
hat <> krypton <> die ordnungszahl <> 36 <> (true)
hat <> krypton <> einen schmelzpunkt <> _von_minus_157_grad_celsius_ <> (true)
hat <> krypton <> einen siedepunkt <> _von_minus_152_grad_celsius_ <> (true)
hat <> kupfer <> _das_chemische_zeichen_cu_ <>  <> (true)
hat <> kupfer <> die ordnungszahl <> 29 <> (true)
hat <> kupfer <> einen schmelzpunkt <> _von_1083_grad_celsius_ <> (true)
hat <> kupfer <> einen siedepunkt <> _von_2595_grad_celsius_ <> (true)
hat <> lanthan <> _das_chemische_zeichen_la_ <>  <> (true)
hat <> lanthan <> die ordnungszahl <> 57 <> (true)
hat <> lanthan <> einen schmelzpunkt <> _von_920_grad_celsius_ <> (true)
hat <> lanthan <> einen siedepunkt <> _von_3454_grad_celsius_ <> (true)
hat <> lawrencium <> _das_chemische_zeichen_lr_ <>  <> (true)
hat <> lawrencium <> die ordungszahl <> 103 <> (true)
hat <> lithium <> _das_chemische_zeichen_li_ <>  <> (true)
hat <> lithium <> die geringste dichte <>  <> (true)
hat <> lithium <> die ordnungszahl <> 3 <> (true)
hat <> lithium <> einen schmelzpunkt  <> _von_180_grad_celsius_ <> (true)
hat <> lithium <> einen siedepunkt  <> _von_1317_grad_celsius_ <> (true)
hat <> lutetium <> _das_chemische_zeichen_lu_ <>  <> (true)
hat <> lutetium <> die ordungszahl <> 71 <> (true)
hat <> lutetium <> einen schmelzpunkt <> _von_1656_grad_celsius_ <> (true)
hat <> lutetium <> einen siedepunkt <> _von_3315_grad_celsius_ <> (true)
hat <> magnesium <> _das_chemische_zeichen_mg_ <>  <> (true)
hat <> magnesium <> die ordungszahl <> 12 <> (true)
hat <> magnesium <> einen schmelzpunkt <> _von_649_grad_celsius_ <> (true)
hat <> magnesium <> einen siedepunkt <> _von_1107_grad_celsius_ <> (true)
hat <> mangan <> _das_chemische_zeichen_mn_ <>  <> (true)
hat <> mangan <> einen schmelzpunkt <> _von_1244_grad_celsius_ <> (true)
hat <> mangan <> einen siedepunkt <> _von_2097_grad_celsius_ <> (true)
hat <> meitnerium <> _das_chemische_zeichen_mt_ <>  <> (true)
hat <> meitnerium <> die ordnungszahl <> 109 <> (true)
hat <> mendelevium <> _das_chemische_zeichen_md_ <>  <> (true)
hat <> mendelevium <> die ordnungszahl <> 101 <> (true)
hat <> molybdaen <> _das_chemische_zeichen_mo_ <>  <> (true)
hat <> molybdaen <> die ordnungszahl <> 42 <> (true)
hat <> molybdaen <> einen schmelzpunkt <> _von_2617_grad_celsius_ <> (true)
hat <> molybdaen <> einen siedepunkt <> _von_5560_grad_celsius_ <> (true)
hat <> natrium <> _das_chemische_zeichen_na_ <>  <> (true)
hat <> natrium <> die ordungszahl <> 11 <> (true)
hat <> natrium <> einen schmelzpunkt <> _von_98_grad_celsius_ <> (true)
hat <> natrium <> einen siedepunkt <> _von_892_grad_celsius_ <> (true)
hat <> natronlauge <> _die_chemische_formel_naoh_ <>  <> (true)
hat <> neodym <> _das_chemische_zeichen_nd_ <>  <> (true)
hat <> neodym <> die ordnungszahl <> 60 <> (true)
hat <> neodym <> einen schmelzpunkt <> _von_1010_grad_celsius_ <> (true)
hat <> neodym <> einen siedepunkt <> _von_3127_grad_celsius_ <> (true)
hat <> neon <> _das_chemische_zeichen_ne_ <>  <> (true)
hat <> neon <> die ordnungszahl <> 10 <> (true)
hat <> neon <> einen siedepunkt <> _von_minus_246_grad_celsius_ <> (true)
hat <> neon <>  <> _meinen_schmelzpunkt_von_minus_249_grad_celsius_ <> (true)
hat <> neptunium <> _das_chemische_zeichen_np_ <>  <> (true)
hat <> neptunium <> die ordnungszahl <> 93 <> (true)
hat <> neptunium <> einen schmelzpunkt <> _von_640_grad_celsius_ <> (true)
hat <> neptunium <> einen siedepunkt <> _von_3902_grad_celsius_ <> (true)
hat <> nickel <> _das_chemische_zeichen_ni_ <>  <> (true)
hat <> nickel <> die ordnungszahl <> 28 <> (true)
hat <> nickel <> einen schmelzpunkt <> _von_1453_grad_celsius_ <> (true)
hat <> nickel <> einen siedepunkt <> _von_2732_grad_celsius_ <> (true)
hat <> niob <> _das_chemische_zeichen_nb_ <>  <> (true)
hat <> niob <> die ordnungszahl <> 41 <> (true)
hat <> niob <> einen schmelzpunkt <> _von_2458_grad_celsius_ <> (true)
hat <> niob <> einen siedepunkt <> _von_4927_grad_celsius_ <> (true)
hat <> nobelium <> _das_chemische_zeichen_no_ <>  <> (true)
hat <> nobelium <> die ordnungszahl <> 102 <> (true)
hat <> osmium <> _das_chemische_zeichen_os_ <>  <> (true)
hat <> osmium <> die ordnungszahl <> 76 <> (true)
hat <> osmium <> die zweitgroesste dichte <>  <> (true)
hat <> osmium <> einen schmelzpunkt <> _von_2045_grad_celsius_ <> (true)
hat <> osmium <> einen siedepunkt <> _von_5027_grad_celsius_ <> (true)
hat <> palladium <> _das_chemische_zeichen_pd_ <>  <> (true)
hat <> palladium <> die ordnungszahl <> 46 <> (true)
hat <> palladium <> einen schmelzpunkt <> _von_1552_grad_celsius_ <> (true)
hat <> palladium <> einen siedepunkt <> _von_3140_grad_celsius_ <> (true)
hat <> phosphor <> _das_chemische_zeichen_p_ <>  <> (true)
hat <> phosphor <> die ordnungszahl <> 15 <> (true)
hat <> phosphor <> einen schmelzpunkt <> _von_44_grad_celsius_ <> (true)
hat <> phosphor <> einen siedepunkt <> _von_280_grad_celsius_ <> (true)
hat <> platin <> _das_chemische_zeichen_pt_ <>  <> (true)
hat <> platin <> die ordnungszahl <> 78 <> (true)
hat <> platin <> einen siedepunkt <> _von_3827_grad_celsius_ <> (true)
hat <> plutonium <> _das_chemische_zeichen_pu_ <>  <> (true)
hat <> plutonium <> die ordungszahl <> 94 <> (true)
hat <> plutonium <> einen schmelzpunkt <> _von_641_grad_celsius_ <> (true)
hat <> plutonium <> einen siedepunkt <> _von_3327_grad_celsius_ <> (true)
hat <> polonium <> _das_chemische_zeichen_po_ <>  <> (true)
hat <> polonium <> die ordnungszahl <> 84 <> (true)
hat <> polonium <> einen schmelzpunkt <> _von_252_grad_celsius_ <> (true)
hat <> polonium <> einen siedepunkt <> _von_962_grad_celsius_ <> (true)
hat <> praseodym <> _das_chemische_zeichen_pr_ <>  <> (true)
hat <> praseodym <> die ordnungszahl <> 59 <> (true)
hat <> praseodym <> einen schmelzpunkt <> _von_931_grad_celsius_ <> (true)
hat <> praseodym <> einen siedepunkt <> _von_3212_grad_celsius_ <> (true)
hat <> promethium <> _das_chemische_zeichen_pm_ <>  <> (true)
hat <> promethium <> die ordnungszahl <> 61 <> (true)
hat <> promethium <> einen schmelzpunkt <> _von_1080_grad_celsius_ <> (true)
hat <> promethium <> einen siedepunkt <> _von_2730_grad_celsius_ <> (true)
hat <> protactinium <> _das_chemische_zeichen_pa_ <>  <> (true)
hat <> protactinium <> die ordnungszahl <> 91 <> (true)
hat <> protactinium <> einen schmelzpunkt <> _von_1554_grad_celsius_ <> (true)
hat <> protactinium <> einen siedepunkt <> _von_4030_grad_celsius_ <> (true)
hat <> quecksilber <> _das_chemische_zeichen_hg_ <>  <> (true)
hat <> quecksilber <> die ordnungszahl <> 80 <> (true)
hat <> quecksilber <> einen schmelzpunkt <> _von_minus_39_grad_celsius_ <> (true)
hat <> quecksilber <> einen siedepunkt <> _von_356_grad_celsius_ <> (true)
hat <> radium <> _das_chemische_zeichen_ra_ <>  <> (true)
hat <> radium <> die ordnungszahl <> 88 <> (true)
hat <> radium <> einen schmelzpunkt <> _von_70_grad_celsius_ <> (true)
hat <> radium <> einen siedepunkt <> _von_1140_grad_celsius_ <> (true)
hat <> radon <> _das_chemische_zeichen_rn_ <>  <> (true)
hat <> radon <> die ordungszahl <> 86 <> (true)
hat <> radon <> einen schmelzpunkt <> _von_minus_71_grad_celsius_ <> (true)
hat <> radon <> einen siedepunkt <> _von_-62_grad_celsius_ <> (true)
hat <> rhenium <> _das_chemische_zeichen_re_ <>  <> (true)
hat <> rhenium <> den hoechsten siedepunkt <>  <> (true)
hat <> rhenium <> die ordnungszahl <> 75 <> (true)
hat <> rhenium <> einen schmelzpunkt <> _von_3180_grad_celsius_ <> (true)
hat <> rhenium <> einen siedepunkt <> _von_5627_grad_celsius_ <> (true)
hat <> rhodium <> _das_chemische_zeichen_rh_ <>  <> (true)
hat <> rhodium <> die ornungszahl <> 45 <> (true)
hat <> rhodium <> einen schmelzpunkt <> _von_1966_grad_celsius_ <> (true)
hat <> rhodium <> einen siedepunkt <> _von_3737_grad_celsius_ <> (true)
hat <> roentgenium <> _das_chemische_zeichen_rg_ <>  <> (true)
hat <> roentgenium <> die ordnungszahl <> 111 <> (true)
hat <> rubidium <> _das_chemische_zeichen_rb_ <>  <> (true)
hat <> rubidium <> die ordnungszahl <> 27 <> (true)
hat <> rubidium <> einen schmelzpunkt <> _von_39_grad_celsius_ <> (true)
hat <> rubidium <> einen siedepunkt <> _von_688_grad_celsius_ <> (true)
hat <> ruthenium <> _das_chemische_zeichen_ru_ <>  <> (true)
hat <> ruthenium <> die ordnungszahl <> 44 <> (true)
hat <> ruthenium <> einen schmelzpunkt <> _von_2310_grad_celsius_ <> (true)
hat <> ruthenium <> einen siedepunkt <> _von_390_grad_celsius_ <> (true)
hat <> rutherfordium <> _das_chemische_zeichen_rf_ <>  <> (true)
hat <> samarium <> _das_chemische_zeichen_sm_ <>  <> (true)
hat <> samarium <> die ordungszahl <> 62 <> (true)
hat <> samarium <> einen schmelzpunkt <> _von_1072_grad_celsius_ <> (true)
hat <> samarium <> einen siedepunkt <> _von_1778_grad_celsius_ <> (true)
hat <> sauerstoff <> _das_chemische_zeichen_o_ <>  <> (true)
hat <> sauerstoff <> die ordnungszahl <> 8 <> (true)
hat <> sauerstoff <> einen schmelzpunkt <> _von_minus_218_grad_celsius_ <> (true)
hat <> sauerstoff <> einen siedepunkt <> _von_minus_183_grad_celsius_ <> (true)
hat <> scandium <> _das_chemische_zeichen_sc_ <>  <> (true)
hat <> scandium <> die ordnungszahl <> 21 <> (true)
hat <> scandium <> einen schmelzpunkt <> _von_1539_grad_celsius_ <> (true)
hat <> scandium <> einen siedepunkt <> _von_2832_grad_celsius_ <> (true)
hat <> schwefel <> _das_chemische_zeichen_s_ <>  <> (true)
hat <> schwefel <> die ordungszahl <> 18 <> (true)
hat <> schwefel <> einen schmelzpunkt <> _von_113_grad_celsius_ <> (true)
hat <> schwefel <> einen siedepunkt <> _von_448_grad_celsius_ <> (true)
hat <> seaborgium <> _das_chemische_zeichen_sg_ <>  <> (true)
hat <> seaborgium <> die ordnungszahl <> 106 <> (true)
hat <> selen <> _das_chemische_zeichen_se_ <>  <> (true)
hat <> selen <> die ordnungszahl <> 34 <> (true)
hat <> selen <> einen schmelzpunkt <> _von_217_grad_celsius_ <> (true)
hat <> selen <> einen siedepunkt <> _von_685_grad_celsius_ <> (true)
hat <> silber <> _das_chemische_zeichen_ag_ <>  <> (true)
hat <> silber <> die ordungszahl <> 47 <> (true)
hat <> silber <> einen schmelzpunkt <> _von_962_grad_celsius_ <> (true)
hat <> silber <> einen siedepunkt <> _von_2212_grad_celsius_ <> (true)
hat <> silicium <> _das_chemische_zeichen_si_ <>  <> (true)
hat <> silicium <> die ordnungszahl <> 14 <> (true)
hat <> silicium <> einen schmelzpunkt <> _von_1410_grad_celsius_ <> (true)
hat <> silicium <> einen siedepunkt <> _von_2355_grad_celsius_ <> (true)
hat <> stickstoff <> _das_chemische_zeichen_n_ <>  <> (true)
hat <> stickstoff <> die ordnungszahl <> 7 <> (true)
hat <> stickstoff <> die ordungszahl <> 7 <> (true)
hat <> stickstoff <> einen schmelzpunkt <> _von_-210_grad_celsius_ <> (true)
hat <> stickstoff <> einen siedepunkt <> _von_minus_196_grad_celsius_ <> (true)
hat <> strontium <> _das_chemische_zeichen_sr_ <>  <> (true)
hat <> strontium <> die ordnungszahl <> 38 <> (true)
hat <> strontium <> einen schmelzpunkt <> _von_769_grad_celsius_ <> (true)
hat <> strontium <> einen siedepunkt <> _von_1384_grad_celsius_ <> (true)
hat <> tahllium <> _das_chemische_zeichen_ti_ <>  <> (true)
hat <> tahllium <> die ordnungszahl <> 81 <> (true)
hat <> tahllium <> einen schmelzpunkt <> _von_307_grad_celsius_ <> (true)
hat <> tahllium <> einen siedepunkt <> _von_1457_grad_celsius_ <> (true)
hat <> tantalum <> _das_chemische_zeichen_ta_ <>  <> (true)
hat <> tantalum <> die ornungszahl <> 73 <> (true)
hat <> tantalum <> _einen_schmelzpunkt_2966_grad_celsius_ <>  <> (true)
hat <> tantalum <> einen siedepunkt <> _von_5425_grad_celsius_ <> (true)
hat <> technetium <> _das_chemische_zeichen_tc_ <>  <> (true)
hat <> technetium <> die ordungszahl <> 43 <> (true)
hat <> technetium <> einen schmelzpunkt <> _von_2172_grad_celsius_ <> (true)
hat <> technetium <> einen siedepunkt <> _von_5030_grad_celsius_ <> (true)
hat <> tellur <> _das_chemische_zeichen_te_ <>  <> (true)
hat <> tellur <> die ordnungszahl <> 52 <> (true)
hat <> tellur <> einen schmelzpunkt <> _von_450_grad_celsius_ <> (true)
hat <> tellur <> einen siedepunkt <> _von_990_grad_celsius_ <> (true)
hat <> terbium <> _das_chemische_zeichen_tb_ <>  <> (true)
hat <> terbium <> die ordnungszahl <> 65 <> (true)
hat <> terbium <> einen schmelzpunkt <> _von_1360_grad_celsius_ <> (true)
hat <> terbium <> einen siedepunkt <> _von_3041_grad_celsius_ <> (true)
hat <> thorium <> _das_chemische_zeichen_th_ <>  <> (true)
hat <> thorium <> einen schmelzpunkt <> _von_1750_grad_celsius_ <> (true)
hat <> thorium <> einen siedepunkt <> _von_4787_grad_celsius_ <> (true)
hat <> thulium <> _das_chemische_zeichen_tm_ <>  <> (true)
hat <> thulium <> die ordnungszahl <> 69 <> (true)
hat <> thulium <> einen schmelzpunkt <> _von_1545_grad_celsius_ <> (true)
hat <> thulium <> einen siedepunkt <> _von_1727_grad_celsius_ <> (true)
hat <> titan <> _das_chemische_zeichen_ti_ <>  <> (true)
hat <> titan <> die ordnungszahl <> 22 <> (true)
hat <> titan <> einen schmelzpunkt <> _von_1660_grad_celsius_ <> (true)
hat <> titan <> einen siedepunkt <> _von_3260_grad_celsius_ <> (true)
hat <> ununbium <> _das_chemische_zeichen_uub_ <>  <> (true)
hat <> ununbium <> die ordnungszahl <> 112 <> (true)
hat <> uran <> _das_chemische_zeichen_u_ <>  <> (true)
hat <> uran <> die ordungszahl <> 92 <> (true)
hat <> uran <> einen schmelzpunkt <> _von_1132_grad_celsius_ <> (true)
hat <> uran <> einen siedepunkt <> _von_3818_grad_celsius_ <> (true)
hat <> vanadium <> _das_chemische_zeichen_v_ <>  <> (true)
hat <> vanadium <> die ornungszahl <> 23 <> (true)
hat <> vanadium <> einen schmelzpunkt <> _von_1890_grad_celsius_ <> (true)
hat <> vanadium <> einen siedepunkt <> _von_3380_grad_celsius_ <> (true)
hat <> wasser <> _das_chemische_zeichen_h2o_ <>  <> (true)
hat <> wasser <> einen siedepunkt <> _von_100_grad_celsius_ <> (true)
hat <> wasser <> einen siedepunkt  <> von 212 grad fahrenheit<> (true)
hat <> wasserstoff <> _das_chemische_zeichen_h_ <>  <> (true)
hat <> wasserstoff <> das kleinste atom <>  <> (true)
hat <> wasserstoff <> den niedrigsten schmelzpunkt <>  <> (true)
hat <> wasserstoff <> die ordnungszahl <> 1 <> (true)
hat <> wasserstoff <> die ordungszahl <> 1 <> (true)
hat <> wasserstoff <> einen schmelzpunkt <> _von_minus_260_grad_celsius_ <> (true)
hat <> wasserstoff <> einen siedepunkt <> _von_minus_253_grad_celsius_ <> (true)
hat <> wolfram <> _das_chemische_zeichen_w_ <>  <> (true)
hat <> wolfram <> den hoechsten schmelzpunkt <>  <> (true)
hat <> wolfram <> die ordnungszahl <> 74 <> (true)
hat <> wolfram <> einen schmelzpunkt <> _von_3407_grad_celsius_ <> (true)
hat <> wolfram <> einen siedepunkt <> _von_5927_grad_celsius_ <> (true)
hat <> xenon <> _das_chemische_zeichen_xe_ <>  <> (true)
hat <> xenon <> die ordnungszahl <> 54 <> (true)
hat <> xenon <> einen schmelzpunkt <> _von_minus_112_grad_celsius_ <> (true)
hat <> xenon <> einen siedepunkt <> _von_minus_107_grad_celsius_ <> (true)
hat <> ytterbium <> _das_chemische_zeichen_yb_ <>  <> (true)
hat <> ytterbium <> die ordnungszahl <> 70 <> (true)
hat <> ytterbium <> einen schmelzpunkt <> _von_824_grad_celsius_ <> (true)
hat <> ytterbium <> einen siedepunkt <> _von_1193_grad_celsius_ <> (true)
hat <> yttrium <> _das_chemische_zeichen_y_ <>  <> (true)
hat <> yttrium <> die ordnungszahl <> 39 <> (true)
hat <> yttrium <> einen schmelzpunkt <> _von_1523_grad_celsius_ <> (true)
hat <> yttrium <> einen siedepunkt <> _von_3337_grad_celsius_ <> (true)
hat <> zink <> _das_chemische_zeichen_zn_ <>  <> (true)
hat <> zink <> die ordnungszahl <> 30 <> (true)
hat <> zink <> einen schmelzpunkt <> _von_419_grad_celsius_ <> (true)
hat <> zink <> einen siedepunkt <> _von_907_grad_celsius_ <> (true)
hat <> zinn <> _das_chemische_zeichen_sn_ <>  <> (true)
hat <> zinn <> die ordnungszahl <> (true) <> (true)
hat <> zinn <> einen schmelzpunkt <> _von_232_grad_celsius_ <> (true)
hat <> zinn <> einen siedepunkt <> _von_2270_grad_celsius_ <> (true)
hat <> zirconium <> _das_chemische_zeichen_zr_ <>  <> (true)
hat <> zirconium <> die ordnungszahl <> 40 <> (true)
hat <> zirconium <> einen schmelzpunkt <> _von_1852_grad_celsius_ <> (true)
hat <> zirconium <> einen siedepunkt <> _von_4377_grad_celsius_ <> (true)
hat <> zyankali <> _die_chemische_formel_kcn_ <>  <> (true)
heisst <> _pb_ <> blei <>  <> (true)
ist <> acetat <> ein salz <> der essigsaeure <> (true)
ist <> actinium <> ein element <>  <> (true)
ist <> actinoide <> eine gruppenbezeichnung aehnlicher elemente <>  <> (true)
ist <> afrika <> die heimat <> der kaffeepflanze <> (true)
ist <> alabaster <> eine abart <> von gips <> (true)
ist <> _alfred_nobel_ <> der erfinder <> von dynamit <> (true)
ist <> aluminium <> ein element <>  <> (true)
ist <> aluminium <> ein element <> der borgruppe <> (true)
ist <> aluminium <> ein leichtmetall <>  <> (true)
ist <> aluminium <> ein metall <>  <> (true)
ist <> americium <> ein actinoid <>  <> (true)
ist <> americium <> ein element <>  <> (true)
ist <> antimon <> ein element <>  <> (true)
ist <> antimon <> ein element <> der stickstoffgruppe <> (true)
ist <> antimon <> ein metall <>  <> (true)
ist <> argon <> ein edelgas <>  <> (true)
ist <> argon <> ein element <>  <> (true)
ist <> arsen <> ein element <>  <> (true)
ist <> arsen <> ein element <> der stickstoffgruppe <> (true)
ist <> arsen <> ein halbmetall <>  <> (true)
ist <> arsen <> ein metall <>  <> (true)
ist <> astat <> ein element <>  <> (true)
ist <> astat <> ein element <> der halogengruppe <> (true)
ist <> astat <> ein halogen <>  <> (true)
ist <> _au_ <> das elementsymbol <> fuer gold <> (true)
ist <> barium <> ein element <>  <> (true)
ist <> barium <> ein erdalkalimetall <>  <> (true)
ist <> berkelium <> ein actinoid <>  <> (true)
ist <> berkelium  <> ein element <>  <> (true)
ist <> berylium <> ein leichtmetall <>  <> (true)
ist <> beryllium <> ein element <>  <> (true)
ist <> beryllium <> ein erdalkalimetall <>  <> (true)
ist <> bionik <> ein wissenschaftszweig technik <> aus biologie <> (true)
ist <> bismut <> ein element <>  <> (true)
ist <> bismut <> ein element <> der stickstoffgruppe <> (true)
ist <> blausaeure <>  <> farblos <> (true)
ist <> blei <> ein element <>  <> (true)
ist <> blei <> ein element <> der kohlenstoffgruppe <> (true)
ist <> bohrium <> ein element <>  <> (true)
ist <> bor <> das zweithaerteste element <>  <> (true)
ist <> bor <> ein element <>  <> (true)
ist <> bor <> ein element <> der borgruppe <> (true)
ist <> bor <> ein halbleiter <>  <> (true)
ist <> bor <> ein halbmetall <>  <> (true)
ist <> botox <> ein starkes gift <>  <> (true)
ist <> botulinumtoxin <> das staerkste gift <>  <> (true)
ist <> brom <> ein element <>  <> (true)
ist <> brom <> ein element <> der halogengruppe <> (true)
ist <> brom <> ein halogen <>  <> (true)
ist <> cadmium <> ein element <>  <> (true)
ist <> caesium <> das weichste chemische element <>  <> (true)
ist <> caesium <> ein alkalimetall <>  <> (true)
ist <> caesium <> ein element <>  <> (true)
ist <> calcium <> ein element <>  <> (true)
ist <> calcium <> ein erdalkalimetall <>  <> (true)
ist <> californium <> ein actinoid <>  <> (true)
ist <> californium <> ein element <>  <> (true)
ist <> cer <> ein element <>  <> (true)
ist <> chlor <> ein element <>  <> (true)
ist <> chlor <> ein element <> der halogengruppe <> (true)
ist <> chlor <> ein halogen <>  <> (true)
ist <> chloroform <> trichlormethan <>  <> (true)
ist <> chrom <> ein element <>  <> (true)
ist <> chrom <> ein schwermetall <>  <> (true)
ist <> cobalt <> ein element <>  <> (true)
ist <> cromargan <> einerostende legierung chrom <> aus stahl;nicht;sowie nickel <> (true)
ist <> curium <> ein actinoid <>  <> (true)
ist <> curium <> ein element <>  <> (true)
ist <> cyanwasserstoff <> blausaeure <>  <> (true)
ist <> darmstadtium <> ein element <>  <> (true)
ist <> das chemische zeichen <> das elementsymbol <>  <> (true)
ist <> das chemische zeichen <> ein elementsymbol <>  <> (true)
ist <> das edelweiss <>  <> ein korbbluetler <> (true)
ist <> das gyroskop <> ein steuergeraet fuer die automatische lenkung <> von flugkoerpern <> (true)
ist <> das log <> ein messgeraet <> zur bestimmung der schiffsgeschwindigkeit <> (true)
ist <> das magma <> geschmolzenes gestein <> in dem erdinnern <> (true)
ist <> das siemens-martin-verfahren  <> ein verfahren <> zur stahlerzeugung <> (true)
ist <> der diamant <> der haerteste stoff <>  <> (true)
ist <> der facharzt fuer hauterkrankungen <> ein dermatologe <>  <> (true)
ist <> der liegende achter <> das zeichen <> fuer unendlich <> (true)
ist <> der ph-wert <>  <> 7;von reinem wasser <> (true)
ist <> _die_archimedische_schraube_ <> ein wasserhebegeraet <>  <> (true)
ist <> die chromosphaere <> die obere schicht <> der sonnenatmosphaere <> (true)
ist <> die endokrinologie <> die lehre <> von den hormonen <>  <>  <>  <>  <>  <> 
ist <> die entropie <> eine zentrale zustandsgroesse der thermodynamik 
ist <> die galeone <> ein spanisch-portugiesisches segelkriegsschiff <>  <> (true)
ist <> die gastroenterologie <> ein teilgebiet der inneren medizin <> 
ist <> die genetik <> die vererbungslehre 
ist <> die gravitation <> die anziehungskraft <>  <> (true)
ist <> die grundflaeche <>  <> eines kegels;kreisfoermig <> (true)
ist <> die luft <> ein gasgemisch <>  <> (true)
ist <> die oxalsaeure <> die einfachste dicarbonsaeure <>  <> (true)
ist <> die schwerkraft <> die anziehungskraft <> der erde <> (true)
ist <> die seismologie <> die erdbebenkunde <>  <> (true)
ist <> die viskositaet <> das mass eines stoffes <> fuer die innere reibung <> (true)
ist <> die zeit <>  eine konstante <>  <>    <>  <>  <>  <>  <>  <> (true)
ist <> dubnium  <> ein element <>  <> (true)
ist <> dysprosium <> ein element <>  <> (true)
ist <> ein amethyst <>  <> violett <> (true)
ist <> ein apsis <> ein edelstein <> nicht <> (true)
ist <> ein bergkristall <>  <> farblos <> (true)
ist <> ein diamant <> ein isolator <>  <> (true)
ist <> ein diamant <> ein nichtleiter <>  <> (true)
ist <> ein diamant <> kohlenstoff <> in seiner haertesten form <> (true)
ist <> eine aphasie <> eine sprachstoerung <>  <> (true)
ist <> eine fluessigkeit <>  <> ein emulsion <> (true)
ist <> eine legierung <> ein gemenge <>  <> charakter <> metallischem <>  <> aus 2 oder mehr chemischen elementen; <> mit <>  <> (true)
ist <> ein elektron <> ein quantenobjekt <>  <> (true)
ist <> eine pipette <> ein saugheber <>  <> (true)
ist <> eine unvertraeglichkeit <> eine allergie <>  <> (true)
ist <> ein hologramm <> ein dreidimensionales bild <> auf einer ebenen flaeche <> (true)
ist <> ein hypochonder <> ein eingebildeter kranker <>  <> (true)
ist <> ein robin <>  <> rot <> (true)
ist <> ein sandkorn <> maximal 2 mm gross <>  <> (true)
ist <> ein taifun <> ein tropischer wirbelsturm <>  <> (true)
ist <> einsteinium <> ein actinoid <>  <> (true)
ist <> einsteinium <> ein element <>  <> (true)
ist <> eisen <> ein bestandteil <> von haemoblobin <> (true)
ist <> eisen <> ein element <>  <> (true)
ist <> energie <> eine physikalische zustandsgroesse <> 
ist <> epheliden <> der fachbegriff fuer sommersprossen <>  <> (true)
ist <> erbium <> ein element <>  <> (true)
ist <> erdgas <> schwerer als luft <>  <> (true)
ist <> europium <> ein element <>  <> (true)
ist <> _farblos_ <> eine farbe <>  <> (true)
ist <> fermium <> ein actinoid <>  <> (true)
ist <> fermium <> ein element <>  <> (true)
ist <> fermium <> mein transuran <>  <> 100
ist <> ferrum <> der lateinische name <> fuer eisen <> (true)
ist <> fluor <> ein element <>  <> (true)
ist <> fluor <> ein element <> der halogengruppe <> (true)
ist <> fluor <> ein halogen <>  <> (true)
ist <> fluor <> ein spurenelement <>  <> (true)
ist <> francium <> ein alkalimetall <>  <> (true)
ist <> francium <> ein element <>  <> (true)
ist <> gadolinium <> ein element <>  <> (true)
ist <> gallium <> ein element <>  <> (true)
ist <> gallium <> ein element <> der borgruppe <> (true)
ist <> germanium <> ein element <>  <> (true)
ist <> germanium <> ein element <> der kohlenstoffgruppe <> (true)
ist <> gips <> calciumsulfat <>  <> (true)
ist <> gips <> der umgangssprachliche name <> fuer calciumsulfat <> (true)
ist <> glaubersalz <> natriumsulfat <>  <> (true)
ist <> glukagon <> ein hormon <>  <> (true)
ist <> glukose <> traubenzucker <>  <> (true)
ist <> glycerin <> der bedeutenste dreiwertige aklohol <>  <> (true)
ist <> gold <> ein edelmetall <> 
ist <> gold <> ein element <>  <> (true)
ist <> gold <> ein reinelement <> ohne isotope <> (true)
ist <> gold <> schwerer als blei <>  <> (true)
ist <> hafnium <> ein element <>  <> (true)
ist <> hassium  <> ein element <>  <> (true)
ist <> helium <> ein edelgas <>  <> (true)
ist <> helium <> ein element <>  <> (true)
ist <> holmium <> ein element <>  <> (true)
ist<> holz <> _ein_nachwachsender,_umweltfreundlicher_rohstoff_ <>  <>  <>    <>  <>  <>  <>  <> (true)
ist <> indium <> ein element <>  <> (true)
ist <> indium <> ein element <> der borgruppe <> (true)
ist <> iod <> ein element <>  <> (true)
ist <> iod <> ein element <> der halogengruppe <> (true)
ist <> iridium <> ein element <>  <> (true)
ist <> iridium <> ein platinmetall <>  <> (true)
ist <> jod <> ein halbleiter <> nicht <> (true)
ist <> kalium <> ein alkalimetall <>  <> (true)
ist <> kalium <> ein element <>  <> (true)
ist <> kaliumpermanganat <> das staerkste oxidationsmittel <>  <> (true)
ist <> kelvin <> eine masseinheit <> fuer die temperatur <> (true)
ist <> kernfusion <>  <> die verschmelzung von atomkernen <> (true)
ist <> kobalt <> ein schwermetall <>  <> (true)
ist <> kohlenstoff <> ein element <>  <> (true)
ist <> kohlenstoff <> ein element <> der kohlenstoffgruppe <> (true)
ist <> krypton <> ein edelgas <>  <> (true)
ist <> krypton <> ein element <>  <> (true)
ist <> kuhmilch <> eine emulsion <>  <> (true)
ist <> kuhmilch <> eine fluessigkeit <>  <> (true)
ist <> kupfer <> ein element <>  <> (true)
ist <> kupfer <> ein guter elektrizitaetsleiter <>  <> (true)
ist <> lakritze <> eine schwarze masse <> aus eingedicktem suessholzwurzelsaft <> (true)
ist <> laktose <> milchzucker <>  <> (true)
ist <> lanthan <> ein element <>  <> (true)
ist <> lanthan <> ein metall <>  <> (true)
ist <> lanthan <> ein schwermetall <>  <> (true)
ist <> lapislazuli <> ein blauer halbedelstein <>  <> (true)
ist <> lawrencium <> ein actinoid <>  <> (true)
ist <> lawrencium <> ein element <>  <> (true)
ist <> lithium <> ein alkalimetall <>  <> (true)
ist <> lithium  <> ein element <>  <> (true)
ist <> lsd <> eine droge <>  <> (true)
ist <> lsd <> ein halluzinogen <>  <> (true)
ist <> lutetium <> ein element <>  <> (true)
ist <> magnesium <> ein chemisches element 
ist <> magnesium <> ein element <>  <> (true)
ist <> magnesium <> ein erdalkalimetall <>  <> (true)
ist <> magnesium <> ein leichtmetall <>  <> (true)
ist <> mangan <> ein element <>  <> (true)
ist <> materie <> eine allgemeine bezeichnung <> fuer alles stoffliche <>  <>  <>  <>  <>  
ist <> meitnerium <> ein element <>  <> (true)
ist <> mendelevium <> ein actinoid <>  <> (true)
ist <> mendelevium <> ein element <>  <> (true)
ist <> mennige <>  <> rot <> (true)
ist <> messing <> eine kupfer-zinklegierung <>  <> (true)
ist <> metall <> der beste waermeleiter <>  <> (true)
ist <> methan <> der einfachste gesaettigte kohlenwasserstoff <>  <> (true)
ist <> milch <> eine emulsion <>  <> (true)
ist <> molybdaen <> ein edelmetall <> nicht <> (true)
ist <> molybdaen <> ein element <>  <> (true)
ist <> molybdaen <> ein metall <>  <> (true)
ist <> molybdaen <> ein schwermetall <>  <> (true)
ist <> montezumas rache <> eine durchfallserkrankung <>  <> (true)
ist <> natriumchlorid <> einfaches tafelsalz <>  <> (true)
ist <> natriumchlorid <> kochsalz <>  <> (true)
ist <> natrium <> ein alkalimetall <>  <> (true)
ist <> natrium <> ein element <>  <> (true)
ist <> natrium <> ein leichtmetall <>  <> (true)
ist <> neon <> ein edelgas <>  <> (true)
ist <> neon <> ein element <>  <> (true)
ist <> neptunium <> ein actinoid <>  <> (true)
ist <> neptunium <> ein element <>  <> (true)
ist <> nickel <> ein element <>  <> (true)
ist <> nickel <> ein metall <>  <> (true)
ist <> nickel <> ein schwermetall <>  <> (true)
ist <> niob <> ein element <>  <> (true)
ist <> nobelium <> ein actinoid <>  <> (true)
ist <> nobelium <> ein element <>  <> (true)
ist <> noedym <> ein element <>  <> (true)
ist <> osmium <> ein element <>  <> (true)
ist <> osmium <> ein metall <>  <> (true)
ist <> oxidation <> die chemische reaktion <> von elementen mit sauerstoff <> (true)
ist <> ozon <> eine verbindung <> aus drei sauerstoffatomen <> (true)
ist <> palladium <> ein element <>  <> (true)
ist <> patchwork <> ein stoff <> aus bunten flecken <> (true)
ist <> patina <> eine gruene oxidationsschicht <> auf kupfer <> (true)
ist <> phosphor <> ein element <>  <> (true)
ist <> phosphor <> ein element <> der stickstoffgruppe <> (true)
ist <> platin <> ein edelmetall <>  <> (true)
ist <> platin <> ein element <>  <> (true)
ist <> plonium <> ein element <>  <> (true)
ist <> plumbum <> der latainische name <> fuer blei <> (true)
ist <> plutonium <> ein actinoid <>  <> (true)
ist <> plutonium <> ein element <>  <> (true)
ist <> polonium <> ein element <> der sauerstoffgruppe <> (true)
ist <> polyethylen <> ein kunststoff <>  <> (true)
ist <> polytetrafluorethylen <> als teflon <> bekannt <> (true)
ist <> praseodym <> ein element <>  <> (true)
ist <> promethium <> ein element <>  <> (true)
ist <> protactinium <> ein actinoid <>  <> (true)
ist <> protactinium <> ein element <>  <> (true)
ist <> quecksilber <> ein edelmetall <>  <> (true)
ist <> quecksilber <> ein element <>  <> (true)
ist <> quecksilber <> ein metall <>  <> (true)
ist <> quecksilber <>  <> unter normalbedingungen fluessig <> (true)
ist <> radium <> ein element <>  <> (true)
ist <> radium <> ein erdalkalimetall <>  <> (true)
ist <> radon <> ein edelgas <>  <> (true)
ist <> radon <> ein element <>  <> (true)
ist reis <> eine gattung <>  <> der suessgraeser <> (true)
ist <> rhenium <> ein element <>  <> (true)
ist <> rhodium <> ein element <>  <> (true)
ist <> roentgenium <> ein element <>  <> (true)
ist <> rubidium <> ein alkalimetall <>  <> (true)
ist <> ruthenium <> ein element <>  <> (true)
ist <> rutherfordium <> ein element <>  <> (true)
ist <> samarium <> ein element <>  <> (true)
ist <> sauerstoff <> das haeufigste element <> in der erdrinde <> (true)
ist <> sauerstoff <> ein chalkogen <>  <> (true)
ist <> sauerstoff <> ein chemisches element <>  <> (true)
ist <> sauerstoff <> ein element <>  <> (true)
ist <> sauerstoff <> ein element <> der sauerstoffgruppe <> (true)
ist <> scandium <> ein element <>  <> (true)
ist <> schwarzpulver <> ein treibmittel <> fuer gewehrkugeln <> (true)
ist <> schwefel <> ein chalkogen <>  <> (true)
ist <> schwefel <> ein element <>  <> (true)
ist <> schwefel <> ein element <> der sauerstoffgruppe <> (true)
ist <> schwefel <>  <> gelb <> (true)
ist <> seaborgium <> ein element <>  <> (true)
ist <> selen <> ein element <>  <> (true)
ist <> selen <> ein element <> der sauerstoffgruppe <> (true)
ist <> silber <> der beste waermeleiter <>  <> (true)
ist <> silber <> ein chemisches element <>  <> (true)
ist <> silber <> ein element <>  <> (true)
ist <> silber <> ein schwermetall <>  <> (true)
ist <> silicium <> ein chemisches element <>  <> (true)
ist <> silicium <> ein element <>  <> (true)
ist <> silicium <> ein element <> der kohlenstoffgruppe <> (true)
ist <> silizium <> ein halbleiter <>  <> (true)
ist <> silizium <> ein halbmetall <>  <> (true)
ist <> soda <> ein wasserloesliches natriumsalz <> der kohlensaeure <> (true)
ist <> sorbit <> ein zuckeraustauschstoff <>  <> (true)
ist <> stahl <> eine legierung <>  <> (true)
ist <> staniol <> eine duenne folie <> aus zinn <> (true)
ist <> stannum <> die lateinische bezeichnung <> fuer zinn <> (true)
ist <> stibium <> der lateinische name <> fuer antimon <> (true)
ist <> stickstoff <> ein element <>  <> (true)
ist <> stickstoff <> ein element <> der stickstoffgruppe <> (true)
ist <> stoechiometrie <> ein teilgebiet <> der chemie <> (true)
ist <> strom <> die bewegung elektrischer ladungen <>  <> (true)
ist <> strontium <> ein element <>  <> (true)
ist <> strontium <> ein erdalkalimetall <>  <> (true)
ist <> sublimation <> der direkte uebergang <> vom festen in den fluessigen aggregatzustand <> (true)
ist <> sulfit <> das salz <> der schwefligen saeure <> (true)
ist <> tahllium <> ein element <>  <> (true)
ist <> talk <> der weichste stoff <>  <> (true)
ist <> tantal <> ein element <>  <> (true)
ist <> technetium <> ein element <>  <> (true)
ist <> tellur <> ein chalkogen <>  <> (true)
ist <> tellur <> ein element <>  <> (true)
ist <> tellur <> ein element <> der sauerstoffgruppe <> (true)
ist <> terbium <> ein element <>  <> (true)
ist <> thallium <> ein element <> der borgruppe <> (true)
ist <> thorium actinium <> ein actinoid <>  <> (true)
ist <> thorium <> ein element <>  <> (true)
ist <> thulium <> ein element <>  <> (true)
ist <> titan <> ein element <>  <> (true)
ist <> titan <> ein leichtmetall <>  <> (true)
ist <> titan <> ein metall <>  <> (true)
ist <> tutia <> ein sublimiertes zinkoxid <>  <> (true)
ist <> und <> ein actinoid <>  <> (true)
ist <> unserer sonne <>  <> der merkur  an dem naechsten <> (true)
ist <> ununbium <> ein element <>  <> (true)
ist  <> uran <> das schwerste natuerlich vorkommende element <>  <> (true)
ist <> uran <> ein actinoid <>  <> (true)
ist <> uran <> ein element <>  <> (true)
ist <> vanadium <> ein element <>  <> (true)
ist <> vanadium <> ein metall <>  <> (true)
ist <> _vitamin_a_ <>  <> fettloeslich <> (true)
ist <> vitamin c <> ascorbinsaeure <>  <> (true)
ist <> wasser <> eine chemische verbindung <>  <> (true)
ist <> wasserstoff <> ein alkalimetall <>  <> (true)
ist <> wasserstoff <> ein chemisches element <>  <> (true)
ist <> wasserstoff <> ein element <>  <> (true)
ist <> wasserstoff <> ein gas <>  <> (true)
ist <> wasserstoff <> ein mischelement <> mit mehreren isotopen <> (true)
ist <> wasserstoff <> leichter als luft <>  <> (true)
ist <> wasserstoff <>  <> leicht entzuendlich <> (true)
ist <> watt <> die einheit fuer leistung <>  <> (true)
ist <> wolfram <> ein element <>  <> (true)
ist <> xenon <> ein edelgas <>  <> (true)
ist <> xenon <> ein element <>  <> (true)
ist <> ytterbium <> ein element <>  <> (true)
ist <> yttrium <> ein element <>  <> (true)
ist <> zeit <> die eine konstante <>  <>    <>  <>  <>  <>  <>  <> (true)
ist <> zibet <> ein stark riechendes druesensekret <> nach moschus <> (true)
ist <> zink <> ein element <>  <> (true)
ist <> zinn <> ein element <>  <> (true)
ist <> zinn <> ein element <> der kohlenstoffgruppe <> (true)
ist <> zirconium <> ein element <>  <> (true)
ist <> zoelestin <> ein mineral <>  <> (true)
ist <> zyankali <> das giftige salz <> der blausaeure <> (true)
kann/can verchromen <> man <> gegenstaende <> mit galvanisieren <> (true)
koennen verbrennen <> diamanten <>  <> ohne weiter rueckstaende zu kohlendioxid <> (true)
laesst <> aerodynamik <> flugzeuge fliegen 
laesst schmelzen <> gallium <> sich <> durch handwaerme <> (true)
lautet <> co2 <> die chemische formel fuer kohlendioxid <>  <> (true)
lautet <> die formel <> _masse_durch_volumen_ <> fuer dichte <> (true)
lautet <> die summenformel <> _h2so4_ <> von schwefelsaeure <> (true)
lautet <> die summenformel <> _kmno4_ <> von kaliumpermanganat <> (true)
lautet <> die summenformel <> _o3_ <> von ozon <> (true)
lebt <> ein rotes blutkoerperchen <> hoechstens 4 monate <>  <> (true)
leitet <> silber <> elektrzitaet <> an dem besten <> (true)
leitet <> silber <> waerme <> an dem besten <> (true)
liegt <> bei 0 grad kelvin <> der absolute nullpunkt <>  <> (true)
reguliert <> melatonin <> die innere uhr <>  <> (true)
schmilzt <> wolfram <> _bei_3422_grad_celsius_ <>  <> (true)
sehen <> menschen <>  <> in einem wellenbereich von 400-800 nanometern <> (true)
siedet <> wasser <> _bei_100_grad_celsius_ <>  <> (true)
siedet <> wasser <> bei 212 grad fahrenheit <>  <> (true)
sind <> actinoide <>  <> radioaktiv <> (true)
sind <> alle edelmetalle <> schwermetalle <>  <> (true)
sind <> alle erdalkalimetalle <> unedle metalle <>  <> (true)
sind <> alle salze <> elektrolyte <>  <> (true)
sind <> carbonate <> salze <> der kohlensaeure <> (true)
sind <> chalkogene <> elemente des periodensystems <> der 6 hauptgruppe <> (true)
sind <> die hauptbestandteile <> pflanzliche oele und butter<> von margrine <> (true)
sind <> die meisten chemischen elemente <> metalle <>  <> (true)
sind <> disulfidbruecken <> chemische bindungsformen <>  <> (true)
sind <> edelgase <>  <> sehr reaktionstraege <> (true)
sind <> eine flatulenz <> blaehungen <>  <> (true)
sind <> elektronen <> negativ geladene elementarteilchen <>  <> (true)
sind <> _erythrocyten_ <> rote blutkoerperchen <>  <> (true)
sind <> kilowattstunden <> die einheit fuer arbeit <>  <> (true)
sind <> mutationen <> aenderungen <> der eigenschaften eines lebewesens <> (true)
sind <> nitride <> verbindungen <> aus stickstoff und einem metall <> (true)
sind <> oliven <> fruechte des oelbaums <>  <> (true)
sind <> oxide <> chemische verbindungen <> mit sauerstoff <> (true)
sind <> proteine <> eiweisse <>  <> (true)
sind <> protuberanzen <> gaswolken <> auf der sonne <> (true)
sind <> schallwellen <> schwingungen <> der materie <> (true)
speichert <> ein kondensator <> elektrische ladung <>  <> (true)
steht <> cr <> fuer das schwermetall chrom <>  <> (true)
steht <> die abkuerzung dvd <> digital-versatile-disc <> fuer <> (true)
steht <> _rom_ <> read-only-memory <> fuer <> (true)
steuert <> melatonin <> euere innere uhr <>  <> (true)
ist <> melatonin <> ein hormon <>  <> (true)
teilen <> keimbahnzellen <> sich <> durch mitose;nicht <> (true)
verchromt werden <> gegenstaende <>  <> mit galvanisieren <> (true)
verhindert <> talkum <> das verklumpen <> von lebensmitteln <> (true)
verursacht <> ein ozonloch <> vermehrte ultraviolettstrahlung <>  <> (true)
verwendet <> das symphatische nervensystem <> azetylcholin <> an der ersten synapse <> (true)
verwendet wird <> aluminium <>  <> in dem flugzeugbau <> (true)
verwendet wird <> ameisensaeureethylester <> als aromastoff <> fuer rum <> (true)
verwendet wird <> titan <>  <> in dem flugzeugbau <> (true)
vorkommt <> aluminium <>  <> in der erdkruste an dem haeufigsten <> (true)
vorkommt <> wasserstoff <>  <> in 3 isotopen <> (true)
wird <> adrenalin <>  <> im nebennierenmark  produziert <> (true)
wird <> aluminium <> gewonnen <> aus bauxit <> (true)
wird <> aluminium <> gewonnen <> durch elektrolyse <> (true)
wird <> aluminium <> gewonnen <> mit dem bauxit-verfahren <> (true)
wird <> benzin <> gewonnen <> aus erdoel <> (true)
wird <> der widerstand <>  <> in ohm gemessen <> (true)
wird <> die einheit <>  <> der spannung;in volt gemessen <> (true)
wird <> die schallstaerke <>  <> in dezibel gemessen <> (true)
wird <> die stromstaerke <>  <> in ampere gemessen <> (true)
wird <> gold <>  <> beim schmelzen gruen <> (true)
wird <> lackmus <>  <> in saeuren rot <> (true)
wird <> leder <>  <> aus tierhaut hergestellt <> (true)
wird <> leinen <>  <> aus flachs hergestellt <> (true)
wird <> luft <> _bei_minus_231_grad_celsius_ <> fluessig <> (true)
wird <> opium <> gewonnen <> aus schlafmohn <> (true)
wird <> papier <>  <> aus holz hergestellt <> (true)
wird <> quecksilber <>  <> bei zimmertemperatur fluessig <> (true)
wird <> raki <>  <> _aus_anis_und_rosinen_hergestellt_ <> (true)
wird zerlegt <> wasser <>  <> durch elektrolyse in seine bestandteile <> (true)
zerlegt <> ein prisma <> das licht <> in farben <> (true)
