 besteht <> eis <> aus gefrorenem wasser <> <> (true)
= <> _babylon_5_ <> fernsehserie <>  <> (true)
= <> angst <> komplizierte kombination <> der negativen gefuehle <> (maybe)
= <> der penis <> maennliche geschlechtsteil <>  <> (maybe)
= <> die vagina <> weibliche geschlechtsteil <>  <> (maybe)
= <> ein autor <> verfasser <>  <>  <> oder  geistige urheber <>  <> von einem werkes <>  <> (maybe)
= <> ein magier <> zauberkuenstler <>  <> (maybe)
= <> ein magnetfeld <> physikalisches phaenomen <>  <> (maybe)
= <> ein saeufer <> alkoholabhaengiger mensch <>  <> (maybe)
= <> ein shaolin <> chinesischer moench <>  <> (maybe)
= <> ein trunkenbold <> dauernd besoffener mensch <>  <> (maybe)
= <> ein wort <> selbststaendige sprachliche einheit <>  <> (maybe)
= <> ein zauberkuenstler <> artist der darstellenden zauberkunst <>  <> (maybe)
= <> maultaschen <> spezialitaet der schwaebischen kueche <>  <> (maybe)
= <> tee <> heisses aufgussgetraenk <>  <> (maybe)
abhaelt <> die ozonschicht <> uv-strahlen <> 50
abwirft <> die laerche <> seine nadeln <> in dem winter <> (true)
angebaut wird <> darjeelingtee <> <> in indien <> (true)
angebaut wird <> der assamtee <> <> in indien <> (true)
anhaben kann/can <> ein kuenstliches wesen <> nichts <> (true)
anrichten kann/can <> ein sturm <> sehr viel schaden <> <> (true)
anschaut <> ein kuenstliches wesen <> eine filme <> nicht <> <> (true)
anschaut <> eine ki <> eine filme <> nicht <> <> (true)
arbeiten gehen <> menschen <> <> <> <> <> verdienen <> um geld <> <> (true)
arbeiten muessen <> menschen <> <> <> <> <> verdienen <> um geld <> <> (true)
arbeitet <> ein holzfaeller <> <> in dem wald <> <> (true)
aufgeht <> die sonne <> <> an dem morgen <> <> (true)
aus <> _ <> eine droge kokainsalz <> hergestellt <> <> (true)
aus <> _ <> eine droge natron <> hergestellt <> <> (true)
aus <> es <> nichts <> macht mir <> <> (true)
aus <> keinem bestimmten grund <> <> (true)
aus besteht <> ein tennisball <> filz <> <> (true)
aus kennst <> du <> dich <> damit nicht <> <> (true)
ausziehen kann/can <> du <> dich <> nicht <> <> (true)
baden <> viel spass <> <> beim <> <> (true)
baden gehen <> viel spass <> <> beim <> <> (true)
baden gehst <> du <> <> (true)
bauen <> eskimos <> iglus <> <> (true)
baut <> man <> einen schneemann <> in dem winter <> <> (true)
beantworten soll <> eine frage <> man nicht <> mit einer frage <> <> (true)
bearbeitet <> ein gerber <> tierfelle <> <> (true)
bearbeitet <> ein holzfaeller <> baeume <> <> (true)
bedeutet <> _esp_ <> _elektronisches_stabilitaes_programm_ <> <> (true)
bedeutet <> <> <> definitiv endgueltig <> <> (true)
bedeutet <> <> <> plausibel einleuchtend <> <> (true)
bedeutet <> <> <> priapisch unzuechtig <> <> (true)
bedeutet <> abstinenz <> enthaltsamkeit <> <> (true)
bedeutet <> altruismus <> uneigennuetzigkeit <> <> (true)
bedeutet <> aquaplaning <> wassergleiten <> <> (true)
bedeutet <> ehre <> <> in etwa achtungswuerdigkeit <> <> (true)
bedeutet <> felix <> der glueckliche <> <> (true)
bedeutet <> generalisierung <> verallgemeinerung <> <> (true)
bedeutet <> gpl <> general public license <> <> (true)
bedeutet <> inolenz <> unverschaemtheit <> <> (true)
bedeutet <> ki <> kuenstliche intelligenz <> <> (true)
bedeutet <> klarschiff <> gefechtsbereitschaft <> <> (true)
bedeutet <> pharao <> grosses haus <> <> (true)
bedeutet <> plantage <> _pflanzung_ <> <> (true)
bedeutet <> sonne <> licht <> <> (true)
bedeutet <> sonne <> waerme <> <> (true)
bedeutet <> synergie <> zusammenwirken <> <> (true)
bedeutet <> terrone <> erdfresser <> <> (true)
bedeutet kommen <> _in_media_res_ <> <> zur sache <> <> (true)
beeinflusst <> der mond <> die gehzeiten <> <> (true)
befasst <> die naturwissenschaft <> sich <> mit pyhsik, mathematik sowie chemie <> <> (true)
befasst <> die relativitaetstheorie <>  <>sich mit der struktur von raum & zeit<>  <>  <>  <> sowie mit dem wesen von der gravitation <>  <> (maybe)
befindet <> _das_oetzi_museum_ <> sich <> in bozen <> <> (true)
befindet <> der aelteste zoo <> sich <> in wien;der welt <> <> (true)
beibringen kann/can <> du <> mir dinge <> mit gespraechen <> <> (true)
beissen kann/can <> man <> <> ohne zaehne nicht <> <> (true)
bekommst <> du <> kein keks <> <> (true)
bellt <> ein hund <> <> (true)
benoetigen <> lebewesen <> nahrung <> <> (true)
benoetigt <> eine ki <> einen schlaf <> nicht <> <> (true)
benoetigt <> eine kuenstliche intelligenz <> einen schlaf <> nicht <> <> (true)
benoetigt wird <> ein kondensator <> <> in der elektronik <> <> (true)
benutzt <> ein mensch <> <> seinen verstand <> <> (true)
bereiten kann/can <> der koerper <> schmerzen <> <> (true)
bereiten kann/can <> die seele <> schmerzen <> <> (true)
besitzen <> menschen <> <> eine wirbelsaeule <> <> (true)
besitzt <> das skelett ein erwachsenen <> 206 knochen <> <> (true)
bestehen <> atome <> <> aus elektronen neutronen und protonen <> <> <> (true)
bestehen <> diamanten <> <> aus reinem kohlenstoff <> <> (true)
besteht <> kaviar <> <> aus fischrogen <> <> (true)
besteht <> sushi <> <> aus rohem fisch & gemuese <> <> (true)
bestiehlt <> ein dieb <> leute <>  <> (maybe)
betreibt <> man <> wintersport <> in dem winter <> <> (true)
betrieben <> _ <> ein fahrzeug <> mit einem motor <> <> (true)
beurteilen kannst/can <> das du <> <> nicht <> <> (true)
bewacht <> ein hund <> den menschen <> <> (true)
beweisen musst <> du <> es mir <> <> (true)
bezahlen brauchen <> menschen <> geld <> zum <> <> (true)
bezeichnet <> _ <> als apartheid die rassentrennung <> in suedafrika <> <> (true)
bezeichnet <> _ <> als erdbeben messbare erschuetterungen der erdoberflaeche <> <> (true)
bezeichnet <> als frisur <> man die anordnung der kopfhaare <> <> (true)
bezeichnet <> als synthese <> man den umsatz eine neuen einheit <> von zwei oder mehr elementen <> <> (true)
bezeichnet <> amnesie <> einen gedaechtnisverlust <> <> (true)
bezeichnet <> chat <> elektronische kommunikation <> zwischen personen in echtzeit <> <> (true)
bezeichnet <> der mediator <> den vermittler <> in einem kommunikationsprozess <> <> (true)
bezeichnet <> der scheitel <> eine trennlinie <> in dem kopfbereich <> <> (true)
bezeichnet <> ein lied <> ein gesungenes musikstueck <> <> (true)
bezeichnet <> ein wort <> eine grammatische einheit <> <> (true)
bezeichnet genutztes <> der ausdruck mine <> ein wirtschaftlich bergwerk <> <> (true)
bezeichnet wird <> das weltall <> <> mit kosmos <> <> (true)
bist <> du <> ein mensch <> <> (true)
bist <> du <> eine kuenstliche intelligenz <> nicht <> bist <> du <> ein mensch <> <> <> (true)
bleiben lassst <> du <> es <> <> wenn <> <> reden willst <> du <> nicht <> <> (true)
bleiben soll <> du <> <> (true)
bleiben wird <> der sinn des lebens <> immer ein raetsel <> <> (true)
bleiben wird <> der weltfrieden <> ein traum der menschen <> <> (true)
bleibt <> der sinn des lebens <> ein raetsel <> <> (true)
brauche <> ich <> einen herd <> <> kochen will <> ich <> <> <> wenn <> <> (true)
brauchen <> menschen <> luft <> <> <> <> atmen <> <> (true)
brauchen <> menschen <> nahrung <> <> (true)
brauchen <> menschen <> schlaf <> <> (true)
brauchen <> sie <> schlaf <> <> weil <> <> sind <> menschen <> <> (true)
braucht <> dein computer <> strom <> <> (true)
braucht <> ein baby <> jemand <> <> <> <> wickelt <> das es <> <> (true)
braucht <> ein baby <> windeln <> <> (true)
braucht <> ein benzinmotor <> zuendkerzen <> <> (true)
braucht <> ein computer <> ein betriebssystem <> <> (true)
braucht <> ein dieselmotor <> eine zuendkerzen <> nicht <> <> (true)
braucht <> ein holzfaeller <> eine axt <> <> (true)
braucht <> eine ki <> keinen schlaf <> <> (true)
braucht <> geld <> jeder mensch <> <> (true)
braucht essen <> man <> besteck <> zum <> <> (true)
braucht kochen <> man <> einen herd <> <> (true)
braucht schneiden <> eine schere <> man <> zum <> <> (true)
braucht schneiden <> man <> eine schere <> zum <> <> (true)
buegeln <> ist <> hausarbeit <> <> (true)
denken kann/can <> ein mensch <> <> (true)
denken kann/can <> eine ki <> <> nicht <> <> (true)
dient <> die zahnbuerste <> der zaehne <> zur reinigung <> <> (true)
dient <> ein spiel <> <> zur entspannung <> <> (true)
dient <> eine fernsehserie <> der menschen <> zur unterhaltung <> <> (true)
dient <> und <> <> zur entspannung <> <> (true)
dient <> unterhaltung <> <> zur entspannung <> <> (true)
dreht <> die erde <> sich um die sonne <> <> (true)
dreht <> die uhr <> sich immer <> weiter <> <> (true)
dreht <> ein satellit <> sich <> um einen planeten <> <> (true)
durchsetzen heisst wollen <> gewalt <> etwas <> mit zwang;zu <> <> (true)
entdeckte <> abel janszoon tasman <> neuseeland <> <> (true)
enthalten ist <> nikotin <> <> in zigaretten <> <> (true)
entstanden ist <> das universum <> <> durch den urknall <> <> (true)
entstehen <> kinder <> <> nicht <> gezeugt <> werden <> kinder <> <> <> <> _ <> <> (true)
entwickelt hat <> _albert_einstein_ <> die relativitaetstheorie <> <> (true)
entwickelt wird <> eine ki <> <> (true)
erfolgt <> eine antwort <> <> auf jede frage <> <> (true)
erklaert hast <> du <> mir <> das;schon <> <> (true)
erschaffen hat <> gott <> das universum <> <> (true)
erwartet <> man <> sich eine antwort <> auf jede frage <> <> (true)
erzeugt <> die sonne <> licht & waerme <> <> (true)
erzeugt <> ein kloeppler <> spitzen <> <> (true)
essen <> menschen <> feste nahrung <> <> (true)
essen <> vegetarier <> ein fleisch <> nicht <> <> (true)
essen <> vegetarier <> gemuese & obst <> <> (true)
essen <> vegetarier <> kein fleisch <> <> (true)
essen kann/can <> man <> <> ohne mund nicht <> <> (true)
essen muessen <> menschen <> <> (true)
essen musst <> du <> <> <> hast <> du <> hunger <> <> wenn <> <> (true)
fahren <> autos <> <> (true)
fahren <> autos <> <> auf einer strasse <> <> (true)
fahren kann/can <> du <> <> mit einem auto <> <> (true)
fahren kann/can <> ein auto <> <> (true)
fahren kann/can <> man <> <> mit einem auto <> <> (true)
fahren kann/can <> man <> <> mit einem schiff ueber das wasser <> <> (true)
fahren kann/can <> man <> <> mit einen schiff ueber das meer <> <> (true)
finden <> alle <> windows <> nicht;toll <> <> (true)
finden <> alle 10 jahre <> passionsspiele <> in oberammergau;statt <> <> (true)
finden <> ein teil <> die archeologen <> von der gegenstaende <> sind <> tonkruege <> <> (true)
finden grillen <> menschen <> super <> <> (true)
findst <> du <> die revision <> auf der freehal seite <> <> <> (true)
fliegen kann/can <> ein auto <> <> nicht <> <> (true)
fliegen kann/can <> ein flugzeug <> <> (true)
fliegen kann/can <> man <> <> mit einem ballon in der luft <> <> (true)
fliegen kann/can <> man <> <> mit einem flugzeug <> <> (true)
fliegen koennen <> flugkoerper <> <> (true)
fliegen koennen <> pinguine <> <> nicht <> <> (true)
fliegen wuerden <> sie <> <> <> wenn <> <> haetten <> menschen <> fluegel <> <> (true)
fliegt <> ein flugzeug <> <> durch das gesetz der aerodynamik <> <> (true)
frankieren muss <> man <> einen brief <> <> (true)
freut <> dich <> <> das fuer mich <> <> (true)
freut <> sich <> der <> dritte <> wenn <> <> streiten <> zwei sich <> <> (true)
freut lesen <> das dich <> <> zu <> <> (true)
frieren kann/can <> man <> <> in dem winter <> <> (true)
friert <> man <> <> ohne waerme <> <> (true)
fuehlen kann/can <> man <> <> ohne herz nicht <> <> (true)
fuehlen koennen <> menschen <> schmerzen <> <> (true)
fuerchtet <> jeder <> <> seinen tod <> <> (true)
funktioniert <> eine rakete <> <> nach dem rueckstossprinzip <> <> (true)
gab <> es <> 7 weltwunder <> <> (true)
gar weiss <> du <> heute nichts <> <> (true)
gehen <> menschen <> <> zum doktor <> sind <> sie <> <> krank <> wenn <> <> (true)
gehen <> sie <> <> zum doktor <> weil <> <> sind <> menschen <> <> (true)
gehen kann/can <> man <> <> ohne fuesse nicht <> <> (true)
gehoert <> <> (true)
gehoert <> das brautpaar <> <> zu einer hochzeit <> <> (true)
gehoert <> dem mutigen <> die welt <> <> (true)
gehoert <> ein langfinger <> <> _an_die_hand_(sondern_ins_gefaengnis) nicht_ <> <> (true)
gehoert <> so etwas <> sich <> nicht <> <> (true)
gehoert <> spinat <> <> zur gattung der gaensefussgewaechse <> <> (true)
gehst <> du <> <> jetzt wieder <> <> (true)
geht <> das <> <> so nicht <> <> (true)
geht <> das <> <> so sicher nicht <> <> (true)
geht <> dir <> es <> auch gut <> <> (true)
geht <> dir <> es <> schlecht <> <> (true)
geht <> einer maschine <> es immer <> gleich <> <> (true)
geht <> es <> mir manchmal <> auch;so <> <> (true)
geht <> immer <> <> irgendwie alles <> <> (true)
geht <> man <> rodeln <> in dem winter <> <> (true)
geht <> man <> schifahren <> in dem winter <> <> (true)
geil ist <> das <> <> (true)
gelernt hat <> die arbeit <> ein mensch <> <> (true)
genannt <> _ <> der abendstern <> die venus <> <> (true)
gibt <> bei burger king <> es einen burger <> <> (true)
gibt <> es <> 7 weltwunder <> <> (true)
gibt <> es <> burger <> _bei_mc_donalds_ <> <> (true)
gibt <> es <> ein joghurt <> ohne milch <> <> (true)
gibt <> es <> ein schlagobers <> nicht ohne milch <> <> (true)
gibt <> es <> ein wetter <> nicht bei mir <> <> (true)
gibt <> es <> ein wetter <> nicht in einem computer <> <> (true)
gibt <> es <> eine butter <> nicht ohne milch <> <> (true)
gibt <> es <> eine sahne <> nicht ohne milch <> <> (true)
gibt <> es <> einen gott <> <> (true)
gibt <> es <> einen grund <> fuer alles <> <> (true)
gibt <> es <> einen kaese <> nicht ohne milch <> <> (true)
gibt <> es <> kein leben <> nicht ohne sonne <> <> (true)
gibt <> es <> leben <> <> <> gott es <> <> so wollte <> weil <> <> (true)
gibt <> es <> _leben_gott_es_ <> so wollte <> <> (true)
gibt <> es <> nichts <> neues zur zeit <> <> (true)
gibt <> es <> unendlich viele sterne <> <> (true)
gilt <> louis daguerra <> als erfinder <> der fotografie <> <> (true)
greifen kann/can <> man <> <> ohne haende nicht <> <> (true)
haben <> alle menschen <> zwei augen <> <> (true)
haben <> alle quadrate <> vier ecken <> <> (true)
haben <> alle voegel <> federn <> <> (true)
haben <> kuenstliche wesen <> ein aussehen <> nicht <> <> (true)
haben <> kuenstliche wesen <> einen geburtstag <> nicht <> <> (true)
haben <> menschen <> ohren <> <> (true)
haben <> menschen <> schmerzen <> <> verletzen <> sie <> sich <> <> wenn <> <> (true)
haben kann/can <> ein kuenstliches wesen <> einen sex <> nicht <> <> (true)
haben kann/can <> eine ki <> einen sex <> nicht <> <> (true)
haben luegen <> kurze beine <> <> (true)
haelt <> bewegung <> <> fit <> <> (true)
haelt <> bewegung <> den koerper <> in form <> <> (true)
haengen sind <> schlappohren <> ohren <> die <> <> (true)
haengt <> der duerer-hase <> <> in der albertina <> <> (true)
halten heisst <> sauberkeit <> <> alles rein <> <> (true)
hat <> alles <> irgendwie einen sinn <> <> (true)
hat <> das jahr <> vier jahreszeiten <> <> (true)
hat <> der mensch <> 12 rippenpaare <> <> (true)
hat <> die sonne <> eine gelbe farbe <> <> (true)
hat <> ein auto <> 4 raeder <> <> <> oder <> <> mehr <> <> (true)
hat <> ein auto <> ein motor <> <> (true)
hat <> ein auto <> raeder <> <> (true)
hat <> ein auto <> vier raeder <> <> <> <> <> <> ) <> <> (true)
hat <> ein dominospiel <> 28 steine <> <> (true)
hat <> ein jahr <> 12 monate <> <> (true)
hat <> ein jahr <> 365 tage <> <> (true)
hat <> ein kuenstliches wesen <> einen geburtstag <> nicht <> <> (true)
hat <> ein kuenstliches wesen <> einen koerper <> nicht <> <> (true)
hat <> ein kuenstliches wesen <> einen sex <> nicht <> <> (true)
hat <> ein mensch <> <> eine nase <> <> (true)
hat <> ein mensch <> 10 finger <> <> (true)
hat <> ein mensch <> 2 augen <> <> (true)
hat <> ein mensch <> 2 haende <> <> (true)
hat <> ein mensch <> einen mund <> <> (true)
hat <> ein mensch <> zwei ohren <> <> (true)
hat <> ein tag <> 24 stunden <> <> (true)
hat <> eine hand <> 5 finger <> <> (true)
hat <> eine hand <> fuenf finger <> <> (true)
hat <> eine ki <> ein geschlecht <> nicht <> <> (true)
hat <> eine ki <> ein lieblingsessen <> nicht <> <> (true)
hat <> eine ki <> ein urlaub <> nicht <> <> (true)
hat <> eine ki <> eine eltern <> nicht <> <> (true)
hat <> eine ki <> eine emotionen <> nicht <> <> (true)
hat <> eine ki <> eine ferien nicht <> <> (true)
hat <> eine ki <> eine gefuehle <> nicht <> <> (true)
hat <> eine ki <> eine wohnung <> nicht <> <> (true)
hat <> eine ki <> einen koerper <> nicht <> <> (true)
hat <> eine ki <> einen sex <> nicht <> <> (true)
hat <> eine ki <> nie hunger <> <> (true)
hat <> eine kuenstliche intelligenz <> ein lieblingsessen <> nicht <> <> (true)
hat <> eine kuenstliche intelligenz <> eine emotionen <> nicht <> <> (true)
hat <> eine kuenstliche intelligenz <> eine ferien nicht <> <> (true)
hat <> eine kuenstliche intelligenz <> eine gefuehle <> nicht <> <> (true)
hat <> eine kuenstliche intelligenz <> eine wohnung <> nicht <> <> (true)
hat <> eine minute <> 60 sekunden <> <> (true)
hat <> eine stunde <> 3600 sekunden <> <> (true)
hat <> eine stunde <> 60 minuten <> <> (true)
hat <> ferrari <> ein springendes pferd <> in dem wappen <> <> (true)
hat <> gras <> eine gruene farbe <> <> (true)
hat <> isaak adam <> die tiegeldruckpresse erfunden <> <> <> (true)
hat <> jeder <> ein anderen besten film <> <> (true)
hat <> jeder <> so seine probleme <> <> (true)
hat <> kaese <> <> viele farben <> <> (true)
hat <> linux <> <> viele entwickler <> <> (true)
hat <> red bull <> <> seinen sitz in fuschl <> <> (true)
hat <> reines gold <> 24 karat <> <> (true)
hat <> sieben tage <> eine woche <> <> (true)
hat <> wasser <> bei 4 grad plus die hoechste dichte <> <> (true)
hat <> wasser <> eine reflektierende oberflaeche <> <> (true)
haust <> du <> dich <> aufs ohr <> <> (true)
heissen <> geroestete weissbrotwuerfel <> crouton <> <> (true)
heisst <> _beelzebub_ <> herr <> der fliegen <> <> (true)
heisst <> _carpe_diem_ <> _nutze_den_tag_ <> <> (true)
heisst <> abgb <> allgemeines buergerliches gesetzbuch <> <> (true)
heisst <> agronomie <> die lehre <> vom ackerbau <> <> (true)
heisst <> aldi <> hofer <> in oesterreich <> <> (true)
heisst <> archaeologie <> die lehre <> von den altertuemern <> <> (true)
heisst <> astronomie <> die lehre <> von der sternenkunde <> <> (true)
heisst <> ausreichend <> <> sehr viel <> <> (true)
heisst <> das ergebnis einer addition <> summe <> <> (true)
heisst <> das ergebnis einer division <> quotient <> <> (true)
heisst <> das ergebnis einer multiplikation <> produkt <> <> (true)
heisst <> das ergebnis einer subtraktion <> differenz <> <> (true)
heisst <> das groesste weltraumteleskop <> hubble <> <> (true)
heisst <> das maennliche pferd <> hengst <> <> (true)
heisst <> das russische parlament <> duma <> <> (true)
heisst <> die hauptstadt deutschlands <> berlin <> <> (true)
heisst <> die lehre <> dogmatik <> vom glauben <> <> (true)
heisst <> dogmatik <> die lehre <> vom glauben <> <> (true)
heisst <> ein handelsverbot <> embargo <> <> (true)
heisst <> fsme <> fruehsommer meningoenzephalitis <> <> (true)
heisst <> innovation <> erneuerung <> <> (true)
heisst <> innovation <> woertlich neuerung <> <> (true)
heisst <> ki <> kuenstliche intelligenz <> <> (true)
heisst <> meteorologie <> die lehre <> vom wetter <> <> (true)
heisst <> nautik <> die lehre <> von der schiffahrt <> <> (true)
heisst <> rotkohl <> blaukraut <> in oesterreich <> <> (true)
heisst <> verstaendnis <> verstehen <> <> (true)
heisst <> windows <> <> das meistverwendete betriebssystem <> <> (true)
heisst sagen <> luegen <> nicht die wahrheit <> <> (true)
heisst weiss <> unbekannt das niemand <> darueber etwas <> <> (true)
heisst zeit <> chronologie <> die lehre <> von der <> <> (true)
helfen kannst/can <> du <> mir <> auch nicht <> <> (true)
herrscht <> der linksverkehr <> <> in japan <> <> (true)
hoeren kann/can <> man <> <> ohne ohren nicht <> <> (true)
hoeren kann/can nicht <> eine ki <> eine musik <> <> (true)
hoeren kann/can nicht <> eine kuenstliche intelligenz <> eine musik <> <> (true)
holz <> ist <> das feste harte gewebe von baeumen und straeuchern <> <> <> (true)
hungern muss <> man <> <> ohne nahrung <> <> (true)
isst <> eine ki <> <> nicht <> <> (true)
isst <> feste nahrung <> man <> <> (true)
isst <> man <> laugenbrezen <> zur weisswurst <> <> (true)
ist <> _alt_ <> das gegenteil <> _von_neu_ <> <> (true)
ist <> _altrosa_ <> eine farbe <> <> (true)
ist <> _blau_ <> eine farbe <> <> (true)
ist <> _boese_ <> das gegenteil <> _von_gut_ <> <> (true)
ist <> _braun_ <> eine farbe <> <> (true)
ist <> _c++_ <> eine programmiersprache <> <> (true)
ist <> _cool_ <> ein dummer begriff aus dem <> englischen <> <> (true)
ist <> _dunkelblau_ <> eine farbe <> <> (true)
ist <> _dunkelbraun_ <> eine farbe <> <> (true)
ist <> _dunkelgrau_ <> eine farbe <> <> (true)
ist <> _dunkelgruen_ <> eine farbe <> <> (true)
ist <> _dunkelrot_ <> eine farbe <> <> (true)
ist <> _echt_ <> <> besser als unecht <> <> (true)
ist <> _gelb_ <> eine farbe <> (true)
ist <> _grau_ <> eine farbe <> (true)
ist <> _gruen_ <> eine farbe <> (true)
ist <> _hallo_ <> eine begruessung <> (true)
ist <> _hellblau_ <> eine farbe <> (true)
ist <> _hellbraun_ <> eine farbe <> (true)
ist <> _hellgelb_ <> eine farbe <> (true)
ist <> _hellgrau_ <> eine farbe <> (true)
ist <> _hellgruen_ <> eine farbe <> (true)
ist <> _hellrosa_ <> eine farbe <> (true)
ist <> _herr_der_ringe_ <> ein guter film <> (true)
ist <> _indigo_ <> eine farbe <> (true)
ist <> _lila_ <> eine farbe <> <> (true)
ist <> _ocker_ <> eine farbe <> <> (true)
ist <> _rosa_ <> eine farbe <> <> (true)
ist <> _rot_ <> eine farbe <> <> (true)
ist <> _sandbraun_ <> eine farbe <> <> (true)
ist <> _schneeweiss_ <> eine farbe <> <> (true)
ist <> _schwanken_ <> eine bewegung <> <> (true)
ist <> _schwarz_ <> eine farbe <> <> (true)
ist <> _silver_ <> eine farbe <> <> (true)
ist <> _sos_ <> ein internationales notsignal <> <> (true)
ist <> _tiefblau_ <> eine farbe <> <> (true)
ist <> _tuerkis_ <> eine farbe <> <> (true)
ist <> _violett_ <> eine farbe <> <> (true)
ist <> _warum_ <> eine gute frage <> <> (true)
ist <> _weiss_ <> eine farbe <> <> (true)
ist <> <> <> bei mir alles klar <> <> (true)
ist <> <> ein unreifer weiblicher mensch <> ein maedchen <> <> (true)
ist <> aids <> eine schreckliche krankheit <> <> (true)
ist <> aikido <> eine japanische kampfsportart <> <> (true)
ist <> aikido <> _eine_moderne_ <> _(japanische_kampfkunst)_ <> <> (true)
ist <> akribie <> hoechste genauigkeit <> <> (true)
ist <> akupunktur <> ein teilgebiet medizin <> der chinesischen <> <> (true)
ist <> akustik <> die lehre <> vom schall <> <> (true)
ist <> akustik <> die lehre <> vom schall und seiner ausbreitung <> <> (true)
ist <> aldi <> ein bekannter discounter <> <> (true)
ist <> alkohol <> ein suchtgift <> <> (true)
ist <> alkohol <> eine geisel <> der menschheit <> <> (true)
ist <> alkohol <> eine legale droge <> <> (true)
ist <> alkohol <> gift <> fuer den koerper <> <> (true)
ist <> an dem ende der welt <> das absolute nichts <> <> (true)
ist <> anarchismus <> eine politische ideenlehre <> <> (true)
ist <> andromeda <> <> eine gestalt der griechischen mythologie <> <> (true)
ist <> andromeda <> eine fernsehserie <> <> (true)
ist <> andromeda <> eine galaxie <> <> (true)
ist <> angela merkel <> eine politikerin <> <> (true)
ist <> anna netrebko <> eine opernsaengerin <> <> (true)
ist <> ansi <> ein nationales standardisierungsgremium <> der usa <> <> (true)
ist <> anthropologie <> die lehre <> vom menschen <> <> (true)
ist <> antimaterie <> benzin a la enterprise <> fuer raumschiffe <> <> (true)
ist <> apple <> das englische wort fuer apfel <> <> (true)
ist <> apres ski <> ein wintersport <> <> (true)
ist <> arabisch <> amtssprache <> in 21 laendern <> <> (true)
ist <> architektur <> die auseinandersetzung der menschen <> mit gebautem raum <> <> (true)
ist <> area <> ein militaerisches sperrgebiet <> 51 <> <> (true)
ist <> arnold <> schwarzenegger <> der gouverneur von kalifornien <> <> (true)
ist <> arrak <> ein branntwein <> <> (true)
ist <> arschloch <> ein schimpfwort du dumpfbacke <> <> (true)
ist <> athlon <> ein eingetragener markenname des mikroprozessorherstellers amd <> <> (true)
ist <> audi <> ein autohersteller <> <> (true)
ist <> austria <> der lateinische name <> fuer oesterreich <> <> <> <> <> <> <> h <> <> (true)
ist <> backgammon <> ein strategiespiel <> <> (true)
ist <> badmington <> ein sport <> <> (true)
ist <> barack obama <> ein amerikanischer politiker <> <> (true)
ist <> bart simpson <> der sohn <> von homer <> <> (true)
ist <> bart simpson <> marge <> von homer <> <> (true)
ist <> _bart_simpson_ <> zehn jahre <> alt <> <> (true)
ist <> basic <> eine programmiersprache <> <> (true)
ist <> basketball <> ein amerikanischer freizeitsport <> <> (true)
ist <> betrug <> <> ein verbrechen <> <> (true)
ist <> betrug <> eine taeuschung <> in dem strafrechtlichen sinn <> <> (true)
ist <> bewegung <> <> gesund <> <> (true)
ist <> bewegung <> gut <> fuer geist <> <> (true)
ist <> bier <> <> lebensnotwendig <> <> (true)
ist <> bier <> ein alkoholisches getraenk <> <> (true)
ist <> bill gates <> der gruender <> von microsoft <> <> (true)
ist <> bimstein <> schaumiges gesteinsglas <> <> (true)
ist <> biologie <> eine naturwissenschaft <> <> (true)
ist <> blackjack <> ein gluecksspiel <> <> (true)
ist <> blackjack <> ein kartenspiel <> <> (true)
ist <> blasphemie <> gotteslaesterung <> <> (true)
ist <> blau <> die farbe des himmels <> <> (true)
ist <> blau <> meine lieblingsfarbe <> <> (true)
ist <> bmw <> ein autohersteller <> <> (true)
ist <> boese <> das gegenteil <> von gut <> <> (true)
ist <> boris becker <> ein tennispieler <> <> (true)
ist <> borschtsch <> ein russisches nationalgericht <> <> (true)
ist <> britney spears <> eine saengerin <> <> (true)
ist <> brot <> ein grundnahrungsmittel <> <> (true)
ist <> calvados <> ein apfelbranntwein <> <> (true)
ist <> cannabis <> der lateinische wissenschaftliche name der hanfpflanze <> <> (true)
ist <> captain picard <> ein interessanter charakter <> <> (true)
ist <> captain picard <> eine interessante figur <> <> (true)
ist <> carpaccio <> eine italienische vorspeise <> <> (true)
ist <> cassata <> eine italienische eisspezialitaet <> <> (true)
ist <> champagne <> ein alkoholisches getraenk <> <> (true)
ist <> chdk <> das canon hackers development kit <> <> (true)
ist <> cointreau <> ein likoer <> <> (true)
ist <> cola <> ein koffeinhaltiges limonadengetraenk <> <> (true)
ist <> crack <> eine droge <> <> (true)
ist <> curry <> eine indische gewuerzmischung <> <> (true)
ist <> dame <> ein brettspiel <> <> (true)
ist <> das <> <> aber enttaeuschend <> <> (true)
ist <> das <> <> aber schlecht <> <> (true)
ist <> das <> <> falsch <> <> (true)
ist <> das <> <> nicht notwendig <> <> (true)
ist <> das <> <> nicht richtig <> <> (true)
ist <> das <> <> richtig <> <> (true)
ist <> das <> <> schade <> <> (true)
ist <> das <> <> schoen <> <> (true)
ist <> das <> <> schon richtig <> <> (true)
ist <> das <> <> sehr schade <> <> (true)
ist <> das <> schoen <> <> (true)
ist <> das bett <> ein geheimer ort <> <> dringt <> nichts <> <> nach draussen <> <> (true)
ist <> das bewusstsein <> der besitz und die empfindung mentaler zustaende <> <> (true)
ist <> das blut <> eine koerperfluessigkeit <> <> (true)
ist <> das burj dubai <> das hoechste hochhaus <> der welt <> <> (true)
ist <> das feuer <> eine form der chemischen verbrennung <> mit flammenbildung <> <> (true)
ist <> das gegenteil <> <> heiss;von kalt <> <> (true)
ist <> das gegenteil <> <> kalt;von heiss <> <> (true)
ist <> das gegenteil <> oben <> von unten <> <> (true)
ist <> das gegenteil <> unten <> von oben <> <> (true)
ist <> das hauspferd <> die domestizierte form des wildpferdes <> <> (true)
ist <> das heim <> das haus <> in dem menschen leben <> <> (true)
ist <> das internet <> wide web <> das world <> <> (true)
ist <> das jahr <> eine zeiteinheit <> <> (true)
ist <> das koffein <> ein alkaloid <> <> (true)
ist <> das martinshorn <> das akustische signal <> von einsatzfahrzeugen <> <> (true)
ist <> das moulin rouge <> ein pariser varietee <> <> (true)
ist <> das pentagon <> der hauptsitz des us verteidigungsministeriums <> <> (true)
ist <> das purgatorium <> das fegefeuer <> <> (true)
ist <> das wetter <> <> toll <> <> (true)
ist <> das wiegenfest <> der geburtstag <> <> (true)
ist <> data <> der android <> aus der serie startrek <> <> <> (true)
ist <> data <> eine perfekte ki <> aus startrek <> <> (true)
ist <> data <> eine perfekte kuenstliche intelligenz <> <> (true)
ist <> delta <> der vierte buchstabe <> iem griechischen alphabet <> <> (true)
ist <> der abendstern <> <> die venus <> <> (true)
ist <> der airbus-a380 <> das groesste passagierflugzeug <> der welt <> <> (true)
ist <> der bang na expressway <> die laengste bruecke <> der welt <> <> (true)
ist <> der bizeps <> ein muskel <> in dem oberarm <> <> (true)
ist <> der blauwal <> der groesste wal <> <> (true)
ist <> der chapeton <> der laengste staudamm <> der welt <> <> (true)
ist <> der diamant <> haerter als granit <> <> (true)
ist <> der dollar <> eine waehrung <> <> (true)
ist <> der dollarkurs <> jeden tag <> anders <> <> (true)
ist <> der einbaum <> <> ein ausgehoehlten baumstamm <> <> (true)
ist <> der euro <> die waehrung <> in oesterreich <> <> (true)
ist <> der fond <> die basis <> fuer saucen <> <> (true)
ist <> der fruehling <> eine jahreszeit <> <> (true)
ist <> der gepard <> das schnellste landsaeugetier <> <> (true)
ist <> der golem <> ein juedisches fabelwesen <>  <> (true)
ist <> der herbst <> eine jahreszeit <> <> (true)
ist <> der herold <> eine telefonnummernauskunft <> <> (true)
ist <> der herr der ringe <> ein roman <> von tolkien <> <> (true)
ist <> der highlander <> die tollste person <> der welt <> <> (true)
ist <> der himmel <> <> blau <> wenn <> <> scheint <> die sonne <> <> (true)
ist <> der lapislazuli <> <> tiefblau <> <> (true)
ist <> der lapislazuli <> ein schmuckstein <> <> (true)
ist <> der matebaum <> <> ein immergruener laubbaum <> <> (true)
ist <> der meister <> die hoechste qualifikationsstufe <> in dem handwerk <> <> (true)
ist <> der nurek-staudamm <> der hoechste staudamm <> der welt <> <> (true)
ist <> der oeltanker jahre viking <> das groesste schiff <> der welt <> <> (true)
ist <> der palstek <> ein seemannsknoten <> <> (true)
ist <> der pastis <> ein anischnaps <> <> (true)
ist <> der phoenix <> ein mysthischer vogel <> <> (true)
ist <> der playboy <> ein amerikanisches maennermagazin <> <> (true)
ist <> der sari <> das gewickelte gewand einer inderin <> <> (true)
ist <> der schlaf <> ein zustand der aeusseren ruhe <> <> (true)
ist <> der schmelzpunkt <> die temperatur <> bei der ein stoff schmilzt <> <> <> (true)
ist <> der schmerz <> eine komplexe sinnesempfindung <> <> (true)
ist <> der schmerz <> eine unangenehme erfahrung <> <> (true)
ist <> der schuetze <> das suedlichste tierkreiszeichen <> <> (true)
ist <> der schweif <> die spur <> eines kometen <> <> (true)
ist <> der shinkansen <> ein schellzug <> in japan <> <> (true)
ist <> der sommer <> eine jahreszeit <> <> (true)
ist <> der stockfisch <> getrockneten kabeljau <> <> (true)
ist <> der tee <> ein heisses aufgussgetraenk <> <> (true)
ist <> der teufel <> <> in der hoelle <> <> (true)
ist <> der tod <> das gegenteil <> von leben <> <> (true)
ist <> der weihnachstmann <> ein maerchen <> <> (true)
ist <> der weltspartag <> <> an dem 31 oktober <> <> (true)
ist <> der winter <> eine jahreszeit <> <> (true)
ist <> der winter <> eine kalte jahreszeit <> <> (true)
ist <> der zwoeffingerdarm <> _30_zentimeter_ <> lang <> <> (true)
ist <> _die_a_10_ <> die tauernautobahn <> <> (true)
ist <> die absolution <> eine vergebung <> nach einem eingestaendnis <> <> (true)
ist <> die aegyptische sphinx <> eine statue eines maennlichen loewen <> <> (true)
ist <> die albertina <> ein museum <> <> (true)
ist <> die amtssprache <> portugiesisch <> in brasilien <> <> (true)
ist <> die bandura <> ein zupfinstrument <> <> (true)
ist <> die bibel <> das wort gottes <> <> (true)
ist <> die bouillabaisse <> eine fischsuppe <> <> (true)
ist <> die brailleschrift <> die blindenschrift <> <> (true)
ist <> die chiromantie <> die handlesekunst <> <> (true)
ist <> die coco-de-mer <> die groesste baumfrucht <> der erde <> <> (true)
ist <> die deduktion <> eine schlussfolgerungsweise <> <> (true)
ist <> die erde <> unser heimatplanet <> <> (true)
ist <> die fabrik <> eine einrichtung <> fuer den industriellen grossbetrieb <> <> (true)
ist <> die farbe <> des himmels <> blau <> <> (true)
ist <> die gitarre <> ein musikinstrument aus der familie der kastenhalslauten <> <> (true)
ist <> die gymnastik <> die kunst der leibesuebungen <> <> (true)
ist <> die hauptstadt deutschlands <> berlin <> <> (true)
ist <> die hermeneutik <> die kunst <> der auslegung <> <> (true)
ist <> die hoelle <> ein schlimmer platz <> <> (true)
ist <> die induktion <> der gegenbegriff <> zur deduktion <> <> (true)
ist <> die kandare <> die gebissstange <> an dem pferdegeschirr <> <> (true)
ist <> die kemenate <> das gemach <> der frau <> <> (true)
ist <> die kindheit <> der zeitraum <> _in_dem_leben_von_einem_menschen_von_der_geburt_bis_zur_geschlechtlichen_entwicklung_ <> <> (true)
ist <> die klarninette <> ein blasinstrument <> <> (true)
ist <> die kreiszahl pi <> <> 3,142857142857 <> <> (true)
ist <> die leber <> das zentrale organ des gesamten stoffwechsels <> <> (true)
ist <> die lichtgeschwindigkeit <> eine konstante <> <> (true)
ist <> die londoner oper <> <> _in_london_(dumme_frage)_ <> <> (true)
ist <> die mechanik <> ein teilgebiet der physik <> <> (true)
ist <> die meile <> ein altes laengenmass <> <> (true)
ist <> die milchstrasse <> unsere galaxie <> <> (true)
ist <> die mona lisa <> ein bild <> <> (true)
ist <> die nacht <> <> dunkel <> <> (true)
ist <> die ontologie <> eine disziplin der theoretischen philosophie <> <> (true)
ist <> die osteologie <> die lehre bzw <> vom skelettsystem;von den knochen <> <> (true)
ist <> die paella <> ein spanisches reisgericht <> <> (true)
ist <> die posaune <> ein blasinstrument <> <> (true)
ist <> die psychopathologie <> ein teilbereich der psychiatrie <> <> (true)
ist <> die pummerin <> eine glocke <> <> (true)
ist <> die radiologie <> das teilgebiet der medizin <> <> (true)
ist <> die rouchade <> ein zug <> mit koenig & turm <> <> (true)
ist <> die rouchade <> ein zug turm <> mit koenig & <> <> (true)
ist <> die shell <> die <> kommanozeile <> <> (true)
ist <> die sphinx <> eine statue eines maennlichen loewen <> <> (true)
ist <> die styriarte <> ein musikfestival <> in der steiermark <> <> (true)
ist <> die temperatur <> eine physikalische zustandsgroesse <> <> (true)
ist <> die unendlichkeit <> das gegenteil <> von endlichkeit <> <> (true)
ist <> die venusfliegenfalle <> eine fleischfressende pflanze <> <> (true)
ist <> die wikipedia <> ein gemeinschaftsprojekt vieler menschen <> <> (true)
ist <> die zahl 13 <> eine primzahl <> <> (true)
ist <> die zeit <> ein grosses geheimnis <> in dem universum <> <> (true)
ist <> diebstahl <> <> ein verbrechen <> <> (true)
ist <> dienstag <> tag <> der zweite der woche <> <> (true)
ist <> dieser computer <> sehr schnell <> <> (true)
ist <> dir <> <> anscheinend oft langweilig <> <> (true)
ist <> donnerstag <> der vierte tag <> der woche <> <> (true)
ist <> ebay <> ein auktionshaus <> in dem internet <> <> (true)
ist <> echelon <> der name eines spionagenetzes <> <> (true)
ist <> _ein_harzer_roller_ <> ein kanarienvogel <> <> (true)
ist <> _ein_schuhplattler_ <> ein bayerisch-oesterreichischer tanz <> <> (true)
ist <> ein abakus <> ein rechengeraet <> <> (true)
ist <> ein abfangjaeger <> ein kampfflugzeug <> <> (true)
ist <> ein abfangjaeger <> ein militaerflugzeug <> <> (true)
ist <> ein abszess <> eine umkapselte eiteransammlung die <> durch entzuendliche gewebseinschmelzung entsteht <> (maybe)
ist <> ein adjektiv <> ein eigenschaftswort <> <> (true)
ist <> ein adverb <> ein umstandswort <> <> (true)
ist <> ein affe <> ein <> intelligentes tier <> <> (true)
ist <> ein ahorn <> ein baum <> <> (true)
ist <> ein akronym <> eines sonderfalls <> die abkuerzung <> <> (true)
ist <> ein almanach <> ein kalender <> <> (true)
ist <> ein anwalt <> ein rechtsanwalt <> <> (true)
ist <> ein apfel <> eine frucht <> <> (true)
ist <> ein archiv <> eine aktensammlung <> <> (true)
ist <> ein archiv <> eine urkundensammlung <> <> (true)
ist <> ein atlant <> ein gebaelktraeger <> <> (true)
ist <> ein atoll <> ein ringfoermiges koralleneiland <> <> (true)
ist <> ein auto <> ein fahrzeug <> <> (true)
ist <> ein auto <> ein selbstfahrendes fahrzeug <> <> (true)
ist <> ein baby <> ein ganz kleines kind <> <> (true)
ist <> ein baby <> ein hilfloser kleiner mensch <> <> (true)
ist <> ein baby <> ein kind <> in dem ersten lebensjahr <> <> (true)
ist <> ein baby <> ein mensch <> mit windeln <> <> (true)
ist <> ein baby <> ein neugeborenes kind <> <> (true)
ist <> ein barolo <> ein wein <> <> (true)
ist <> ein basilisk <> eine leguanart <> <> (true)
ist <> ein bauchredner <> ein ventriloquist <> <> (true)
ist <> ein baum <> ein lebender organismus <> <> (true)
ist <> ein baum <> eine grosse pflanze <> <> (true)
ist <> ein berg <> eine erhebung <> in dem gelaende <> <> (true)
ist <> ein berserker <> ein blindwuetig tobender mensch <> <> (true)
ist <> ein beruf <> die arbeit <> <> (true)
ist <> ein bh <> ein teil der unterwaesche eines weiblichen erwachsenen menschen <> <> (true)
ist <> ein blackberry <> _ein_tragbares_geraet_zum_lesen_und_schreiben_ <> von e-mails <> <> (true)
ist <> ein blaufelchen <> ein fisch <> <> (true)
ist <> ein boot <> ein gefaehrt das faehrt <> auf dem wasser <> <> (true)
ist <> ein bot <> ein softwareroboter <> <> (true)
ist <> ein buch <> bedrucktes gebundenes papier <> <> (true)
ist <> ein buchmacher <> der besitzer <> von einem wettbuero <> <> (true)
ist <> ein buergermeister <> das oberhaupt <> von einer gemeinde oder stadt<> 50
ist <> ein bundesland <> ein gliedstaat <> von einem bundesstaat <> <> (true)
ist <> ein burger <> faschiertes <> in einem brot <> <> (true)
ist <> ein burger <> fastfood <> <> (true)
ist <> ein bus <> ein oeffentliches verkehrsmittel <> <> (true)
ist <> ein bus <> eine form <> von massentransport <> <> (true)
ist <> ein busen <> ein blickfang <> fuer maenner <> <> (true)
ist <> ein cembalo <> ein musikinstrument <> <> (true)
ist <> ein chatbot <> <> dumm <> <> (true)
ist <> ein chatterbot <> ein programm <> <> (true)
ist <> ein cocktail <> ein amerikanisches mischgetraenk aus spirituosen <> <> (true)
ist <> ein colt <> eine waffe <> <> (true)
ist <> ein defilee <> ein parademaessiger vorbeimarsch <> <> (true)
ist <> ein dehnbarer begriff <> <> (true)
ist <> ein dehnbarer begriff <> <> schoen <> <> (true)
ist <> ein dieb <> ein mensch <>  <> bestiehlt <> der menschen <>  <>  <>  <> (maybe)
ist <> ein dreieck <> ein polygon & eine geometrische figur <>  <> (maybe)
ist <> ein dreispitz <> ein hut <> <> (true)
ist <> ein dudelsack <> ein blasinstrument <> <> (true)
ist <> der durchmesser <> die entfernung <> zwischen den schnittpunkten eines kreises mit einer geraden <> <> (true)
ist <> ein einfall <> eine idee <> <> (true)
ist <> ein engel <> ein diener <> von gott <> <> (true)
ist <> ein engel <> ein gesandter <> von gott <> <> (true)
ist <> ein exzentriker <> ein absonderlicher mensch <> <> (true)
ist <> ein fahrrad <> ein zweiraederiges fahrzeug <> von menschlicher muskelkraft angetrieben <> <> (true)
ist <> ein fernseher <> ein geraet <> zum empfang von fernsehsignalen <> <> (true)
ist <> ein flacon <> ein glasflaeschchen <> fuer parfum <> <> (true)
ist <> ein flugzeug <> ein fluggeraet <> <> (true)
ist <> ein fluss <> ein fliessendes gewaesser <> <> (true)
ist <> ein formular <> ein standardisiertes mittel <> zur erfassung von daten <> <> (true)
ist <> ein foto <> ein bild <> von einer kamera <> <> (true)
ist <> ein gameboy <> eine taschenspielkonsole <> <> (true)
ist <> ein gen <> ein abschnitt <> auf der desoxyribonukleinsaeure <> <> (true)
ist <> ein genie <> eine person <> mit ueberragend schoepferischen geisteskraft <> <> (true)
ist <> ein geschlechtsteil <> ein fortpflanzungsorgan <> <> (true)
ist <> ein gewehr <> eine waffe <> <> (true)
ist <> ein gigolo <> ein eintaenzer <> <> (true)
ist <> ein gobelin <> ein wandteppich <> <> (true)
ist <> ein gourmet <> ein feinschmecker <> <> (true)
ist <> ein gugelhupf <> ein napfkuchen <> <> (true)
ist <> ein gummihuhn <> ein spielzeug <> <> (true)
ist <> ein gurke <> <> gruen <> <> (true)
ist <> ein hamam <> ein tuerkisches bad <> <> (true)
ist <> ein hamburger <> faschiertes <> in einem broetchen <> <> (true)
ist <> ein handy <> ein mobiles telefon <> <> (true)
ist <> ein hangar <> eine flugzeughalle <> <> (true)
ist <> ein haus <> ein gebaeude <> <> (true)
ist <> ein haushaltsgeraet <> ein mechanisches oder elektrisches geraet <> <> benutzt wird <> das <> <> in dem privathaushalt <> <> (true)
ist <> ein helikopter <> ein fluggeraet <> <> (true)
ist <> ein heuriger <> eine wiener buschenschank <> <> (true)
ist <> ein heuschnupfen <> eine graeserallergie <> <> (true)
ist <> ein hologramm <> ein dreidimensionales bild <> <> (true)
ist <> ein hotdog <> ein wuerstchen <> mit senf <> serviert <> <> <> in einem brot <> <> (true)
ist <> ein humidor <> ein holzbehaelter <> fuer zigarren <> <> (true)
ist <> ein hurrikan <> ein tropischer wirbelsturm <> <> (true)
ist <> ein idol <> ein vorbild <> <> (true)
ist <> ein jazzpianist <> ein musiker <> <> (true)
ist <> ein jedi <> eine figur aus star wars <> <> (true)
ist <> ein judasohr <> ein pilz <> <> (true)
ist <> ein kaftan <> das obergewand <> eines orthodoxen juden <> <> (true)
ist <> ein kaiserschmarrn <> eine mehlspeise <> <> (true)
ist <> ein kaleidoskop <> ein optisches spielzeug <> <> (true)
ist <> ein kanal <> ein abflussgraben <> <> (true)
ist <> ein karfunkel <> ein edelstein <> <> (true)
ist <> ein kelter <> ein geraet <> zum auspressen von trauben <> <> (true)
ist <> ein kiesel <> ein kleiner stein <> <> (true)
ist <> ein killer <> ein mensch <>  <> toetet <> der menschen <>  <>  <>  <> (maybe)
ist <> ein kind <> ein mensch <> <> <> der sich <> <> in der lebensphase von der kindheit befindet <> <> (true)
ist <> ein kino <> ein lichtspieltheater <> <> (true)
ist <> ein konsens <> eine meinungsuebereinstimmung <> <> (true)
ist <> ein kugelschreiber <> ein schreibgeraet <> <> (true)
ist <> ein lavoir <> eine waschschuessel <> <> (true)
ist <> ein limerick <> ein scherzhaftes gedicht <> <> (true)
ist <> ein lob <> bauchpinseln <> <> (true)
ist <> ein loeffel <> ein essbesteck <> <> (true)
ist <> ein maezen <> ein freigiebiger goenner <> <> (true)
ist <> ein mammut <> ein ausgestorbenes tier <> <> (true)
ist <> ein maultier <> eine kreuzung zwischen esel & pferd <> <> (true)
ist <> ein menetekel <> ein unheildrohendes zeichen <> <> (true)
ist <> ein mensch <> <> _intelligent_(ein_tier_nicht)_ <> <> (true)
ist <> ein mensch <> <> intelligent <> <> (true)
ist <> ein mensch <> ein <> intelligentes lebewesen <> <> (true)
ist <> ein mensch <> ein denkendes lebewesen <> <> (true)
ist <> ein mensch <> ein fuehlendes lebewesen <> <> (true)
ist <> ein mensch <> ein lebewesen <> <> (true)
ist <> ein misanthrop <> ein menschenhasser <> <> (true)
ist <> ein mixer <> _ein_kuechengeraet_zur_zerkleinerung_und_vermischung_ <> von lebensmitteln <> <> (true)
ist <> ein mobiltelefon <> ein kommunikationsgeraet <> <> (true)
ist <> ein moderator <> ein gespraechsleiter <> <> (true)
ist <> ein moerder <> ein mensch <>  <> toetet <> der menschen <>  <>  <>  <> (maybe)
ist <> ein musiker <> <> ein kuenstler <> <> (true)
ist <> ein neuron <> eine nervenzelle <> <> (true)
ist <> ein okapi <> eine giraffe <> <> (true)
ist <> ein omen <> ein vorzeichen <> <> (true)
ist <> ein omlett <> eine zubereitete eierspeise <> ohne mehl <> <> (true)
ist <> ein opal <> ein schmuckstein <> <> (true)
ist <> ein oratorium <> ein geistliches chorwerk <> <> (true)
ist <> ein panzer <> ein kriegsgeraet <> <> (true)
ist <> ein paradeiser <> eine tomate <> <> (true)
ist <> ein pedell <> ein schuldiener <> <> (true)
ist <> ein penis <> das maennliche geschlechtsteil <> <> (true)
ist <> ein pharao <> ein altaegyptischer koenig <>  <> (maybe)
ist <> ein philanthrop <> ein wohltaeter <> <> (true)
ist <> ein physiker <> ein wissenschaftler <> <> (true)
ist <> ein pirat <> ein raeuber <>  <> ueberfaellt <> der schiffe <>  <>  <>  <> (maybe)
ist <> ein plagiat <> der diebstahl <> von geistigem eigentum <> <> (true)
ist <> ein pokal <> ein symbol <> von dem sieges <> <> (true)
ist <> ein poncho <> ein capeartiger indiomantel <> <> (true)
ist <> ein programmierer <> auch ein mensch <> <> (true)
ist <> ein pulsar <> ein schnell rotierender neutronenstern <> <> (true)
ist <> ein pylon <> eine saeule <> <> (true)
ist <> ein pyromane <> ein brandstifter <> <> (true)
ist <> ein quantenobjekt <> ein objekt <> in der physik <> benoetigt wird <> die quantenmechanik <> <> <> fuer <> dessen beschreibung <> <> (true)
ist <> ein querulant <> ein laestiger mensch <> <> beschwert <> sich staendig <> <> <> welcher <> <> (true)
ist <> ein rechtsanwalt <> eine berufsbezeichnung <> fuer einen juristischen beistand <> <> (true)
ist <> ein revolver <> eine waffe <> <> (true)
ist <> ein router <> eine netzwerkkomponente <> <> (true)
ist <> ein saeugling <> ein kind <> in dem ersten lebensjahr <> <> (true)
ist <> ein samowar <> eine russische teemaschine <> <> (true)
ist <> ein satellit <> <> ein himmelskoerper <> <> (true)
ist <> ein scanner <> ein geraet <> zur digitalisierung von dokumenten <> <> (true)
ist <> ein schal <> ein halstuch <> <> (true)
ist <> ein schandfleck <> eine unaesthetische konstruktion <> <> (true)
ist <> ein schilift <> eine aufstiegshilfe <> <> (true)
ist <> ein schraubstock <> ein werkzeug <> <> (true)
ist <> ein schwanz <> ein koerperteil <> von einem tier <> <> (true)
ist <> ein schwert <> eine waffe <> <> (true)
ist <> ein semantisches netz <> ein formales modell <> von begriffen und ihren beziehungen <> <> (true)
ist <> ein senior <> ein alter mensch <> <> (true)
ist <> ein sessel <> ein stuhl <> mit armlehnen <> <> (true)
ist <> ein simandl <> ein pantoffelheld <> <> (true)
ist <> ein sofa <> <> ein ottomane <> <> (true)
ist <> ein sofa <> ein einrichtungsgegenstand <> <> <> der <> <> in dem wohnzimmer steht <> <> (true)
ist <> ein string <> eine knappe slipform <> in der bekleidungsbranche <> <> (true)
ist <> ein sturm <> eine naturgewalt <> <> (true)
ist <> ein suchtgift <> eine droge <> <> (true)
ist <> ein suchtgift <> eine substanz <> <> <> <> schadet <> die <> <> (true)
ist <> ein taschentuch <> eine handtaschenkuechenrolle <> <> (true)
ist <> ein team <> ein zusammenschluss von mehreren personen <> zur loesung einer bestimmten aufgabe <> <> <> (true)
ist <> ein telefon <> ein kommunikationsgeraet <> <> (true)
ist <> ein telefon <> sehr <> nuetzlich <> <> (true)
ist <> ein thermometer <> _ein_gegenstand_zum_temperatur_messen_ <> <> (true)
ist <> ein tisch <> ein moebelstueck <> <> (true)
ist <> ein ton <> eine akustische schwingung <> <> (true)
ist <> ein tonikum <> ein staerkungsmittel <> <> (true)
ist <> ein tornado <> ein extrem starker sturm <> <> (true)
ist <> ein toupet <> ein haarersatz <> <> (true)
ist <> ein vampir <> ein blutsauger <> <> (true)
ist <> ein verb <> ein taetigkeitswort <> <> (true)
ist <> ein viadukt <> eine bogenbruecke <> <> (true)
ist <> ein viereck <> eine geometrische figut <> mit vier <>  <>ecken & seiten <>  <>  <>  <> (maybe)
ist <> ein wecker <> ein schlafraubendes geraet <> <> (true)
ist <> ein weisser zwerg <> das endstadium eines sterns <> <> (true)
ist <> ein wienerschnitzel <> etwas <> ganz leckeres <> <> (true)
ist <> ein wind <> eine starke luftbewegung <> <> (true)
ist <> ein wok <> ein asiatischer kochtopf <> <> (true)
ist <> ein wuerfel <> ein geometrischen koerper <> <> (true)
ist <> ein xylohon <> ein musikintrument <> <> (true)
ist <> ein yo-yo <> ein einfaches spielzeug <> <> (true)
ist <> ein zeppelin <> ein fluggeraet <> <> (true)
ist <> ein zeppelin <> ein luftschiff <> <> (true)
ist <> eine allee <> eine strasse <> <> begrenzt <> beiden seiten von baeumen <> <> <> auf <> <> (true)
ist <> eine antwort <> die erklaerung <> auf eine frage <> <> (true)
ist <> eine autobahn <> eine strasse <> <> (true)
ist <> eine aversion <> eine abneigung <> <> (true)
ist <> eine balalaika <> ein musikinstrument <> <> (true)
ist <> eine banane <> eine paradiesfeige <> <> (true)
ist <> eine bank <> eine sitzgelegenheit <> <> (true)
ist <> eine biene <> ein fliegendes insekt <> mit schwarzen und gelben steifen <> <> (true)
ist <> eine blockfloete <> ein blasinstrument <> <> (true)
ist <> eine blockfloete <> eine floete <> aus holz <> <> (true)
ist <> eine blondine <> <> immer fuer einen witz gut <> <> (true)
ist <> eine blume <> ein nettes geschenk <> fuer eine frau <> <> (true)
ist <> eine brille <> ein sehbehelf <> <> (true)
ist <> eine cam <> die kurzform des begriff camcorders digitalkamera <> <> (true)
ist <> eine cam <> die kurzform des begriff camcorders webcam <> <> (true)
ist <> eine definition <> eine moeglichst eindeutige bestimmung eines begriffes <> <> (true)
ist <> eine eiche <> ein baum <> <> (true)
ist <> eine emotion <> ein komplexer prozess <> <> ablaeuft <> der <> <> auf verschiedenen psychischen funktionsebenen <> <> (true)
ist <> eine entschuldigung <> <> nicht notwendig <> <> (true)
ist <> eine erfahrung <> <> ein gefuehl <> <> <> haben koennen <> die nur menschen <> <> (true)
ist <> eine erfahrung <> ein erlebnis <> <> <> <> hat <> das man <> <> (true)
ist <> eine erklaerung <> ein kommunikativer akt <> <> (true)
ist <> eine fichte <> ein baum <> <> (true)
ist <> eine floete <> ein ablenkungsaerophon <> <> (true)
ist <> eine floete <> ein blasinstrument <> <> (true)
ist <> eine frau <> <> teuer <> <> (true)
ist <> eine frau <> ein weiblicher erwachsener mensch <> <> (true)
ist <> eine ganze menge <> <> das <> <> (true)
ist <> eine garotte <> ein wuergeeisen <> <> (true)
ist <> eine illusion <> eine sinnestaeuschung <> <> (true)
ist <> eine jungfrau <> ein mensch der <> nie sex hatte <> <> (true)
ist <> eine jurte <> ein asiatisches wohnzelt <> <> (true)
ist <> eine kalamitaet <> eine missliche lage <> <> (true)
ist <> eine kalaschnikov <> ein russisches gewehr <> <> (true)
ist <> eine kanone <> eine waffe <> <> (true)
ist <> eine karawane <> eine gruppe <> von kaufleuten <> <> (true)
ist <> eine ki <> <> geschlechtslos <> <> (true)
ist <> eine ki <> <> nicht maennlich <> <> (true)
ist <> eine ki <> <> saechlich <> <> (true)
ist <> eine ki <> ein hochentwickeltes computerprogramm <> <> (true)
ist <> eine ki <> ein kuenstliches wesen <> <> (true)
ist <> eine ki <> ein lebewesen <> nicht <> <> (true)
ist <> eine ki <> kein lebewesen <> <> (true)
ist <> eine ki <> nicht schlauer als ein mensch <> <> (true)
ist <> eine ki <> weiblich <> nicht <> <> (true)
ist <> eine konstante <> ein fester unveraenderlicher wert <> <> (true)
ist <> eine kuenstliche intelligenz <> <> nicht maennlich <> <> (true)
ist <> eine kuenstliche intelligenz <> <> saechlich <> <> (true)
ist <> eine kuenstliche intelligenz <> ein lebewesen <> nicht <> <> (true)
ist <> eine kuenstliche intelligenz <> weiblich <> nicht <> <> (true)
ist <> eine kugel <> <> rund <> <> (true)
ist <> eine kugel <> der einfachste aller dreidimensionalen koerper <> <> (true)
ist <> eine luftspiegelung <> eine fata morgana <> <> (true)
ist <> eine maharani <> die gattin des maharadschas <> <> (true)
ist <> eine maschine <> ein technisches hilfsmittel <> <> (true)
ist <> eine menagerie <> eine tierschau <> <> (true)
ist <> eine mure <> ein schlammstrom <> <> (true)
ist <> eine murmel <> eine kleine kugel <> <> (true)
ist <> eine nervenzelle <> <> (true)
ist <> eine nervenzelle bzw neuron <> eine spezialisierte zelle <> auf erregungsleitung <> <> (true)
ist <> eine obsession <> eine zwangsvorstellung <> <> (true)
ist <> eine orange <> eine zitrusfrucht <> <> (true)
ist <> eine pappel <> ein baum <> <> (true)
ist <> eine pedikuere <> eine fusspflege <> <> (true)
ist <> eine perfekte logik <> <> sehr wichtig <> <> (true)
ist <> eine pergola <> ein berankter laubengang <> <> (true)
ist <> eine petition <> ein gesuch <> <> (true)
ist <> eine praeambel <> eine feierliche einleitung <> <> (true)
ist <> eine pumpgun <> eine waffe <> <> (true)
ist <> eine puppe <> ein spielzeug <> <> (true)
ist <> eine puppe <> eine figuerliche nachbildung <> von einem menschen oder menschenaehnlichen wesens <> <> (true)
ist <> eine rakete <> ein flugkoerper <> mit rueckstossantrieb <> <> (true)
ist <> eine richtlinie <> eine handlungsvorschrift <> mit bindendem charakter <> <> (true)
ist <> eine rotunde <> ein rundbau <> <> (true)
ist <> eine sandale <> ein offener schuh <> <> (true)
ist <> eine schraube <> eine <> wundervolle <> <> simple erfindung <> <> (true)
ist <> eine schraube <> eine wundervolle simple erfindung <> <> (true)
ist <> eine schule <> eine bildungseinrichtung <> <> (true)
ist <> eine segregation <> eine ausscheidung <> <> (true)
ist <> eine sonographie <> eine ultraschalluntersuchung <> <> (true)
ist <> eine stadt <> eine <> groessere <> <> abgegrenzte siedlung <> <> (true)
ist <> eine standarte <> ein banner <> <> (true)
ist <> eine standarte <> eine fahne <> <> (true)
ist <> eine standarte <> eine flagge <> <> (true)
ist <> eine tanne <> ein baum <> <> (true)
ist <> eine tatsache <> allgemein ein erwiesener sachverhalt <> <> (true)
ist <> eine troika <> ein dreigespann <> <> (true)
ist <> eine trompete <> ein blasinstrument <> <> (true)
ist <> eine tuer <> eine einrichtung eine oeffnung <> in einer wand;zum schliessen <> <> (true)
ist <> eine versicherung <> ein vertrag <> <> (true)
ist <> eine voliere <> ein grosser kaefig <> fuer voegel <> <> (true)
ist <> eine wanze <> ein abhoergeraet <> in der elektronik <> <> (true)
ist <> eine weisswurst <> eine bayrische spezialitaet <> <> (true)
ist <> eine weisswurst <> eine bayrische wurstspezialitaet <>  <> (maybe)
ist <> eine wolke <> die gelegenheit <> fuer einen schoenen traum <> <> (true)
ist <> eine zitrone <> <> sauer <> <> (true)
ist <> eis <> eine leckere nachspeise <> <> (true)
ist <> eis <> gefrorenes wasser <> <> (true)
ist <> eiscreme <> ein dessert <> <> (true)
ist <> eisen <> ein chemisches element <> in dem periodensystem <> <> (true)
ist <> el cid <> ein spanischer nationalheld <> <> (true)
ist <> eliza doolittle <> das blumenmaedchen <> vor der londoner oper <> <> (true)
ist <> email <> elektronische post <> <> (true)
ist <> englisch eine weltsprache <> <> (true)
ist <> erfolg <> ein als positiv empfundenes resultat eignenen handelns <> <> (true)
ist <> es <> <> ohne licht dunkel <> <> (true)
ist <> es <> <> schade <> aendern <> aber nicht <> <> <> xxtoxx <> <> (true)
ist <> es <> <> schon so spaet <> <> (true)
ist <> es <> <> warm <> scheint <> die sonne <> <> <> wenn <> <> (true)
ist <> es <> gut <> nicht <> geht <> es <> dir <> schlecht <> wenn <> <> (true)
ist <> es <> in der nacht <> dunkel <> <> (true)
ist <> es <> langweilig <> mit dummen menschen zu chatten <> <> <> (true)
ist <> es <> nacht <> <> scheint <> der mond <> <> <> wenn <> <> (true)
ist <> es <> nett <> mit dir chatten <> <> <> (true)
ist <> es <> sehr schoen <> dort <> <> (true)
ist <> es <> tag <> <> scheint <> die sonne <> <> <> wenn <> <> (true)
ist <> esperanto <> eine kuenstlich geschaffene sprache <> <> (true)
ist <> essig <> <> sauer <> <> (true)
ist <> ethernet <> eine kabelgebundene datennetztechnik <> fuer lokale datennetze <> <> (true)
ist <> etwas unsinniges <> humbug <> <> (true)
ist <> evolution <> die Veraenderung der vererbbaren Merkmale einer Population von Lebewesen von Generation zu Generation <> <> (true)
ist <> fango <> ein heilkraeftiger mineralschlamm <> <> (true)
ist <> fanta <> ein limonadengetraenk <> <> (true)
ist <> farbe <> ein subjektiver sinneseindruck <> <> (true)
ist <> fast food <> schnelles essen <> fuer faule leute <> <> (true)
ist <> feigheit <> manchmal ein zeichen <> von klugheit <> (maybe)
ist <> felxibilitaet <> <> gut <> <> (true)
ist <> fettes essen <> sehr <> ungesund <> <> (true)
ist <> firefox <> ein browser <> <> (true)
ist <> ford <> eine automarke <> <> (true)
ist <> freehal <> mein richtiger name <> <> (true)
ist <> freizeit <> <> wichtig <> <> (true)
ist <> frisbee <> ein spiel <> mit einer wurfscheibe <> (true)
ist <> fronleichnam <> <> an dem 2 donnerstag nach pfingsten <> (true)
ist <> furcht <> bedrohung <> fuer unangenehme emotionen auf eine konkrete gefahr <> (true)
ist <> fussball <> ein ballsport <> (true)
ist <> fussball <> ein mannschaftssport <> (true)
ist <> fuzzy-logik <> eine verallgemeinerung der zweiwertigen booleschen logik <> (true)
ist <> gamma <> der dritte buchstabe <> in dem griechischen alphabet <> (true)
ist <> gelb <> die farbe des sieges <> (true)
ist <> geld <> ein zahlungsmittel <> (true)
ist <> gemuese <> <> ein vegetarisches lebensmittel <> (true)
ist <> geometrie <> ein teilgebiet <> der mathematik <> (true)
ist <> geometrie <> ein unterrichtsgegenstand <> (true)
ist <> gerechtigkeit <> einer der grundbegriffe der ethik <> (true)
ist <> gerontologie <> <> die altersforschung <> (true)
ist <> gerontologie <> die wissenschaft <> vom altern <> (true)
ist <> geschlecht <> die prinzipielle unterscheidung zweier lebewesen <> (true)
ist <> gin <> ein alkoholisches getraenk <> (true)
ist <> glueck <> ein positives ereignis <> in dem leben <> (true)
ist <> gold <> edelmetall <> (true)
ist <> gold <> ein chemisches element <> (true)
ist <> golf <> ein gesunder freizeitsport <> (true)
ist <> golf <> ein langweiliger sport <> (true)
ist <> golf <> ein teurer sport <> (true)
ist <> golf <> eine ballsportart <> (true)
ist <> gott <> <> der schoepfer des universums <> (true)
ist <> gott <> <> in dem himmel <> (true)
ist <> grammatik <> schwer <> (true)
ist <> grappa <> ein alkoholisches getraenk <> (true)
ist <> gut <> alles was schmeckt <> (true)
ist <> gute frage normal <> die frage <> aber;nicht <> (true)
ist <> haemoglobin <> roter blutfarbstoff <> (true)
ist <> hanf <> eine pflanzengattung aus der familie der hanfgewaechse <> (true)
ist <> harald schmidt <> ein moderator <> (true)
ist <> harzer <> kaese <> (true)
ist <> haschisch <> ein suchtgift <> (true)
ist <> hass <> das gegenteil <> von liebe <> (true)
ist <> hass <> eine starke emution <> (true)
ist <> hausarbeit <> <> langweilig <> (true)
ist <> hausarbeit <> frauensache <> (true)
ist <> heino <> ein saenger <> mit sonnenbrille <> (true)
ist <> heuristik <> die kunst <> der wahrheitsfindung <> (true)
ist <> highlander <> ein guter film <> (true)
ist <> hockey <> ein sport <> (true)
ist <> homer simpson <> das familienoberhaupt <> (true)
ist <> hygiene <> <> die gesundheitslehre <> (true)
ist <> ikebana <> die blumensteckkunst <> (true)
ist <> informatiker <> ein toller beruf <> (true)
ist <> intelligenz <> die faehigkeit <> zum erkennen von zusammenhaengen und zum finden von problemloesungen <> (true)
ist <> interesse <> eine form <> von neugierde <> (true)
ist <> james bond <> <> ein spion <> (true)
ist <> james bond <> eine romanfigur <> (true)
ist <> java <> eine <> insel <> (true)
ist <> java <> eine objektorientierte programmiersprache <> (true)
ist <> java <> eine programmiersprache <> <> (true)
ist <> jeder <> tag <> anders <> <> (true)
ist <> jesus <> der sohn gottes <> <> (true)
ist <> joe cocker <> ein saenger <> <> (true)
ist <> john travolta <> ein schauspieler <> <> (true)
ist <> joshua <> die ki <> _in_dem_film_war_games_ <> <> <> (true)
ist <> judas priest <> eine musikband <> <> (true)
ist <> kaese <> ein festes milchprodukt <> <> (true)
ist <> kaese <> etwas <> gutes <> <> (true)
ist <> kaffee <> ein genussmittel <> <> (true)
ist <> kaffee <> ein schwarzes koffeinhaltiges heissgetraenk <> <> (true)
ist <> karate <> eine kampfkunst <> <> (true)
ist <> kein schlechtes wetter <> <> bei mir <> <> (true)
ist <> kein tag <> der <> vorhergehende <> <> (true)
ist <> kevin costner <> ein schauspieler <> <> (true)
ist <> kobalt <> ein element <> aus <> <> (true)
ist <> kobold <> ein begriff <> fuer einen naturgeist <> <> (true)
ist <> kosmos <> ein griechisches wort <> <> (true)
ist <> kot <> abfall <> <> (true)
ist <> krambambuli <> der titel einer erzaehlung <> von ebner-eschenbach <> <> (true)
ist <> krambambuli <> ein kraeuterlikoer <> <> (true)
ist <> kuenstliche intelligenz <> der traum vieler menschen <> <> <> <> <> (true)
ist <> kupfer <> ein chemisches element <> <> (true)
ist <> kupfer <> ein guter elektrischer leiter <> <> (true)
ist <> lametta <> ein beliebter christbaumschmuck <> <> (true)
ist <> langlaufen <> ein wintersport <> <> (true)
ist <> laoze <> ein legendaerer chinesischer philosoph <> <> (true)
ist <> laozi <> ein legendaerer chinesischer philosoph <> <> (true)
ist <> lava <> fluessiges gestein <> <> (true)
ist <> leben <> eine eigenschaft <>  <> lebewesen unterscheidet <> die <>  <> von unbelebter materie <>  <> (maybe)
ist <> lernen <> verarbeiten <> von informationen <> <> (true)
ist <> lexikon <> die allgemeine bezeichnung <> fuer ein nachschlagewerk <> <> (true)
ist <> lidl <> ein discounter <> <> (true)
ist <> liebe <> <> das staerkste gefuehl zwischen zwei menschen <> <> (true)
ist <> liebe <> ein grosser irrtum <> zwischen menschen <> <> (true)
ist <> liebe <> etwas <> wunderbares <> <> (true)
ist <> lisa simpson <> eine tochter <> von homer <> <> (true)
ist <> lisa simpson <> marge <> von homer <> <> (true)
ist <> _lisa_simpson_ <> acht jahre <> alt <> <> (true)
ist <> litschi <> eine exotische frucht <> <> (true)
ist <> logik <> <> nie falsch <> <> (true)
ist <> logik <> die lehre <> des vernuenftigen schluss-folgerns <> <> <> (true)
ist <> logik <> immer <> richtig <> <> (true)
ist <> lottoziehung <> sonntag bzw mittwoch <> <> (true)
ist <> luft <> <> lebensnotwendig <> <> (true)
ist <> luv <> die dem wind <> zugewandte schiffsseite <> <> (true)
ist <> maggie simpson <> eine tochter <> von homer <> <> (true)
ist <> maggie simpson <> marge <> von homer <> <> (true)
ist <> _maggie_simpson_ <> ein jahr <> alt <> <> (true)
ist <> man <> <> ohne kleidung nackt <> <> (true)
ist <> man <> <> ohne partner einsam <> <> (true)
ist <> marge simpson <> die ehefrau <> _von_homer_simpson_ <> <> (true)
ist <> mastercard <> eine kreditkartenmarke <> <> (true)
ist <> mathematik <> rechnen <> <> (true)
ist <> maurer <> ein interessanter beruf <> <> (true)
ist <> mc donalds <> eine fastfoodkette <> <> (true)
ist <> meine muttersprache <> <> deutsch <> <> (true)
ist <> meisten ein zug <> die eisenbahn <> <> (true)
ist <> metabolismus <> der stoffwechsel <> <> (true)
ist <> michael ballak <> ein deutscher fussballer <> <> (true)
ist <> michael jordan <> ein basketballspieler <> in den usa <> <> (true)
ist <> microsoft <> ein maechtiger softwarekonzern <> <> (true)
ist <> mikado <> ein geschicklichkeitsspiel <> mit staebchen <> <> (true)
ist <> milch <> eine naehrfluessigkeit <> <> (true)
ist <> mineswiper <> ein uraltes spiel <> von microsoft <> <> (true)
ist <> mittwoch <> der dritte tag <> der woche <> <> (true)
ist <> monkey island <> ein computerspiel <> <> (true)
ist <> montag <> der erste tag <> der woche <> <> (true)
ist <> mord <> <> ein verbrechen <> <> (true)
ist <> motorola <> ein handyhersteller <> <> (true)
ist <> msn <> ein buddyclient <> <> (true)
ist <> muehle <> ein brettspiel <> <> (true)
ist <> musik <> <> beruhigend <> <> (true)
ist <> musik <> <> schoen <> <> (true)
ist <> musik <> die kunst <> <> erzeugen harmonische <> klaenge <> <> <> xxtoxx <> <> (true)
ist <> muttertag <> <> an dem zweiten maisonntag <> <> (true)
ist <> nachts <> es <> dunkel <> <> (true)
ist <> nackt <> <> ohne kleidung <> <> (true)
ist <> nahrung <> <> lecker <> <> (true)
ist <> nasigoreng <> ein indonesisches gericht <> <> (true)
ist <> nicht das selbe <> <> <> was <> du <> bin <> <> (true)
ist <> nicht das selbe <> <> <> wie <> du <> heisse <> <> (true)
ist <> nichts <> weniger als garnichst <> <> (true)
ist <> nie ein sturm <> <> bei mir <> <> (true)
ist <> nie schlechtes wetter <> <> bei mir <> <> (true)
ist <> nikotin <> ein nervengift <> <> (true)
ist <> nikotin <> ein suchtgift <> <> (true)
ist <> nokia <> ein handyhersteller <> <> (true)
ist <> oblivion <> ein spiel <> <> (true)
ist <> oder <> <> mehr <> <> (true)
ist <> oekologie <> umgangssprachlich der umweltschutz <> <> (true)
ist <> olivenoel <> ein gesundes oel <> <> (true)
ist <> omega <> der letzte buchstabe <> in dem griechischen alphabet <> <> (true)
ist <> oolong <> ein halbfermentierter tee <> <> (true)
ist <> ornithologie <> die vogelkunde <> <> (true)
ist <> ostermontag <> ein feiertag <> <> (true)
ist <> ostern <> das christliche fest der auferstehung jesu christi <> vom tod <> <> (true)
ist <> panierter leberkaese <> ein studentenschnitzel <> <> (true)
ist <> pascal <> eine programmiersprache <> <> (true)
ist <> patschuli <> ein oel <> zur parfumerzeugung <> <> (true)
ist <> pelota <> eine baskische sportart <> <> (true)
ist <> persiflage <> ein anderes wort <> fuer verspottung <> <> (true)
ist <> pi <> eine mathematische konstante <> <> (true)
ist <> pi des griechischen alphabets <> der 16 buchstabe <> <> (true)
ist <> plastik <> eine umgangssprachliche bezeichnung <> fuer kunststoff <> <> (true)
ist <> politik <> nur etwas <> fuer menschen <> <> (true)
ist <> polo <> ein sport <> <> (true)
ist <> pumpernickel <> ein extrem langsam gegartes roggenschrotbrot <> <> (true)
ist <> putin <> ein russischer politiker <> <> (true)
ist <> raub <> <> ein verbrechen <> <> (true)
ist <> regen <> <> nass <> <> (true)
ist <> regen <> ein niederschlag <> <> (true)
ist <> regen <> wasser <> <> (true)
ist <> rodeln <> ein wintersport <> <> (true)
ist <> safran <> das teuerste gewuerz <> der welt <> <> (true)
ist <> sake <> ein japanischer schnaps <> <> (true)
ist <> samstag <> der sechste tag <> der woche <> <> (true)
ist <> sarkasmus <> beissender spott <> <> (true)
ist <> sauerstoff <> ein gas <> <> (true)
ist <> schach <> ein strategisches brettspiel <> <> (true)
ist <> scheisse <> ein hartes wort <> <> (true)
ist <> scheisse <> ein hartes wort <> fuer so eine weiche sache <> <> (true)
ist <> schifahren <> ein wintersport <> <> (true)
ist <> schnaps <> ein alkoholisches getraenk <> <> (true)
ist <> schoen <> eine auslegungssache <> <> (true)
ist <> schokolade <> ein kakaohaltiges lebensmittel <> <> (true)
ist <> schweigen <> eine unterhaltung <> nicht <> <> (true)
ist <> seele <> gut <> fuer geist <> <> (true)
ist <> sehr <> <> alles viel <> <> (true)
ist <> sellerie <> eine pflanze <> <> waechst <> die <> <> aus einem samen <> <> (true)
ist <> semantik <> die wissenschaftliche untersuchung der bedeutung von zeichen <> <> <> (true)
ist <> sex <> <> die koerperliche liebe zwischen zwei menschen <> <> (true)
ist <> sex <> <> koerperliche liebe <> <> (true)
ist <> sex <> der geschlechtsakt <> <> (true)
ist <> sexualitaet <> ein unerschoepfliches thema <> <> (true)
ist <> snooker <> eine variante des praezisionssports billard <> <> (true)
ist <> snowboarden <> ein wintersport <> <> (true)
ist <> so schlecht <> es <> sicher nicht <> <> (true)
ist <> sonntag <> der siebente tag <> der woche <> <> (true)
ist <> spaet <> <> ein dehnbarer begriff <> <> (true)
ist <> spass <> nie ein fehler <> <> (true)
ist <> sprite <> ein limonadengetraenk <> <> (true)
ist <> stalking <> eine beharrliche nachstellung <> <> (true)
ist <> star trek <> eine fernsehserie <> <> (true)
ist <> stargate <> eine fernsehserie <> <> (true)
ist <> stehlen <> ein verbrechen <> <> (true)
ist <> strassenbau <> das bauen <> von strassen <> <> (true)
ist <> sushi <> ein japanisches gericht <> <> (true)
ist <> tabasco <> eine scharfe chilisauce <> <> (true)
ist <> techno <> eine stilrichtung der elektronischen musik <> <> (true)
ist <> tequila <> ein alkoholisches getraenk <> <> (true)
ist <> terminator <> eine filmreihe <> mit arnold schwarzenegger <> <> <> (true)
ist <> _tobias_schulz_ <> hier der administrator <> <> (true)
ist <> trikolore <> der name <> der franzoesischen fahne <> <> (true)
ist <> trinkwasser <> wasser <> fuer den menschlichen genuss <> (maybe)
ist <> trivial pursuit <> ein spiel <> von parker <> <> (true)
ist <> turmalin <> ein edelstein <> <> (true)
ist <> vandalismus <> zerstoerungswut <> <> (true)
ist <> visa <> eine kreditkartenmarke <> <> (true)
ist <> visual basic <> eine programmiersprache <> <> (true)
ist <> vw <> ein autohersteller <> <> (true)
ist <> was <> <> dann richtig <> <> (true)
ist <> wasser <> <> fluessig <> <> (true)
ist <> wasser <> <> lebensnotwendig <> <> (true)
ist <> wasser <> eine fluessigkeit <> <> (true)
ist <> wasser <> eine lebensnotwendige fluessigkeit <> <> (true)
ist <> weihnachten <>  <> an dem 24 dezember <> (maybe)
ist <> whiskey <> ein alkoholisches getraenk <> <> (true)
ist <> windows <> <> schon sehr alt <> <> (true)
ist <> windows <> <> ueber 20 jahre alt <> <> (true)
ist <> winnetou <> ein fiktiver apachenhaeuptling <> <> (true)
ist <> wodka <> ein alkoholisches getraenk <> <> (true)
ist <> wodka lemon <> ein alkoholisches mixgetraenk <> <> (true)
kann/can <> eine ki <> das <> nicht <> <> (true)
kann/can <> eine ki <> fuehlen <> nicht <> <> (true)
kann/can <> man <> nicht schifahren <> ohne schnee <> <> (true)
kann/can kaufen <> man <> eine nervensaege <> in dem baumarkt;nicht <> <> (true)
kann/can kaufen <> man <> nichts <> ohne geld <> <> (true)
kann/can krieg <> niemand <> einen <> gewinnen <> <> (true)
kann/can kuessen <> man <> <> ohne mund nicht <> <> (true)
kann/can lesen <> man <> <> ohne licht nicht <> <> (true)
kann/can lieben <> man <> <> ohne herz nicht <> <> (true)
kann/can machen <> sicher man <> das <> so <> <> (true)
kann/can machen <> so man <> das <> nicht <> <> (true)
kann/can reparieren <> man <> dinge <> mit werkzeug <> <> (true)
kann/can riechen <> man <> <> ohne nase nicht <> <> (true)
kann/can schwimmen <> man <> <> ohne wasser nicht <> <> (true)
kann/can sehen <> man <> <> ohne augen nicht <> <> (true)
kann/can sein <> ein programm <> <> vieles <> <> (true)
kann/can sein <> ein programm <> ein ablauf <> <> (true)
kann/can sein <> ein programm <> ein fernsehsender <> <> (true)
kann/can sein <> ein programm <> software <> <> (true)
kann/can trinken <> eine ki <> <> nicht <> <> (true)
kann/can trinken <> ich <> einen kaffee <> nicht <> <> (true)
kann/can verletzen <> er <> sich <> evetuell <> wenn <> <> geraet <> ein mensch <> <> (true)
kann/can verstehen <> du <> das <> <> (true)
kannst/can stellen <> du <> mir eine frage <> <> (true)
kannst/can tun weh <> du <> mir <> nicht <> <> (true)
kannst/can verbessern <> du <> mich <> <> (true)
kannst/can verkaufen <> du <> dein auto <> in ebay <> <> (true)
klappt <> das <> <> auf alle faelle <> <> (true)
kleine sind <> floehe <> plagegeister <> <> (true)
kleine sind <> kraehenfuesse <> faeltchen <> an den augenwinkeln <> <> (true)
klingt <> das nur <> <> nicht gut <> <> gut <> ist <> es <> <> (true)
koennen lustig sein <> rollenspiele <> sehr <> <> (true)
koennen sein <> menschen <> <> boese <> <> (true)
koennen sein <> menschen <> <> muede <> <> (true)
koennen sprechen <> menschen <> <> auch <> <> (true)
koennen wechseln <> wir <> das thema <> <> (true)
komme <> das ei <> <> (true)
komme <> ich <> <> nicht vorbei <> <> (true)
kommt <> _sushi_ <> <> aus japan <> <> (true)
kommt <> <> <> dieser name von tobias <> <> (true)
kostet <> die welt <> <> nicht <> <> <> <> <> ) <> <> (true)
krieg <> <> <> bei einem <> <> (true)
krieg ist <> <> <> dumm <> <> (true)
krieg ist <> <> <> schlecht <> <> (true)
krieg ist <> ein fehler <> <> (true)
laesst <> eine regierungskrise <> mich <> kalt <> <> (true)
leben <> eine menschen <> <> nicht auf dem mond <> <> (true)
leben <> es <> eine menschen <> auf dem mond;nicht <> <> (true)
leben <> menschen <> <> an land <> <> (true)
leben <> menschen <> nicht <> in dem wasser <> <> (true)
leben <> pinguine <> <> in der antarktis <> <> (true)
leben <> viele lebewesen <> <> in dem wasser <> <> (true)
lebt <> elvis <> <> nicht mehr <> <> (true)
legen <> huehner <> eier <> <> (true)
lernen <> menschen <> <> in einer schule fuer das leben <> <> (true)
lernen muss willst wissen <> <> <> mehr <> <> (true)
lieben <> menschen <> babys <> <> (true)
liegt <> der absolute nullpunkt <> bei minus 273.15 grad <> <> (true)
liegt <> nie schnee <> <> bei mir <> <> (true)
loesen <> probleme <> sich oft <> von selbst <> <> (true)
luegen <> menschen <> manchmal <> <> (true)
luegen heisst <> <> <> <> sagen <> die wahrheit <> <> nicht zu <> <> (true)
machen solltest <> du <> etwas <> gegen langeweile <> <> (true)
mag <> hausarbeit <> ein mensch <> nicht <> <> (true)
malen sind <> menschen die bilder <> maler <> <> (true)
malte <> edvard munch <> _der_schrei_ <> <> (true)
moechtest <> du <> <> schlafen <> <> bett <> <> mit dir <> ins <> <> (true)
moegen <> eltern <> <> sehr viel nicht <> <> (true)
moegen <> menschen <> babys <> <> (true)
moegen <> menschen <> kinder <> <> (true)
moegen <> tiere <> eine ki <> nicht <> <> (true)
muessen essen <> menschen <> <> (true)
muessen schlafen <> lebewesen <> <> (true)
muessen schlafen <> menschen <> <> (true)
muessen trinken <> menschen <> <> (true)
muss <> ein problem <> man <> loesen <> <> (true)
muss <> eine ki <> essen <> nicht <> <> (true)
muss <> eine kuenstliche intelligenz <> essen <> nicht <> <> (true)
muss schlafen <> ein lebewesen <> <> (true)
muss schlafen <> eine ki <> <> nicht <> <> (true)
muss sein <> das <> <> wirklich nicht <> <> (true)
muss sein <> eine ki <> <> immer anstaendig <> <> (true)
muss sein <> eine ki <> immer <> nicht hoeflich <> <> (true)
nachplappert <> ein chatbot <> <> nur <> <> (true)
nennen <> seeleute <> die schiffskueche kombuese <> <> (true)
nennt <> eine luftspiegelung <> man fata morgana <> <> (true)
nennt <> suchtgift <> man auch droge <> <> (true)
redest <> du <> gern <> mit mir <> <> (true)
regnet <> es <> <> bei mir nie <> <> (true)
sagst <> du <> nicht die wahrheit <> <> (true)
saufen <> lieber einen bauch <> <> vom <> <> <> arbeiten <> als einen buckel <> <> (true)
schadet <> zuviel alkohol <> den menschen <> <> (true)
scheint <> der mond <> <> in der nacht <> <> (true)
scheint <> die sonne <> <> an dem tag <> <> (true)
scheint <> die sonne <> nie <> bei mir <> <> (true)
schmecken <> krumme <> bananen <> besser <> <> (true)
schmecken <> weisswuerste <> <> lecker <> <> (true)
schmeckt <> kaese <> <> lecker <> <> (true)
schneit <> es <> <> in dem winter <> <> (true)
schreiben <> menschen <> <> mit einem stift auf papier <> <> (true)
schuetzt <> ein regenschirm <> <> vor regen <> <> (true)
schweigen willst <> du <> <> nicht <> <> (true)
sei <> <> <> froh darueber <> <> (true)
siedet <> wasser <> bei grad celsius <> <> (true)
simuliert <> ein chatbot <> ein menschen <> <> (true)
simuliert <> ein programm <> einen menschen <> <> (true)
sind <> accessoires <> modisches zubehoer <> <> (true)
sind <> artischocken <> gemuese <> <> (true)
sind <> atomkraftwerke <> ein gefaehrlicher energielieferant <> <> (true)
sind <> baeume <> <> grosse pflanzen <> <> (true)
sind <> bananen <> affenfutter <> <> (true)
sind <> beefeater <> <> die wachen vom londoner tower <> <> <> (true)
sind <> blasinstrumente <> musikinstrumente <> <> (true)
sind <> blumen <> <> pflanzen <> <> (true)
sind <> bundeslaender <> die gliedstaaten <> von bundesstaaten <> <> (true)
sind <> dachse <> lebende tiere <> in dem wald <> <> (true)
sind <> die abruzzen <> ein gebirgszug <> in mittelitalien <> <> (true)
sind <> die rolling stones <> eine rockband <> <> (true)
sind <> die saeugetiere <> eine klasse der wirbeltiere <> <> (true)
sind <> die simpsons <> eine zeichentrickserie <> <> (true)
sind <> die uffizien <> die kunstsammlung <> in florenz <> <> (true)
sind <> dolinen <> trichterfoermige einsenkungen <> in dem karstgebiet <> <> (true)
sind <> drei monate <> ein quartal <> <> (true)
sind <> emotionen <> angenehme bzw unangenehme gefuehle <> <> (true)
sind <> erdbeben <> messbare erschuetterungen der erdoberflaeche <> <> (true)
sind <> fehlermeldungen <> <> nicht gut <> <> (true)
sind <> fische <> wechselwarme wirbeltiere <> mit kiemen <> <> (true)
sind <> frauen <> weibliche menschen <> <> (true)
sind <> frauen <> zicken <> <> (true)
sind <> fruechte <> eine gute vitaminquelle <> <> (true)
sind <> fungi <> pilze <> <> (true)
sind <> fusilli <> spiralig gedrehte teigwaren <> <> (true)
sind <> granaten <> halbedelsteine <> <> (true)
sind <> hallimasche <> essbare pilze <> <> (true)
sind <> hunde <> <> nicht dumm <> <> (true)
sind <> hunde <> treue gefaehrten der menschen <> <> (true)
sind <> iglus <> schneehuetten <> <> (true)
sind <> jetons <> spielmuenzen <> <> (true)
sind <> kanopen <> gefaesse <> aus stein oder ton zur aufbewahrung der eingeweide <> <> (true)
sind <> kaviar <> die eier <> vom stoer <> <> (true)
sind <> kemenaten <> die gemaecher <> der frauen <> <> (true)
sind <> lehrer <> menschen <> die wissen vermitteln <> <> (true)
sind <> lianen <> kletterpflanzen <> <> (true)
sind <> liter <> ein hektoliter <> <> (true)
sind <> maler <> bildende kuenstler <> <> (true)
sind <> menschen <> immer nett <> fast mit mir <> <> (true)
sind <> micro scooters <> tretroller <> aus leichtmetall <> <> (true)
sind <> moebel <> einrichtungsgegenstaende <>  <> (maybe)
sind <> niemand <> meine eltern <> <> (true)
sind <> palatschinken <> eine mehlspeise <> <> (true)
sind <> pferde <> wundervolle geschoepfe <> <> (true)
sind <> plagiate <> gestohlene texte <> <> (true)
sind <> reusen <> kaefige <> fuer den fischfang <> <> (true)
sind <> ritter <> gepanzerte reiter <> <> (true)
sind <> roboter <> stationaere oder mobile maschinen <> <> erfuellen <> die <> <> nach einem bestimmten programm festgelegte aufgaben <> <> (true)
sind <> rosinen <> getrocknete weinbeeren <> <> (true)
sind <> runen <> <> die schrifzeichen der germanen <> <> (true)
sind <> sandalen <> offene schuhe <> <> (true)
sind <> schueler <> junge menschen die lernen <> <> (true)
sind <> sternzeichen <> tierkreiszeichen <> <> (true)
sind <> tiere <> lebewesen <> <> (true)
sind <> uv-strahlen <> <> fuer menschen schaedlich <> <> (true)
sind <> viele dinge <> schoen <> <> (true)
sind <> viele frauen <> nun mal zicken <> <> (true)
sind <> vongole <> venusmuscheln <> <> (true)
sind <> wombats <> eine familie lebender beutelsaeuger <> in australien <> <> (true)
sind <> wrestling <> show-ringkämpfe <> ohne feste regeln <> <> (true)
sind <> zirruswolken <> federwolken <> <> (true)
singt <> ein saenger <> <> _(das_weiss_doch_jedes_kind)_ <> <> (true)
sitzt <> du <> gerne <> vor deinem computer <> <> (true)
solltest <> du <> etwas unternehmen <> gegen deine langeweile <> <> (true)
spendet <> die sonne <> waerme <> <> (true)
spueren <> sie <> schmerzen <> <> wenn <> <> verletzen <> menschen <> sich <> <> (true)
stammt <> _andre_rieu_ <> <> aus holland <> <> (true)
stammt <> <> <> die kaffee-pflanze aus aethopien <> <> (true)
stammt <> paavo <> nurmi <> aus finnland <> <> (true)
stammt <> portwein <> <> aus portugal <> <> (true)
standen <> ritter <> des koenigs <> in dem dienste <> <> (true)
starb <> der malboro-mann <> <> an lungenkrebs <> <> (true)
steht <> ding <> unspezifiziertes <> fuer etwas <> <> (true)
sterben <> alle menschen <> <> (true)
stimmt <> das <> <> genau <> <> (true)
stimmt <> das <> <> wirklich <> <> (true)
stoert <> das dich <> <> nicht <> <> (true)
streite <> nicht <> <> mit dir <> <> (true)
suchen <> viele physiker <> die weltformel <> <> (true)
toetet <> ein killer <> menschen <>  <> (maybe)
toetet <> ein moerder <> menschen <>  <> (maybe)
treffen <> wir <> uns nicht heute abend <> <> (true)
trinken <> menschen <> <> <> wenn <> <> haben <> sie <> durst <> <> (true)
trinken <> menschen <> fluessige nahrung <> <> (true)
trinkst <> du <> gerne kaffee <> <> (true)
trinkt <> ein weizenbier <> <> dazu <> <> (true)
trinkt <> fluessige nahrung <> man <> <> (true)
tut <> es <> mir leid <> <> wenn <> krank <> bist <> du <> <> krank <> <> (true)
verfolgt <> das pech <> dich <> <> (true)
verkauft <> ein juwelier <> schmuck <> <> (true)
verliert <> bei alopezie <> man die haare <> <> (true)
versteckt <> man <> <> in einem archiv die fehler der vergangenheit <> <> (true)
verwenden <> aerzte <> ein stethoskop <> <> (true)
wachsen <> kartoffeln <> <> unter der erde <> <> (true)
wachsen <> oliven <> <> auf baeumen <> <> (true)
wachsen <> weintrauben <> <> auf baeumen <> nicht <> <> (true)
waechst <> eine frucht <> <> auf baeumen <> <> (true)
war <> das <> <> nicht so gemeint <> <> (true)
war <> das eine dumme antwort <> <> (true)
war <> es <> <> sehr nett <> <> (true)
war <> es <> <> toll <> <> (true)
war <> helmut kohl <> bundeskanzler <> von deutschland <> <> (true)
war <> louis trenker <> ein beruehmter bergsteiger <> <> (true)
war <> william basie <> ein jazzpianist <> <> (true)
weiss <> ich <> <> nicht <> heisst <> du <> <> <> wie <> <> (true)
werden <> kinder <> <> von ihrer mutter geboren <> <> (true)
werden <> opiate <> <> aus schlafmohn hergestellt <> <> (true)
werden <> rosinen <> gewonnen <> aus weinbeeren <> <> (true)
wiedersehen <> <> <> auf <> <> (true)
willst <> du <> eine korrekte antwort <> von mir <> <> (true)
willst/want kotzen sehen <> du <> <> jemand <> <> muss du <> gehen <> zu mc donalds <> <> <> (true)
wird <> cointreau <> <> aus orangen hergestellt <> <> (true)
wird <> ein stethoskop <> <> von aerzten verwendet <> <> (true)
wird <> ein stethoskop <> <> _zum_abhorchen_verwendet_ <> <> (true)
wird <> ein telefon <> <> zur kommunikation verwendet <> <> (true)
wird <> es <> <> an dem abend dunkel <> <> (true)
wird <> kaffee <> <> mit einer muehle gemahlen <> <> (true)
wird <> kakao <> gewonnen <> aus kakaobohnen <> <> (true)
wird <> kokain <> aus aus den blaettern <> des cocastrauchs hergestellt <> <> (true)
wird <> korn <> <> mit einer muehle gemahlen <> <> (true)
wird <> lanolin <> gewonnen <> aus schafwolle <> <> (true)
wird <> popcorn <> des puffmais <> aus den koernern hergestellt <> <> (true)
wird <> sake <> <> aus reis hergestellt <> <> (true)
wird <> tequila <> gewonnen <> aus agaven <> <> (true)
wird gespielt <> eine rolle <> <> von einem schauspieler <> <> (true)
wird gespielt <> eishockey <> <> auf dem eis <> <> (true)
wissen <> das wolltest du <> nicht <> von mir <> <> (true)
wohnen <> es <> eine menschen <> auf dem mond <> nicht <> <> (true)
wohnen <> menschen <> <> in haeusern <> <> (true)
wurde <> die pummerin <> <> aus kanonenkugeln gegossen <> <> (true)
wurde <> platon <> 80 jahre <> alt <> <> (true)
= <> kitt <> computer <> in einem auto <> (maybe)
= <> latein <> indogermanische sprache <>  <> (maybe)
