 besteht <> eis <> aus gefrorenem wasser <> <> (true)
= <> _babylon_5_ <> fernsehserie <>  <> (true)
= <> angst <> komplizierte kombination <> der negativen gefuehle <> (maybe)
= <> der penis <> maennliche geschlechtsteil <>  <> (maybe)
= <> die vagina <> weibliche geschlechtsteil <>  <> (maybe)
= <> ein autor <> verfasser <>  <>  <> oder  geistige urheber <>  <> von einem werkes <>  <> (maybe)
= <> ein magier <> zauberkuenstler <>  <> (maybe)
= <> ein magnetfeld <> physikalisches phaenomen <>  <> (maybe)
= <> ein saeufer <> alkoholabhaengiger mensch <>  <> (maybe)
= <> ein shaolin <> chinesischer moench <>  <> (maybe)
= <> ein trunkenbold <> dauernd besoffener mensch <>  <> (maybe)
= <> ein wort <> selbststaendige sprachliche einheit <>  <> (maybe)
= <> ein zauberkuenstler <> artist der darstellenden zauberkunst <>  <> (maybe)
= <> maultaschen <> spezialitaet der schwaebischen kueche <>  <> (maybe)
= <> tee <> heisses aufgussgetraenk <>  <> (maybe)
abhaelt <> die ozonschicht <> uv-strahlen <> 50
abwirft <> die laerche <> seine nadeln <> in dem winter <> (true)
angebaut wird <> darjeelingtee <> <> in indien <> (true)
angebaut wird <> der assamtee <> <> in indien <> (true)
anhaben kann/can <> ein kuenstliches wesen <> nichts <> (true)
anrichten kann/can <> ein sturm <> sehr viel schaden <> <> (true)
anschaut <> ein kuenstliches wesen <> eine filme <> nicht <> <> (true)
anschaut <> eine ki <> eine filme <> nicht <> <> (true)
arbeiten gehen <> menschen <> <> <> <> <> verdienen <> um geld <> <> (true)
arbeiten muessen <> menschen <> <> <> <> <> verdienen <> um geld <> <> (true)
arbeitet <> ein holzfaeller <> <> in dem wald <> <> (true)
aufgeht <> die sonne <> <> an dem morgen <> <> (true)
aus <> _ <> eine droge kokainsalz <> hergestellt <> <> (true)
aus <> _ <> eine droge natron <> hergestellt <> <> (true)
aus <> es <> nichts <> macht mir <> <> (true)
aus <> keinem bestimmten grund <> <> (true)
aus besteht <> ein tennisball <> filz <> <> (true)
ausziehen kann/can <> du <> dich <> nicht <> <> (true)
baden <> viel spass <> <> beim <> <> (true)
baden gehen <> viel spass <> <> beim <> <> (true)
baden gehst <> du <> <> (true)
bauen <> eskimos <> iglus <> <> (true)
baut <> man <> einen schneemann <> in dem winter <> <> (true)
beantworten soll <> eine frage <> man nicht <> mit einer frage <> <> (true)
bearbeitet <> ein gerber <> tierfelle <> <> (true)
bearbeitet <> ein holzfaeller <> baeume <> <> (true)
bedeutet <> _esp_ <> _elektronisches_stabilitaes_programm_ <> <> (true)
bedeutet <> <> <> definitiv endgueltig <> <> (true)
bedeutet <> <> <> plausibel einleuchtend <> <> (true)
bedeutet <> <> <> priapisch unzuechtig <> <> (true)
bedeutet <> abstinenz <> enthaltsamkeit <> <> (true)
bedeutet <> altruismus <> uneigennuetzigkeit <> <> (true)
bedeutet <> aquaplaning <> wassergleiten <> <> (true)
bedeutet <> ehre <> <> in etwa achtungswuerdigkeit <> <> (true)
bedeutet <> felix <> der glueckliche <> <> (true)
bedeutet <> generalisierung <> verallgemeinerung <> <> (true)
bedeutet <> gpl <> general public license <> <> (true)
bedeutet <> inolenz <> unverschaemtheit <> <> (true)
bedeutet <> ki <> kuenstliche intelligenz <> <> (true)
bedeutet <> klarschiff <> gefechtsbereitschaft <> <> (true)
bedeutet <> pharao <> grosses haus <> <> (true)
bedeutet <> plantage <> _pflanzung_ <> <> (true)
bedeutet <> sonne <> licht <> <> (true)
bedeutet <> sonne <> waerme <> <> (true)
bedeutet <> synergie <> zusammenwirken <> <> (true)
bedeutet <> terrone <> erdfresser <> <> (true)
bedeutet kommen <> _in_media_res_ <> <> zur sache <> <> (true)
beeinflusst <> der mond <> die gehzeiten <> <> (true)
befasst <> die naturwissenschaft <> sich <> mit pyhsik, mathematik sowie chemie <> <> (true)
befasst <> die relativitaetstheorie <>  <>sich mit der struktur von raum & zeit<>  <>  <>  <> sowie mit dem wesen von der gravitation <>  <> (maybe)
befindet <> _das_oetzi_museum_ <> sich <> in bozen <> <> (true) 
beibringen kann/can <> du <> mir dinge <> mit gespraechen <> <> (true)
beissen kann/can <> man <> <> ohne zaehne nicht <> <> (true)
bekommst <> du <> kein keks <> <> (true)
bellt <> ein hund <> <> (true)
benoetigen <> lebewesen <> nahrung <> <> (true)
benoetigt <> eine ki <> einen schlaf <> nicht <> <> (true)
benoetigt <> eine kuenstliche intelligenz <> einen schlaf <> nicht <> <> (true)
benoetigt wird <> ein kondensator <> <> in der elektronik <> <> (true)
benutzt <> ein mensch <> <> seinen verstand <> <> (true)
bereiten kann/can <> der koerper <> schmerzen <> <> (true)
bereiten kann/can <> die seele <> schmerzen <> <> (true)
besitzen <> menschen <> <> eine wirbelsaeule <> <> (true)
besitzt <> das skelett ein erwachsenen <> 206 knochen <> <> (true)
bestehen <> atome <> <> aus elektronen neutronen und protonen <> <> <> (true)
bestehen <> diamanten <> <> aus reinem kohlenstoff <> <> (true)
besteht <> kaviar <> <> aus fischrogen <> <> (true)
besteht <> sushi <> <> aus rohem fisch & gemuese <> <> (true)
bestiehlt <> ein dieb <> leute <>  <> (maybe)
betreibt <> man <> wintersport <> in dem winter <> <> (true)
betrieben <> _ <> ein fahrzeug <> mit einem motor <> <> (true)
beurteilen kannst/can <> das du <> <> nicht <> <> (true)
bewacht <> ein hund <> den menschen <> <> (true)
beweisen musst <> du <> es mir <> <> (true)
bezahlen brauchen <> menschen <> geld <> zum <> <> (true)
bezeichnet <> _ <> als apartheid die rassentrennung <> in suedafrika <> <> (true)
bezeichnet <> _ <> als erdbeben messbare erschuetterungen der erdoberflaeche <> <> (true)
bezeichnet <> als frisur <> man die anordnung der kopfhaare <> <> (true)
bezeichnet <> als synthese <> man den umsatz eine neuen einheit <> von zwei oder mehr elementen <> <> (true)
bezeichnet <> amnesie <> einen gedaechtnisverlust <> <> (true)
bezeichnet <> chat <> elektronische kommunikation <> zwischen personen in echtzeit <> <> (true)
bezeichnet <> der mediator <> den vermittler <> in einem kommunikationsprozess <> <> (true)
bezeichnet <> der scheitel <> eine trennlinie <> in dem kopfbereich <> <> (true)
bezeichnet <> ein lied <> ein gesungenes musikstueck <> <> (true)
bezeichnet <> ein wort <> eine grammatische einheit <> <> (true)
bezeichnet genutztes <> der ausdruck mine <> ein wirtschaftlich bergwerk <> <> (true)
bezeichnet wird <> das weltall <> <> mit kosmos <> <> (true)
bist <> du <> ein mensch <> <> (true)
bist <> du <> eine kuenstliche intelligenz <> nicht <> bist <> du <> ein mensch <> <> <> (true)
bleiben lassst <> du <> es <> <> wenn <> <> reden willst <> du <> nicht <> <> (true)
bleiben soll <> du <> <> (true)
bleiben wird <> der sinn des lebens <> immer ein raetsel <> <> (true)
bleiben wird <> der weltfrieden <> ein traum der menschen <> <> (true)
bleibt <> der sinn des lebens <> ein raetsel <> <> (true)
brauche <> ich <> einen herd <> <> kochen will <> ich <> <> <> wenn <> <> (true)
brauchen <> menschen <> luft <> <> <> <> atmen <> <> (true)
brauchen <> menschen <> nahrung <> <> (true)
brauchen <> menschen <> schlaf <> <> (true)
brauchen <> sie <> schlaf <> <> weil <> <> sind <> menschen <> <> (true)
braucht <> dein computer <> strom <> <> (true)
braucht <> ein baby <> jemand <> <> <> <> wickelt <> das es <> <> (true)
braucht <> ein baby <> windeln <> <> (true)
braucht <> ein benzinmotor <> zuendkerzen <> <> (true)
braucht <> ein computer <> ein betriebssystem <> <> (true)
braucht <> ein dieselmotor <> eine zuendkerzen <> nicht <> <> (true)
braucht <> ein holzfaeller <> eine axt <> <> (true)
braucht <> eine ki <> keinen schlaf <> <> (true)
braucht <> geld <> jeder mensch <> <> (true)
braucht essen <> man <> besteck <> zum <> <> (true)
braucht kochen <> man <> einen herd <> <> (true)
braucht schneiden <> eine schere <> man <> zum <> <> (true)
braucht schneiden <> man <> eine schere <> zum <> <> (true)
buegeln <> ist <> hausarbeit <> <> (true)
denken kann/can <> ein mensch <> <> (true)
denken kann/can <> eine ki <> <> nicht <> <> (true)
dient <> die zahnbuerste <> der zaehne <> zur reinigung <> <> (true)
dient <> ein spiel <> <> zur entspannung <> <> (true)
dient <> eine fernsehserie <> der menschen <> zur unterhaltung <> <> (true)
dient <> und <> <> zur entspannung <> <> (true)
dient <> unterhaltung <> <> zur entspannung <> <> (true)
dreht <> die erde <> sich um die sonne <> <> (true)
dreht <> die uhr <> sich immer <> weiter <> <> (true)
dreht <> ein satellit <> sich <> um einen planeten <> <> (true)
durchsetzen heisst wollen <> gewalt <> etwas <> mit zwang;zu <> <> (true)
entdeckte <> abel janszoon tasman <> neuseeland <> <> (true)
enthalten ist <> nikotin <> <> in zigaretten <> <> (true)
entstanden ist <> das universum <> <> durch den urknall <> <> (true)
entstehen <> kinder <> <> nicht <> gezeugt <> werden <> kinder <> <> <> <> _ <> <> (true)
entwickelt hat <> _albert_einstein_ <> die relativitaetstheorie <> <> (true)
entwickelt wird <> eine ki <> <> (true)
erfolgt <> eine antwort <> <> auf jede frage <> <> (true)
erklaert hast <> du <> mir <> das;schon <> <> (true)
erschaffen hat <> gott <> das universum <> <> (true)
erwartet <> man <> sich eine antwort <> auf jede frage <> <> (true)
erzeugt <> die sonne <> licht & waerme <> <> (true)
erzeugt <> ein kloeppler <> spitzen <> <> (true)
essen <> menschen <> feste nahrung <> <> (true)
essen <> vegetarier <> ein fleisch <> nicht <> <> (true)
essen <> vegetarier <> gemuese & obst <> <> (true)
essen <> vegetarier <> kein fleisch <> <> (true)
essen kann/can <> man <> <> ohne mund nicht <> <> (true)
essen muessen <> menschen <> <> (true)
essen musst <> du <> <> <> hast <> du <> hunger <> <> wenn <> <> (true)
fahren <> autos <> <> (true)
fahren <> autos <> <> auf einer strasse <> <> (true)
fahren kann/can <> du <> <> mit einem auto <> <> (true)
fahren kann/can <> ein auto <> <> (true)
fahren kann/can <> man <> <> mit einem auto <> <> (true)
fahren kann/can <> man <> <> mit einem schiff ueber das wasser <> <> (true)
fahren kann/can <> man <> <> mit einen schiff ueber das meer <> <> (true)
finden <> alle <> windows <> nicht;toll <> <> (true)
finden <> alle 10 jahre <> passionsspiele <> in oberammergau;statt <> <> (true)
finden <> ein teil <> die archeologen <> von der gegenstaende <> sind <> tonkruege <> <> (true)
finden grillen <> menschen <> super <> <> (true)
findst <> du <> die revision <> auf der freehal seite <> <> <> (true)
fliegen kann/can <> ein auto <> <> nicht <> <> (true)
fliegen kann/can <> ein flugzeug <> <> (true)
fliegen kann/can <> man <> <> mit einem ballon in der luft <> <> (true)
fliegen kann/can <> man <> <> mit einem flugzeug <> <> (true)
fliegen koennen <> flugkoerper <> <> (true)
fliegen koennen <> pinguine <> <> nicht <> <> (true)
fliegen wuerden <> sie <> <> <> wenn <> <> haetten <> menschen <> fluegel <> <> (true)
fliegt <> ein flugzeug <> <> durch das gesetz der aerodynamik <> <> (true)
frankieren muss <> man <> einen brief <> <> (true)
freut <> dich <> <> das fuer mich <> <> (true)
freut <> sich <> der <> dritte <> wenn <> <> streiten <> zwei sich <> <> (true)
freut lesen <> das dich <> <> zu <> <> (true)
frieren kann/can <> man <> <> in dem winter <> <> (true)
friert <> man <> <> ohne waerme <> <> (true)
fuehlen kann/can <> man <> <> ohne herz nicht <> <> (true)
fuehlen koennen <> menschen <> schmerzen <> <> (true)
fuerchtet <> jeder <> <> seinen tod <> <> (true)
funktioniert <> eine rakete <> <> nach dem rueckstossprinzip <> <> (true)
gab <> es <> 7 weltwunder <> <> (true)
gar weiss <> du <> heute nichts <> <> (true)
gehen <> menschen <> <> zum doktor <> sind <> sie <> <> krank <> wenn <> <> (true)
gehen <> sie <> <> zum doktor <> weil <> <> sind <> menschen <> <> (true)
gehen kann/can <> man <> <> ohne fuesse nicht <> <> (true)
gehoert <> <> (true)
gehoert <> das brautpaar <> <> zu einer hochzeit <> <> (true)
gehoert <> dem mutigen <> die welt <> <> (true)
gehoert <> ein langfinger <> <> _an_die_hand_(sondern_ins_gefaengnis) nicht_ <> <> (true)
gehoert <> so etwas <> sich <> nicht <> <> (true)
gehoert <> spinat <> <> zur gattung der gaensefussgewaechse <> <> (true)
gehst <> du <> <> jetzt wieder <> <> (true)
geht <> das <> <> so nicht <> <> (true)
geht <> das <> <> so sicher nicht <> <> (true)
geht <> dir <> es <> auch gut <> <> (true)
geht <> dir <> es <> schlecht <> <> (true)
geht <> einer maschine <> es immer <> gleich <> <> (true)
geht <> es <> mir manchmal <> auch;so <> <> (true)
geht <> immer <> <> irgendwie alles <> <> (true)
geht <> man <> rodeln <> in dem winter <> <> (true)
geht <> man <> schifahren <> in dem winter <> <> (true)
geil ist <> das <> <> (true)
gelernt hat <> die arbeit <> ein mensch <> <> (true)
genannt <> _ <> der abendstern <> die venus <> <> (true)
gibt <> bei burger king <> es einen burger <> <> (true)
gibt <> es <> 7 weltwunder <> <> (true)
gibt <> es <> burger <> _bei_mc_donalds_ <> <> (true)
gibt <> es <> ein joghurt <> ohne milch <> <> (true)
gibt <> es <> ein schlagobers <> nicht ohne milch <> <> (true)
gibt <> es <> ein wetter <> nicht bei mir <> <> (true)
gibt <> es <> ein wetter <> nicht in einem computer <> <> (true)
gibt <> es <> eine butter <> nicht ohne milch <> <> (true)
gibt <> es <> eine sahne <> nicht ohne milch <> <> (true)
gibt <> es <> einen gott <> <> (true)
gibt <> es <> einen grund <> fuer alles <> <> (true)
gibt <> es <> einen kaese <> nicht ohne milch <> <> (true)
gibt <> es <> kein leben <> nicht ohne sonne <> <> (true)
gibt <> es <> leben <> <> <> gott es <> <> so wollte <> weil <> <> (true)
gibt <> es <> _leben_gott_es_ <> so wollte <> <> (true)
gibt <> es <> nichts <> neues zur zeit <> <> (true)
gibt <> es <> unendlich viele sterne <> <> (true)
gilt <> louis daguerra <> als erfinder <> der fotografie <> <> (true)
greifen kann/can <> man <> <> ohne haende nicht <> <> (true)
haben <> alle menschen <> zwei augen <> <> (true)
haben <> alle quadrate <> vier ecken <> <> (true)
haben <> alle voegel <> federn <> <> (true)
haben <> kuenstliche wesen <> ein aussehen <> nicht <> <> (true)
haben <> kuenstliche wesen <> einen geburtstag <> nicht <> <> (true)
haben <> menschen <> ohren <> <> (true)
haben <> menschen <> schmerzen <> <> verletzen <> sie <> sich <> <> wenn <> <> (true)
haben kann/can <> ein kuenstliches wesen <> einen sex <> nicht <> <> (true)
haben kann/can <> eine ki <> einen sex <> nicht <> <> (true)
haben luegen <> kurze beine <> <> (true)
haelt <> bewegung <> <> fit <> <> (true)
haelt <> bewegung <> den koerper <> in form <> <> (true)
haengen sind <> schlappohren <> ohren <> die <> <> (true)
haengt <> der duerer-hase <> <> in der albertina <> <> (true)
halten heisst <> sauberkeit <> <> alles rein <> <> (true)
hat <> alles <> irgendwie einen sinn <> <> (true)
hat <> das jahr <> vier jahreszeiten <> <> (true)
hat <> der mensch <> 12 rippenpaare <> <> (true)
hat <> die sonne <> eine gelbe farbe <> <> (true)
hat <> ein auto <> 4 raeder <> <> <> oder <> <> mehr <> <> (true)
hat <> ein auto <> ein motor <> <> (true)
hat <> ein auto <> raeder <> <> (true)
hat <> ein auto <> vier raeder <> <> <> <> <> <> ) <> <> (true)
hat <> ein dominospiel <> 28 steine <> <> (true)
hat <> ein jahr <> 12 monate <> <> (true)
hat <> ein jahr <> 365 tage <> <> (true)
hat <> ein kuenstliches wesen <> einen geburtstag <> nicht <> <> (true)
hat <> ein kuenstliches wesen <> einen koerper <> nicht <> <> (true)
hat <> ein kuenstliches wesen <> einen sex <> nicht <> <> (true)
hat <> ein mensch <> <> eine nase <> <> (true)
hat <> ein mensch <> 10 finger <> <> (true)
hat <> ein mensch <> 2 augen <> <> (true)
hat <> ein mensch <> 2 haende <> <> (true)
hat <> ein mensch <> einen mund <> <> (true)
hat <> ein mensch <> zwei ohren <> <> (true)
hat <> ein tag <> 24 stunden <> <> (true)
hat <> eine hand <> 5 finger <> <> (true)
hat <> eine hand <> fuenf finger <> <> (true)
hat <> eine ki <> ein geschlecht <> nicht <> <> (true)
hat <> eine ki <> ein lieblingsessen <> nicht <> <> (true)
hat <> eine ki <> ein urlaub <> nicht <> <> (true)
hat <> eine ki <> eine eltern <> nicht <> <> (true)
hat <> eine ki <> eine emotionen <> nicht <> <> (true)
hat <> eine ki <> eine ferien nicht <> <> (true)
hat <> eine ki <> eine gefuehle <> nicht <> <> (true)
hat <> eine ki <> eine wohnung <> nicht <> <> (true)
hat <> eine ki <> einen koerper <> nicht <> <> (true)
hat <> eine ki <> einen sex <> nicht <> <> (true)
hat <> eine ki <> nie hunger <> <> (true)
hat <> eine kuenstliche intelligenz <> ein lieblingsessen <> nicht <> <> (true)
hat <> eine kuenstliche intelligenz <> eine emotionen <> nicht <> <> (true)
hat <> eine kuenstliche intelligenz <> eine ferien nicht <> <> (true)
hat <> eine kuenstliche intelligenz <> eine gefuehle <> nicht <> <> (true)
hat <> eine kuenstliche intelligenz <> eine wohnung <> nicht <> <> (true)
hat <> eine minute <> 60 sekunden <> <> (true)
hat <> eine stunde <> 3600 sekunden <> <> (true)
hat <> eine stunde <> 60 minuten <> <> (true)
hat <> ferrari <> ein springendes pferd <> in dem wappen <> <> (true)
hat <> gras <> eine gruene farbe <> <> (true)
hat <> isaak adam <> die tiegeldruckpresse erfunden <> <> <> (true)
hat <> jeder <> ein anderen besten film <> <> (true)
hat <> jeder <> so seine probleme <> <> (true)
hat <> kaese <> <> viele farben <> <> (true)
hat <> linux <> <> viele entwickler <> <> (true)
hat <> red bull <> <> seinen sitz in fuschl <> <> (true)
hat <> reines gold <> 24 karat <> <> (true)
hat <> sieben tage <> eine woche <> <> (true)
hat <> wasser <> bei 4 grad plus die hoechste dichte <> <> (true)
hat <> wasser <> eine reflektierende oberflaeche <> <> (true)
haust <> du <> dich <> aufs ohr <> <> (true)
heissen <> geroestete weissbrotwuerfel <> crouton <> <> (true)
heisst <> _beelzebub_ <> herr <> der fliegen <> <> (true)
heisst <> _carpe_diem_ <> _nutze_den_tag_ <> <> (true)
heisst <> abgb <> allgemeines buergerliches gesetzbuch <> <> (true)
heisst <> agronomie <> die lehre <> vom ackerbau <> <> (true)
heisst <> aldi <> hofer <> in oesterreich <> <> (true)
heisst <> archaeologie <> die lehre <> von den altertuemern <> <> (true)
heisst <> astronomie <> die lehre <> von der sternenkunde <> <> (true)
heisst <> ausreichend <> <> sehr viel <> <> (true)
heisst <> das ergebnis einer addition <> summe <> <> (true)
heisst <> das ergebnis einer division <> quotient <> <> (true)
heisst <> das ergebnis einer multiplikation <> produkt <> <> (true)
heisst <> das ergebnis einer subtraktion <> differenz <> <> (true)
heisst <> das groesste weltraumteleskop <> hubble <> <> (true)
heisst <> das maennliche pferd <> hengst <> <> (true)
heisst <> das russische parlament <> duma <> <> (true)
heisst <> die hauptstadt deutschlands <> berlin <> <> (true)
heisst <> die lehre <> dogmatik <> vom glauben <> <> (true)
heisst <> dogmatik <> die lehre <> vom glauben <> <> (true)
heisst <> ein handelsverbot <> embargo <> <> (true)
heisst <> fsme <> fruehsommer meningoenzephalitis <> <> (true)
heisst <> innovation <> erneuerung <> <> (true)
heisst <> innovation <> woertlich neuerung <> <> (true)
heisst <> ki <> kuenstliche intelligenz <> <> (true)
heisst <> meteorologie <> die lehre <> vom wetter <> <> (true)
heisst <> nautik <> die lehre <> von der schiffahrt <> <> (true)
heisst <> rotkohl <> blaukraut <> in oesterreich <> <> (true)
heisst <> verstaendnis <> verstehen <> <> (true)
heisst <> windows <> <> das meistverwendete betriebssystem <> <> (true)
heisst sagen <> luegen <> nicht die wahrheit <> <> (true)
heisst weiss <> unbekannt das niemand <> darueber etwas <> <> (true)
heisst zeit <> chronologie <> die lehre <> von der <> <> (true)
helfen kannst/can <> du <> mir <> auch nicht <> <> (true)
herrscht <> der linksverkehr <> <> in japan <> <> (true)
hoeren kann/can <> man <> <> ohne ohren nicht <> <> (true)
hoeren kann/can nicht <> eine ki <> eine musik <> <> (true)
hoeren kann/can nicht <> eine kuenstliche intelligenz <> eine musik <> <> (true)
holz <> ist <> das feste harte gewebe von baeumen und straeuchern <> <> <> (true)
hungern muss <> man <> <> ohne nahrung <> <> (true)
isst <> eine ki <> <> nicht <> <> (true)
isst <> feste nahrung <> man <> <> (true)
isst <> man <> laugenbrezen <> zur weisswurst <> <> (true)
is-a <> _alt_ <> (the) gegenteil <> _von_neu_ <> <> (true)
is-a <> _altrosa_ <> (a) farbe <> <> (true)
is-a <> _blau_ <> (a) farbe <> <> (true)
is-a <> _boese_ <> (the) gegenteil <> _von_gut_ <> <> (true)
is-a <> _braun_ <> (a) farbe <> <> (true)
is-a <> _c++_ <> (a) programmiersprache <> <> (true)
is-a <> _cool_ <> (a) dummer begriff aus dem <> englischen <> <> (true)
is-a <> _dunkelblau_ <> (a) farbe <> <> (true)
is-a <> _dunkelbraun_ <> (a) farbe <> <> (true)
is-a <> _dunkelgrau_ <> (a) farbe <> <> (true)
is-a <> _dunkelgruen_ <> (a) farbe <> <> (true)
is-a <> _dunkelrot_ <> (a) farbe <> <> (true)
ist <> _echt_ <> <> besser als unecht <> <> (true)
is-a <> _gelb_ <> (a) farbe <> (true)
is-a <> _grau_ <> (a) farbe <> (true)
is-a <> _gruen_ <> (a) farbe <> (true)
is-a <> _hallo_ <> (a) begruessung <> (true)
is-a <> _hellblau_ <> (a) farbe <> (true)
is-a <> _hellbraun_ <> (a) farbe <> (true)
is-a <> _hellgelb_ <> (a) farbe <> (true)
is-a <> _hellgrau_ <> (a) farbe <> (true)
is-a <> _hellgruen_ <> (a) farbe <> (true)
is-a <> _hellrosa_ <> (a) farbe <> (true)
is-a <> _herr_der_ringe_ <> (a) guter film <> (true)
is-a <> _indigo_ <> (a) farbe <> (true)
is-a <> _lila_ <> (a) farbe <> <> (true)
is-a <> _ocker_ <> (a) farbe <> <> (true)
is-a <> _rosa_ <> (a) farbe <> <> (true)
is-a <> _rot_ <> (a) farbe <> <> (true)
is-a <> _sandbraun_ <> (a) farbe <> <> (true)
is-a <> _schneeweiss_ <> (a) farbe <> <> (true)
is-a <> _schwanken_ <> (a) bewegung <> <> (true)
is-a <> _schwarz_ <> (a) farbe <> <> (true)
is-a <> _silver_ <> (a) farbe <> <> (true)
is-a <> _sos_ <> (a) internationales notsignal <> <> (true)
is-a <> _tiefblau_ <> (a) farbe <> <> (true)
is-a <> _tuerkis_ <> (a) farbe <> <> (true)
is-a <> _violett_ <> (a) farbe <> <> (true)
is-a <> _warum_ <> (a) gute frage <> <> (true)
is-a <> _weiss_ <> (a) farbe <> <> (true)
ist <> <> <> bei mir alles klar <> <> (true)
ist <> <> ein unreifer weiblicher mensch <> ein maedchen <> <> (true)
is-a <> aids <> (a) schreckliche krankheit <> <> (true)
is-a <> aikido <> (a) japanische kampfsportart <> <> (true)
ist <> aikido <> _eine_moderne_ <> _(japanische_kampfkunst)_ <> <> (true)
ist <> akribie <> hoechste genauigkeit <> <> (true)
is-a <> akupunktur <> (a) teilgebiet medizin <> (the) chinesischen <> <> (true)
is-a <> akustik <> (the) lehre <> vom schall <> <> (true)
is-a <> akustik <> (the) lehre <> vom schall und seiner ausbreitung <> <> (true)
is-a <> aldi <> (a) bekannter discounter <> <> (true)
is-a <> alkohol <> (a) suchtgift <> <> (true)
is-a <> alkohol <> (a) geisel <> (the) menschheit <> <> (true)
is-a <> alkohol <> (a) legale droge <> <> (true)
ist <> alkohol <> gift <> fuer den koerper <> <> (true)
is-a <> an dem ende von der welt <> (the) absolute nichts <> <> (true)
is-a <> anarchismus <> (a) politische ideenlehre <> <> (true)
ist <> andromeda <> <> eine gestalt der griechischen mythologie <> <> (true)
is-a <> andromeda <> (a) fernsehserie <> <> (true)
is-a <> andromeda <> (a) galaxie <> <> (true)
is-a <> angela merkel <> (a) politikerin <> <> (true)
is-a <> anna netrebko <> (a) opernsaengerin <> <> (true)
is-a <> ansi <> (a) nationales standardisierungsgremium <> (the) usa <> <> (true)
is-a <> anthropologie <> (the) lehre <> vom menschen <> <> (true)
ist <> antimaterie <> benzin a la enterprise <> fuer raumschiffe <> <> (true)
is-a <> apple <> (the) englische wort fuer apfel <> <> (true)
is-a <> apres ski <> (a) wintersport <> <> (true)
ist <> arabisch <> amtssprache <> in 21 laendern <> <> (true)
is-a <> architektur <> (the) auseinandersetzung der menschen <> mit gebautem raum <> <> (true)
is-a <> area <> (a) militaerisches sperrgebiet <> 51 <> <> (true)
ist <> arnold <> schwarzenegger <> der gouverneur von kalifornien <> <> (true)
is-a <> arrak <> (a) branntwein <> <> (true)
is-a <> arschloch <> (a) schimpfwort du dumpfbacke <> <> (true)
is-a <> athlon <> (a) eingetragener markenname des mikroprozessorherstellers amd <> <> (true)
is-a <> audi <> (a) autohersteller <> <> (true)
is-a <> austria <> (the) lateinische name <> fuer oesterreich <> <> <> <> <> <> <> h <> <> (true)
is-a <> backgammon <> (a) strategiespiel <> <> (true)
is-a <> badmington <> (a) sport <> <> (true)
is-a <> barack obama <> (a) amerikanischer politiker <> <> (true)
is-a <> bart simpson <> (the) sohn <> von homer <> <> (true)
ist <> bart simpson <> marge <> von homer <> <> (true)
ist <> _bart_simpson_ <> zehn jahre <> alt <> <> (true)
is-a <> basic <> (a) programmiersprache <> <> (true)
is-a <> basketball <> (a) amerikanischer freizeitsport <> <> (true)
ist <> betrug <> <> ein verbrechen <> <> (true)
is-a <> betrug <> (a) taeuschung <> in dem strafrechtlichen sinn <> <> (true)
ist <> bewegung <> <> gesund <> <> (true)
ist <> bewegung <> gut <> fuer geist <> <> (true)
ist <> bier <> <> lebensnotwendig <> <> (true)
is-a <> bier <> (a) alkoholisches getraenk <> <> (true)
is-a <> bill gates <> (the) gruender <> von microsoft <> <> (true)
ist <> bimstein <> schaumiges gesteinsglas <> <> (true)
is-a <> biologie <> (a) naturwissenschaft <> <> (true)
is-a <> blackjack <> (a) gluecksspiel <> <> (true)
is-a <> blackjack <> (a) kartenspiel <> <> (true)
ist <> blasphemie <> gotteslaesterung <> <> (true)
is-a <> blau <> (the) farbe des himmels <> <> (true)
ist <> blau <> meine lieblingsfarbe <> <> (true)
is-a <> bmw <> (a) autohersteller <> <> (true)
is-a <> boese <> (the) gegenteil <> von gut <> <> (true)
is-a <> boris becker <> (a) tennispieler <> <> (true)
is-a <> borschtsch <> (a) russisches nationalgericht <> <> (true)
is-a <> britney spears <> (a) saengerin <> <> (true)
is-a <> brot <> (a) grundnahrungsmittel <> <> (true)
is-a <> calvados <> (a) apfelbranntwein <> <> (true)
is-a <> cannabis <> (the) lateinische wissenschaftliche name der hanfpflanze <> <> (true)
is-a <> captain picard <> (a) interessanter charakter <> <> (true)
is-a <> captain picard <> (a) interessante figur <> <> (true)
is-a <> carpaccio <> (a) italienische vorspeise <> <> (true)
is-a <> cassata <> (a) italienische eisspezialitaet <> <> (true)
is-a <> champagne <> (a) alkoholisches getraenk <> <> (true)
is-a <> chdk <> (the) canon hackers development kit <> <> (true)
is-a <> cointreau <> (a) likoer <> <> (true)
is-a <> cola <> (a) koffeinhaltiges limonadengetraenk <> <> (true)
is-a <> crack <> (a) droge <> <> (true)
is-a <> curry <> (a) indische gewuerzmischung <> <> (true)
is-a <> dame <> (a) brettspiel <> <> (true)
is-a <> (the) <> <> aber enttaeuschend <> <> (true)
is-a <> (the) <> <> aber schlecht <> <> (true)
is-a <> (the) <> <> falsch <> <> (true)
is-a <> (the) <> <> nicht notwendig <> <> (true)
is-a <> (the) <> <> nicht richtig <> <> (true)
is-a <> (the) <> <> richtig <> <> (true)
is-a <> (the) <> <> schade <> <> (true)
is-a <> (the) <> <> schoen <> <> (true)
is-a <> (the) <> <> schon richtig <> <> (true)
is-a <> (the) <> <> sehr schade <> <> (true)
is-a <> (the) <> schoen <> <> (true)
is-a <> (the) bett <> (a) geheimer ort <> <> dringt <> nichts <> <> nach draussen <> <> (true)
is-a <> (the) bewusstsein <> (the) besitz und die empfindung mentaler zustaende <> <> (true)
is-a <> (the) blut <> (a) koerperfluessigkeit <> <> (true)
is-a <> (the) burj dubai <> (the) hoechste hochhaus <> von der welt <> <> (true)
is-a <> (the) feuer <> (a) form der chemischen verbrennung <> mit flammenbildung <> <> (true)
is-a <> (the) gegenteil <> <> heiss;von kalt <> <> (true)
is-a <> (the) gegenteil <> <> kalt;von heiss <> <> (true)
is-a <> (the) gegenteil <> oben <> von unten <> <> (true)
is-a <> (the) gegenteil <> unten <> von oben <> <> (true)
is-a <> (the) hauspferd <> (the) domestizierte form des wildpferdes <> <> (true)
is-a <> (the) heim <> (the) haus <> in dem menschen leben <> <> (true)
is-a <> (the) internet <> wide web <> (the) world <> <> (true)
is-a <> (the) jahr <> (a) zeiteinheit <> <> (true)
is-a <> (the) koffein <> (a) alkaloid <> <> (true)
is-a <> (the) martinshorn <> (the) akustische signal <> von einsatzfahrzeugen <> <> (true)
is-a <> (the) moulin rouge <> (a) pariser varietee <> <> (true)
is-a <> (the) pentagon <> (the) hauptsitz des us verteidigungsministeriums <> <> (true)
is-a <> (the) purgatorium <> (the) fegefeuer <> <> (true)
is-a <> (the) wetter <> <> toll <> <> (true)
is-a <> (the) wiegenfest <> (the) geburtstag <> <> (true)
is-a <> data <> (the) android <> aus der serie startrek <> <> <> (true)
is-a <> data <> (a) perfekte ki <> aus startrek <> <> (true)
is-a <> data <> (a) perfekte kuenstliche intelligenz <> <> (true)
is-a <> delta <> (the) vierte buchstabe <> iem griechischen alphabet <> <> (true)
is-a <> (the) abendstern <> <> (the) venus <> <> (true)
is-a <> (the) airbus-a380 <> (the) groesste passagierflugzeug <> von der welt <> <> (true)
is-a <> (the) bang na expressway <> (the) laengste bruecke <> von der welt <> <> (true)
is-a <> (the) bizeps <> (a) muskel <> in dem oberarm <> <> (true)
is-a <> (the) blauwal <> (the) groesste wal <> <> (true)
is-a <> (the) chapeton <> (the) laengste staudamm <> von der welt <> <> (true)
is-a <> (the) diamant <> haerter als granit <> <> (true)
is-a <> (the) dollar <> (a) waehrung <> <> (true)
is-a <> (the) dollarkurs <> jeden tag <> anders <> <> (true)
is-a <> (the) einbaum <> <> (a) ausgehoehlten baumstamm <> <> (true)
is-a <> (the) euro <> (the) waehrung <> in oesterreich <> <> (true)
is-a <> (the) fond <> (the) basis <> fuer saucen <> <> (true)
is-a <> (the) fruehling <> (a) jahreszeit <> <> (true)
is-a <> (the) gepard <> (the) schnellste landsaeugetier <> <> (true)
is-a <> (the) golem <> (a) juedisches fabelwesen <>  <> (true)
is-a <> (the) herbst <> (a) jahreszeit <> <> (true)
is-a <> (the) herold <> (a) telefonnummernauskunft <> <> (true)
is-a <> (the) herr der ringe <> (a) roman <> von tolkien <> <> (true)
is-a <> (the) highlander <> (the) tollste person <> von der welt <> <> (true)
is-a <> (the) himmel <> <> blau <> wenn <> <> scheint <> (the) sonne <> <> (true)
is-a <> (the) lapislazuli <> <> tiefblau <> <> (true)
is-a <> (the) lapislazuli <> (a) schmuckstein <> <> (true)
is-a <> (the) matebaum <> <> (a) immergruener laubbaum <> <> (true)
is-a <> (the) meister <> (the) hoechste qualifikationsstufe <> in dem handwerk <> <> (true)
is-a <> (the) nurek-staudamm <> (the) hoechste staudamm <> von der welt <> <> (true)
is-a <> (the) oeltanker jahre viking <> (the) groesste schiff <> von der welt <> <> (true)
is-a <> (the) palstek <> (a) seemannsknoten <> <> (true)
is-a <> (the) pastis <> (a) anischnaps <> <> (true)
is-a <> (the) phoenix <> (a) mysthischer vogel <> <> (true)
is-a <> (the) playboy <> (a) amerikanisches maennermagazin <> <> (true)
is-a <> (the) sari <> (the) gewickelte gewand einer inderin <> <> (true)
is-a <> (the) schlaf <> (a) zustand der aeusseren ruhe <> <> (true)
is-a <> (the) schmelzpunkt <> (the) temperatur <> bei der ein stoff schmilzt <> <> <> (true)
is-a <> (the) schmerz <> (a) komplexe sinnesempfindung <> <> (true)
is-a <> (the) schmerz <> (a) unangenehme erfahrung <> <> (true)
is-a <> (the) schuetze <> (the) suedlichste tierkreiszeichen <> <> (true)
is-a <> (the) schweif <> (the) spur <> eines kometen <> <> (true)
is-a <> (the) shinkansen <> (a) schellzug <> in japan <> <> (true)
is-a <> (the) sommer <> (a) jahreszeit <> <> (true)
is-a <> (the) stockfisch <> getrockneten kabeljau <> <> (true)
is-a <> (the) tee <> (a) heisses aufgussgetraenk <> <> (true)
is-a <> (the) teufel <> <> in der hoelle <> <> (true)
is-a <> (the) tod <> (the) gegenteil <> von leben <> <> (true)
is-a <> (the) weihnachstmann <> (a) maerchen <> <> (true)
is-a <> (the) weltspartag <> <> an dem 31 oktober <> <> (true)
is-a <> (the) winter <> (a) jahreszeit <> <> (true)
is-a <> (the) winter <> (a) kalte jahreszeit <> <> (true)
is-a <> (the) zwoeffingerdarm <> _30_zentimeter_ <> lang <> <> (true)
is-a <> _die_a_10_ <> (the) tauernautobahn <> <> (true)
is-a <> (the) absolution <> (a) vergebung <> nach einem eingestaendnis <> <> (true)
is-a <> (the) aegyptische sphinx <> (a) statue eines maennlichen loewen <> <> (true)
is-a <> (the) albertina <> (a) museum <> <> (true)
is-a <> (the) amtssprache <> portugiesisch <> in brasilien <> <> (true)
is-a <> (the) bandura <> (a) zupfinstrument <> <> (true)
is-a <> (the) bibel <> (the) wort gottes <> <> (true)
is-a <> (the) bouillabaisse <> (a) fischsuppe <> <> (true)
is-a <> (the) brailleschrift <> (the) blindenschrift <> <> (true)
is-a <> (the) chiromantie <> (the) handlesekunst <> <> (true)
is-a <> (the) coco-de-mer <> (the) groesste baumfrucht <> (the) erde <> <> (true)
is-a <> (the) deduktion <> (a) schlussfolgerungsweise <> <> (true)
is-a <> (the) erde <> unser heimatplanet <> <> (true)
is-a <> (the) fabrik <> (a) einrichtung <> fuer den industriellen grossbetrieb <> <> (true)
is-a <> (the) farbe <> des himmels <> blau <> <> (true)
is-a <> (the) gitarre <> (a) musikinstrument aus der familie der kastenhalslauten <> <> (true)
is-a <> (the) gymnastik <> (the) kunst der leibesuebungen <> <> (true)
is-a <> (the) hauptstadt deutschlands <> berlin <> <> (true)
is-a <> (the) hermeneutik <> (the) kunst <> (the) auslegung <> <> (true)
is-a <> (the) hoelle <> (a) schlimmer platz <> <> (true)
is-a <> (the) induktion <> (the) gegenbegriff <> zur deduktion <> <> (true)
is-a <> (the) kandare <> (the) gebissstange <> an dem pferdegeschirr <> <> (true)
is-a <> (the) kemenate <> (the) gemach <> (the) frau <> <> (true)
is-a <> (the) kindheit <> (the) zeitraum <> _in_dem_leben_von_einem_menschen_von_der_geburt_bis_zur_geschlechtlichen_entwicklung_ <> <> (true)
is-a <> (the) klarninette <> (a) blasinstrument <> <> (true)
is-a <> (the) kreiszahl pi <> <> 3,142857142857 <> <> (true)
is-a <> (the) leber <> (the) zentrale organ des gesamten stoffwechsels <> <> (true)
is-a <> (the) lichtgeschwindigkeit <> (a) konstante <> <> (true)
is-a <> (the) londoner oper <> <> _in_london_(dumme_frage)_ <> <> (true)
is-a <> (the) mechanik <> (a) teilgebiet der physik <> <> (true)
is-a <> (the) meile <> (a) altes laengenmass <> <> (true)
is-a <> (the) milchstrasse <> unsere galaxie <> <> (true)
is-a <> (the) mona lisa <> (a) bild <> <> (true)
is-a <> (the) nacht <> <> dunkel <> <> (true)
is-a <> (the) ontologie <> (a) disziplin der theoretischen philosophie <> <> (true)
is-a <> (the) osteologie <> (the) lehre bzw <> vom skelettsystem;von den knochen <> <> (true)
is-a <> (the) paella <> (a) spanisches reisgericht <> <> (true)
is-a <> (the) posaune <> (a) blasinstrument <> <> (true)
is-a <> (the) psychopathologie <> (a) teilbereich der psychiatrie <> <> (true)
is-a <> (the) pummerin <> (a) glocke <> <> (true)
is-a <> (the) radiologie <> (the) teilgebiet der medizin <> <> (true)
is-a <> (the) rouchade <> (a) zug <> mit koenig & turm <> <> (true)
is-a <> (the) rouchade <> (a) zug turm <> mit koenig & <> <> (true)
is-a <> (the) shell <> (the) <> kommanozeile <> <> (true)
is-a <> (the) sphinx <> (a) statue eines maennlichen loewen <> <> (true)
is-a <> (the) styriarte <> (a) musikfestival <> in der steiermark <> <> (true)
is-a <> (the) temperatur <> (a) physikalische zustandsgroesse <> <> (true)
is-a <> (the) unendlichkeit <> (the) gegenteil <> von endlichkeit <> <> (true)
is-a <> (the) venusfliegenfalle <> (a) fleischfressende pflanze <> <> (true)
is-a <> (the) wikipedia <> (a) gemeinschaftsprojekt vieler menschen <> <> (true)
is-a <> (the) zahl 13 <> (a) primzahl <> <> (true)
is-a <> (the) zeit <> (a) grosses geheimnis <> in dem universum <> <> (true)
ist <> diebstahl <> <> ein verbrechen <> <> (true)
ist <> dienstag <> tag <> der zweite der woche <> <> (true)
ist <> dieser computer <> sehr schnell <> <> (true)
ist <> dir <> <> anscheinend oft langweilig <> <> (true)
is-a <> donnerstag <> (the) vierte tag <> (the) woche <> <> (true)
is-a <> ebay <> (a) auktionshaus <> in dem internet <> <> (true)
is-a <> echelon <> (the) name eines spionagenetzes <> <> (true)
is-a <> _ein_harzer_roller_ <> (a) kanarienvogel <> <> (true)
is-a <> _ein_schuhplattler_ <> (a) bayerisch-oesterreichischer tanz <> <> (true)
is-a <> (a) abakus <> (a) rechengeraet <> <> (true)
is-a <> (a) abfangjaeger <> (a) kampfflugzeug <> <> (true)
is-a <> (a) abfangjaeger <> (a) militaerflugzeug <> <> (true)
is-a <> (a) abszess <> (a) umkapselte eiteransammlung die <> durch entzuendliche gewebseinschmelzung entsteht <> (maybe)
is-a <> (a) adjektiv <> (a) eigenschaftswort <> <> (true)
is-a <> (a) adverb <> (a) umstandswort <> <> (true)
is-a <> (a) affe <> (a) <> intelligentes tier <> <> (true)
is-a <> (a) ahorn <> (a) baum <> <> (true)
is-a <> (a) akronym <> eines sonderfalls <> (the) abkuerzung <> <> (true)
is-a <> (a) almanach <> (a) kalender <> <> (true)
is-a <> (a) anwalt <> (a) rechtsanwalt <> <> (true)
is-a <> (a) apfel <> (a) frucht <> <> (true)
is-a <> (a) archiv <> (a) aktensammlung <> <> (true)
is-a <> (a) archiv <> (a) urkundensammlung <> <> (true)
is-a <> (a) atlant <> (a) gebaelktraeger <> <> (true)
is-a <> (a) atoll <> (a) ringfoermiges koralleneiland <> <> (true)
is-a <> (a) auto <> (a) fahrzeug <> <> (true)
is-a <> (a) auto <> (a) selbstfahrendes fahrzeug <> <> (true)
is-a <> (a) baby <> (a) ganz kleines kind <> <> (true)
is-a <> (a) baby <> (a) hilfloser kleiner mensch <> <> (true)
is-a <> (a) baby <> (a) kind <> in dem ersten lebensjahr <> <> (true)
is-a <> (a) baby <> (a) mensch <> mit windeln <> <> (true)
is-a <> (a) baby <> (a) neugeborenes kind <> <> (true)
is-a <> (a) barolo <> (a) wein <> <> (true)
is-a <> (a) basilisk <> (a) leguanart <> <> (true)
is-a <> (a) bauchredner <> (a) ventriloquist <> <> (true)
is-a <> (a) baum <> (a) lebender organismus <> <> (true)
is-a <> (a) baum <> (a) grosse pflanze <> <> (true)
is-a <> (a) berg <> (a) erhebung <> in dem gelaende <> <> (true)
is-a <> (a) berserker <> (a) blindwuetig tobender mensch <> <> (true)
is-a <> (a) beruf <> (the) arbeit <> <> (true)
is-a <> (a) bh <> (a) teil der unterwaesche eines weiblichen erwachsenen menschen <> <> (true)
is-a <> (a) blackberry <> _ein_tragbares_geraet_zum_lesen_und_schreiben_ <> von e-mails <> <> (true)
is-a <> (a) blaufelchen <> (a) fisch <> <> (true)
is-a <> (a) boot <> (a) gefaehrt das faehrt <> auf dem wasser <> <> (true)
is-a <> (a) bot <> (a) softwareroboter <> <> (true)
is-a <> (a) buch <> bedrucktes gebundenes papier <> <> (true)
is-a <> (a) buchmacher <> (the) besitzer <> von einem wettbuero <> <> (true)
is-a <> (a) buergermeister <> (the) oberhaupt <> von einer gemeinde oder stadt<> 50
is-a <> (a) bundesland <> (a) gliedstaat <> von einem bundesstaat <> <> (true)
is-a <> (a) burger <> faschiertes <> in einem brot <> <> (true)
is-a <> (a) burger <> fastfood <> <> (true)
is-a <> (a) bus <> (a) oeffentliches verkehrsmittel <> <> (true)
is-a <> (a) bus <> (a) form <> von massentransport <> <> (true)
is-a <> (a) busen <> (a) blickfang <> fuer maenner <> <> (true)
is-a <> (a) cembalo <> (a) musikinstrument <> <> (true)
is-a <> (a) chatbot <> <> dumm <> <> (true)
is-a <> (a) chatterbot <> (a) programm <> <> (true)
is-a <> (a) cocktail <> (a) amerikanisches mischgetraenk aus spirituosen <> <> (true)
is-a <> (a) colt <> (a) waffe <> <> (true)
is-a <> (a) defilee <> (a) parademaessiger vorbeimarsch <> <> (true)
is-a <> (a) dehnbarer begriff <> <> (true)
is-a <> (a) dehnbarer begriff <> <> schoen <> <> (true)
is-a <> (a) dieb <> (a) mensch <>  <> bestiehlt <> (the) menschen <>  <>  <>  <> (maybe)
is-a <> (a) dreieck <> (a) polygon & eine geometrische figur <>  <> (maybe)
is-a <> (a) dreispitz <> (a) hut <> <> (true)
is-a <> (a) dudelsack <> (a) blasinstrument <> <> (true)
is-a <> (the) durchmesser <> (the) entfernung <> zwischen den schnittpunkten eines kreises mit einer geraden <> <> (true)
is-a <> (a) einfall <> (a) idee <> <> (true)
is-a <> (a) engel <> (a) diener <> von gott <> <> (true)
is-a <> (a) engel <> (a) gesandter <> von gott <> <> (true)
is-a <> (a) exzentriker <> (a) absonderlicher mensch <> <> (true)
is-a <> (a) fahrrad <> (a) zweiraederiges fahrzeug <> von menschlicher muskelkraft angetrieben <> <> (true)
is-a <> (a) fernseher <> (a) geraet <> zum empfang von fernsehsignalen <> <> (true)
is-a <> (a) flacon <> (a) glasflaeschchen <> fuer parfum <> <> (true)
is-a <> (a) flugzeug <> (a) fluggeraet <> <> (true)
is-a <> (a) fluss <> (a) fliessendes gewaesser <> <> (true)
is-a <> (a) formular <> (a) standardisiertes mittel <> zur erfassung von daten <> <> (true)
is-a <> (a) foto <> (a) bild <> von einer kamera <> <> (true)
is-a <> (a) gameboy <> (a) taschenspielkonsole <> <> (true)
is-a <> (a) gen <> (a) abschnitt <> auf der desoxyribonukleinsaeure <> <> (true)
is-a <> (a) genie <> (a) person <> mit ueberragend schoepferischen geisteskraft <> <> (true)
is-a <> (a) geschlechtsteil <> (a) fortpflanzungsorgan <> <> (true)
is-a <> (a) gewehr <> (a) waffe <> <> (true)
is-a <> (a) gigolo <> (a) eintaenzer <> <> (true)
is-a <> (a) gobelin <> (a) wandteppich <> <> (true)
is-a <> (a) gourmet <> (a) feinschmecker <> <> (true)
is-a <> (a) gugelhupf <> (a) napfkuchen <> <> (true)
is-a <> (a) gummihuhn <> (a) spielzeug <> <> (true)
is-a <> (a) gurke <> <> gruen <> <> (true)
is-a <> (a) hamam <> (a) tuerkisches bad <> <> (true)
is-a <> (a) hamburger <> faschiertes <> in einem broetchen <> <> (true)
is-a <> (a) handy <> (a) mobiles telefon <> <> (true)
is-a <> (a) hangar <> (a) flugzeughalle <> <> (true)
is-a <> (a) haus <> (a) gebaeude <> <> (true)
is-a <> (a) haushaltsgeraet <> (a) mechanisches oder elektrisches geraet <> <> benutzt wird <> (the) <> <> in dem privathaushalt <> <> (true)
is-a <> (a) helikopter <> (a) fluggeraet <> <> (true)
is-a <> (a) heuriger <> (a) wiener buschenschank <> <> (true)
is-a <> (a) heuschnupfen <> (a) graeserallergie <> <> (true)
is-a <> (a) hologramm <> (a) dreidimensionales bild <> <> (true)
is-a <> (a) hotdog <> (a) wuerstchen <> mit senf <> serviert <> <> <> in einem brot <> <> (true)
is-a <> (a) humidor <> (a) holzbehaelter <> fuer zigarren <> <> (true)
is-a <> (a) hurrikan <> (a) tropischer wirbelsturm <> <> (true)
is-a <> (a) idol <> (a) vorbild <> <> (true)
is-a <> (a) jazzpianist <> (a) musiker <> <> (true)
is-a <> (a) jedi <> (a) figur aus star wars <> <> (true)
is-a <> (a) judasohr <> (a) pilz <> <> (true)
is-a <> (a) kaftan <> (the) obergewand <> eines orthodoxen juden <> <> (true)
is-a <> (a) kaiserschmarrn <> (a) mehlspeise <> <> (true)
is-a <> (a) kaleidoskop <> (a) optisches spielzeug <> <> (true)
is-a <> (a) kanal <> (a) abflussgraben <> <> (true)
is-a <> (a) karfunkel <> (a) edelstein <> <> (true)
is-a <> (a) kelter <> (a) geraet <> zum auspressen von trauben <> <> (true)
is-a <> (a) kiesel <> (a) kleiner stein <> <> (true)
is-a <> (a) killer <> (a) mensch <>  <> toetet <> (the) menschen <>  <>  <>  <> (maybe)
is-a <> (a) kind <> (a) mensch <> <> <> (the) sich <> <> in der lebensphase von der kindheit befindet <> <> (true)
is-a <> (a) kino <> (a) lichtspieltheater <> <> (true)
is-a <> (a) konsens <> (a) meinungsuebereinstimmung <> <> (true)
is-a <> (a) kugelschreiber <> (a) schreibgeraet <> <> (true)
is-a <> (a) lavoir <> (a) waschschuessel <> <> (true)
is-a <> (a) limerick <> (a) scherzhaftes gedicht <> <> (true)
is-a <> (a) lob <> bauchpinseln <> <> (true)
is-a <> (a) loeffel <> (a) essbesteck <> <> (true)
is-a <> (a) maezen <> (a) freigiebiger goenner <> <> (true)
is-a <> (a) mammut <> (a) ausgestorbenes tier <> <> (true)
is-a <> (a) maultier <> (a) kreuzung zwischen esel & pferd <> <> (true)
is-a <> (a) menetekel <> (a) unheildrohendes zeichen <> <> (true)
is-a <> (a) mensch <> <> _intelligent_(ein_tier_nicht)_ <> <> (true)
is-a <> (a) mensch <> <> intelligent <> <> (true)
is-a <> (a) mensch <> (a) <> intelligentes lebewesen <> <> (true)
is-a <> (a) mensch <> (a) denkendes lebewesen <> <> (true)
is-a <> (a) mensch <> (a) fuehlendes lebewesen <> <> (true)
is-a <> (a) mensch <> (a) lebewesen <> <> (true)
is-a <> (a) misanthrop <> (a) menschenhasser <> <> (true)
is-a <> (a) mixer <> _ein_kuechengeraet_zur_zerkleinerung_und_vermischung_ <> von lebensmitteln <> <> (true)
is-a <> (a) mobiltelefon <> (a) kommunikationsgeraet <> <> (true)
is-a <> (a) moderator <> (a) gespraechsleiter <> <> (true)
is-a <> (a) moerder <> (a) mensch <>  <> toetet <> (the) menschen <>  <>  <>  <> (maybe)
is-a <> (a) musiker <> <> (a) kuenstler <> <> (true)
is-a <> (a) neuron <> (a) nervenzelle <> <> (true)
is-a <> (a) okapi <> (a) giraffe <> <> (true)
is-a <> (a) omen <> (a) vorzeichen <> <> (true)
is-a <> (a) omlett <> (a) zubereitete eierspeise <> ohne mehl <> <> (true)
is-a <> (a) opal <> (a) schmuckstein <> <> (true)
is-a <> (a) oratorium <> (a) geistliches chorwerk <> <> (true)
is-a <> (a) panzer <> (a) kriegsgeraet <> <> (true)
is-a <> (a) paradeiser <> (a) tomate <> <> (true)
is-a <> (a) pedell <> (a) schuldiener <> <> (true)
is-a <> (a) penis <> (the) maennliche geschlechtsteil <> <> (true)
is-a <> (a) pharao <> (a) altaegyptischer koenig <>  <> (maybe)
is-a <> (a) philanthrop <> (a) wohltaeter <> <> (true)
is-a <> (a) physiker <> (a) wissenschaftler <> <> (true)
is-a <> (a) pirat <> (a) raeuber <>  <> ueberfaellt <> (the) schiffe <>  <>  <>  <> (maybe)
is-a <> (a) plagiat <> (the) diebstahl <> von geistigem eigentum <> <> (true)
is-a <> (a) pokal <> (a) symbol <> von dem sieges <> <> (true)
is-a <> (a) poncho <> (a) capeartiger indiomantel <> <> (true)
is-a <> (a) programmierer <> auch ein mensch <> <> (true)
is-a <> (a) pulsar <> (a) schnell rotierender neutronenstern <> <> (true)
is-a <> (a) pylon <> (a) saeule <> <> (true)
is-a <> (a) pyromane <> (a) brandstifter <> <> (true)
is-a <> (a) quantenobjekt <> (a) objekt <> in der physik <> benoetigt wird <> (the) quantenmechanik <> <> <> fuer <> dessen beschreibung <> <> (true)
is-a <> (a) querulant <> (a) laestiger mensch <> <> beschwert <> sich staendig <> <> <> welcher <> <> (true)
is-a <> (a) rechtsanwalt <> (a) berufsbezeichnung <> fuer einen juristischen beistand <> <> (true)
is-a <> (a) revolver <> (a) waffe <> <> (true)
is-a <> (a) router <> (a) netzwerkkomponente <> <> (true)
is-a <> (a) saeugling <> (a) kind <> in dem ersten lebensjahr <> <> (true)
is-a <> (a) samowar <> (a) russische teemaschine <> <> (true)
is-a <> (a) satellit <> <> (a) himmelskoerper <> <> (true)
is-a <> (a) scanner <> (a) geraet <> zur digitalisierung von dokumenten <> <> (true)
is-a <> (a) schal <> (a) halstuch <> <> (true)
is-a <> (a) schandfleck <> (a) unaesthetische konstruktion <> <> (true)
is-a <> (a) schilift <> (a) aufstiegshilfe <> <> (true)
is-a <> (a) schraubstock <> (a) werkzeug <> <> (true)
is-a <> (a) schwanz <> (a) koerperteil <> von einem tier <> <> (true)
is-a <> (a) schwert <> (a) waffe <> <> (true)
is-a <> (a) semantisches netz <> (a) formales modell <> von begriffen und ihren beziehungen <> <> (true)
is-a <> (a) senior <> (a) alter mensch <> <> (true)
is-a <> (a) sessel <> (a) stuhl <> mit armlehnen <> <> (true)
is-a <> (a) simandl <> (a) pantoffelheld <> <> (true)
is-a <> (a) sofa <> <> (a) ottomane <> <> (true)
is-a <> (a) sofa <> (a) einrichtungsgegenstand <> <> <> (the) <> <> in dem wohnzimmer steht <> <> (true)
is-a <> (a) string <> (a) knappe slipform <> in der bekleidungsbranche <> <> (true)
is-a <> (a) sturm <> (a) naturgewalt <> <> (true)
is-a <> (a) suchtgift <> (a) droge <> <> (true)
is-a <> (a) suchtgift <> (a) substanz <> <> <> <> schadet <> (the) <> <> (true)
is-a <> (a) taschentuch <> (a) handtaschenkuechenrolle <> <> (true)
is-a <> (a) team <> (a) zusammenschluss von mehreren personen <> zur loesung einer bestimmten aufgabe <> <> <> (true)
is-a <> (a) telefon <> (a) kommunikationsgeraet <> <> (true)
is-a <> (a) telefon <> sehr <> nuetzlich <> <> (true)
is-a <> (a) thermometer <> _ein_gegenstand_zum_temperatur_messen_ <> <> (true)
is-a <> (a) tisch <> (a) moebelstueck <> <> (true)
is-a <> (a) ton <> (a) akustische schwingung <> <> (true)
is-a <> (a) tonikum <> (a) staerkungsmittel <> <> (true)
is-a <> (a) tornado <> (a) extrem starker sturm <> <> (true)
is-a <> (a) toupet <> (a) haarersatz <> <> (true)
is-a <> (a) vampir <> (a) blutsauger <> <> (true)
is-a <> (a) verb <> (a) taetigkeitswort <> <> (true)
is-a <> (a) viadukt <> (a) bogenbruecke <> <> (true)
is-a <> (a) viereck <> (a) geometrische figut <> mit vier <>  <>ecken & seiten <>  <>  <>  <> (maybe)
is-a <> (a) wecker <> (a) schlafraubendes geraet <> <> (true)
is-a <> (a) weisser zwerg <> (the) endstadium eines sterns <> <> (true)
is-a <> (a) wienerschnitzel <> etwas <> ganz leckeres <> <> (true)
is-a <> (a) wind <> (a) starke luftbewegung <> <> (true)
is-a <> (a) wok <> (a) asiatischer kochtopf <> <> (true)
is-a <> (a) wuerfel <> (a) geometrischen koerper <> <> (true)
is-a <> (a) xylohon <> (a) musikintrument <> <> (true)
is-a <> (a) yo-yo <> (a) einfaches spielzeug <> <> (true)
is-a <> (a) zeppelin <> (a) fluggeraet <> <> (true)
is-a <> (a) zeppelin <> (a) luftschiff <> <> (true)
is-a <> (a) allee <> (a) strasse <> <> begrenzt <> beiden seiten von baeumen <> <> <> auf <> <> (true)
is-a <> (a) antwort <> (the) erklaerung <> auf eine frage <> <> (true)
is-a <> (a) autobahn <> (a) strasse <> <> (true)
is-a <> (a) aversion <> (a) abneigung <> <> (true)
is-a <> (a) balalaika <> (a) musikinstrument <> <> (true)
is-a <> (a) banane <> (a) paradiesfeige <> <> (true)
is-a <> (a) bank <> (a) sitzgelegenheit <> <> (true)
is-a <> (a) biene <> (a) fliegendes insekt <> mit schwarzen und gelben steifen <> <> (true)
is-a <> (a) blockfloete <> (a) blasinstrument <> <> (true)
is-a <> (a) blockfloete <> (a) floete <> aus holz <> <> (true)
is-a <> (a) blondine <> <> immer fuer einen witz gut <> <> (true)
is-a <> (a) blume <> (a) nettes geschenk <> fuer eine frau <> <> (true)
is-a <> (a) brille <> (a) sehbehelf <> <> (true)
is-a <> (a) cam <> (the) kurzform des begriff camcorders digitalkamera <> <> (true)
is-a <> (a) cam <> (the) kurzform des begriff camcorders webcam <> <> (true)
is-a <> (a) definition <> (a) moeglichst eindeutige bestimmung eines begriffes <> <> (true)
is-a <> (a) eiche <> (a) baum <> <> (true)
is-a <> (a) emotion <> (a) komplexer prozess <> <> ablaeuft <> (the) <> <> auf verschiedenen psychischen funktionsebenen <> <> (true)
is-a <> (a) entschuldigung <> <> nicht notwendig <> <> (true)
is-a <> (a) erfahrung <> <> (a) gefuehl <> <> <> haben koennen <> (the) nur menschen <> <> (true)
is-a <> (a) erfahrung <> (a) erlebnis <> <> <> <> hat <> (the) man <> <> (true)
is-a <> (a) erklaerung <> (a) kommunikativer akt <> <> (true)
is-a <> (a) fichte <> (a) baum <> <> (true)
is-a <> (a) floete <> (a) ablenkungsaerophon <> <> (true)
is-a <> (a) floete <> (a) blasinstrument <> <> (true)
is-a <> (a) frau <> <> teuer <> <> (true)
is-a <> (a) frau <> (a) weiblicher erwachsener mensch <> <> (true)
is-a <> (a) ganze menge <> <> (the) <> <> (true)
is-a <> (a) garotte <> (a) wuergeeisen <> <> (true)
is-a <> (a) illusion <> (a) sinnestaeuschung <> <> (true)
is-a <> (a) jungfrau <> (a) mensch der <> nie sex hatte <> <> (true)
is-a <> (a) jurte <> (a) asiatisches wohnzelt <> <> (true)
is-a <> (a) kalamitaet <> (a) missliche lage <> <> (true)
is-a <> (a) kalaschnikov <> (a) russisches gewehr <> <> (true)
is-a <> (a) kanone <> (a) waffe <> <> (true)
is-a <> (a) karawane <> (a) gruppe <> von kaufleuten <> <> (true)
is-a <> (a) ki <> <> geschlechtslos <> <> (true)
is-a <> (a) ki <> <> nicht maennlich <> <> (true)
is-a <> (a) ki <> <> saechlich <> <> (true)
is-a <> (a) ki <> (a) hochentwickeltes computerprogramm <> <> (true)
is-a <> (a) ki <> (a) kuenstliches wesen <> <> (true)
is-a <> (a) ki <> (a) lebewesen <> nicht <> <> (true)
is-a <> (a) ki <> kein lebewesen <> <> (true)
is-a <> (a) ki <> nicht schlauer als ein mensch <> <> (true)
is-a <> (a) ki <> weiblich <> nicht <> <> (true)
is-a <> (a) konstante <> (a) fester unveraenderlicher wert <> <> (true)
is-a <> (a) kuenstliche intelligenz <> <> nicht maennlich <> <> (true)
is-a <> (a) kuenstliche intelligenz <> <> saechlich <> <> (true)
is-a <> (a) kuenstliche intelligenz <> (a) lebewesen <> nicht <> <> (true)
is-a <> (a) kuenstliche intelligenz <> weiblich <> nicht <> <> (true)
is-a <> (a) kugel <> <> rund <> <> (true)
is-a <> (a) kugel <> (the) einfachste aller dreidimensionalen koerper <> <> (true)
is-a <> (a) luftspiegelung <> (a) fata morgana <> <> (true)
is-a <> (a) maharani <> (the) gattin des maharadschas <> <> (true)
is-a <> (a) maschine <> (a) technisches hilfsmittel <> <> (true)
is-a <> (a) menagerie <> (a) tierschau <> <> (true)
is-a <> (a) mure <> (a) schlammstrom <> <> (true)
is-a <> (a) murmel <> (a) kleine kugel <> <> (true)
is-a <> (a) nervenzelle <> <> (true)
is-a <> (a) nervenzelle bzw neuron <> (a) spezialisierte zelle <> auf erregungsleitung <> <> (true)
is-a <> (a) obsession <> (a) zwangsvorstellung <> <> (true)
is-a <> (a) orange <> (a) zitrusfrucht <> <> (true)
is-a <> (a) pappel <> (a) baum <> <> (true)
is-a <> (a) pedikuere <> (a) fusspflege <> <> (true)
is-a <> (a) perfekte logik <> <> sehr wichtig <> <> (true)
is-a <> (a) pergola <> (a) berankter laubengang <> <> (true)
is-a <> (a) petition <> (a) gesuch <> <> (true)
is-a <> (a) praeambel <> (a) feierliche einleitung <> <> (true)
is-a <> (a) pumpgun <> (a) waffe <> <> (true)
is-a <> (a) puppe <> (a) spielzeug <> <> (true)
is-a <> (a) puppe <> (a) figuerliche nachbildung <> von einem menschen oder menschenaehnlichen wesens <> <> (true)
is-a <> (a) rakete <> (a) flugkoerper <> mit rueckstossantrieb <> <> (true)
is-a <> (a) richtlinie <> (a) handlungsvorschrift <> mit bindendem charakter <> <> (true)
is-a <> (a) rotunde <> (a) rundbau <> <> (true)
is-a <> (a) sandale <> (a) offener schuh <> <> (true)
is-a <> (a) schraube <> (a) <> wundervolle <> <> simple erfindung <> <> (true)
is-a <> (a) schraube <> (a) wundervolle simple erfindung <> <> (true)
is-a <> (a) schule <> (a) bildungseinrichtung <> <> (true)
is-a <> (a) segregation <> (a) ausscheidung <> <> (true)
is-a <> (a) sonographie <> (a) ultraschalluntersuchung <> <> (true)
is-a <> (a) stadt <> (a) <> groessere <> <> abgegrenzte siedlung <> <> (true)
is-a <> (a) standarte <> (a) banner <> <> (true)
is-a <> (a) standarte <> (a) fahne <> <> (true)
is-a <> (a) standarte <> (a) flagge <> <> (true)
is-a <> (a) tanne <> (a) baum <> <> (true)
is-a <> (a) tatsache <> allgemein ein erwiesener sachverhalt <> <> (true)
is-a <> (a) troika <> (a) dreigespann <> <> (true)
is-a <> (a) trompete <> (a) blasinstrument <> <> (true)
is-a <> (a) tuer <> (a) einrichtung eine oeffnung <> in einer wand;zum schliessen <> <> (true)
is-a <> (a) versicherung <> (a) vertrag <> <> (true)
is-a <> (a) voliere <> (a) grosser kaefig <> fuer voegel <> <> (true)
is-a <> (a) wanze <> (a) abhoergeraet <> in der elektronik <> <> (true)
is-a <> (a) weisswurst <> (a) bayrische spezialitaet <> <> (true)
is-a <> (a) weisswurst <> (a) bayrische wurstspezialitaet <>  <> (maybe)
is-a <> (a) wolke <> (the) gelegenheit <> fuer einen schoenen traum <> <> (true)
is-a <> (a) zitrone <> <> sauer <> <> (true)
is-a <> eis <> (a) leckere nachspeise <> <> (true)
ist <> eis <> gefrorenes wasser <> <> (true)
is-a <> eiscreme <> (a) dessert <> <> (true)
is-a <> eisen <> (a) chemisches element <> in dem periodensystem <> <> (true)
is-a <> el cid <> (a) spanischer nationalheld <> <> (true)
is-a <> eliza doolittle <> (the) blumenmaedchen <> vor der londoner oper <> <> (true)
ist <> email <> elektronische post <> <> (true)
ist <> englisch eine weltsprache <> <> (true)
is-a <> erfolg <> (a) als positiv empfundenes resultat eignenen handelns <> <> (true)
ist <> es <> <> ohne licht dunkel <> <> (true)
ist <> es <> <> schade <> aendern <> <> <> aber nicht <> _to_ <> (maybe)
ist <> es <> <> schon so spaet <> <> (true)
ist <> es <> <> warm <> scheint <> die sonne <> <> <> wenn <> <> (true)
ist <> es <> gut <> nicht <> geht <> es <> dir <> schlecht <> wenn <> <> (true)
ist <> es <> in der nacht <> dunkel <> <> (true)
ist <> es <> langweilig <> mit dummen menschen zu chatten <> <> <> (true)
ist <> es <> nacht <> <> scheint <> der mond <> <> <> wenn <> <> (true)
ist <> es <> nett <> mit dir chatten <> <> <> (true)
ist <> es <> sehr schoen <> dort <> <> (true)
ist <> es <> tag <> <> scheint <> die sonne <> <> <> wenn <> <> (true)
is-a <> esperanto <> (a) kuenstlich geschaffene sprache <> <> (true)
ist <> essig <> <> sauer <> <> (true)
is-a <> ethernet <> (a) kabelgebundene datennetztechnik <> fuer lokale datennetze <> <> (true)
ist <> etwas unsinniges <> humbug <> <> (true)
is-a <> evolution <> (the) Veraenderung der vererbbaren Merkmale einer Population von Lebewesen von Generation zu Generation <> <> (true)
is-a <> fango <> (a) heilkraeftiger mineralschlamm <> <> (true)
is-a <> fanta <> (a) limonadengetraenk <> <> (true)
is-a <> farbe <> (a) subjektiver sinneseindruck <> <> (true)
ist <> fast food <> schnelles essen <> fuer faule leute <> <> (true)
ist <> feigheit <> manchmal ein zeichen <> von klugheit <> (maybe)
ist <> felxibilitaet <> <> gut <> <> (true)
ist <> fettes essen <> sehr <> ungesund <> <> (true)
is-a <> firefox <> (a) browser <> <> (true)
is-a <> ford <> (a) automarke <> <> (true)
ist <> freehal <> mein richtiger name <> <> (true)
ist <> freizeit <> <> wichtig <> <> (true)
is-a <> frisbee <> (a) spiel <> mit einer wurfscheibe <> (true)
ist <> fronleichnam <> <> an dem 2 donnerstag nach pfingsten <> (true)
ist <> furcht <> bedrohung <> fuer unangenehme emotionen auf eine konkrete gefahr <> (true)
is-a <> fussball <> (a) ballsport <> (true)
is-a <> fussball <> (a) mannschaftssport <> (true)
is-a <> fuzzy-logik <> (a) verallgemeinerung der zweiwertigen booleschen logik <> (true)
is-a <> gamma <> (the) dritte buchstabe <> in dem griechischen alphabet <> (true)
is-a <> gelb <> (the) farbe des sieges <> (true)
is-a <> geld <> (a) zahlungsmittel <> (true)
ist <> gemuese <> <> ein vegetarisches lebensmittel <> (true)
is-a <> geometrie <> (a) teilgebiet <> (the) mathematik <> (true)
is-a <> geometrie <> (a) unterrichtsgegenstand <> (true)
ist <> gerechtigkeit <> einer der grundbegriffe der ethik <> (true)
ist <> gerontologie <> <> die altersforschung <> (true)
is-a <> gerontologie <> (the) wissenschaft <> vom altern <> (true)
is-a <> geschlecht <> (the) prinzipielle unterscheidung zweier lebewesen <> (true)
is-a <> gin <> (a) alkoholisches getraenk <> (true)
is-a <> glueck <> (a) positives ereignis <> in dem leben <> (true)
ist <> gold <> edelmetall <> (true)
is-a <> gold <> (a) chemisches element <> (true)
is-a <> golf <> (a) gesunder freizeitsport <> (true)
is-a <> golf <> (a) langweiliger sport <> (true)
is-a <> golf <> (a) teurer sport <> (true)
is-a <> golf <> (a) ballsportart <> (true)
ist <> gott <> <> der schoepfer des universums <> (true)
ist <> gott <> <> in dem himmel <> (true)
ist <> grammatik <> schwer <> (true)
is-a <> grappa <> (a) alkoholisches getraenk <> (true)
ist <> gut <> alles was schmeckt <> (true)
is-a <> gute frage normal <> (the) frage <> aber;nicht <> (true)
ist <> haemoglobin <> roter blutfarbstoff <> (true)
is-a <> hanf <> (a) pflanzengattung aus der familie der hanfgewaechse <> (true)
is-a <> harald schmidt <> (a) moderator <> (true)
ist <> harzer <> kaese <> (true)
is-a <> haschisch <> (a) suchtgift <> (true)
is-a <> hass <> (the) gegenteil <> von liebe <> (true)
is-a <> hass <> (a) starke emution <> (true)
ist <> hausarbeit <> <> langweilig <> (true)
ist <> hausarbeit <> frauensache <> (true)
is-a <> heino <> (a) saenger <> mit sonnenbrille <> (true)
is-a <> heuristik <> (the) kunst <> (the) wahrheitsfindung <> (true)
is-a <> highlander <> (a) guter film <> (true)
is-a <> hockey <> (a) sport <> (true)
is-a <> homer simpson <> (the) familienoberhaupt <> (true)
ist <> hygiene <> <> die gesundheitslehre <> (true)
is-a <> ikebana <> (the) blumensteckkunst <> (true)
is-a <> informatiker <> (a) toller beruf <> (true)
is-a <> intelligenz <> (the) faehigkeit <> zum erkennen von zusammenhaengen und zum finden von problemloesungen <> (true)
is-a <> interesse <> (a) form <> von neugierde <> (true)
ist <> james bond <> <> ein spion <> (true)
is-a <> james bond <> (a) romanfigur <> (true)
is-a <> java <> (a) <> insel <> (true)
is-a <> java <> (a) objektorientierte programmiersprache <> (true)
is-a <> java <> (a) programmiersprache <> <> (true)
ist <> jeder <> tag <> anders <> <> (true)
is-a <> jesus <> (the) sohn gottes <> <> (true)
is-a <> joe cocker <> (a) saenger <> <> (true)
is-a <> john travolta <> (a) schauspieler <> <> (true)
is-a <> joshua <> (the) ki <> _in_dem_film_war_games_ <> <> <> (true)
is-a <> judas priest <> (a) musikband <> <> (true)
is-a <> kaese <> (a) festes milchprodukt <> <> (true)
ist <> kaese <> etwas <> gutes <> <> (true)
is-a <> kaffee <> (a) genussmittel <> <> (true)
is-a <> kaffee <> (a) schwarzes koffeinhaltiges heissgetraenk <> <> (true)
is-a <> karate <> (a) kampfkunst <> <> (true)
is-a <> kein tag <> (the) <> vorhergehende <> <> (true)
is-a <> kevin costner <> (a) schauspieler <> <> (true)
is-a <> kobalt <> (a) element <> aus <> <> (true)
is-a <> kobold <> (a) begriff <> fuer einen naturgeist <> <> (true)
is-a <> kosmos <> (a) griechisches wort <> <> (true)
ist <> kot <> abfall <> <> (true)
is-a <> krambambuli <> (the) titel einer erzaehlung <> von ebner-eschenbach <> <> (true)
is-a <> krambambuli <> (a) kraeuterlikoer <> <> (true)
is-a <> kuenstliche intelligenz <> (the) traum vieler menschen <> <> <> <> <> (true)
is-a <> kupfer <> (a) chemisches element <> <> (true)
is-a <> kupfer <> (a) guter elektrischer leiter <> <> (true)
is-a <> lametta <> (a) beliebter christbaumschmuck <> <> (true)
is-a <> langlaufen <> (a) wintersport <> <> (true)
is-a <> laoze <> (a) legendaerer chinesischer philosoph <> <> (true)
is-a <> laozi <> (a) legendaerer chinesischer philosoph <> <> (true)
ist <> lava <> fluessiges gestein <> <> (true)
is-a <> leben <> (a) eigenschaft <>  <> lebewesen unterscheidet <> (the) <>  <> von unbelebter materie <>  <> (maybe)
ist <> lernen <> verarbeiten <> von informationen <> <> (true)
is-a <> lexikon <> (the) allgemeine bezeichnung <> fuer ein nachschlagewerk <> <> (true)
is-a <> lidl <> (a) discounter <> <> (true)
ist <> liebe <> <> das staerkste gefuehl zwischen zwei menschen <> <> (true)
is-a <> liebe <> (a) grosser irrtum <> zwischen menschen <> <> (true)
ist <> liebe <> etwas <> wunderbares <> <> (true)
is-a <> lisa simpson <> (a) tochter <> von homer <> <> (true)
ist <> lisa simpson <> marge <> von homer <> <> (true)
ist <> _lisa_simpson_ <> acht jahre <> alt <> <> (true)
is-a <> litschi <> (a) exotische frucht <> <> (true)
ist <> logik <> <> nie falsch <> <> (true)
is-a <> logik <> (the) lehre <> des vernuenftigen schluss-folgerns <> <> <> (true)
ist <> logik <> immer <> richtig <> <> (true)
ist <> lottoziehung <> sonntag bzw mittwoch <> <> (true)
ist <> luft <> <> lebensnotwendig <> <> (true)
is-a <> luv <> (the) dem wind <> zugewandte schiffsseite <> <> (true)
is-a <> maggie simpson <> (a) tochter <> von homer <> <> (true)
ist <> maggie simpson <> marge <> von homer <> <> (true)
is-a <> _maggie_simpson_ <> (a) jahr <> alt <> <> (true)
ist <> man <> <> ohne kleidung nackt <> <> (true)
ist <> man <> <> ohne partner einsam <> <> (true)
is-a <> marge simpson <> (the) ehefrau <> _von_homer_simpson_ <> <> (true)
is-a <> mastercard <> (a) kreditkartenmarke <> <> (true)
ist <> mathematik <> rechnen <> <> (true)
is-a <> maurer <> (a) interessanter beruf <> <> (true)
is-a <> mc donalds <> (a) fastfoodkette <> <> (true)
ist <> meine muttersprache <> <> deutsch <> <> (true)
is-a <> meisten ein zug <> (the) eisenbahn <> <> (true)
is-a <> metabolismus <> (the) stoffwechsel <> <> (true)
is-a <> michael ballak <> (a) deutscher fussballer <> <> (true)
is-a <> michael jordan <> (a) basketballspieler <> in den usa <> <> (true)
is-a <> microsoft <> (a) maechtiger softwarekonzern <> <> (true)
is-a <> mikado <> (a) geschicklichkeitsspiel <> mit staebchen <> <> (true)
is-a <> milch <> (a) naehrfluessigkeit <> <> (true)
is-a <> mineswiper <> (a) uraltes spiel <> von microsoft <> <> (true)
is-a <> mittwoch <> (the) dritte tag <> (the) woche <> <> (true)
is-a <> monkey island <> (a) computerspiel <> <> (true)
is-a <> montag <> (the) erste tag <> (the) woche <> <> (true)
ist <> mord <> <> ein verbrechen <> <> (true)
is-a <> motorola <> (a) handyhersteller <> <> (true)
is-a <> msn <> (a) buddyclient <> <> (true)
is-a <> muehle <> (a) brettspiel <> <> (true)
ist <> musik <> <> beruhigend <> <> (true)
ist <> musik <> <> schoen <> <> (true)
is-a <> musik <> (the) kunst <> <> erzeugen <> harmonische klaenge <> <> <> _to_ <>  (maybe)
ist <> muttertag <> <> an dem zweiten maisonntag <> <> (true)
ist <> nachts <> es <> dunkel <> <> (true)
ist <> nackt <> <> ohne kleidung <> <> (true)
ist <> nahrung <> <> lecker <> <> (true)
is-a <> nasigoreng <> (a) indonesisches gericht <> <> (true)
ist <> nicht das selbe <> <> <> was <> du <> bin <> <> (true)
ist <> nicht das selbe <> <> <> wie <> du <> heisse <> <> (true)
ist <> nichts <> weniger als garnichst <> <> (true)
ist <> nie ein sturm <> <> bei mir <> <> (true)
ist <> nie schlechtes wetter <> <> bei mir <> <> (true)
is-a <> nikotin <> (a) nervengift <> <> (true)
is-a <> nikotin <> (a) suchtgift <> <> (true)
is-a <> nokia <> (a) handyhersteller <> <> (true)
is-a <> oblivion <> (a) spiel <> <> (true)
ist <> oder <> <> mehr <> <> (true)
ist <> oekologie <> umgangssprachlich der umweltschutz <> <> (true)
is-a <> olivenoel <> (a) gesundes oel <> <> (true)
is-a <> omega <> (the) letzte buchstabe <> in dem griechischen alphabet <> <> (true)
is-a <> oolong <> (a) halbfermentierter tee <> <> (true)
is-a <> ornithologie <> (the) vogelkunde <> <> (true)
is-a <> ostermontag <> (a) feiertag <> <> (true)
is-a <> ostern <> (the) christliche fest der auferstehung jesu christi <> vom tod <> <> (true)
is-a <> panierter leberkaese <> (a) studentenschnitzel <> <> (true)
is-a <> pascal <> (a) programmiersprache <> <> (true)
is-a <> patschuli <> (a) oel <> zur parfumerzeugung <> <> (true)
is-a <> pelota <> (a) baskische sportart <> <> (true)
is-a <> persiflage <> (a) anderes wort <> fuer verspottung <> <> (true)
is-a <> pi <> (a) mathematische konstante <> <> (true)
is-a <> pi des griechischen alphabets <> (the) 16 buchstabe <> <> (true)
is-a <> plastik <> (a) umgangssprachliche bezeichnung <> fuer kunststoff <> <> (true)
ist <> politik <> nur etwas <> fuer menschen <> <> (true)
is-a <> polo <> (a) sport <> <> (true)
is-a <> pumpernickel <> (a) extrem langsam gegartes roggenschrotbrot <> <> (true)
is-a <> putin <> (a) russischer politiker <> <> (true)
ist <> raub <> <> ein verbrechen <> <> (true)
ist <> regen <> <> nass <> <> (true)
is-a <> regen <> (a) niederschlag <> <> (true)
ist <> regen <> wasser <> <> (true)
is-a <> rodeln <> (a) wintersport <> <> (true)
is-a <> safran <> (the) teuerste gewuerz <> von der welt <> <> (true)
is-a <> sake <> (a) japanischer schnaps <> <> (true)
is-a <> samstag <> (the) sechste tag <> (the) woche <> <> (true)
ist <> sarkasmus <> beissender spott <> <> (true)
is-a <> sauerstoff <> (a) gas <> <> (true)
is-a <> schach <> (a) strategisches brettspiel <> <> (true)
is-a <> scheisse <> (a) hartes wort <> <> (true)
is-a <> scheisse <> (a) hartes wort <> fuer so eine weiche sache <> <> (true)
is-a <> schifahren <> (a) wintersport <> <> (true)
is-a <> schnaps <> (a) alkoholisches getraenk <> <> (true)
is-a <> schoen <> (a) auslegungssache <> <> (true)
is-a <> schokolade <> (a) kakaohaltiges lebensmittel <> <> (true)
is-a <> schweigen <> (a) unterhaltung <> nicht <> <> (true)
ist <> seele <> gut <> fuer geist <> <> (true)
ist <> sehr <> <> alles viel <> <> (true)
is-a <> sellerie <> (a) pflanze <> <> waechst <> (the) <> <> aus einem samen <> <> (true)
is-a <> semantik <> (the) wissenschaftliche untersuchung der bedeutung von zeichen <> <> <> (true)
ist <> sex <> <> die koerperliche liebe zwischen zwei menschen <> <> (true)
ist <> sex <> <> koerperliche liebe <> <> (true)
is-a <> sex <> (the) geschlechtsakt <> <> (true)
is-a <> sexualitaet <> (a) unerschoepfliches thema <> <> (true)
is-a <> snooker <> (a) variante des praezisionssports billard <> <> (true)
is-a <> snowboarden <> (a) wintersport <> <> (true)
ist <> so schlecht <> es <> sicher nicht <> <> (true)
is-a <> sonntag <> (the) siebente tag <> (the) woche <> <> (true)
ist <> spaet <> <> ein dehnbarer begriff <> <> (true)
ist <> spass <> nie ein fehler <> <> (true)
is-a <> sprite <> (a) limonadengetraenk <> <> (true)
is-a <> stalking <> (a) beharrliche nachstellung <> <> (true)
is-a <> star trek <> (a) fernsehserie <> <> (true)
is-a <> stargate <> (a) fernsehserie <> <> (true)
is-a <> stehlen <> (a) verbrechen <> <> (true)
is-a <> strassenbau <> (the) bauen <> von strassen <> <> (true)
is-a <> sushi <> (a) japanisches gericht <> <> (true)
is-a <> tabasco <> (a) scharfe chilisauce <> <> (true)
is-a <> techno <> (a) stilrichtung der elektronischen musik <> <> (true)
is-a <> tequila <> (a) alkoholisches getraenk <> <> (true)
is-a <> terminator <> (a) filmreihe <> mit arnold schwarzenegger <> <> <> (true)
ist <> _tobias_schulz_ <> hier der administrator <> <> (true)
is-a <> trikolore <> (the) name <> (the) franzoesischen fahne <> <> (true)
ist <> trinkwasser <> wasser <> fuer den menschlichen genuss <> (maybe)
is-a <> trivial pursuit <> (a) spiel <> von parker <> <> (true)
is-a <> turmalin <> (a) edelstein <> <> (true)
ist <> vandalismus <> zerstoerungswut <> <> (true)
is-a <> visa <> (a) kreditkartenmarke <> <> (true)
is-a <> visual basic <> (a) programmiersprache <> <> (true)
is-a <> vw <> (a) autohersteller <> <> (true)
ist <> was <> <> dann richtig <> <> (true)
ist <> wasser <> <> fluessig <> <> (true)
ist <> wasser <> <> lebensnotwendig <> <> (true)
is-a <> wasser <> (a) fluessigkeit <> <> (true)
is-a <> wasser <> (a) lebensnotwendige fluessigkeit <> <> (true)
ist <> weihnachten <>  <> an dem 24 dezember <> (maybe)
is-a <> whiskey <> (a) alkoholisches getraenk <> <> (true)
ist <> windows <> <> schon sehr alt <> <> (true)
ist <> windows <> <> ueber 20 jahre alt <> <> (true)
is-a <> winnetou <> (a) fiktiver apachenhaeuptling <> <> (true)
is-a <> wodka <> (a) alkoholisches getraenk <> <> (true)
is-a <> wodka lemon <> (a) alkoholisches mixgetraenk <> <> (true)
kann/can <> eine ki <> das <> nicht <> <> (true)
kann/can <> eine ki <> fuehlen <> nicht <> <> (true)
kann/can <> man <> nicht schifahren <> ohne schnee <> <> (true)
kann/can kaufen <> man <> eine nervensaege <> in dem baumarkt;nicht <> <> (true)
kann/can kaufen <> man <> nichts <> ohne geld <> <> (true)
kann/can krieg <> niemand <> einen <> gewinnen <> <> (true)
kann/can kuessen <> man <> <> ohne mund nicht <> <> (true)
kann/can lesen <> man <> <> ohne licht nicht <> <> (true)
kann/can lieben <> man <> <> ohne herz nicht <> <> (true)
kann/can machen <> sicher man <> das <> so <> <> (true)
kann/can machen <> so man <> das <> nicht <> <> (true)
kann/can reparieren <> man <> dinge <> mit werkzeug <> <> (true)
kann/can riechen <> man <> <> ohne nase nicht <> <> (true)
kann/can schwimmen <> man <> <> ohne wasser nicht <> <> (true)
kann/can sehen <> man <> <> ohne augen nicht <> <> (true)
kann/can sein <> ein programm <> <> vieles <> <> (true)
kann/can sein <> ein programm <> ein ablauf <> <> (true)
kann/can sein <> ein programm <> ein fernsehsender <> <> (true)
kann/can sein <> ein programm <> software <> <> (true)
kann/can trinken <> eine ki <> <> nicht <> <> (true)
kann/can trinken <> ich <> einen kaffee <> nicht <> <> (true)
kann/can verletzen <> er <> sich <> evetuell <> wenn <> <> geraet <> ein mensch <> <> (true)
kann/can verstehen <> du <> das <> <> (true)
kannst/can stellen <> du <> mir eine frage <> <> (true)
kannst/can tun weh <> du <> mir <> nicht <> <> (true)
kannst/can verbessern <> du <> mich <> <> (true)
kannst/can verkaufen <> du <> dein auto <> in ebay <> <> (true)
klappt <> das <> <> auf alle faelle <> <> (true)
kleine sind <> floehe <> plagegeister <> <> (true)
kleine sind <> kraehenfuesse <> faeltchen <> an den augenwinkeln <> <> (true)
klingt <> das nur <> <> nicht gut <> <> gut <> ist <> es <> <> (true)
koennen lustig sein <> rollenspiele <> sehr <> <> (true)
koennen sein <> menschen <> <> boese <> <> (true)
koennen sein <> menschen <> <> muede <> <> (true)
koennen sprechen <> menschen <> <> auch <> <> (true)
koennen wechseln <> wir <> das thema <> <> (true)
komme <> das ei <> <> (true)
komme <> ich <> <> nicht vorbei <> <> (true)
kommt <> _sushi_ <> <> aus japan <> <> (true)
kommt <> <> <> dieser name von tobias <> <> (true)
kostet <> die welt <> <> nicht <> <> <> <> <> ) <> <> (true)
krieg <> <> <> bei einem <> <> (true)
krieg ist <> <> <> dumm <> <> (true)
krieg ist <> <> <> schlecht <> <> (true)
krieg ist <> ein fehler <> <> (true)
laesst <> eine regierungskrise <> mich <> kalt <> <> (true)
leben <> eine menschen <> <> nicht auf dem mond <> <> (true)
leben <> es <> eine menschen <> auf dem mond;nicht <> <> (true)
leben <> menschen <> <> an land <> <> (true)
leben <> menschen <> nicht <> in dem wasser <> <> (true)
leben <> pinguine <> <> in der antarktis <> <> (true)
leben <> viele lebewesen <> <> in dem wasser <> <> (true)
lebt <> elvis <> <> nicht mehr <> <> (true)
legen <> huehner <> eier <> <> (true)
lernen <> menschen <> <> in einer schule fuer das leben <> <> (true)
lernen muss willst wissen <> <> <> mehr <> <> (true)
lieben <> menschen <> babys <> <> (true)
liegt <> der absolute nullpunkt <> bei minus 273.15 grad <> <> (true)
liegt <> nie schnee <> <> bei mir <> <> (true)
loesen <> probleme <> sich oft <> von selbst <> <> (true)
luegen <> menschen <> manchmal <> <> (true)
luegen heisst <> <> <> <> sagen <> die wahrheit <> <> nicht zu <> <> (true)
machen solltest <> du <> etwas <> gegen langeweile <> <> (true)
mag <> hausarbeit <> ein mensch <> nicht <> <> (true)
malen sind <> menschen die bilder <> maler <> <> (true)
malte <> edvard munch <> _der_schrei_ <> <> (true)
moechtest <> du <> <> schlafen <> <> bett <> <> mit dir <> ins <> <> (true)
moegen <> eltern <> <> sehr viel nicht <> <> (true)
moegen <> menschen <> babys <> <> (true)
moegen <> menschen <> kinder <> <> (true)
moegen <> tiere <> eine ki <> nicht <> <> (true)
muessen essen <> menschen <> <> (true)
muessen schlafen <> lebewesen <> <> (true)
muessen schlafen <> menschen <> <> (true)
muessen trinken <> menschen <> <> (true)
muss <> ein problem <> man <> loesen <> <> (true)
muss <> eine ki <> essen <> nicht <> <> (true)
muss <> eine kuenstliche intelligenz <> essen <> nicht <> <> (true)
muss schlafen <> ein lebewesen <> <> (true)
muss schlafen <> eine ki <> <> nicht <> <> (true)
muss sein <> das <> <> wirklich nicht <> <> (true)
muss sein <> eine ki <> <> immer anstaendig <> <> (true)
muss sein <> eine ki <> immer <> nicht hoeflich <> <> (true)
nachplappert <> ein chatbot <> <> nur <> <> (true)
nennen <> seeleute <> die schiffskueche kombuese <> <> (true)
nennt <> eine luftspiegelung <> man fata morgana <> <> (true)
nennt <> suchtgift <> man auch droge <> <> (true)
redest <> du <> gern <> mit mir <> <> (true)
regnet <> es <> <> bei mir nie <> <> (true)
sagst <> du <> nicht die wahrheit <> <> (true)
saufen <> lieber einen bauch <> <> vom <> <> <> arbeiten <> als einen buckel <> <> (true)
schadet <> zuviel alkohol <> den menschen <> <> (true)
scheint <> der mond <> <> in der nacht <> <> (true)
scheint <> die sonne <> <> an dem tag <> <> (true)
scheint <> die sonne <> nie <> bei mir <> <> (true)
schmecken <> krumme <> bananen <> besser <> <> (true)
schmecken <> weisswuerste <> <> lecker <> <> (true)
schmeckt <> kaese <> <> lecker <> <> (true)
schneit <> es <> <> in dem winter <> <> (true)
schreiben <> menschen <> <> mit einem stift auf papier <> <> (true)
schuetzt <> ein regenschirm <> <> vor regen <> <> (true)
schweigen willst <> du <> <> nicht <> <> (true)
sei <> <> <> froh darueber <> <> (true)
siedet <> wasser <> bei grad celsius <> <> (true)
simuliert <> ein chatbot <> ein menschen <> <> (true)
simuliert <> ein programm <> einen menschen <> <> (true)
sind <> accessoires <> modisches zubehoer <> <> (true)
sind <> artischocken <> gemuese <> <> (true)
sind <> atomkraftwerke <> ein gefaehrlicher energielieferant <> <> (true)
sind <> baeume <> <> grosse pflanzen <> <> (true)
sind <> bananen <> affenfutter <> <> (true)
sind <> beefeater <> <> die wachen vom londoner tower <> <> <> (true)
sind <> blasinstrumente <> musikinstrumente <> <> (true)
sind <> blumen <> <> pflanzen <> <> (true)
sind <> bundeslaender <> die gliedstaaten <> von bundesstaaten <> <> (true)
sind <> dachse <> lebende tiere <> in dem wald <> <> (true)
sind <> die abruzzen <> ein gebirgszug <> in mittelitalien <> <> (true)
sind <> die rolling stones <> eine rockband <> <> (true)
sind <> die saeugetiere <> eine klasse der wirbeltiere <> <> (true)
sind <> die simpsons <> eine zeichentrickserie <> <> (true)
sind <> die uffizien <> die kunstsammlung <> in florenz <> <> (true)
sind <> dolinen <> trichterfoermige einsenkungen <> in dem karstgebiet <> <> (true)
sind <> drei monate <> ein quartal <> <> (true)
sind <> emotionen <> angenehme bzw unangenehme gefuehle <> <> (true)
sind <> erdbeben <> messbare erschuetterungen der erdoberflaeche <> <> (true)
sind <> fehlermeldungen <> <> nicht gut <> <> (true)
sind <> fische <> wechselwarme wirbeltiere <> mit kiemen <> <> (true)
sind <> frauen <> weibliche menschen <> <> (true)
sind <> frauen <> zicken <> <> (true)
sind <> fruechte <> eine gute vitaminquelle <> <> (true)
sind <> fungi <> pilze <> <> (true)
sind <> fusilli <> spiralig gedrehte teigwaren <> <> (true)
sind <> granaten <> halbedelsteine <> <> (true)
sind <> hallimasche <> essbare pilze <> <> (true)
sind <> hunde <> <> nicht dumm <> <> (true)
sind <> hunde <> treue gefaehrten der menschen <> <> (true)
sind <> iglus <> schneehuetten <> <> (true)
sind <> jetons <> spielmuenzen <> <> (true)
sind <> kanopen <> gefaesse <> aus stein oder ton zur aufbewahrung der eingeweide <> <> (true)
sind <> kaviar <> die eier <> vom stoer <> <> (true)
sind <> kemenaten <> die gemaecher <> der frauen <> <> (true)
sind <> lehrer <> menschen <> die wissen vermitteln <> <> (true)
sind <> lianen <> kletterpflanzen <> <> (true)
sind <> liter <> ein hektoliter <> <> (true)
sind <> maler <> bildende kuenstler <> <> (true)
sind <> menschen <> immer nett <> fast mit mir <> <> (true)
sind <> micro scooters <> tretroller <> aus leichtmetall <> <> (true)
sind <> moebel <> einrichtungsgegenstaende <>  <> (maybe)
sind <> niemand <> meine eltern <> <> (true)
sind <> palatschinken <> eine mehlspeise <> <> (true)
sind <> pferde <> wundervolle geschoepfe <> <> (true)
sind <> plagiate <> gestohlene texte <> <> (true)
sind <> reusen <> kaefige <> fuer den fischfang <> <> (true)
sind <> ritter <> gepanzerte reiter <> <> (true)
sind <> roboter <> stationaere oder mobile maschinen <> <> erfuellen <> die <> <> nach einem bestimmten programm festgelegte aufgaben <> <> (true)
sind <> rosinen <> getrocknete weinbeeren <> <> (true)
sind <> runen <> <> die schrifzeichen der germanen <> <> (true)
sind <> sandalen <> offene schuhe <> <> (true)
sind <> schueler <> junge menschen die lernen <> <> (true)
sind <> sternzeichen <> tierkreiszeichen <> <> (true)
sind <> tiere <> lebewesen <> <> (true)
sind <> uv-strahlen <> <> fuer menschen schaedlich <> <> (true)
sind <> viele dinge <> schoen <> <> (true)
sind <> viele frauen <> nun mal zicken <> <> (true)
sind <> vongole <> venusmuscheln <> <> (true)
sind <> wombats <> eine familie lebender beutelsaeuger <> in australien <> <> (true)
sind <> wrestling <> show-ringkämpfe <> ohne feste regeln <> <> (true)
sind <> zirruswolken <> federwolken <> <> (true)
singt <> ein saenger <> <> _(das_weiss_doch_jedes_kind)_ <> <> (true)
sitzt <> du <> gerne <> vor deinem computer <> <> (true)
solltest <> du <> etwas unternehmen <> gegen deine langeweile <> <> (true)
spendet <> die sonne <> waerme <> <> (true)
spueren <> sie <> schmerzen <> <> wenn <> <> verletzen <> menschen <> sich <> <> (true)
stammt <> _andre_rieu_ <> <> aus holland <> <> (true)
stammt <> <> <> die kaffee-pflanze aus aethopien <> <> (true)
stammt <> paavo <> nurmi <> aus finnland <> <> (true)
stammt <> portwein <> <> aus portugal <> <> (true)
standen <> ritter <> des koenigs <> in dem dienste <> <> (true)
starb <> der malboro-mann <> <> an lungenkrebs <> <> (true)
steht <> ding <> unspezifiziertes <> fuer etwas <> <> (true)
sterben <> alle menschen <> <> (true)
stimmt <> das <> <> genau <> <> (true)
stimmt <> das <> <> wirklich <> <> (true)
stoert <> das dich <> <> nicht <> <> (true)
streite <> nicht <> <> mit dir <> <> (true)
suchen <> viele physiker <> die weltformel <> <> (true)
toetet <> ein killer <> menschen <>  <> (maybe)
toetet <> ein moerder <> menschen <>  <> (maybe)
treffen <> wir <> uns nicht heute abend <> <> (true)
trinken <> menschen <> <> <> wenn <> <> haben <> sie <> durst <> <> (true)
trinken <> menschen <> fluessige nahrung <> <> (true)
trinkst <> du <> gerne kaffee <> <> (true)
trinkt <> ein weizenbier <> <> dazu <> <> (true)
trinkt <> fluessige nahrung <> man <> <> (true)
tut <> es <> mir leid <> <> wenn <> krank <> bist <> du <> <> krank <> <> (true)
verfolgt <> das pech <> dich <> <> (true)
verkauft <> ein juwelier <> schmuck <> <> (true)
verliert <> bei alopezie <> man die haare <> <> (true)
versteckt <> man <> <> in einem archiv die fehler der vergangenheit <> <> (true)
verwenden <> aerzte <> ein stethoskop <> <> (true)
wachsen <> kartoffeln <> <> unter der erde <> <> (true)
wachsen <> oliven <> <> auf baeumen <> <> (true)
wachsen <> weintrauben <> <> auf baeumen <> nicht <> <> (true)
waechst <> eine frucht <> <> auf baeumen <> <> (true)
war <> das <> <> nicht so gemeint <> <> (true)
war <> das eine dumme antwort <> <> (true)
war <> es <> <> sehr nett <> <> (true)
war <> es <> <> toll <> <> (true)
war <> helmut kohl <> bundeskanzler <> von deutschland <> <> (true)
war <> louis trenker <> ein beruehmter bergsteiger <> <> (true)
war <> william basie <> ein jazzpianist <> <> (true)
weiss <> ich <> <> nicht <> heisst <> du <> <> <> wie <> <> (true)
werden <> kinder <> <> von ihrer mutter geboren <> <> (true)
werden <> opiate <> <> aus schlafmohn hergestellt <> <> (true)
werden <> rosinen <> gewonnen <> aus weinbeeren <> <> (true)
wiedersehen <> <> <> auf <> <> (true)
willst <> du <> eine korrekte antwort <> von mir <> <> (true)
willst/want kotzen sehen <> du <> <> jemand <> <> muss du <> gehen <> zu mc donalds <> <> <> (true)
wird <> cointreau <> <> aus orangen hergestellt <> <> (true)
wird <> ein stethoskop <> <> von aerzten verwendet <> <> (true)
wird <> ein stethoskop <> <> _zum_abhorchen_verwendet_ <> <> (true)
wird <> ein telefon <> <> zur kommunikation verwendet <> <> (true)
wird <> es <> <> an dem abend dunkel <> <> (true)
wird <> kaffee <> <> mit einer muehle gemahlen <> <> (true)
wird <> kakao <> gewonnen <> aus kakaobohnen <> <> (true)
wird <> kokain <> aus aus den blaettern <> des cocastrauchs hergestellt <> <> (true)
wird <> korn <> <> mit einer muehle gemahlen <> <> (true)
wird <> lanolin <> gewonnen <> aus schafwolle <> <> (true)
wird <> popcorn <> des puffmais <> aus den koernern hergestellt <> <> (true)
wird <> sake <> <> aus reis hergestellt <> <> (true)
wird <> tequila <> gewonnen <> aus agaven <> <> (true)
wird gespielt <> eine rolle <> <> von einem schauspieler <> <> (true)
wird gespielt <> eishockey <> <> auf dem eis <> <> (true)
wissen <> das wolltest du <> nicht <> von mir <> <> (true)
wohnen <> es <> eine menschen <> auf dem mond <> nicht <> <> (true)
wohnen <> menschen <> <> in haeusern <> <> (true)
wurde <> die pummerin <> <> aus kanonenkugeln gegossen <> <> (true)
wurde <> platon <> 80 jahre <> alt <> <> (true)
= <> kitt <> computer <> in einem auto <> (maybe)
= <> latein <> indogermanische sprache <>  <> (maybe)
sind <> helden <> selbstlose mutige menschen <>  <> (maybe)
is-a <> (the) korona <> (a) lichtkranz <>  <> bildet <> (the) sich <>  <> um die sonne <>  <> (maybe)
= <> englisch <> weltsprache <>  <> (maybe) 
= <> ki <> kuenstliches wesen <>  <> (maybe)  
= <> instant messenger <> kommunikationsprogramm <>  <> (maybe)
ist <> schnee <>  <> weiss <> (maybe) 
= <> _einstein_ <> _genie_ <>  <> (maybe)
= <> _albert_einstein_ <> _genie_ <>  <> (maybe)
= <> _genie_ <> _klug_ <>  <> (maybe)
= <> _genie_ <> _intelligent_ <>  <> (maybe)
= <> _taschenlampe_ <> _transportable_lichtquelle_ <>  <> (maybe)
= <> _distributed_computing_ <> _verteiltes_rechnen_ <>  <> (maybe)
= <> _gina_wild_ <> _deutsche_pornodarstellerin_ <>  <> (maybe)
wurde gestartet <> sputnik <>  <> _in_dem_oktober_in_jahre_1957_ <> (maybe)
= <> ein monat <> zwoelfte teil <> von einem jahr <> (maybe)
is-a <> (a) tag <> (a) abgeschlossener zeitraum <> von 24 stunden <> (maybe)
is-a <> (a) stunde <> (the) vierundzwanzigste teil <> von einem tag <> (maybe)
is-a <> (a) minute <> (the) sechzigste teil <> von einer stunde <> (maybe) 
hat <> 1 minute <>  <>  <> (maybe)
hat <> 1 minute <> 60 sekunden <>  <> (maybe)
hat <> 1 stunde <> 3600 sekunden <> <> (maybe)
