#!/bin/bash
export LC_ALL=C

test -d /var/lib/apt && (
	echo Install dependencies
	sudo apt-get install build-essential subversion cmake libperl-dev boinc-dev libboost-system-dev libboost-thread-dev libboost-iostreams-dev libasio-dev qt4-dev-tools wget \
	|| (
		echo "Could not install dependencies. Please run as root:"
		echo
		echo sudo apt-get install build-essential subversion cmake libperl-dev boinc-dev libboost-system-dev libboost-thread-dev libboost-iostreams-dev libasio-dev qt4-dev-tools wget
		echo
		exit 0
	)
)

function depmiss {
	echo "Dependencies are missing. Please install "$*
}

wget --help >/dev/null 2>&1 || depmiss wget
cmake --help >/dev/null 2>&1 || depmiss cmake
qmake -help >/dev/null 2>&1 || depmiss "QT, at least version 4.5"


cd ~
mkdir bin 2>/dev/null
cd bin

rm -rf freehal-svn-old 2>/dev/null
mv -f freehal-svn freehal-svn-old 2>/dev/null
echo Download source code...
svn co http://freehal.org/code/hal2009 freehal-svn > /dev/null || (echo Error: Download source code ; exit 0)
cd freehal-svn
echo Compile server
(./configure && make hal2009-server hal2009-server-thread) > compile-server.log 2>&1 || (echo Error: Compile server ; exit 0)
mkdir -p saved/de saved/en
cp lang_de/*.pro* lang_de/*/*.pro* lang_de/*.xml* lang_de/*/*.xml* saved/de/
cp lang_en/*.pro* lang_en/*/*.pro* lang_en/*.xml* lang_en/*/*.xml* saved/en/

echo Download database...
for x in en de
do
	wget http://www.freehal.org/download/${x}-database.db.main
	wget http://www.freehal.org/download/${x}-database.db.index
	wget http://www.freehal.org/download/${x}-database.db.cache
	mv ${x}-database.db.main lang_de/database.db.main
	mv ${x}-database.db.index lang_de/database.db.index
	mv ${x}-database.db.cache lang_de/database.db.cache
done

cd gui-qt
echo Compile GUI
(qmake gui-qt.pro && make) > ../compile-gui.log 2>&1 || (echo Error: Compile GUI ; exit 0)

echo Create links...
echo '#!/bin/bash' > ~/bin/freehal
echo "cd ~/bin/freehal-svn/" >> ~/bin/freehal
echo "./gui-qt/bin/freehal" >> ~/bin/freehal
chmod 0777 ~/bin/freehal
sudo ln -sf ~/bin/freehal /usr/local/bin/freehal
