#!/bin/bash
export LC_ALL=C

svn up

scripts/update_zips

# ssh tobias@freehal.net "rm /disk/web1/var/www/data/wu-files/fh-*.zip"

ssh tobias@freehal.net "rm /disk/web1/var/www/projects/freehal_at_home/new/zip/fh-*.zip"
scp -C fh-*.zip tobias@freehal.net:/disk/web1/var/www/projects/freehal_at_home/new/zip/
ssh tobias@freehal.net "echo sudo /usr/local/bin/new_job_register_samefiles | go web1"


true
