# DO NOT EDIT THIS FILE.
#
# This file is generated automatically from
# include/parrot/warnings.h by config/gen/parrot_include.pm
#
# Any changes made here will be lost.
#
.macro_const PARROT_ERRORS_NONE_FLAG	0
.macro_const PARROT_ERRORS_GLOBALS_FLAG	1
.macro_const PARROT_ERRORS_OVERFLOW_FLAG	2
.macro_const PARROT_ERRORS_PARAM_COUNT_FLAG	4
.macro_const PARROT_ERRORS_RESULT_COUNT_FLAG	8
.macro_const PARROT_ERRORS_ALL_FLAG	255
