# DO NOT EDIT THIS FILE.
#
# This file is generated automatically from
# include/parrot/exceptions.h by config/gen/parrot_include.pm
#
# Any changes made here will be lost.
#
.macro_const EXCEPT_NORMAL	0
.macro_const EXCEPT_WARNING	1
.macro_const EXCEPT_ERROR	2
.macro_const EXCEPT_SEVERE	3
.macro_const EXCEPT_FATAL	4
.macro_const EXCEPT_DOOMED	5
.macro_const EXCEPT_EXIT	6
