# DO NOT EDIT THIS FILE.
#
# This file is generated automatically from
# include/parrot/interpreter.h by config/gen/parrot_include.pm
#
# Any changes made here will be lost.
#
.macro_const PARROT_NO_TRACE	0
.macro_const PARROT_TRACE_OPS_FLAG	1
.macro_const PARROT_TRACE_FIND_METH_FLAG	2
.macro_const PARROT_TRACE_SUB_CALL_FLAG	4
.macro_const PARROT_ALL_TRACE_FLAGS	65535
