# DO NOT EDIT THIS FILE.
#
# This file is generated automatically from
# include/parrot/events.h by config/gen/parrot_include.pm
#
# Any changes made here will be lost.
#
.macro_const IO_THR_MSG_NONE	0
.macro_const IO_THR_MSG_TERMINATE	1
.macro_const IO_THR_MSG_ADD_SELECT_RD	2
