# DO NOT EDIT THIS FILE.
#
# This file is generated automatically from
# include/parrot/enums.h by config/gen/parrot_include.pm
#
# Any changes made here will be lost.
#
.macro_const ITERATE_FROM_START	0
.macro_const ITERATE_FROM_START_KEYS	1
.macro_const ITERATE_GET_NEXT	2
.macro_const ITERATE_GET_PREV	3
.macro_const ITERATE_FROM_END	4
