# DO NOT EDIT THIS FILE.
#
# This file is generated automatically from
# include/parrot/longopt.h by config/gen/parrot_include.pm
#
# Any changes made here will be lost.
#
.macro_const OPTION_REQUIRED_FLAG	1
.macro_const OPTION_OPTIONAL_FLAG	2
