# DO NOT EDIT THIS FILE.
#
# This file is generated automatically from
# include/parrot/vtable.h by config/gen/parrot_include.pm
#
# Any changes made here will be lost.
#
.macro_const MMD_USER_FIRST	0
