# DO NOT EDIT THIS FILE.
#
# This file is generated automatically from
# include/parrot/io.h by config/gen/parrot_include.pm
#
# Any changes made here will be lost.
#
.macro_const PIO_STDIN_FILENO	0
.macro_const PIO_STDOUT_FILENO	1
.macro_const PIO_STDERR_FILENO	2
