# DO NOT EDIT THIS FILE.
#
# This file is generated automatically from
# include/parrot/string.h by config/gen/parrot_include.pm
#
# Any changes made here will be lost.
#
.macro_const STRINGINFO_HEADER	1
.macro_const STRINGINFO_STRSTART	2
.macro_const STRINGINFO_BUFLEN	3
.macro_const STRINGINFO_FLAGS	4
.macro_const STRINGINFO_BUFUSED	5
.macro_const STRINGINFO_STRLEN	6
