# DO NOT EDIT THIS FILE.
#
# This file is generated automatically from
# include/parrot/scheduler.h by config/gen/parrot_include.pm
#
# Any changes made here will be lost.
#
.macro_const PARROT_TIMER_SEC	0
.macro_const PARROT_TIMER_USEC	1
.macro_const PARROT_TIMER_NSEC	2
.macro_const PARROT_TIMER_REPEAT	3
.macro_const PARROT_TIMER_INTERVAL	4
.macro_const PARROT_TIMER_RUNNING	5
.macro_const PARROT_TIMER_HANDLER	6
.macro_const PARROT_TIMER_MAX	7
