# DO NOT EDIT THIS FILE.
#
# This file is generated automatically from
# src/utils.c by config/gen/parrot_include.pm
#
# Any changes made here will be lost.
#
.macro_const TM_SEC	0
.macro_const TM_MIN	1
.macro_const TM_HOUR	2
.macro_const TM_MDAY	3
.macro_const TM_MON	4
.macro_const TM_YEAR	5
.macro_const TM_WDAY	6
.macro_const TM_YDAY	7
.macro_const TM_ISDST	8
