# DO NOT EDIT THIS FILE.
#
# This file is generated automatically from
# include/parrot/warnings.h by config/gen/parrot_include.pm
#
# Any changes made here will be lost.
#
.macro_const PARROT_WARNINGS_ALL_FLAG	255
.macro_const PARROT_WARNINGS_NONE_FLAG	0
.macro_const PARROT_WARNINGS_UNDEF_FLAG	1
.macro_const PARROT_WARNINGS_IO_FLAG	2
.macro_const PARROT_WARNINGS_PLATFORM_FLAG	4
.macro_const PARROT_WARNINGS_DYNEXT_FLAG	8
.macro_const PARROT_WARNINGS_DEPRECATED_FLAG	16
