/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/tobias/perl-5.10.0/miniperl ../bin/enc2xs -Q -o gb_03_t.c -f gb_03_t.fnm
 enc2xs VERSION 2.05
*/
extern encode_t gb2312_raw_encoding;
