/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/tobias/perl-5.10.0/miniperl ../bin/enc2xs -Q -o ma_05_t.c -f ma_05_t.fnm
 enc2xs VERSION 2.05
*/
extern encode_t MacChineseSimp_encoding;
